State 0:
toplevel' -> . toplevel [ # ]
-- On UCID shift to state 1
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 85
-- On LAMBDA shift to state 52
-- On EOF shift to state 90
-- On toplevel shift to state 96
-- On Term shift to state 92
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 1:
toplevel -> UCID . TyBinder SEMI toplevel [ # ]
-- On LEQ shift to state 2
-- On TyBinder shift to state 29
-- On SEMI reduce production TyBinder ->

State 2:
TyBinder -> LEQ . Type [ SEMI ]
-- On UCID shift to state 3
-- On TTOP shift to state 4
-- On LPAREN shift to state 5
-- On LCURLY shift to state 6
-- On ALL shift to state 9
-- On Type shift to state 28
-- On ArrowType shift to state 13
-- On AType shift to state 14

State 3:
AType -> UCID . [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ARROW ]
-- On SEMI reduce production AType -> UCID
-- On RSQUARE reduce production AType -> UCID
-- On RPAREN reduce production AType -> UCID
-- On RCURLY reduce production AType -> UCID
-- On EQ reduce production AType -> UCID
-- On DOT reduce production AType -> UCID
-- On COMMA reduce production AType -> UCID
-- On ARROW reduce production AType -> UCID

State 4:
AType -> TTOP . [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ARROW ]
-- On SEMI reduce production AType -> TTOP
-- On RSQUARE reduce production AType -> TTOP
-- On RPAREN reduce production AType -> TTOP
-- On RCURLY reduce production AType -> TTOP
-- On EQ reduce production AType -> TTOP
-- On DOT reduce production AType -> TTOP
-- On COMMA reduce production AType -> TTOP
-- On ARROW reduce production AType -> TTOP

State 5:
AType -> LPAREN . Type RPAREN [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ARROW ]
-- On UCID shift to state 3
-- On TTOP shift to state 4
-- On LPAREN shift to state 5
-- On LCURLY shift to state 6
-- On ALL shift to state 9
-- On Type shift to state 26
-- On ArrowType shift to state 13
-- On AType shift to state 14

State 6:
AType -> LCURLY . FieldTypes RCURLY [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ARROW ]
-- On LCID shift to state 7
-- On NEFieldTypes shift to state 23
-- On FieldTypes shift to state 24
-- On RCURLY reduce production FieldTypes ->

State 7:
NEFieldTypes -> LCID . COLON Type [ RCURLY ]
NEFieldTypes -> LCID . COLON Type COMMA NEFieldTypes [ RCURLY ]
-- On COLON shift to state 8

State 8:
NEFieldTypes -> LCID COLON . Type [ RCURLY ]
NEFieldTypes -> LCID COLON . Type COMMA NEFieldTypes [ RCURLY ]
-- On UCID shift to state 3
-- On TTOP shift to state 4
-- On LPAREN shift to state 5
-- On LCURLY shift to state 6
-- On ALL shift to state 9
-- On Type shift to state 20
-- On ArrowType shift to state 13
-- On AType shift to state 14

State 9:
Type -> ALL . UCID OType DOT Type [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ]
-- On UCID shift to state 10

State 10:
Type -> ALL UCID . OType DOT Type [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ]
-- On LEQ shift to state 11
-- On OType shift to state 17
-- On DOT reduce production OType ->

State 11:
OType -> LEQ . Type [ DOT ]
-- On UCID shift to state 3
-- On TTOP shift to state 4
-- On LPAREN shift to state 5
-- On LCURLY shift to state 6
-- On ALL shift to state 9
-- On Type shift to state 12
-- On ArrowType shift to state 13
-- On AType shift to state 14

State 12:
OType -> LEQ Type . [ DOT ]
-- On DOT reduce production OType -> LEQ Type

State 13:
Type -> ArrowType . [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ]
-- On SEMI reduce production Type -> ArrowType
-- On RSQUARE reduce production Type -> ArrowType
-- On RPAREN reduce production Type -> ArrowType
-- On RCURLY reduce production Type -> ArrowType
-- On EQ reduce production Type -> ArrowType
-- On DOT reduce production Type -> ArrowType
-- On COMMA reduce production Type -> ArrowType

State 14:
ArrowType -> AType . ARROW ArrowType [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ]
ArrowType -> AType . [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ]
-- On ARROW shift to state 15
-- On SEMI reduce production ArrowType -> AType
-- On RSQUARE reduce production ArrowType -> AType
-- On RPAREN reduce production ArrowType -> AType
-- On RCURLY reduce production ArrowType -> AType
-- On EQ reduce production ArrowType -> AType
-- On DOT reduce production ArrowType -> AType
-- On COMMA reduce production ArrowType -> AType

State 15:
ArrowType -> AType ARROW . ArrowType [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ]
-- On UCID shift to state 3
-- On TTOP shift to state 4
-- On LPAREN shift to state 5
-- On LCURLY shift to state 6
-- On ArrowType shift to state 16
-- On AType shift to state 14

State 16:
ArrowType -> AType ARROW ArrowType . [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ]
-- On SEMI reduce production ArrowType -> AType ARROW ArrowType
-- On RSQUARE reduce production ArrowType -> AType ARROW ArrowType
-- On RPAREN reduce production ArrowType -> AType ARROW ArrowType
-- On RCURLY reduce production ArrowType -> AType ARROW ArrowType
-- On EQ reduce production ArrowType -> AType ARROW ArrowType
-- On DOT reduce production ArrowType -> AType ARROW ArrowType
-- On COMMA reduce production ArrowType -> AType ARROW ArrowType

State 17:
Type -> ALL UCID OType . DOT Type [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ]
-- On DOT shift to state 18

State 18:
Type -> ALL UCID OType DOT . Type [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ]
-- On UCID shift to state 3
-- On TTOP shift to state 4
-- On LPAREN shift to state 5
-- On LCURLY shift to state 6
-- On ALL shift to state 9
-- On Type shift to state 19
-- On ArrowType shift to state 13
-- On AType shift to state 14

State 19:
Type -> ALL UCID OType DOT Type . [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ]
-- On SEMI reduce production Type -> ALL UCID OType DOT Type
-- On RSQUARE reduce production Type -> ALL UCID OType DOT Type
-- On RPAREN reduce production Type -> ALL UCID OType DOT Type
-- On RCURLY reduce production Type -> ALL UCID OType DOT Type
-- On EQ reduce production Type -> ALL UCID OType DOT Type
-- On DOT reduce production Type -> ALL UCID OType DOT Type
-- On COMMA reduce production Type -> ALL UCID OType DOT Type

State 20:
NEFieldTypes -> LCID COLON Type . [ RCURLY ]
NEFieldTypes -> LCID COLON Type . COMMA NEFieldTypes [ RCURLY ]
-- On COMMA shift to state 21
-- On RCURLY reduce production NEFieldTypes -> LCID COLON Type

State 21:
NEFieldTypes -> LCID COLON Type COMMA . NEFieldTypes [ RCURLY ]
-- On LCID shift to state 7
-- On NEFieldTypes shift to state 22

State 22:
NEFieldTypes -> LCID COLON Type COMMA NEFieldTypes . [ RCURLY ]
-- On RCURLY reduce production NEFieldTypes -> LCID COLON Type COMMA NEFieldTypes

State 23:
FieldTypes -> NEFieldTypes . [ RCURLY ]
-- On RCURLY reduce production FieldTypes -> NEFieldTypes

State 24:
AType -> LCURLY FieldTypes . RCURLY [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ARROW ]
-- On RCURLY shift to state 25

State 25:
AType -> LCURLY FieldTypes RCURLY . [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ARROW ]
-- On SEMI reduce production AType -> LCURLY FieldTypes RCURLY
-- On RSQUARE reduce production AType -> LCURLY FieldTypes RCURLY
-- On RPAREN reduce production AType -> LCURLY FieldTypes RCURLY
-- On RCURLY reduce production AType -> LCURLY FieldTypes RCURLY
-- On EQ reduce production AType -> LCURLY FieldTypes RCURLY
-- On DOT reduce production AType -> LCURLY FieldTypes RCURLY
-- On COMMA reduce production AType -> LCURLY FieldTypes RCURLY
-- On ARROW reduce production AType -> LCURLY FieldTypes RCURLY

State 26:
AType -> LPAREN Type . RPAREN [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ARROW ]
-- On RPAREN shift to state 27

State 27:
AType -> LPAREN Type RPAREN . [ SEMI RSQUARE RPAREN RCURLY EQ DOT COMMA ARROW ]
-- On SEMI reduce production AType -> LPAREN Type RPAREN
-- On RSQUARE reduce production AType -> LPAREN Type RPAREN
-- On RPAREN reduce production AType -> LPAREN Type RPAREN
-- On RCURLY reduce production AType -> LPAREN Type RPAREN
-- On EQ reduce production AType -> LPAREN Type RPAREN
-- On DOT reduce production AType -> LPAREN Type RPAREN
-- On COMMA reduce production AType -> LPAREN Type RPAREN
-- On ARROW reduce production AType -> LPAREN Type RPAREN

State 28:
TyBinder -> LEQ Type . [ SEMI ]
-- On SEMI reduce production TyBinder -> LEQ Type

State 29:
toplevel -> UCID TyBinder . SEMI toplevel [ # ]
-- On SEMI shift to state 30

State 30:
toplevel -> UCID TyBinder SEMI . toplevel [ # ]
-- On UCID shift to state 1
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 85
-- On LAMBDA shift to state 52
-- On EOF shift to state 90
-- On toplevel shift to state 95
-- On Term shift to state 92
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 31:
ATerm -> LPAREN . TermSeq RPAREN [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 51
-- On LAMBDA shift to state 52
-- On TermSeq shift to state 80
-- On Term shift to state 82
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 32:
Term -> LET . Pattern EQ Term IN Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On USCORE shift to state 33
-- On LCURLY shift to state 34
-- On LCID shift to state 37
-- On Pattern shift to state 46

State 33:
Pattern -> USCORE . [ RCURLY EQ COMMA ]
-- On RCURLY reduce production Pattern -> USCORE
-- On EQ reduce production Pattern -> USCORE
-- On COMMA reduce production Pattern -> USCORE

State 34:
Pattern -> LCURLY . PatFields RCURLY [ RCURLY EQ COMMA ]
-- On LCID shift to state 35
-- On PatFields shift to state 43
-- On NEPatFields shift to state 45
-- On RCURLY reduce production PatFields ->

State 35:
NEPatFields -> LCID . EQ Pattern [ RCURLY ]
NEPatFields -> LCID . EQ Pattern COMMA NEPatFields [ RCURLY ]
-- On EQ shift to state 36

State 36:
NEPatFields -> LCID EQ . Pattern [ RCURLY ]
NEPatFields -> LCID EQ . Pattern COMMA NEPatFields [ RCURLY ]
-- On USCORE shift to state 33
-- On LCURLY shift to state 34
-- On LCID shift to state 37
-- On Pattern shift to state 40

State 37:
Pattern -> LCID . COLON Type [ RCURLY EQ COMMA ]
-- On COLON shift to state 38

State 38:
Pattern -> LCID COLON . Type [ RCURLY EQ COMMA ]
-- On UCID shift to state 3
-- On TTOP shift to state 4
-- On LPAREN shift to state 5
-- On LCURLY shift to state 6
-- On ALL shift to state 9
-- On Type shift to state 39
-- On ArrowType shift to state 13
-- On AType shift to state 14

State 39:
Pattern -> LCID COLON Type . [ RCURLY EQ COMMA ]
-- On RCURLY reduce production Pattern -> LCID COLON Type
-- On EQ reduce production Pattern -> LCID COLON Type
-- On COMMA reduce production Pattern -> LCID COLON Type

State 40:
NEPatFields -> LCID EQ Pattern . [ RCURLY ]
NEPatFields -> LCID EQ Pattern . COMMA NEPatFields [ RCURLY ]
-- On COMMA shift to state 41
-- On RCURLY reduce production NEPatFields -> LCID EQ Pattern

State 41:
NEPatFields -> LCID EQ Pattern COMMA . NEPatFields [ RCURLY ]
-- On LCID shift to state 35
-- On NEPatFields shift to state 42

State 42:
NEPatFields -> LCID EQ Pattern COMMA NEPatFields . [ RCURLY ]
-- On RCURLY reduce production NEPatFields -> LCID EQ Pattern COMMA NEPatFields

State 43:
Pattern -> LCURLY PatFields . RCURLY [ RCURLY EQ COMMA ]
-- On RCURLY shift to state 44

State 44:
Pattern -> LCURLY PatFields RCURLY . [ RCURLY EQ COMMA ]
-- On RCURLY reduce production Pattern -> LCURLY PatFields RCURLY
-- On EQ reduce production Pattern -> LCURLY PatFields RCURLY
-- On COMMA reduce production Pattern -> LCURLY PatFields RCURLY

State 45:
PatFields -> NEPatFields . [ RCURLY ]
-- On RCURLY reduce production PatFields -> NEPatFields

State 46:
Term -> LET Pattern . EQ Term IN Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On EQ shift to state 47

State 47:
Term -> LET Pattern EQ . Term IN Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 51
-- On LAMBDA shift to state 52
-- On Term shift to state 77
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 48:
ATerm -> LCURLY . Fields RCURLY [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On LCID shift to state 49
-- On NEFields shift to state 74
-- On Fields shift to state 75
-- On RCURLY reduce production Fields ->

State 49:
NEFields -> LCID . EQ Term [ RCURLY ]
NEFields -> LCID . EQ Term COMMA NEFields [ RCURLY ]
-- On EQ shift to state 50

State 50:
NEFields -> LCID EQ . Term [ RCURLY ]
NEFields -> LCID EQ . Term COMMA NEFields [ RCURLY ]
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 51
-- On LAMBDA shift to state 52
-- On Term shift to state 71
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 51:
ATerm -> LCID . [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On SEMI reduce production ATerm -> LCID
-- On RPAREN reduce production ATerm -> LCID
-- On RCURLY reduce production ATerm -> LCID
-- On LSQUARE reduce production ATerm -> LCID
-- On LPAREN reduce production ATerm -> LCID
-- On LCURLY reduce production ATerm -> LCID
-- On LCID reduce production ATerm -> LCID
-- On IN reduce production ATerm -> LCID
-- On DOT reduce production ATerm -> LCID
-- On COMMA reduce production ATerm -> LCID

State 52:
Term -> LAMBDA . LCID COLON Type DOT Term [ SEMI RPAREN RCURLY IN COMMA ]
Term -> LAMBDA . UCID OType DOT Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On UCID shift to state 53
-- On LCID shift to state 66

State 53:
Term -> LAMBDA UCID . OType DOT Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On LEQ shift to state 11
-- On OType shift to state 54
-- On DOT reduce production OType ->

State 54:
Term -> LAMBDA UCID OType . DOT Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On DOT shift to state 55

State 55:
Term -> LAMBDA UCID OType DOT . Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 51
-- On LAMBDA shift to state 52
-- On Term shift to state 56
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 56:
Term -> LAMBDA UCID OType DOT Term . [ SEMI RPAREN RCURLY IN COMMA ]
-- On SEMI reduce production Term -> LAMBDA UCID OType DOT Term
-- On RPAREN reduce production Term -> LAMBDA UCID OType DOT Term
-- On RCURLY reduce production Term -> LAMBDA UCID OType DOT Term
-- On IN reduce production Term -> LAMBDA UCID OType DOT Term
-- On COMMA reduce production Term -> LAMBDA UCID OType DOT Term

State 57:
AppTerm -> PathTerm . [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN COMMA ]
PathTerm -> PathTerm . DOT LCID [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On DOT shift to state 58
-- On SEMI reduce production AppTerm -> PathTerm
-- On RPAREN reduce production AppTerm -> PathTerm
-- On RCURLY reduce production AppTerm -> PathTerm
-- On LSQUARE reduce production AppTerm -> PathTerm
-- On LPAREN reduce production AppTerm -> PathTerm
-- On LCURLY reduce production AppTerm -> PathTerm
-- On LCID reduce production AppTerm -> PathTerm
-- On IN reduce production AppTerm -> PathTerm
-- On COMMA reduce production AppTerm -> PathTerm

State 58:
PathTerm -> PathTerm DOT . LCID [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On LCID shift to state 59

State 59:
PathTerm -> PathTerm DOT LCID . [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On SEMI reduce production PathTerm -> PathTerm DOT LCID
-- On RPAREN reduce production PathTerm -> PathTerm DOT LCID
-- On RCURLY reduce production PathTerm -> PathTerm DOT LCID
-- On LSQUARE reduce production PathTerm -> PathTerm DOT LCID
-- On LPAREN reduce production PathTerm -> PathTerm DOT LCID
-- On LCURLY reduce production PathTerm -> PathTerm DOT LCID
-- On LCID reduce production PathTerm -> PathTerm DOT LCID
-- On IN reduce production PathTerm -> PathTerm DOT LCID
-- On DOT reduce production PathTerm -> PathTerm DOT LCID
-- On COMMA reduce production PathTerm -> PathTerm DOT LCID

State 60:
AppTerm -> AppTerm . PathTerm [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN COMMA ]
AppTerm -> AppTerm . LSQUARE Type RSQUARE [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN COMMA ]
Term -> AppTerm . [ SEMI RPAREN RCURLY IN COMMA ]
-- On LSQUARE shift to state 61
-- On LPAREN shift to state 31
-- On LCURLY shift to state 48
-- On LCID shift to state 51
-- On PathTerm shift to state 64
-- On ATerm shift to state 65
-- On SEMI reduce production Term -> AppTerm
-- On RPAREN reduce production Term -> AppTerm
-- On RCURLY reduce production Term -> AppTerm
-- On IN reduce production Term -> AppTerm
-- On COMMA reduce production Term -> AppTerm

State 61:
AppTerm -> AppTerm LSQUARE . Type RSQUARE [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN COMMA ]
-- On UCID shift to state 3
-- On TTOP shift to state 4
-- On LPAREN shift to state 5
-- On LCURLY shift to state 6
-- On ALL shift to state 9
-- On Type shift to state 62
-- On ArrowType shift to state 13
-- On AType shift to state 14

State 62:
AppTerm -> AppTerm LSQUARE Type . RSQUARE [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN COMMA ]
-- On RSQUARE shift to state 63

State 63:
AppTerm -> AppTerm LSQUARE Type RSQUARE . [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN COMMA ]
-- On SEMI reduce production AppTerm -> AppTerm LSQUARE Type RSQUARE
-- On RPAREN reduce production AppTerm -> AppTerm LSQUARE Type RSQUARE
-- On RCURLY reduce production AppTerm -> AppTerm LSQUARE Type RSQUARE
-- On LSQUARE reduce production AppTerm -> AppTerm LSQUARE Type RSQUARE
-- On LPAREN reduce production AppTerm -> AppTerm LSQUARE Type RSQUARE
-- On LCURLY reduce production AppTerm -> AppTerm LSQUARE Type RSQUARE
-- On LCID reduce production AppTerm -> AppTerm LSQUARE Type RSQUARE
-- On IN reduce production AppTerm -> AppTerm LSQUARE Type RSQUARE
-- On COMMA reduce production AppTerm -> AppTerm LSQUARE Type RSQUARE

State 64:
AppTerm -> AppTerm PathTerm . [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN COMMA ]
PathTerm -> PathTerm . DOT LCID [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On DOT shift to state 58
-- On SEMI reduce production AppTerm -> AppTerm PathTerm
-- On RPAREN reduce production AppTerm -> AppTerm PathTerm
-- On RCURLY reduce production AppTerm -> AppTerm PathTerm
-- On LSQUARE reduce production AppTerm -> AppTerm PathTerm
-- On LPAREN reduce production AppTerm -> AppTerm PathTerm
-- On LCURLY reduce production AppTerm -> AppTerm PathTerm
-- On LCID reduce production AppTerm -> AppTerm PathTerm
-- On IN reduce production AppTerm -> AppTerm PathTerm
-- On COMMA reduce production AppTerm -> AppTerm PathTerm

State 65:
PathTerm -> ATerm . [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On SEMI reduce production PathTerm -> ATerm
-- On RPAREN reduce production PathTerm -> ATerm
-- On RCURLY reduce production PathTerm -> ATerm
-- On LSQUARE reduce production PathTerm -> ATerm
-- On LPAREN reduce production PathTerm -> ATerm
-- On LCURLY reduce production PathTerm -> ATerm
-- On LCID reduce production PathTerm -> ATerm
-- On IN reduce production PathTerm -> ATerm
-- On DOT reduce production PathTerm -> ATerm
-- On COMMA reduce production PathTerm -> ATerm

State 66:
Term -> LAMBDA LCID . COLON Type DOT Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On COLON shift to state 67

State 67:
Term -> LAMBDA LCID COLON . Type DOT Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On UCID shift to state 3
-- On TTOP shift to state 4
-- On LPAREN shift to state 5
-- On LCURLY shift to state 6
-- On ALL shift to state 9
-- On Type shift to state 68
-- On ArrowType shift to state 13
-- On AType shift to state 14

State 68:
Term -> LAMBDA LCID COLON Type . DOT Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On DOT shift to state 69

State 69:
Term -> LAMBDA LCID COLON Type DOT . Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 51
-- On LAMBDA shift to state 52
-- On Term shift to state 70
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 70:
Term -> LAMBDA LCID COLON Type DOT Term . [ SEMI RPAREN RCURLY IN COMMA ]
-- On SEMI reduce production Term -> LAMBDA LCID COLON Type DOT Term
-- On RPAREN reduce production Term -> LAMBDA LCID COLON Type DOT Term
-- On RCURLY reduce production Term -> LAMBDA LCID COLON Type DOT Term
-- On IN reduce production Term -> LAMBDA LCID COLON Type DOT Term
-- On COMMA reduce production Term -> LAMBDA LCID COLON Type DOT Term

State 71:
NEFields -> LCID EQ Term . [ RCURLY ]
NEFields -> LCID EQ Term . COMMA NEFields [ RCURLY ]
-- On COMMA shift to state 72
-- On RCURLY reduce production NEFields -> LCID EQ Term

State 72:
NEFields -> LCID EQ Term COMMA . NEFields [ RCURLY ]
-- On LCID shift to state 49
-- On NEFields shift to state 73

State 73:
NEFields -> LCID EQ Term COMMA NEFields . [ RCURLY ]
-- On RCURLY reduce production NEFields -> LCID EQ Term COMMA NEFields

State 74:
Fields -> NEFields . [ RCURLY ]
-- On RCURLY reduce production Fields -> NEFields

State 75:
ATerm -> LCURLY Fields . RCURLY [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On RCURLY shift to state 76

State 76:
ATerm -> LCURLY Fields RCURLY . [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On SEMI reduce production ATerm -> LCURLY Fields RCURLY
-- On RPAREN reduce production ATerm -> LCURLY Fields RCURLY
-- On RCURLY reduce production ATerm -> LCURLY Fields RCURLY
-- On LSQUARE reduce production ATerm -> LCURLY Fields RCURLY
-- On LPAREN reduce production ATerm -> LCURLY Fields RCURLY
-- On LCURLY reduce production ATerm -> LCURLY Fields RCURLY
-- On LCID reduce production ATerm -> LCURLY Fields RCURLY
-- On IN reduce production ATerm -> LCURLY Fields RCURLY
-- On DOT reduce production ATerm -> LCURLY Fields RCURLY
-- On COMMA reduce production ATerm -> LCURLY Fields RCURLY

State 77:
Term -> LET Pattern EQ Term . IN Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On IN shift to state 78

State 78:
Term -> LET Pattern EQ Term IN . Term [ SEMI RPAREN RCURLY IN COMMA ]
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 51
-- On LAMBDA shift to state 52
-- On Term shift to state 79
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 79:
Term -> LET Pattern EQ Term IN Term . [ SEMI RPAREN RCURLY IN COMMA ]
-- On SEMI reduce production Term -> LET Pattern EQ Term IN Term
-- On RPAREN reduce production Term -> LET Pattern EQ Term IN Term
-- On RCURLY reduce production Term -> LET Pattern EQ Term IN Term
-- On IN reduce production Term -> LET Pattern EQ Term IN Term
-- On COMMA reduce production Term -> LET Pattern EQ Term IN Term

State 80:
ATerm -> LPAREN TermSeq . RPAREN [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On RPAREN shift to state 81

State 81:
ATerm -> LPAREN TermSeq RPAREN . [ SEMI RPAREN RCURLY LSQUARE LPAREN LCURLY LCID IN DOT COMMA ]
-- On SEMI reduce production ATerm -> LPAREN TermSeq RPAREN
-- On RPAREN reduce production ATerm -> LPAREN TermSeq RPAREN
-- On RCURLY reduce production ATerm -> LPAREN TermSeq RPAREN
-- On LSQUARE reduce production ATerm -> LPAREN TermSeq RPAREN
-- On LPAREN reduce production ATerm -> LPAREN TermSeq RPAREN
-- On LCURLY reduce production ATerm -> LPAREN TermSeq RPAREN
-- On LCID reduce production ATerm -> LPAREN TermSeq RPAREN
-- On IN reduce production ATerm -> LPAREN TermSeq RPAREN
-- On DOT reduce production ATerm -> LPAREN TermSeq RPAREN
-- On COMMA reduce production ATerm -> LPAREN TermSeq RPAREN

State 82:
TermSeq -> Term . [ RPAREN ]
TermSeq -> Term . SEMI TermSeq [ RPAREN ]
-- On SEMI shift to state 83
-- On RPAREN reduce production TermSeq -> Term

State 83:
TermSeq -> Term SEMI . TermSeq [ RPAREN ]
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 51
-- On LAMBDA shift to state 52
-- On TermSeq shift to state 84
-- On Term shift to state 82
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 84:
TermSeq -> Term SEMI TermSeq . [ RPAREN ]
-- On RPAREN reduce production TermSeq -> Term SEMI TermSeq

State 85:
ATerm -> LCID . [ SEMI LSQUARE LPAREN LCURLY LCID DOT ]
toplevel -> LCID . Binder SEMI toplevel [ # ]
-- On COLON shift to state 86
-- On Binder shift to state 88
-- On SEMI reduce production ATerm -> LCID
-- On LSQUARE reduce production ATerm -> LCID
-- On LPAREN reduce production ATerm -> LCID
-- On LCURLY reduce production ATerm -> LCID
-- On LCID reduce production ATerm -> LCID
-- On DOT reduce production ATerm -> LCID

State 86:
Binder -> COLON . Type [ SEMI ]
-- On UCID shift to state 3
-- On TTOP shift to state 4
-- On LPAREN shift to state 5
-- On LCURLY shift to state 6
-- On ALL shift to state 9
-- On Type shift to state 87
-- On ArrowType shift to state 13
-- On AType shift to state 14

State 87:
Binder -> COLON Type . [ SEMI ]
-- On SEMI reduce production Binder -> COLON Type

State 88:
toplevel -> LCID Binder . SEMI toplevel [ # ]
-- On SEMI shift to state 89

State 89:
toplevel -> LCID Binder SEMI . toplevel [ # ]
-- On UCID shift to state 1
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 85
-- On LAMBDA shift to state 52
-- On EOF shift to state 90
-- On toplevel shift to state 91
-- On Term shift to state 92
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 90:
toplevel -> EOF . [ # ]
-- On # reduce production toplevel -> EOF

State 91:
toplevel -> LCID Binder SEMI toplevel . [ # ]
-- On # reduce production toplevel -> LCID Binder SEMI toplevel

State 92:
toplevel -> Term . SEMI toplevel [ # ]
-- On SEMI shift to state 93

State 93:
toplevel -> Term SEMI . toplevel [ # ]
-- On UCID shift to state 1
-- On LPAREN shift to state 31
-- On LET shift to state 32
-- On LCURLY shift to state 48
-- On LCID shift to state 85
-- On LAMBDA shift to state 52
-- On EOF shift to state 90
-- On toplevel shift to state 94
-- On Term shift to state 92
-- On PathTerm shift to state 57
-- On AppTerm shift to state 60
-- On ATerm shift to state 65

State 94:
toplevel -> Term SEMI toplevel . [ # ]
-- On # reduce production toplevel -> Term SEMI toplevel

State 95:
toplevel -> UCID TyBinder SEMI toplevel . [ # ]
-- On # reduce production toplevel -> UCID TyBinder SEMI toplevel

State 96:
toplevel' -> toplevel . [ # ]
-- On # accept toplevel

