State 0:
toplevel' -> . toplevel [ # ]
-- On UCID shift to state 1
-- On LPAREN shift to state 91
-- On LCID shift to state 95
-- On LAMBDA shift to state 12
-- On IMPORT shift to state 103
-- On EOF shift to state 105
-- On ALL shift to state 31
-- On toplevel shift to state 106
-- On Term shift to state 107
-- On PathTerm shift to state 37
-- On Command shift to state 108
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 1:
Command -> UCID . TyBinder [ SEMI ]
-- On EQ shift to state 2
-- On COLON shift to state 66
-- On TyBinder shift to state 90

State 2:
TyBinder -> EQ . Type [ SEMI ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 65
-- On AppType shift to state 21
-- On AType shift to state 24

State 3:
AType -> UCID . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On SEMI reduce production AType -> UCID
-- On RPAREN reduce production AType -> UCID
-- On LPAREN reduce production AType -> UCID
-- On LCID reduce production AType -> UCID
-- On DOT reduce production AType -> UCID
-- On ARROW reduce production AType -> UCID

State 4:
Type -> SIGMA . LCID COLON Type DOT Type [ SEMI RPAREN DOT ]
-- On LCID shift to state 5

State 5:
Type -> SIGMA LCID . COLON Type DOT Type [ SEMI RPAREN DOT ]
-- On COLON shift to state 6

State 6:
Type -> SIGMA LCID COLON . Type DOT Type [ SEMI RPAREN DOT ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 62
-- On AppType shift to state 21
-- On AType shift to state 24

State 7:
AType -> PROP . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On SEMI reduce production AType -> PROP
-- On RPAREN reduce production AType -> PROP
-- On LPAREN reduce production AType -> PROP
-- On LCID reduce production AType -> PROP
-- On DOT reduce production AType -> PROP
-- On ARROW reduce production AType -> PROP

State 8:
AType -> PRF . LPAREN Term RPAREN [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On LPAREN shift to state 9

State 9:
AType -> PRF LPAREN . Term RPAREN [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 60
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 10:
ATerm -> LPAREN . Term RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
ATerm -> LPAREN . Term COMMA TermList COLON Type RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 50
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 11:
ATerm -> LCID . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
-- On SEMI reduce production ATerm -> LCID
-- On RPAREN reduce production ATerm -> LCID
-- On LPAREN reduce production ATerm -> LCID
-- On LCID reduce production ATerm -> LCID
-- On DOT reduce production ATerm -> LCID
-- On COMMA reduce production ATerm -> LCID
-- On COLON reduce production ATerm -> LCID
-- On ARROW reduce production ATerm -> LCID

State 12:
Term -> LAMBDA . LCID COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
Term -> LAMBDA . USCORE COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
-- On USCORE shift to state 13
-- On LCID shift to state 45

State 13:
Term -> LAMBDA USCORE . COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
-- On COLON shift to state 14

State 14:
Term -> LAMBDA USCORE COLON . Type DOT Term [ SEMI RPAREN COMMA COLON ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 29
-- On AppType shift to state 21
-- On AType shift to state 24

State 15:
Type -> PI . LCID COLON Type DOT Type [ SEMI RPAREN DOT ]
-- On LCID shift to state 16

State 16:
Type -> PI LCID . COLON Type DOT Type [ SEMI RPAREN DOT ]
-- On COLON shift to state 17

State 17:
Type -> PI LCID COLON . Type DOT Type [ SEMI RPAREN DOT ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 26
-- On AppType shift to state 21
-- On AType shift to state 24

State 18:
AType -> LPAREN . Type RPAREN [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 19
-- On AppType shift to state 21
-- On AType shift to state 24

State 19:
AType -> LPAREN Type . RPAREN [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On RPAREN shift to state 20

State 20:
AType -> LPAREN Type RPAREN . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On SEMI reduce production AType -> LPAREN Type RPAREN
-- On RPAREN reduce production AType -> LPAREN Type RPAREN
-- On LPAREN reduce production AType -> LPAREN Type RPAREN
-- On LCID reduce production AType -> LPAREN Type RPAREN
-- On DOT reduce production AType -> LPAREN Type RPAREN
-- On ARROW reduce production AType -> LPAREN Type RPAREN

State 21:
AppType -> AppType . ATerm [ SEMI RPAREN LPAREN LCID DOT ARROW ]
Type -> AppType . [ SEMI RPAREN DOT ]
Type -> AppType . ARROW Type [ SEMI RPAREN DOT ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On ARROW shift to state 22
-- On ATerm shift to state 25
-- On SEMI reduce production Type -> AppType
-- On RPAREN reduce production Type -> AppType
-- On DOT reduce production Type -> AppType

State 22:
Type -> AppType ARROW . Type [ SEMI RPAREN DOT ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 23
-- On AppType shift to state 21
-- On AType shift to state 24

State 23:
Type -> AppType ARROW Type . [ SEMI RPAREN DOT ]
-- On SEMI reduce production Type -> AppType ARROW Type
-- On RPAREN reduce production Type -> AppType ARROW Type
-- On DOT reduce production Type -> AppType ARROW Type

State 24:
AppType -> AType . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On SEMI reduce production AppType -> AType
-- On RPAREN reduce production AppType -> AType
-- On LPAREN reduce production AppType -> AType
-- On LCID reduce production AppType -> AType
-- On DOT reduce production AppType -> AType
-- On ARROW reduce production AppType -> AType

State 25:
AppType -> AppType ATerm . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On SEMI reduce production AppType -> AppType ATerm
-- On RPAREN reduce production AppType -> AppType ATerm
-- On LPAREN reduce production AppType -> AppType ATerm
-- On LCID reduce production AppType -> AppType ATerm
-- On DOT reduce production AppType -> AppType ATerm
-- On ARROW reduce production AppType -> AppType ATerm

State 26:
Type -> PI LCID COLON Type . DOT Type [ SEMI RPAREN DOT ]
-- On DOT shift to state 27

State 27:
Type -> PI LCID COLON Type DOT . Type [ SEMI RPAREN DOT ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 28
-- On AppType shift to state 21
-- On AType shift to state 24

State 28:
Type -> PI LCID COLON Type DOT Type . [ SEMI RPAREN DOT ]
-- On SEMI reduce production Type -> PI LCID COLON Type DOT Type
-- On RPAREN reduce production Type -> PI LCID COLON Type DOT Type
-- On DOT reduce production Type -> PI LCID COLON Type DOT Type

State 29:
Term -> LAMBDA USCORE COLON Type . DOT Term [ SEMI RPAREN COMMA COLON ]
-- On DOT shift to state 30

State 30:
Term -> LAMBDA USCORE COLON Type DOT . Term [ SEMI RPAREN COMMA COLON ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 44
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 31:
Term -> ALL . LCID COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
-- On LCID shift to state 32

State 32:
Term -> ALL LCID . COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
-- On COLON shift to state 33

State 33:
Term -> ALL LCID COLON . Type DOT Term [ SEMI RPAREN COMMA COLON ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 34
-- On AppType shift to state 21
-- On AType shift to state 24

State 34:
Term -> ALL LCID COLON Type . DOT Term [ SEMI RPAREN COMMA COLON ]
-- On DOT shift to state 35

State 35:
Term -> ALL LCID COLON Type DOT . Term [ SEMI RPAREN COMMA COLON ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 36
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 36:
Term -> ALL LCID COLON Type DOT Term . [ SEMI RPAREN COMMA COLON ]
-- On SEMI reduce production Term -> ALL LCID COLON Type DOT Term
-- On RPAREN reduce production Term -> ALL LCID COLON Type DOT Term
-- On COMMA reduce production Term -> ALL LCID COLON Type DOT Term
-- On COLON reduce production Term -> ALL LCID COLON Type DOT Term

State 37:
AppTerm -> PathTerm . [ SEMI RPAREN LPAREN LCID COMMA COLON ]
PathTerm -> PathTerm . DOT TWO [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
PathTerm -> PathTerm . DOT ONE [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
-- On DOT shift to state 38
-- On SEMI reduce production AppTerm -> PathTerm
-- On RPAREN reduce production AppTerm -> PathTerm
-- On LPAREN reduce production AppTerm -> PathTerm
-- On LCID reduce production AppTerm -> PathTerm
-- On COMMA reduce production AppTerm -> PathTerm
-- On COLON reduce production AppTerm -> PathTerm

State 38:
PathTerm -> PathTerm DOT . TWO [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
PathTerm -> PathTerm DOT . ONE [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
-- On TWO shift to state 39
-- On ONE shift to state 40

State 39:
PathTerm -> PathTerm DOT TWO . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
-- On SEMI reduce production PathTerm -> PathTerm DOT TWO
-- On RPAREN reduce production PathTerm -> PathTerm DOT TWO
-- On LPAREN reduce production PathTerm -> PathTerm DOT TWO
-- On LCID reduce production PathTerm -> PathTerm DOT TWO
-- On DOT reduce production PathTerm -> PathTerm DOT TWO
-- On COMMA reduce production PathTerm -> PathTerm DOT TWO
-- On COLON reduce production PathTerm -> PathTerm DOT TWO

State 40:
PathTerm -> PathTerm DOT ONE . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
-- On SEMI reduce production PathTerm -> PathTerm DOT ONE
-- On RPAREN reduce production PathTerm -> PathTerm DOT ONE
-- On LPAREN reduce production PathTerm -> PathTerm DOT ONE
-- On LCID reduce production PathTerm -> PathTerm DOT ONE
-- On DOT reduce production PathTerm -> PathTerm DOT ONE
-- On COMMA reduce production PathTerm -> PathTerm DOT ONE
-- On COLON reduce production PathTerm -> PathTerm DOT ONE

State 41:
AppTerm -> AppTerm . ATerm [ SEMI RPAREN LPAREN LCID COMMA COLON ]
Term -> AppTerm . [ SEMI RPAREN COMMA COLON ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On ATerm shift to state 42
-- On SEMI reduce production Term -> AppTerm
-- On RPAREN reduce production Term -> AppTerm
-- On COMMA reduce production Term -> AppTerm
-- On COLON reduce production Term -> AppTerm

State 42:
AppTerm -> AppTerm ATerm . [ SEMI RPAREN LPAREN LCID COMMA COLON ]
-- On SEMI reduce production AppTerm -> AppTerm ATerm
-- On RPAREN reduce production AppTerm -> AppTerm ATerm
-- On LPAREN reduce production AppTerm -> AppTerm ATerm
-- On LCID reduce production AppTerm -> AppTerm ATerm
-- On COMMA reduce production AppTerm -> AppTerm ATerm
-- On COLON reduce production AppTerm -> AppTerm ATerm

State 43:
PathTerm -> ATerm . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
-- On SEMI reduce production PathTerm -> ATerm
-- On RPAREN reduce production PathTerm -> ATerm
-- On LPAREN reduce production PathTerm -> ATerm
-- On LCID reduce production PathTerm -> ATerm
-- On DOT reduce production PathTerm -> ATerm
-- On COMMA reduce production PathTerm -> ATerm
-- On COLON reduce production PathTerm -> ATerm

State 44:
Term -> LAMBDA USCORE COLON Type DOT Term . [ SEMI RPAREN COMMA COLON ]
-- On SEMI reduce production Term -> LAMBDA USCORE COLON Type DOT Term
-- On RPAREN reduce production Term -> LAMBDA USCORE COLON Type DOT Term
-- On COMMA reduce production Term -> LAMBDA USCORE COLON Type DOT Term
-- On COLON reduce production Term -> LAMBDA USCORE COLON Type DOT Term

State 45:
Term -> LAMBDA LCID . COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
-- On COLON shift to state 46

State 46:
Term -> LAMBDA LCID COLON . Type DOT Term [ SEMI RPAREN COMMA COLON ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 47
-- On AppType shift to state 21
-- On AType shift to state 24

State 47:
Term -> LAMBDA LCID COLON Type . DOT Term [ SEMI RPAREN COMMA COLON ]
-- On DOT shift to state 48

State 48:
Term -> LAMBDA LCID COLON Type DOT . Term [ SEMI RPAREN COMMA COLON ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 49
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 49:
Term -> LAMBDA LCID COLON Type DOT Term . [ SEMI RPAREN COMMA COLON ]
-- On SEMI reduce production Term -> LAMBDA LCID COLON Type DOT Term
-- On RPAREN reduce production Term -> LAMBDA LCID COLON Type DOT Term
-- On COMMA reduce production Term -> LAMBDA LCID COLON Type DOT Term
-- On COLON reduce production Term -> LAMBDA LCID COLON Type DOT Term

State 50:
ATerm -> LPAREN Term . RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
ATerm -> LPAREN Term . COMMA TermList COLON Type RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
-- On RPAREN shift to state 51
-- On COMMA shift to state 52

State 51:
ATerm -> LPAREN Term RPAREN . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
-- On SEMI reduce production ATerm -> LPAREN Term RPAREN
-- On RPAREN reduce production ATerm -> LPAREN Term RPAREN
-- On LPAREN reduce production ATerm -> LPAREN Term RPAREN
-- On LCID reduce production ATerm -> LPAREN Term RPAREN
-- On DOT reduce production ATerm -> LPAREN Term RPAREN
-- On COMMA reduce production ATerm -> LPAREN Term RPAREN
-- On COLON reduce production ATerm -> LPAREN Term RPAREN
-- On ARROW reduce production ATerm -> LPAREN Term RPAREN

State 52:
ATerm -> LPAREN Term COMMA . TermList COLON Type RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On TermList shift to state 53
-- On Term shift to state 57
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 53:
ATerm -> LPAREN Term COMMA TermList . COLON Type RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
-- On COLON shift to state 54

State 54:
ATerm -> LPAREN Term COMMA TermList COLON . Type RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 55
-- On AppType shift to state 21
-- On AType shift to state 24

State 55:
ATerm -> LPAREN Term COMMA TermList COLON Type . RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
-- On RPAREN shift to state 56

State 56:
ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
-- On SEMI reduce production ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN
-- On RPAREN reduce production ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN
-- On LPAREN reduce production ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN
-- On LCID reduce production ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN
-- On DOT reduce production ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN
-- On COMMA reduce production ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN
-- On COLON reduce production ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN
-- On ARROW reduce production ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN

State 57:
TermList -> Term . [ COLON ]
TermList -> Term . COMMA TermList [ COLON ]
-- On COMMA shift to state 58
-- On COLON reduce production TermList -> Term

State 58:
TermList -> Term COMMA . TermList [ COLON ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On TermList shift to state 59
-- On Term shift to state 57
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 59:
TermList -> Term COMMA TermList . [ COLON ]
-- On COLON reduce production TermList -> Term COMMA TermList

State 60:
AType -> PRF LPAREN Term . RPAREN [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On RPAREN shift to state 61

State 61:
AType -> PRF LPAREN Term RPAREN . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
-- On SEMI reduce production AType -> PRF LPAREN Term RPAREN
-- On RPAREN reduce production AType -> PRF LPAREN Term RPAREN
-- On LPAREN reduce production AType -> PRF LPAREN Term RPAREN
-- On LCID reduce production AType -> PRF LPAREN Term RPAREN
-- On DOT reduce production AType -> PRF LPAREN Term RPAREN
-- On ARROW reduce production AType -> PRF LPAREN Term RPAREN

State 62:
Type -> SIGMA LCID COLON Type . DOT Type [ SEMI RPAREN DOT ]
-- On DOT shift to state 63

State 63:
Type -> SIGMA LCID COLON Type DOT . Type [ SEMI RPAREN DOT ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 64
-- On AppType shift to state 21
-- On AType shift to state 24

State 64:
Type -> SIGMA LCID COLON Type DOT Type . [ SEMI RPAREN DOT ]
-- On SEMI reduce production Type -> SIGMA LCID COLON Type DOT Type
-- On RPAREN reduce production Type -> SIGMA LCID COLON Type DOT Type
-- On DOT reduce production Type -> SIGMA LCID COLON Type DOT Type

State 65:
TyBinder -> EQ Type . [ SEMI ]
-- On SEMI reduce production TyBinder -> EQ Type

State 66:
TyBinder -> COLON . Kind [ SEMI ]
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 68
-- On LPAREN shift to state 73
-- On Kind shift to state 89
-- On ArrowKind shift to state 80
-- On AppType shift to state 87
-- On AType shift to state 24
-- On AKind shift to state 84

State 67:
AKind -> STAR . [ SEMI RPAREN ]
-- On SEMI reduce production AKind -> STAR
-- On RPAREN reduce production AKind -> STAR

State 68:
Kind -> PI . LCID COLON Type DOT Kind [ SEMI ]
-- On LCID shift to state 69

State 69:
Kind -> PI LCID . COLON Type DOT Kind [ SEMI ]
-- On COLON shift to state 70

State 70:
Kind -> PI LCID COLON . Type DOT Kind [ SEMI ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 71
-- On AppType shift to state 21
-- On AType shift to state 24

State 71:
Kind -> PI LCID COLON Type . DOT Kind [ SEMI ]
-- On DOT shift to state 72

State 72:
Kind -> PI LCID COLON Type DOT . Kind [ SEMI ]
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 68
-- On LPAREN shift to state 73
-- On Kind shift to state 79
-- On ArrowKind shift to state 80
-- On AppType shift to state 87
-- On AType shift to state 24
-- On AKind shift to state 84

State 73:
AKind -> LPAREN . Kind RPAREN [ SEMI RPAREN ]
AType -> LPAREN . Type RPAREN [ RPAREN LPAREN LCID ARROW ]
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 74
-- On LPAREN shift to state 73
-- On Type shift to state 19
-- On Kind shift to state 85
-- On ArrowKind shift to state 80
-- On AppType shift to state 81
-- On AType shift to state 24
-- On AKind shift to state 84

State 74:
Kind -> PI . LCID COLON Type DOT Kind [ RPAREN ]
Type -> PI . LCID COLON Type DOT Type [ RPAREN ]
-- On LCID shift to state 75

State 75:
Kind -> PI LCID . COLON Type DOT Kind [ RPAREN ]
Type -> PI LCID . COLON Type DOT Type [ RPAREN ]
-- On COLON shift to state 76

State 76:
Kind -> PI LCID COLON . Type DOT Kind [ RPAREN ]
Type -> PI LCID COLON . Type DOT Type [ RPAREN ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 77
-- On AppType shift to state 21
-- On AType shift to state 24

State 77:
Kind -> PI LCID COLON Type . DOT Kind [ RPAREN ]
Type -> PI LCID COLON Type . DOT Type [ RPAREN ]
-- On DOT shift to state 78

State 78:
Kind -> PI LCID COLON Type DOT . Kind [ RPAREN ]
Type -> PI LCID COLON Type DOT . Type [ RPAREN ]
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 74
-- On LPAREN shift to state 73
-- On Type shift to state 28
-- On Kind shift to state 79
-- On ArrowKind shift to state 80
-- On AppType shift to state 81
-- On AType shift to state 24
-- On AKind shift to state 84

State 79:
Kind -> PI LCID COLON Type DOT Kind . [ SEMI RPAREN ]
-- On SEMI reduce production Kind -> PI LCID COLON Type DOT Kind
-- On RPAREN reduce production Kind -> PI LCID COLON Type DOT Kind

State 80:
Kind -> ArrowKind . [ SEMI RPAREN ]
-- On SEMI reduce production Kind -> ArrowKind
-- On RPAREN reduce production Kind -> ArrowKind

State 81:
AppType -> AppType . ATerm [ RPAREN LPAREN LCID ARROW ]
ArrowKind -> AppType . ARROW ArrowKind [ RPAREN ]
Type -> AppType . [ RPAREN ]
Type -> AppType . ARROW Type [ RPAREN ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On ARROW shift to state 82
-- On ATerm shift to state 25
-- On RPAREN reduce production Type -> AppType

State 82:
ArrowKind -> AppType ARROW . ArrowKind [ RPAREN ]
Type -> AppType ARROW . Type [ RPAREN ]
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 73
-- On Type shift to state 23
-- On ArrowKind shift to state 83
-- On AppType shift to state 81
-- On AType shift to state 24
-- On AKind shift to state 84

State 83:
ArrowKind -> AppType ARROW ArrowKind . [ SEMI RPAREN ]
-- On SEMI reduce production ArrowKind -> AppType ARROW ArrowKind
-- On RPAREN reduce production ArrowKind -> AppType ARROW ArrowKind

State 84:
ArrowKind -> AKind . [ SEMI RPAREN ]
-- On SEMI reduce production ArrowKind -> AKind
-- On RPAREN reduce production ArrowKind -> AKind

State 85:
AKind -> LPAREN Kind . RPAREN [ SEMI RPAREN ]
-- On RPAREN shift to state 86

State 86:
AKind -> LPAREN Kind RPAREN . [ SEMI RPAREN ]
-- On SEMI reduce production AKind -> LPAREN Kind RPAREN
-- On RPAREN reduce production AKind -> LPAREN Kind RPAREN

State 87:
AppType -> AppType . ATerm [ LPAREN LCID ARROW ]
ArrowKind -> AppType . ARROW ArrowKind [ SEMI ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On ARROW shift to state 88
-- On ATerm shift to state 25

State 88:
ArrowKind -> AppType ARROW . ArrowKind [ SEMI ]
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On LPAREN shift to state 73
-- On ArrowKind shift to state 83
-- On AppType shift to state 87
-- On AType shift to state 24
-- On AKind shift to state 84

State 89:
TyBinder -> COLON Kind . [ SEMI ]
-- On SEMI reduce production TyBinder -> COLON Kind

State 90:
Command -> UCID TyBinder . [ SEMI ]
-- On SEMI reduce production Command -> UCID TyBinder

State 91:
ATerm -> LPAREN . Term RPAREN [ SEMI LPAREN LCID DOT ]
ATerm -> LPAREN . Term COMMA TermList COLON Type RPAREN [ SEMI LPAREN LCID DOT ]
Command -> LPAREN . NORMAL Term RPAREN [ SEMI ]
-- On NORMAL shift to state 92
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 50
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 92:
Command -> LPAREN NORMAL . Term RPAREN [ SEMI ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 93
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 93:
Command -> LPAREN NORMAL Term . RPAREN [ SEMI ]
-- On RPAREN shift to state 94

State 94:
Command -> LPAREN NORMAL Term RPAREN . [ SEMI ]
-- On SEMI reduce production Command -> LPAREN NORMAL Term RPAREN

State 95:
ATerm -> LCID . [ SEMI LPAREN LCID DOT ]
Command -> LCID . Binder [ SEMI ]
-- On EQ shift to state 96
-- On COLON shift to state 100
-- On Binder shift to state 102
-- On SEMI reduce production ATerm -> LCID
-- On LPAREN reduce production ATerm -> LCID
-- On LCID reduce production ATerm -> LCID
-- On DOT reduce production ATerm -> LCID

State 96:
Binder -> EQ . Term [ SEMI ]
Binder -> EQ . Term COLON Type [ SEMI ]
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 97
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 97:
Binder -> EQ Term . [ SEMI ]
Binder -> EQ Term . COLON Type [ SEMI ]
-- On COLON shift to state 98
-- On SEMI reduce production Binder -> EQ Term

State 98:
Binder -> EQ Term COLON . Type [ SEMI ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 99
-- On AppType shift to state 21
-- On AType shift to state 24

State 99:
Binder -> EQ Term COLON Type . [ SEMI ]
-- On SEMI reduce production Binder -> EQ Term COLON Type

State 100:
Binder -> COLON . Type [ SEMI ]
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 101
-- On AppType shift to state 21
-- On AType shift to state 24

State 101:
Binder -> COLON Type . [ SEMI ]
-- On SEMI reduce production Binder -> COLON Type

State 102:
Command -> LCID Binder . [ SEMI ]
-- On SEMI reduce production Command -> LCID Binder

State 103:
Command -> IMPORT . STRINGV [ SEMI ]
-- On STRINGV shift to state 104

State 104:
Command -> IMPORT STRINGV . [ SEMI ]
-- On SEMI reduce production Command -> IMPORT STRINGV

State 105:
toplevel -> EOF . [ # ]
-- On # reduce production toplevel -> EOF

State 106:
toplevel' -> toplevel . [ # ]
-- On # accept toplevel

State 107:
Command -> Term . [ SEMI ]
-- On SEMI reduce production Command -> Term

State 108:
toplevel -> Command . SEMI toplevel [ # ]
-- On SEMI shift to state 109

State 109:
toplevel -> Command SEMI . toplevel [ # ]
-- On UCID shift to state 1
-- On LPAREN shift to state 91
-- On LCID shift to state 95
-- On LAMBDA shift to state 12
-- On IMPORT shift to state 103
-- On EOF shift to state 105
-- On ALL shift to state 31
-- On toplevel shift to state 110
-- On Term shift to state 107
-- On PathTerm shift to state 37
-- On Command shift to state 108
-- On AppTerm shift to state 41
-- On ATerm shift to state 43

State 110:
toplevel -> Command SEMI toplevel . [ # ]
-- On # reduce production toplevel -> Command SEMI toplevel

