State 0:
## Known stack suffix:
##
## LR(1) items:
toplevel' -> . toplevel [ # ]
## Transitions:
-- On UCID shift to state 1
-- On LPAREN shift to state 91
-- On LCID shift to state 95
-- On LAMBDA shift to state 12
-- On IMPORT shift to state 103
-- On EOF shift to state 105
-- On ALL shift to state 31
-- On toplevel shift to state 106
-- On Term shift to state 107
-- On PathTerm shift to state 37
-- On Command shift to state 108
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 1:
## Known stack suffix:
## UCID
## LR(1) items:
Command -> UCID . TyBinder [ SEMI ]
## Transitions:
-- On EQ shift to state 2
-- On COLON shift to state 66
-- On TyBinder shift to state 90
## Reductions:

State 2:
## Known stack suffix:
## EQ
## LR(1) items:
TyBinder -> EQ . Type [ SEMI ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 65
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 3:
## Known stack suffix:
## UCID
## LR(1) items:
AType -> UCID . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT ARROW
--   reduce production AType -> UCID

State 4:
## Known stack suffix:
## SIGMA
## LR(1) items:
Type -> SIGMA . LCID COLON Type DOT Type [ SEMI RPAREN DOT ]
## Transitions:
-- On LCID shift to state 5
## Reductions:

State 5:
## Known stack suffix:
## SIGMA LCID
## LR(1) items:
Type -> SIGMA LCID . COLON Type DOT Type [ SEMI RPAREN DOT ]
## Transitions:
-- On COLON shift to state 6
## Reductions:

State 6:
## Known stack suffix:
## SIGMA LCID COLON
## LR(1) items:
Type -> SIGMA LCID COLON . Type DOT Type [ SEMI RPAREN DOT ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 62
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 7:
## Known stack suffix:
## PROP
## LR(1) items:
AType -> PROP . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT ARROW
--   reduce production AType -> PROP

State 8:
## Known stack suffix:
## PRF
## LR(1) items:
AType -> PRF . LPAREN Term RPAREN [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
-- On LPAREN shift to state 9
## Reductions:

State 9:
## Known stack suffix:
## PRF LPAREN
## LR(1) items:
AType -> PRF LPAREN . Term RPAREN [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 60
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 10:
## Known stack suffix:
## LPAREN
## LR(1) items:
ATerm -> LPAREN . Term RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
ATerm -> LPAREN . Term COMMA TermList COLON Type RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 50
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 11:
## Known stack suffix:
## LCID
## LR(1) items:
ATerm -> LCID . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW
--   reduce production ATerm -> LCID

State 12:
## Known stack suffix:
## LAMBDA
## LR(1) items:
Term -> LAMBDA . LCID COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
Term -> LAMBDA . USCORE COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On USCORE shift to state 13
-- On LCID shift to state 45
## Reductions:

State 13:
## Known stack suffix:
## LAMBDA USCORE
## LR(1) items:
Term -> LAMBDA USCORE . COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On COLON shift to state 14
## Reductions:

State 14:
## Known stack suffix:
## LAMBDA USCORE COLON
## LR(1) items:
Term -> LAMBDA USCORE COLON . Type DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 29
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 15:
## Known stack suffix:
## PI
## LR(1) items:
Type -> PI . LCID COLON Type DOT Type [ SEMI RPAREN DOT ]
## Transitions:
-- On LCID shift to state 16
## Reductions:

State 16:
## Known stack suffix:
## PI LCID
## LR(1) items:
Type -> PI LCID . COLON Type DOT Type [ SEMI RPAREN DOT ]
## Transitions:
-- On COLON shift to state 17
## Reductions:

State 17:
## Known stack suffix:
## PI LCID COLON
## LR(1) items:
Type -> PI LCID COLON . Type DOT Type [ SEMI RPAREN DOT ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 26
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 18:
## Known stack suffix:
## LPAREN
## LR(1) items:
AType -> LPAREN . Type RPAREN [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 19
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 19:
## Known stack suffix:
## LPAREN Type
## LR(1) items:
AType -> LPAREN Type . RPAREN [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
-- On RPAREN shift to state 20
## Reductions:

State 20:
## Known stack suffix:
## LPAREN Type RPAREN
## LR(1) items:
AType -> LPAREN Type RPAREN . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT ARROW
--   reduce production AType -> LPAREN Type RPAREN

State 21:
## Known stack suffix:
## AppType
## LR(1) items:
AppType -> AppType . ATerm [ SEMI RPAREN LPAREN LCID DOT ARROW ]
Type -> AppType . [ SEMI RPAREN DOT ]
Type -> AppType . ARROW Type [ SEMI RPAREN DOT ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On ARROW shift to state 22
-- On ATerm shift to state 25
## Reductions:
-- On SEMI RPAREN DOT
--   reduce production Type -> AppType

State 22:
## Known stack suffix:
## AppType ARROW
## LR(1) items:
Type -> AppType ARROW . Type [ SEMI RPAREN DOT ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 23
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 23:
## Known stack suffix:
## AppType ARROW Type
## LR(1) items:
Type -> AppType ARROW Type . [ SEMI RPAREN DOT ]
## Transitions:
## Reductions:
-- On SEMI RPAREN DOT
--   reduce production Type -> AppType ARROW Type

State 24:
## Known stack suffix:
## AType
## LR(1) items:
AppType -> AType . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT ARROW
--   reduce production AppType -> AType

State 25:
## Known stack suffix:
## AppType ATerm
## LR(1) items:
AppType -> AppType ATerm . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT ARROW
--   reduce production AppType -> AppType ATerm

State 26:
## Known stack suffix:
## PI LCID COLON Type
## LR(1) items:
Type -> PI LCID COLON Type . DOT Type [ SEMI RPAREN DOT ]
## Transitions:
-- On DOT shift to state 27
## Reductions:

State 27:
## Known stack suffix:
## PI LCID COLON Type DOT
## LR(1) items:
Type -> PI LCID COLON Type DOT . Type [ SEMI RPAREN DOT ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 28
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 28:
## Known stack suffix:
## PI LCID COLON Type DOT Type
## LR(1) items:
Type -> PI LCID COLON Type DOT Type . [ SEMI RPAREN DOT ]
## Transitions:
## Reductions:
-- On SEMI RPAREN DOT
--   reduce production Type -> PI LCID COLON Type DOT Type

State 29:
## Known stack suffix:
## LAMBDA USCORE COLON Type
## LR(1) items:
Term -> LAMBDA USCORE COLON Type . DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On DOT shift to state 30
## Reductions:

State 30:
## Known stack suffix:
## LAMBDA USCORE COLON Type DOT
## LR(1) items:
Term -> LAMBDA USCORE COLON Type DOT . Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 44
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 31:
## Known stack suffix:
## ALL
## LR(1) items:
Term -> ALL . LCID COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On LCID shift to state 32
## Reductions:

State 32:
## Known stack suffix:
## ALL LCID
## LR(1) items:
Term -> ALL LCID . COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On COLON shift to state 33
## Reductions:

State 33:
## Known stack suffix:
## ALL LCID COLON
## LR(1) items:
Term -> ALL LCID COLON . Type DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 34
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 34:
## Known stack suffix:
## ALL LCID COLON Type
## LR(1) items:
Term -> ALL LCID COLON Type . DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On DOT shift to state 35
## Reductions:

State 35:
## Known stack suffix:
## ALL LCID COLON Type DOT
## LR(1) items:
Term -> ALL LCID COLON Type DOT . Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 36
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 36:
## Known stack suffix:
## ALL LCID COLON Type DOT Term
## LR(1) items:
Term -> ALL LCID COLON Type DOT Term . [ SEMI RPAREN COMMA COLON ]
## Transitions:
## Reductions:
-- On SEMI RPAREN COMMA COLON
--   reduce production Term -> ALL LCID COLON Type DOT Term

State 37:
## Known stack suffix:
## PathTerm
## LR(1) items:
AppTerm -> PathTerm . [ SEMI RPAREN LPAREN LCID COMMA COLON ]
PathTerm -> PathTerm . DOT TWO [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
PathTerm -> PathTerm . DOT ONE [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
## Transitions:
-- On DOT shift to state 38
## Reductions:
-- On SEMI RPAREN LPAREN LCID COMMA COLON
--   reduce production AppTerm -> PathTerm

State 38:
## Known stack suffix:
## PathTerm DOT
## LR(1) items:
PathTerm -> PathTerm DOT . TWO [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
PathTerm -> PathTerm DOT . ONE [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
## Transitions:
-- On TWO shift to state 39
-- On ONE shift to state 40
## Reductions:

State 39:
## Known stack suffix:
## PathTerm DOT TWO
## LR(1) items:
PathTerm -> PathTerm DOT TWO . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT COMMA COLON
--   reduce production PathTerm -> PathTerm DOT TWO

State 40:
## Known stack suffix:
## PathTerm DOT ONE
## LR(1) items:
PathTerm -> PathTerm DOT ONE . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT COMMA COLON
--   reduce production PathTerm -> PathTerm DOT ONE

State 41:
## Known stack suffix:
## AppTerm
## LR(1) items:
AppTerm -> AppTerm . ATerm [ SEMI RPAREN LPAREN LCID COMMA COLON ]
Term -> AppTerm . [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On ATerm shift to state 42
## Reductions:
-- On SEMI RPAREN COMMA COLON
--   reduce production Term -> AppTerm

State 42:
## Known stack suffix:
## AppTerm ATerm
## LR(1) items:
AppTerm -> AppTerm ATerm . [ SEMI RPAREN LPAREN LCID COMMA COLON ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID COMMA COLON
--   reduce production AppTerm -> AppTerm ATerm

State 43:
## Known stack suffix:
## ATerm
## LR(1) items:
PathTerm -> ATerm . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT COMMA COLON
--   reduce production PathTerm -> ATerm

State 44:
## Known stack suffix:
## LAMBDA USCORE COLON Type DOT Term
## LR(1) items:
Term -> LAMBDA USCORE COLON Type DOT Term . [ SEMI RPAREN COMMA COLON ]
## Transitions:
## Reductions:
-- On SEMI RPAREN COMMA COLON
--   reduce production Term -> LAMBDA USCORE COLON Type DOT Term

State 45:
## Known stack suffix:
## LAMBDA LCID
## LR(1) items:
Term -> LAMBDA LCID . COLON Type DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On COLON shift to state 46
## Reductions:

State 46:
## Known stack suffix:
## LAMBDA LCID COLON
## LR(1) items:
Term -> LAMBDA LCID COLON . Type DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 47
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 47:
## Known stack suffix:
## LAMBDA LCID COLON Type
## LR(1) items:
Term -> LAMBDA LCID COLON Type . DOT Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On DOT shift to state 48
## Reductions:

State 48:
## Known stack suffix:
## LAMBDA LCID COLON Type DOT
## LR(1) items:
Term -> LAMBDA LCID COLON Type DOT . Term [ SEMI RPAREN COMMA COLON ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 49
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 49:
## Known stack suffix:
## LAMBDA LCID COLON Type DOT Term
## LR(1) items:
Term -> LAMBDA LCID COLON Type DOT Term . [ SEMI RPAREN COMMA COLON ]
## Transitions:
## Reductions:
-- On SEMI RPAREN COMMA COLON
--   reduce production Term -> LAMBDA LCID COLON Type DOT Term

State 50:
## Known stack suffix:
## LPAREN Term
## LR(1) items:
ATerm -> LPAREN Term . RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
ATerm -> LPAREN Term . COMMA TermList COLON Type RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
## Transitions:
-- On RPAREN shift to state 51
-- On COMMA shift to state 52
## Reductions:

State 51:
## Known stack suffix:
## LPAREN Term RPAREN
## LR(1) items:
ATerm -> LPAREN Term RPAREN . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW
--   reduce production ATerm -> LPAREN Term RPAREN

State 52:
## Known stack suffix:
## LPAREN Term COMMA
## LR(1) items:
ATerm -> LPAREN Term COMMA . TermList COLON Type RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On TermList shift to state 53
-- On Term shift to state 57
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 53:
## Known stack suffix:
## LPAREN Term COMMA TermList
## LR(1) items:
ATerm -> LPAREN Term COMMA TermList . COLON Type RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
## Transitions:
-- On COLON shift to state 54
## Reductions:

State 54:
## Known stack suffix:
## LPAREN Term COMMA TermList COLON
## LR(1) items:
ATerm -> LPAREN Term COMMA TermList COLON . Type RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 55
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 55:
## Known stack suffix:
## LPAREN Term COMMA TermList COLON Type
## LR(1) items:
ATerm -> LPAREN Term COMMA TermList COLON Type . RPAREN [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
## Transitions:
-- On RPAREN shift to state 56
## Reductions:

State 56:
## Known stack suffix:
## LPAREN Term COMMA TermList COLON Type RPAREN
## LR(1) items:
ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN . [ SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW
--   reduce production ATerm -> LPAREN Term COMMA TermList COLON Type RPAREN

State 57:
## Known stack suffix:
## Term
## LR(1) items:
TermList -> Term . [ COLON ]
TermList -> Term . COMMA TermList [ COLON ]
## Transitions:
-- On COMMA shift to state 58
## Reductions:
-- On COLON
--   reduce production TermList -> Term

State 58:
## Known stack suffix:
## Term COMMA
## LR(1) items:
TermList -> Term COMMA . TermList [ COLON ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On TermList shift to state 59
-- On Term shift to state 57
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 59:
## Known stack suffix:
## Term COMMA TermList
## LR(1) items:
TermList -> Term COMMA TermList . [ COLON ]
## Transitions:
## Reductions:
-- On COLON
--   reduce production TermList -> Term COMMA TermList

State 60:
## Known stack suffix:
## PRF LPAREN Term
## LR(1) items:
AType -> PRF LPAREN Term . RPAREN [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
-- On RPAREN shift to state 61
## Reductions:

State 61:
## Known stack suffix:
## PRF LPAREN Term RPAREN
## LR(1) items:
AType -> PRF LPAREN Term RPAREN . [ SEMI RPAREN LPAREN LCID DOT ARROW ]
## Transitions:
## Reductions:
-- On SEMI RPAREN LPAREN LCID DOT ARROW
--   reduce production AType -> PRF LPAREN Term RPAREN

State 62:
## Known stack suffix:
## SIGMA LCID COLON Type
## LR(1) items:
Type -> SIGMA LCID COLON Type . DOT Type [ SEMI RPAREN DOT ]
## Transitions:
-- On DOT shift to state 63
## Reductions:

State 63:
## Known stack suffix:
## SIGMA LCID COLON Type DOT
## LR(1) items:
Type -> SIGMA LCID COLON Type DOT . Type [ SEMI RPAREN DOT ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 64
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 64:
## Known stack suffix:
## SIGMA LCID COLON Type DOT Type
## LR(1) items:
Type -> SIGMA LCID COLON Type DOT Type . [ SEMI RPAREN DOT ]
## Transitions:
## Reductions:
-- On SEMI RPAREN DOT
--   reduce production Type -> SIGMA LCID COLON Type DOT Type

State 65:
## Known stack suffix:
## EQ Type
## LR(1) items:
TyBinder -> EQ Type . [ SEMI ]
## Transitions:
## Reductions:
-- On SEMI
--   reduce production TyBinder -> EQ Type

State 66:
## Known stack suffix:
## COLON
## LR(1) items:
TyBinder -> COLON . Kind [ SEMI ]
## Transitions:
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 68
-- On LPAREN shift to state 73
-- On Kind shift to state 89
-- On ArrowKind shift to state 80
-- On AppType shift to state 87
-- On AType shift to state 24
-- On AKind shift to state 84
## Reductions:

State 67:
## Known stack suffix:
## STAR
## LR(1) items:
AKind -> STAR . [ SEMI RPAREN ]
## Transitions:
## Reductions:
-- On SEMI RPAREN
--   reduce production AKind -> STAR

State 68:
## Known stack suffix:
## PI
## LR(1) items:
Kind -> PI . LCID COLON Type DOT Kind [ SEMI ]
## Transitions:
-- On LCID shift to state 69
## Reductions:

State 69:
## Known stack suffix:
## PI LCID
## LR(1) items:
Kind -> PI LCID . COLON Type DOT Kind [ SEMI ]
## Transitions:
-- On COLON shift to state 70
## Reductions:

State 70:
## Known stack suffix:
## PI LCID COLON
## LR(1) items:
Kind -> PI LCID COLON . Type DOT Kind [ SEMI ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 71
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 71:
## Known stack suffix:
## PI LCID COLON Type
## LR(1) items:
Kind -> PI LCID COLON Type . DOT Kind [ SEMI ]
## Transitions:
-- On DOT shift to state 72
## Reductions:

State 72:
## Known stack suffix:
## PI LCID COLON Type DOT
## LR(1) items:
Kind -> PI LCID COLON Type DOT . Kind [ SEMI ]
## Transitions:
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 68
-- On LPAREN shift to state 73
-- On Kind shift to state 79
-- On ArrowKind shift to state 80
-- On AppType shift to state 87
-- On AType shift to state 24
-- On AKind shift to state 84
## Reductions:

State 73:
## Known stack suffix:
## LPAREN
## LR(1) items:
AKind -> LPAREN . Kind RPAREN [ SEMI RPAREN ]
AType -> LPAREN . Type RPAREN [ RPAREN LPAREN LCID ARROW ]
## Transitions:
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 74
-- On LPAREN shift to state 73
-- On Type shift to state 19
-- On Kind shift to state 85
-- On ArrowKind shift to state 80
-- On AppType shift to state 81
-- On AType shift to state 24
-- On AKind shift to state 84
## Reductions:

State 74:
## Known stack suffix:
## PI
## LR(1) items:
Kind -> PI . LCID COLON Type DOT Kind [ RPAREN ]
Type -> PI . LCID COLON Type DOT Type [ RPAREN ]
## Transitions:
-- On LCID shift to state 75
## Reductions:

State 75:
## Known stack suffix:
## PI LCID
## LR(1) items:
Kind -> PI LCID . COLON Type DOT Kind [ RPAREN ]
Type -> PI LCID . COLON Type DOT Type [ RPAREN ]
## Transitions:
-- On COLON shift to state 76
## Reductions:

State 76:
## Known stack suffix:
## PI LCID COLON
## LR(1) items:
Kind -> PI LCID COLON . Type DOT Kind [ RPAREN ]
Type -> PI LCID COLON . Type DOT Type [ RPAREN ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 77
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 77:
## Known stack suffix:
## PI LCID COLON Type
## LR(1) items:
Kind -> PI LCID COLON Type . DOT Kind [ RPAREN ]
Type -> PI LCID COLON Type . DOT Type [ RPAREN ]
## Transitions:
-- On DOT shift to state 78
## Reductions:

State 78:
## Known stack suffix:
## PI LCID COLON Type DOT
## LR(1) items:
Kind -> PI LCID COLON Type DOT . Kind [ RPAREN ]
Type -> PI LCID COLON Type DOT . Type [ RPAREN ]
## Transitions:
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 74
-- On LPAREN shift to state 73
-- On Type shift to state 28
-- On Kind shift to state 79
-- On ArrowKind shift to state 80
-- On AppType shift to state 81
-- On AType shift to state 24
-- On AKind shift to state 84
## Reductions:

State 79:
## Known stack suffix:
## PI LCID COLON Type DOT Kind
## LR(1) items:
Kind -> PI LCID COLON Type DOT Kind . [ SEMI RPAREN ]
## Transitions:
## Reductions:
-- On SEMI RPAREN
--   reduce production Kind -> PI LCID COLON Type DOT Kind

State 80:
## Known stack suffix:
## ArrowKind
## LR(1) items:
Kind -> ArrowKind . [ SEMI RPAREN ]
## Transitions:
## Reductions:
-- On SEMI RPAREN
--   reduce production Kind -> ArrowKind

State 81:
## Known stack suffix:
## AppType
## LR(1) items:
AppType -> AppType . ATerm [ RPAREN LPAREN LCID ARROW ]
ArrowKind -> AppType . ARROW ArrowKind [ RPAREN ]
Type -> AppType . [ RPAREN ]
Type -> AppType . ARROW Type [ RPAREN ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On ARROW shift to state 82
-- On ATerm shift to state 25
## Reductions:
-- On RPAREN
--   reduce production Type -> AppType

State 82:
## Known stack suffix:
## AppType ARROW
## LR(1) items:
ArrowKind -> AppType ARROW . ArrowKind [ RPAREN ]
Type -> AppType ARROW . Type [ RPAREN ]
## Transitions:
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 73
-- On Type shift to state 23
-- On ArrowKind shift to state 83
-- On AppType shift to state 81
-- On AType shift to state 24
-- On AKind shift to state 84
## Reductions:

State 83:
## Known stack suffix:
## AppType ARROW ArrowKind
## LR(1) items:
ArrowKind -> AppType ARROW ArrowKind . [ SEMI RPAREN ]
## Transitions:
## Reductions:
-- On SEMI RPAREN
--   reduce production ArrowKind -> AppType ARROW ArrowKind

State 84:
## Known stack suffix:
## AKind
## LR(1) items:
ArrowKind -> AKind . [ SEMI RPAREN ]
## Transitions:
## Reductions:
-- On SEMI RPAREN
--   reduce production ArrowKind -> AKind

State 85:
## Known stack suffix:
## LPAREN Kind
## LR(1) items:
AKind -> LPAREN Kind . RPAREN [ SEMI RPAREN ]
## Transitions:
-- On RPAREN shift to state 86
## Reductions:

State 86:
## Known stack suffix:
## LPAREN Kind RPAREN
## LR(1) items:
AKind -> LPAREN Kind RPAREN . [ SEMI RPAREN ]
## Transitions:
## Reductions:
-- On SEMI RPAREN
--   reduce production AKind -> LPAREN Kind RPAREN

State 87:
## Known stack suffix:
## AppType
## LR(1) items:
AppType -> AppType . ATerm [ LPAREN LCID ARROW ]
ArrowKind -> AppType . ARROW ArrowKind [ SEMI ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On ARROW shift to state 88
-- On ATerm shift to state 25
## Reductions:

State 88:
## Known stack suffix:
## AppType ARROW
## LR(1) items:
ArrowKind -> AppType ARROW . ArrowKind [ SEMI ]
## Transitions:
-- On UCID shift to state 3
-- On STAR shift to state 67
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On LPAREN shift to state 73
-- On ArrowKind shift to state 83
-- On AppType shift to state 87
-- On AType shift to state 24
-- On AKind shift to state 84
## Reductions:

State 89:
## Known stack suffix:
## COLON Kind
## LR(1) items:
TyBinder -> COLON Kind . [ SEMI ]
## Transitions:
## Reductions:
-- On SEMI
--   reduce production TyBinder -> COLON Kind

State 90:
## Known stack suffix:
## UCID TyBinder
## LR(1) items:
Command -> UCID TyBinder . [ SEMI ]
## Transitions:
## Reductions:
-- On SEMI
--   reduce production Command -> UCID TyBinder

State 91:
## Known stack suffix:
## LPAREN
## LR(1) items:
ATerm -> LPAREN . Term RPAREN [ SEMI LPAREN LCID DOT ]
ATerm -> LPAREN . Term COMMA TermList COLON Type RPAREN [ SEMI LPAREN LCID DOT ]
Command -> LPAREN . NORMAL Term RPAREN [ SEMI ]
## Transitions:
-- On NORMAL shift to state 92
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 50
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 92:
## Known stack suffix:
## LPAREN NORMAL
## LR(1) items:
Command -> LPAREN NORMAL . Term RPAREN [ SEMI ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 93
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 93:
## Known stack suffix:
## LPAREN NORMAL Term
## LR(1) items:
Command -> LPAREN NORMAL Term . RPAREN [ SEMI ]
## Transitions:
-- On RPAREN shift to state 94
## Reductions:

State 94:
## Known stack suffix:
## LPAREN NORMAL Term RPAREN
## LR(1) items:
Command -> LPAREN NORMAL Term RPAREN . [ SEMI ]
## Transitions:
## Reductions:
-- On SEMI
--   reduce production Command -> LPAREN NORMAL Term RPAREN

State 95:
## Known stack suffix:
## LCID
## LR(1) items:
ATerm -> LCID . [ SEMI LPAREN LCID DOT ]
Command -> LCID . Binder [ SEMI ]
## Transitions:
-- On EQ shift to state 96
-- On COLON shift to state 100
-- On Binder shift to state 102
## Reductions:
-- On SEMI LPAREN LCID DOT
--   reduce production ATerm -> LCID

State 96:
## Known stack suffix:
## EQ
## LR(1) items:
Binder -> EQ . Term [ SEMI ]
Binder -> EQ . Term COLON Type [ SEMI ]
## Transitions:
-- On LPAREN shift to state 10
-- On LCID shift to state 11
-- On LAMBDA shift to state 12
-- On ALL shift to state 31
-- On Term shift to state 97
-- On PathTerm shift to state 37
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 97:
## Known stack suffix:
## EQ Term
## LR(1) items:
Binder -> EQ Term . [ SEMI ]
Binder -> EQ Term . COLON Type [ SEMI ]
## Transitions:
-- On COLON shift to state 98
## Reductions:
-- On SEMI
--   reduce production Binder -> EQ Term

State 98:
## Known stack suffix:
## EQ Term COLON
## LR(1) items:
Binder -> EQ Term COLON . Type [ SEMI ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 99
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 99:
## Known stack suffix:
## EQ Term COLON Type
## LR(1) items:
Binder -> EQ Term COLON Type . [ SEMI ]
## Transitions:
## Reductions:
-- On SEMI
--   reduce production Binder -> EQ Term COLON Type

State 100:
## Known stack suffix:
## COLON
## LR(1) items:
Binder -> COLON . Type [ SEMI ]
## Transitions:
-- On UCID shift to state 3
-- On SIGMA shift to state 4
-- On PROP shift to state 7
-- On PRF shift to state 8
-- On PI shift to state 15
-- On LPAREN shift to state 18
-- On Type shift to state 101
-- On AppType shift to state 21
-- On AType shift to state 24
## Reductions:

State 101:
## Known stack suffix:
## COLON Type
## LR(1) items:
Binder -> COLON Type . [ SEMI ]
## Transitions:
## Reductions:
-- On SEMI
--   reduce production Binder -> COLON Type

State 102:
## Known stack suffix:
## LCID Binder
## LR(1) items:
Command -> LCID Binder . [ SEMI ]
## Transitions:
## Reductions:
-- On SEMI
--   reduce production Command -> LCID Binder

State 103:
## Known stack suffix:
## IMPORT
## LR(1) items:
Command -> IMPORT . STRINGV [ SEMI ]
## Transitions:
-- On STRINGV shift to state 104
## Reductions:

State 104:
## Known stack suffix:
## IMPORT STRINGV
## LR(1) items:
Command -> IMPORT STRINGV . [ SEMI ]
## Transitions:
## Reductions:
-- On SEMI
--   reduce production Command -> IMPORT STRINGV

State 105:
## Known stack suffix:
## EOF
## LR(1) items:
toplevel -> EOF . [ # ]
## Transitions:
## Reductions:
-- On #
--   reduce production toplevel -> EOF

State 106:
## Known stack suffix:
## toplevel
## LR(1) items:
toplevel' -> toplevel . [ # ]
## Transitions:
## Reductions:
-- On #
--   accept toplevel

State 107:
## Known stack suffix:
## Term
## LR(1) items:
Command -> Term . [ SEMI ]
## Transitions:
## Reductions:
-- On SEMI
--   reduce production Command -> Term

State 108:
## Known stack suffix:
## Command
## LR(1) items:
toplevel -> Command . SEMI toplevel [ # ]
## Transitions:
-- On SEMI shift to state 109
## Reductions:

State 109:
## Known stack suffix:
## Command SEMI
## LR(1) items:
toplevel -> Command SEMI . toplevel [ # ]
## Transitions:
-- On UCID shift to state 1
-- On LPAREN shift to state 91
-- On LCID shift to state 95
-- On LAMBDA shift to state 12
-- On IMPORT shift to state 103
-- On EOF shift to state 105
-- On ALL shift to state 31
-- On toplevel shift to state 110
-- On Term shift to state 107
-- On PathTerm shift to state 37
-- On Command shift to state 108
-- On AppTerm shift to state 41
-- On ATerm shift to state 43
## Reductions:

State 110:
## Known stack suffix:
## Command SEMI toplevel
## LR(1) items:
toplevel -> Command SEMI toplevel . [ # ]
## Transitions:
## Reductions:
-- On #
--   reduce production toplevel -> Command SEMI toplevel

