Grammar has 4 nonterminal symbols, among which 1 start symbols.
Grammar has 3 terminal symbols.
Grammar has 7 productions.
nullable(main) = true
nullable(liste(C)) = true
nullable(liste(B)) = true
nullable(liste(A)) = true
first(main) = C B A
first(liste(C)) = C
first(liste(B)) = B
first(liste(A)) = A
minimal(main) = (* 0 *)
minimal(liste(C)) = (* 0 *)
minimal(liste(B)) = (* 0 *)
minimal(liste(A)) = (* 0 *)
maximal(main) = infinity
maximal(liste(C)) = infinity
maximal(liste(B)) = infinity
maximal(liste(A)) = infinity
follow(main) = #
follow(liste(C)) = #
follow(liste(B)) = C #
follow(liste(A)) = C B #
Built an LR(0) automaton with 11 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 11 states.
Warning: 8 end-of-stream conflicts were arbitrarily resolved.
File "attributes-expansion.mly", line 13, characters 1-1:
Warning: production liste(C) -> is never reduced.
Warning: in total, 1 production is never reduced.
5 out of 11 states have a default reduction.
The action table is 44 entries; 12 non-zero; 17 compressed.
The action table occupies roughly 104 bytes.
The goto table is 55 entries; 7 non-zero; 18 compressed.
The goto table occupies roughly 104 bytes.
The error table occupies roughly 40 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
