State 0:
## Known stack suffix:
##
## LR(1) items:
desc' -> . desc [ # ]
## Transitions:
-- On SIZE shift to state 1
-- On BANG shift to state 3
-- On exprl shift to state 5
-- On desc shift to state 13
## Reductions:
-- On ARROW reduce production exprl ->

State 1:
## Known stack suffix:
## SIZE
## LR(1) items:
exprl -> SIZE . exprl [ SIZE EOF BANG ARROW ]
## Transitions:
-- On SIZE shift to state 1
-- On exprl shift to state 2
## Reductions:
-- On SIZE reduce production exprl ->
-- On EOF reduce production exprl ->
-- On BANG reduce production exprl ->
-- On ARROW reduce production exprl ->
** Conflict on SIZE

State 2:
## Known stack suffix:
## SIZE exprl
## LR(1) items:
exprl -> SIZE exprl . [ SIZE EOF BANG ARROW ]
## Transitions:
## Reductions:
-- On SIZE reduce production exprl -> SIZE exprl
-- On EOF reduce production exprl -> SIZE exprl
-- On BANG reduce production exprl -> SIZE exprl
-- On ARROW reduce production exprl -> SIZE exprl

State 3:
## Known stack suffix:
## BANG
## LR(1) items:
exprl -> BANG . exprl [ SIZE EOF BANG ARROW ]
## Transitions:
-- On SIZE shift to state 1
-- On exprl shift to state 4
## Reductions:
-- On SIZE reduce production exprl ->
-- On EOF reduce production exprl ->
-- On BANG reduce production exprl ->
-- On ARROW reduce production exprl ->
** Conflict on SIZE

State 4:
## Known stack suffix:
## BANG exprl
## LR(1) items:
exprl -> BANG exprl . [ SIZE EOF BANG ARROW ]
## Transitions:
## Reductions:
-- On SIZE reduce production exprl -> BANG exprl
-- On EOF reduce production exprl -> BANG exprl
-- On BANG reduce production exprl -> BANG exprl
-- On ARROW reduce production exprl -> BANG exprl

State 5:
## Known stack suffix:
## exprl
## LR(1) items:
desc -> exprl . ARROW expr EOF [ # ]
## Transitions:
-- On ARROW shift to state 6
## Reductions:

State 6:
## Known stack suffix:
## exprl ARROW
## LR(1) items:
desc -> exprl ARROW . expr EOF [ # ]
## Transitions:
-- On LOG shift to state 7
-- On expr shift to state 9
## Reductions:

State 7:
## Known stack suffix:
## LOG
## LR(1) items:
expr -> LOG . exprl [ SIZE EOF BANG ]
## Transitions:
-- On SIZE shift to state 1
-- On exprl shift to state 8
## Reductions:
-- On SIZE reduce production exprl ->
-- On EOF reduce production exprl ->
-- On BANG reduce production exprl ->
** Conflict on SIZE

State 8:
## Known stack suffix:
## LOG exprl
## LR(1) items:
expr -> LOG exprl . [ SIZE EOF BANG ]
## Transitions:
## Reductions:
-- On SIZE reduce production expr -> LOG exprl
-- On EOF reduce production expr -> LOG exprl
-- On BANG reduce production expr -> LOG exprl

State 9:
## Known stack suffix:
## exprl ARROW expr
## LR(1) items:
desc -> exprl ARROW expr . EOF [ # ]
expr -> expr . BANG [ SIZE EOF BANG ]
expr -> expr . SIZE [ SIZE EOF BANG ]
## Transitions:
-- On SIZE shift to state 10
-- On EOF shift to state 11
-- On BANG shift to state 12
## Reductions:

State 10:
## Known stack suffix:
## expr SIZE
## LR(1) items:
expr -> expr SIZE . [ SIZE EOF BANG ]
## Transitions:
## Reductions:
-- On SIZE reduce production expr -> expr SIZE
-- On EOF reduce production expr -> expr SIZE
-- On BANG reduce production expr -> expr SIZE

State 11:
## Known stack suffix:
## exprl ARROW expr EOF
## LR(1) items:
desc -> exprl ARROW expr EOF . [ # ]
## Transitions:
## Reductions:
-- On # reduce production desc -> exprl ARROW expr EOF

State 12:
## Known stack suffix:
## expr BANG
## LR(1) items:
expr -> expr BANG . [ SIZE EOF BANG ]
## Transitions:
## Reductions:
-- On SIZE reduce production expr -> expr BANG
-- On EOF reduce production expr -> expr BANG
-- On BANG reduce production expr -> expr BANG

State 13:
## Known stack suffix:
## desc
## LR(1) items:
desc' -> desc . [ # ]
## Transitions:
## Reductions:
-- On # accept desc

