
** Conflict (reduce/reduce) in state 12.
** Token involved: DOT
** This state is reached from debut after reading:

SEP expr DOT 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

debut 
expr EOF 
inst DOT expr 
SEP inst inst 
    (?)

** In state 12, looking ahead at DOT, reducing production
** expr -> expr DOT 
** is permitted because of the following sub-derivation:

expr DOT // lookahead token appears
expr DOT . 

** In state 12, looking ahead at DOT, reducing production
** inst -> expr DOT 
** is permitted because of the following sub-derivation:

expr DOT 
inst DOT expr // lookahead token appears
expr DOT . 

** Conflict (shift/reduce) in state 10.
** Token involved: DOT
** This state is reached from debut after reading:

SEP inst inst 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

debut 
expr EOF 
(?)

** In state 10, looking ahead at DOT, shifting is permitted
** because of the following sub-derivation:

inst DOT expr 
SEP inst inst 
         expr DOT 
         inst . DOT expr 

** In state 10, looking ahead at DOT, reducing production
** inst -> SEP inst inst 
** is permitted because of the following sub-derivation:

inst DOT expr // lookahead token appears
SEP inst inst . 

** Conflict (shift/reduce) in state 8.
** Token involved: DOT
** This state is reached from debut after reading:

LIDENT expr 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

debut 
expr EOF 
(?)

** In state 8, looking ahead at DOT, shifting is permitted
** because of the following sub-derivation:

inst DOT expr 
LIDENT expr 
       expr . DOT 

** In state 8, looking ahead at DOT, reducing production
** inst -> LIDENT expr 
** is permitted because of the following sub-derivation:

inst DOT expr // lookahead token appears
LIDENT expr . 

** Conflict (reduce/reduce) in state 7.
** Token involved: DOT
** This state is reached from debut after reading:

expr DOT 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

debut 
expr EOF 
(?)

** In state 7, looking ahead at DOT, reducing production
** expr -> expr DOT 
** is permitted because of the following sub-derivation:

expr DOT // lookahead token appears
expr DOT . 

** In state 7, looking ahead at DOT, reducing production
** inst -> expr DOT 
** is permitted because of the following sub-derivation:

inst DOT expr // lookahead token appears
expr DOT . 

** Conflict (shift/reduce) in state 6.
** Token involved: DOT
** This state is reached from debut after reading:

inst DOT expr 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

debut 
expr EOF 
(?)

** In state 6, looking ahead at DOT, shifting is permitted
** because of the following sub-derivation:

inst DOT expr 
         expr . DOT 

** In state 6, looking ahead at DOT, reducing production
** expr -> inst DOT expr 
** is permitted because of the following sub-derivation:

expr DOT // lookahead token appears
inst DOT expr . 

** Conflict (shift/reduce) in state 3.
** Tokens involved: SEP LIDENT
** The following explanations concentrate on token SEP.
** This state is reached from debut after reading:

SEP LIDENT LIDENT 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

debut 
expr EOF 
inst DOT expr 
(?)

** In state 3, looking ahead at SEP, reducing production
** expr -> LIDENT 
** is permitted because of the following sub-derivation:

SEP inst inst // lookahead token appears because inst can begin with SEP
    LIDENT expr // lookahead token is inherited
           LIDENT . 

** In state 3, looking ahead at SEP, shifting is permitted
** because of the following sub-derivation:

SEP inst inst 
    LIDENT expr 
           inst DOT expr 
           LIDENT expr 
                  inst DOT expr 
                  . SEP inst inst 
