Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 4 terminal symbols.
Grammar has 7 productions.
nullable(inst) = false
nullable(expr) = false
nullable(debut) = false
first(inst) = SEP LIDENT
first(expr) = SEP LIDENT
first(debut) = SEP LIDENT
minimal(inst) = (* 2 *) LIDENT LIDENT
minimal(expr) = (* 1 *) LIDENT
minimal(debut) = (* 2 *) LIDENT EOF
maximal(inst) = infinity
maximal(expr) = infinity
maximal(debut) = infinity
follow(inst) = SEP LIDENT DOT
follow(expr) = SEP LIDENT EOF DOT
follow(debut) = #
Built an LR(0) automaton with 14 states.
The grammar is not SLR(1) -- 5 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 16 states.
Warning: 4 states have shift/reduce conflicts.
Warning: 2 states have reduce/reduce conflicts.
Warning: 5 shift/reduce conflicts were arbitrarily resolved.
Warning: 2 reduce/reduce conflicts were arbitrarily resolved.
3 out of 16 states have a default reduction.
The action table is 80 entries; 35 non-zero; 44 compressed.
The action table occupies roughly 136 bytes.
The goto table is 64 entries; 13 non-zero; 27 compressed.
The goto table occupies roughly 120 bytes.
The error table occupies roughly 48 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
