Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 3 terminal symbols.
Grammar has 7 productions.
nullable(inst) = false
nullable(expr) = false
nullable(debut) = false
first(inst) = SEP LIDENT
first(expr) = SEP LIDENT
first(debut) = SEP LIDENT
minimal(inst) = (* 2 *) LIDENT LIDENT
minimal(expr) = (* 1 *) LIDENT
minimal(debut) = (* 2 *) LIDENT DOT
maximal(inst) = infinity
maximal(expr) = infinity
maximal(debut) = infinity
follow(inst) = SEP LIDENT DOT
follow(expr) = SEP LIDENT DOT
follow(debut) = #
Built an LR(0) automaton with 14 states.
The grammar is not SLR(1) -- 6 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 16 states.
Warning: 4 states have shift/reduce conflicts.
Warning: 3 states have reduce/reduce conflicts.
Warning: 5 shift/reduce conflicts were arbitrarily resolved.
Warning: 3 reduce/reduce conflicts were arbitrarily resolved.
Warning: one state end-of-stream conflict was arbitrarily resolved.
File "boris-mini.mly", line 38, characters 2-10:
Warning: production debut -> expr DOT is never reduced.
Warning: in total, 1 production is never reduced.
3 out of 16 states have a default reduction.
The action table is 64 entries; 30 non-zero; 39 compressed.
The action table occupies roughly 128 bytes.
The goto table is 64 entries; 13 non-zero; 27 compressed.
The goto table occupies roughly 120 bytes.
The error table occupies roughly 40 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
