Grammar has 4 nonterminal symbols, among which 1 start symbols.
Grammar has 8 terminal symbols.
Grammar has 10 productions.
nullable(multiplicative_expr) = false
nullable(main) = false
nullable(atomic_expr) = false
nullable(additive_expr) = false
first(multiplicative_expr) = MINUS LPAREN INT
first(main) = MINUS LPAREN INT
first(atomic_expr) = MINUS LPAREN INT
first(additive_expr) = MINUS LPAREN INT
minimal(multiplicative_expr) = (* 1 *) INT
minimal(main) = (* 2 *) INT EOL
minimal(atomic_expr) = (* 1 *) INT
minimal(additive_expr) = (* 1 *) INT
maximal(multiplicative_expr) = infinity
maximal(main) = infinity
maximal(atomic_expr) = infinity
maximal(additive_expr) = infinity
follow(multiplicative_expr) = TIMES RPAREN PLUS MINUS EOL DIV
follow(main) = #
follow(atomic_expr) = TIMES RPAREN PLUS MINUS EOL DIV
follow(additive_expr) = RPAREN PLUS MINUS EOL
Built an LR(0) automaton with 20 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 20 states.
8 out of 20 states have a default reduction.
The action table is 180 entries; 45 non-zero; 53 compressed.
The action table occupies roughly 152 bytes.
The goto table is 100 entries; 14 non-zero; 34 compressed.
The goto table occupies roughly 128 bytes.
The error table occupies roughly 56 bytes.
The default_reduction table occupies roughly 48 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
