
** Conflict (shift/reduce) in state 48.
** Tokens involved: OR IMPLIES EQUIV AND
** The following explanations concentrate on token OR.
** This state is reached from constraint_entry after reading:

FORALL id_list COMMA formula 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

constraint_entry 
formula EOF 
(?)

** In state 48, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

FORALL id_list COMMA formula 
                     formula . OR formula 

** In state 48, looking ahead at OR, reducing production
** formula -> FORALL id_list COMMA formula 
** is permitted because of the following sub-derivation:

formula OR formula // lookahead token appears
FORALL id_list COMMA formula . 

** Conflict (shift/reduce) in state 30.
** Tokens involved: OR IMPLIES EQUIV AND
** The following explanations concentrate on token OR.
** This state is reached from constraint_entry after reading:

EXISTS id_list COMMA formula 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

constraint_entry 
formula EOF 
(?)

** In state 30, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

EXISTS id_list COMMA formula 
                     formula . OR formula 

** In state 30, looking ahead at OR, reducing production
** formula -> EXISTS id_list COMMA formula 
** is permitted because of the following sub-derivation:

formula OR formula // lookahead token appears
EXISTS id_list COMMA formula . 
