File "cime-poly-interp.mly", line 29, characters 7-15:
Warning: the token LEFT_BRA is unused.
File "cime-poly-interp.mly", line 29, characters 16-25:
Warning: the token RIGHT_BRA is unused.
Grammar has 7 nonterminal symbols, among which 2 start symbols.
Grammar has 15 terminal symbols.
Grammar has 18 productions.
nullable(weight_entry) = false
nullable(weight) = true
nullable(vars) = false
nullable(symbol_interp) = false
nullable(poly_interp_entry) = false
nullable(poly) = false
nullable(interp) = true
first(weight_entry) = INTERP EOF
first(weight) = INTERP
first(vars) = VAR
first(symbol_interp) = INTERP
first(poly_interp_entry) = INTERP EOF
first(poly) = VAR MINUS LEFT_PAR INT
first(interp) = INTERP
minimal(weight_entry) = (* 1 *) EOF
minimal(weight) = (* 0 *)
minimal(vars) = (* 2 *) VAR RIGHT_PAR
minimal(symbol_interp) = (* 1 *) INTERP
minimal(poly_interp_entry) = (* 1 *) EOF
minimal(poly) = (* 1 *) VAR
minimal(interp) = (* 0 *)
maximal(weight_entry) = infinity
maximal(weight) = infinity
maximal(vars) = infinity
maximal(symbol_interp) = infinity
maximal(poly_interp_entry) = infinity
maximal(poly) = infinity
maximal(interp) = infinity
follow(weight_entry) = #
follow(weight) = EOF
follow(vars) = EQUAL
follow(symbol_interp) = EQUAL
follow(poly_interp_entry) = #
follow(poly) = SEMICOLON RIGHT_PAR PLUS MULT MINUS EXP
follow(interp) = EOF
Built an LR(0) automaton with 40 states.
The grammar is not SLR(1) -- 4 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 40 states.
16 shift/reduce conflicts were silently solved.
13 out of 40 states have a default reduction.
The action table is 640 entries; 79 non-zero; 92 compressed.
The action table occupies roughly 184 bytes.
The goto table is 360 entries; 16 non-zero; 56 compressed.
The goto table occupies roughly 144 bytes.
The error table occupies roughly 112 bytes.
The default_reduction table occupies roughly 72 bytes.
The lhs table occupies roughly 48 bytes.
The trace table occupies roughly 8 bytes.
