Grammar has 14 nonterminal symbols, among which 1 start symbols.
Grammar has 16 terminal symbols.
Grammar has 33 productions.
nullable(trailer) = false
nullable(terminals) = true
nullable(symbols) = true
nullable(symbol) = false
nullable(rules) = true
nullable(rule) = false
nullable(productions) = true
nullable(production) = false
nullable(precedence) = true
nullable(optional_bar) = true
nullable(nonterminals) = true
nullable(grammar) = false
nullable(declarations) = true
nullable(declaration) = false
first(trailer) = PERCENTPERCENT EOF
first(terminals) = UID LID
first(symbols) = UID LID
first(symbol) = UID LID
first(rules) = UID LID
first(rule) = UID LID
first(productions) = BAR
first(production) = UID PREC LID ACTION
first(precedence) = PREC
first(optional_bar) = BAR
first(nonterminals) = UID LID
first(grammar) = TYPE TOKEN START RIGHT PERCENTPERCENT NONASSOC LEFT HEADER
first(declarations) = TYPE TOKEN START RIGHT NONASSOC LEFT HEADER
first(declaration) = TYPE TOKEN START RIGHT NONASSOC LEFT HEADER
minimal(trailer) = (* 1 *) EOF
minimal(terminals) = (* 0 *)
minimal(symbols) = (* 0 *)
minimal(symbol) = (* 1 *) LID
minimal(rules) = (* 0 *)
minimal(rule) = (* 3 *) LID COLON ACTION
minimal(productions) = (* 0 *)
minimal(production) = (* 1 *) ACTION
minimal(precedence) = (* 0 *)
minimal(optional_bar) = (* 0 *)
minimal(nonterminals) = (* 0 *)
minimal(grammar) = (* 2 *) PERCENTPERCENT EOF
minimal(declarations) = (* 0 *)
minimal(declaration) = (* 1 *) HEADER
maximal(trailer) = 1
maximal(terminals) = infinity
maximal(symbols) = infinity
maximal(symbol) = 1
maximal(rules) = infinity
maximal(rule) = infinity
maximal(productions) = infinity
maximal(production) = infinity
maximal(precedence) = 2
maximal(optional_bar) = 1
maximal(nonterminals) = infinity
maximal(grammar) = infinity
maximal(declarations) = infinity
maximal(declaration) = infinity
follow(trailer) = #
follow(terminals) = UID TYPE TOKEN START RIGHT PERCENTPERCENT NONASSOC LID LEFT HEADER
follow(symbols) = UID TYPE TOKEN START RIGHT PREC PERCENTPERCENT NONASSOC LID LEFT HEADER ACTION
follow(symbol) = UID TYPE TOKEN START RIGHT PREC PERCENTPERCENT NONASSOC LID LEFT HEADER COLON ACTION
follow(rules) = UID PERCENTPERCENT LID EOF
follow(rule) = UID PERCENTPERCENT LID EOF
follow(productions) = UID PERCENTPERCENT LID EOF BAR
follow(production) = UID PERCENTPERCENT LID EOF BAR
follow(precedence) = ACTION
follow(optional_bar) = UID PREC LID ACTION
follow(nonterminals) = UID TYPE TOKEN START RIGHT PERCENTPERCENT NONASSOC LID LEFT HEADER
follow(grammar) = #
follow(declarations) = TYPE TOKEN START RIGHT PERCENTPERCENT NONASSOC LEFT HEADER
follow(declaration) = TYPE TOKEN START RIGHT PERCENTPERCENT NONASSOC LEFT HEADER
Built an LR(0) automaton with 46 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 46 states.
29 out of 46 states have a default reduction.
The action table is 782 entries; 112 non-zero; 186 compressed.
The action table occupies roughly 280 bytes.
The goto table is 690 entries; 27 non-zero; 69 compressed.
The goto table occupies roughly 160 bytes.
The error table occupies roughly 136 bytes.
The default_reduction table occupies roughly 80 bytes.
The lhs table occupies roughly 56 bytes.
The trace table occupies roughly 8 bytes.
