Grammar has 27 nonterminal symbols, among which 1 start symbols.
Grammar has 28 terminal symbols.
Grammar has 82 productions.
nullable(zfile) = false
nullable(ttl) = false
nullable(single_hex) = false
nullable(s) = false
nullable(rrline) = false
nullable(rrclass) = false
nullable(rr) = false
nullable(owner) = true
nullable(origin) = false
nullable(lines) = true
nullable(label_except_specials) = false
nullable(label_except_at) = false
nullable(label) = false
nullable(keyword_or_number) = false
nullable(ipv6) = false
nullable(ipv4) = false
nullable(int8) = false
nullable(int32) = false
nullable(int16) = false
nullable(hostname) = false
nullable(hex) = false
nullable(generic_type) = false
nullable(generic_rdata) = false
nullable(domain_labels) = false
nullable(domain) = false
nullable(charstrings) = false
nullable(charstring) = false
first(zfile) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A STTL SPACE SORIGIN NUMBER EOL EOF DOT CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(ttl) = STTL
first(single_hex) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(s) = SPACE
first(rrline) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A SPACE NUMBER DOT CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(rrclass) = CLASS_IN CLASS_HS CLASS_CS CLASS_CH
first(rr) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_GENERIC TYPE_DNSKEY TYPE_CNAME TYPE_CAA TYPE_AAAA TYPE_A CHARSTRING
first(owner) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER DOT CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(origin) = SORIGIN
first(lines) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A STTL SPACE SORIGIN NUMBER EOL DOT CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(label_except_specials) = CHARSTRING
first(label_except_at) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING
first(label) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(keyword_or_number) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER CLASS_IN CLASS_HS CLASS_CS CLASS_CH
first(ipv6) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(ipv4) = NUMBER
first(int8) = NUMBER
first(int32) = NUMBER
first(int16) = NUMBER
first(hostname) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER DOT CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(hex) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(generic_type) = TYPE_GENERIC
first(generic_rdata) = GENERIC
first(domain_labels) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(domain) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER DOT CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(charstrings) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
first(charstring) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A NUMBER CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
minimal(zfile) = (* 1 *) EOF
minimal(ttl) = (* 3 *) STTL SPACE NUMBER
minimal(single_hex) = (* 1 *) CHARSTRING
minimal(s) = (* 1 *) SPACE
minimal(rrline) = (* 3 *) SPACE CHARSTRING SPACE
minimal(rrclass) = (* 1 *) CLASS_IN
minimal(rr) = (* 2 *) CHARSTRING SPACE
minimal(owner) = (* 0 *)
minimal(origin) = (* 3 *) SORIGIN SPACE DOT
minimal(lines) = (* 0 *)
minimal(label_except_specials) = (* 1 *) CHARSTRING
minimal(label_except_at) = (* 1 *) CHARSTRING
minimal(label) = (* 1 *) CHARSTRING
minimal(keyword_or_number) = (* 1 *) NUMBER
minimal(ipv6) = (* 1 *) CHARSTRING
minimal(ipv4) = (* 7 *) NUMBER DOT NUMBER DOT NUMBER DOT NUMBER
minimal(int8) = (* 1 *) NUMBER
minimal(int32) = (* 1 *) NUMBER
minimal(int16) = (* 1 *) NUMBER
minimal(hostname) = (* 1 *) DOT
minimal(hex) = (* 1 *) CHARSTRING
minimal(generic_type) = (* 1 *) TYPE_GENERIC
minimal(generic_rdata) = (* 5 *) GENERIC SPACE NUMBER SPACE CHARSTRING
minimal(domain_labels) = (* 1 *) CHARSTRING
minimal(domain) = (* 1 *) DOT
minimal(charstrings) = (* 1 *) CHARSTRING
minimal(charstring) = (* 1 *) CHARSTRING
maximal(zfile) = infinity
maximal(ttl) = infinity
maximal(single_hex) = 1
maximal(s) = infinity
maximal(rrline) = infinity
maximal(rrclass) = 1
maximal(rr) = infinity
maximal(owner) = infinity
maximal(origin) = infinity
maximal(lines) = infinity
maximal(label_except_specials) = 1
maximal(label_except_at) = 1
maximal(label) = 1
maximal(keyword_or_number) = 1
maximal(ipv6) = 1
maximal(ipv4) = 7
maximal(int8) = 1
maximal(int32) = 1
maximal(int16) = 1
maximal(hostname) = infinity
maximal(hex) = infinity
maximal(generic_type) = 1
maximal(generic_rdata) = infinity
maximal(domain_labels) = infinity
maximal(domain) = infinity
maximal(charstrings) = infinity
maximal(charstring) = 1
follow(zfile) = #
follow(ttl) = EOL
follow(single_hex) = SPACE EOL
follow(s) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_GENERIC TYPE_DNSKEY TYPE_CNAME TYPE_CAA TYPE_AAAA TYPE_A SPACE NUMBER GENERIC EOL DOT CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
follow(rrline) = EOL
follow(rrclass) = SPACE
follow(rr) = EOL
follow(owner) = SPACE
follow(origin) = EOL
follow(lines) = TYPE_TXT TYPE_TLSA TYPE_SSHFP TYPE_SRV TYPE_SOA TYPE_PTR TYPE_NS TYPE_MX TYPE_DNSKEY TYPE_CNAME TYPE_AAAA TYPE_A STTL SPACE SORIGIN NUMBER EOL EOF DOT CLASS_IN CLASS_HS CLASS_CS CLASS_CH CHARSTRING AT
follow(label_except_specials) = SPACE EOL DOT
follow(label_except_at) = SPACE EOL DOT
follow(label) = SPACE EOL DOT
follow(keyword_or_number) = SPACE EOL DOT
follow(ipv6) = EOL
follow(ipv4) = EOL
follow(int8) = SPACE
follow(int32) = SPACE EOL
follow(int16) = SPACE
follow(hostname) = EOL
follow(hex) = SPACE EOL
follow(generic_type) = SPACE
follow(generic_rdata) = EOL
follow(domain_labels) = SPACE EOL DOT
follow(domain) = SPACE EOL
follow(charstrings) = SPACE EOL
follow(charstring) = SPACE EOL
Built an LR(0) automaton with 182 states.
The grammar is not SLR(1) -- 2 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 182 states.
71 out of 182 states have a default reduction.
The action table is 5278 entries; 644 non-zero; 358 compressed.
The action table occupies roughly 808 bytes.
The goto table is 5096 entries; 178 non-zero; 357 compressed.
The goto table occupies roughly 632 bytes.
The error table occupies roughly 696 bytes.
The default_reduction table occupies roughly 216 bytes.
The lhs table occupies roughly 120 bytes.
The trace table occupies roughly 8 bytes.
