File "dune.1.4.0-opamBaseParser.mly", line 49, characters 10-16:
Warning: the token URELOP is unused.
Grammar has 6 nonterminal symbols, among which 2 start symbols.
Grammar has 17 terminal symbols.
Grammar has 22 productions.
nullable(values) = true
nullable(value) = false
nullable(main) = false
nullable(items) = true
nullable(item) = false
nullable(atom) = false
first(values) = STRING RELOP PFXOP LPAR LBRACKET INT IDENT BOOL
first(value) = STRING RELOP PFXOP LPAR LBRACKET INT IDENT BOOL
first(main) = IDENT EOF
first(items) = IDENT
first(item) = IDENT
first(atom) = STRING INT IDENT BOOL
minimal(values) = (* 0 *)
minimal(value) = (* 1 *) IDENT
minimal(main) = (* 1 *) EOF
minimal(items) = (* 0 *)
minimal(item) = (* 3 *) IDENT COLON IDENT
minimal(atom) = (* 1 *) IDENT
maximal(values) = infinity
maximal(value) = infinity
maximal(main) = infinity
maximal(items) = infinity
maximal(item) = infinity
maximal(atom) = 1
follow(values) = RPAR RBRACKET RBRACE
follow(value) = STRING RPAR RELOP RBRACKET RBRACE PFXOP OR LPAR LBRACKET LBRACE INT IDENT EOF BOOL AND #
follow(main) = #
follow(items) = RBRACE EOF
follow(item) = RBRACE IDENT EOF
follow(atom) = STRING RPAR RELOP RBRACKET RBRACE PFXOP OR LPAR LBRACKET LBRACE INT IDENT EOF ENVOP BOOL AND #
Built an LR(0) automaton with 46 states.
The grammar is not SLR(1) -- 4 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 46 states.
10 shift/reduce conflicts were silently solved.
File "dune.1.4.0-opamBaseParser.mly", line 41, characters 0-5:
Warning: the precedence level assigned to COLON is never useful.
File "dune.1.4.0-opamBaseParser.mly", line 45, characters 0-9:
Warning: the precedence level assigned to ENVOP is never useful.
File "dune.1.4.0-opamBaseParser.mly", line 47, characters 0-5:
Warning: the precedence level assigned to RBRACE is never useful.
File "dune.1.4.0-opamBaseParser.mly", line 49, characters 0-9:
Warning: the precedence level assigned to URELOP is never useful.
Warning: 15 end-of-stream conflicts were arbitrarily resolved.
File "dune.1.4.0-opamBaseParser.mly", line 79, characters 0-5:
Warning: symbol value is never accepted.
Warning: in total, 1 production is never reduced.
16 out of 46 states have a default reduction.
The action table is 828 entries; 182 non-zero; 142 compressed.
The action table occupies roughly 232 bytes.
The goto table is 368 entries; 34 non-zero; 84 compressed.
The goto table occupies roughly 176 bytes.
The error table occupies roughly 136 bytes.
The default_reduction table occupies roughly 80 bytes.
The lhs table occupies roughly 48 bytes.
The trace table occupies roughly 8 bytes.
