
** Conflict (reduce/reduce) in state 238.
** Tokens involved: UNTIL UNIV TILDE THIS STAR SOME_ARROW_SOME SOME_ARROW_SET SOME_ARROW_ONE SOME_ARROW_LONE SOME SINCE SET_ARROW_SOME SET_ARROW_SET SET_ARROW_ONE SET_ARROW_LONE RPROJ RBRACE QSOME QONE QNO QLONE QALL PRIME PREVIOUS PLUS OVERRIDE OR ONE_ARROW_SOME ONE_ARROW_SET ONE_ARROW_ONE ONE_ARROW_LONE ONE ONCE NUMBER NOT NONE NO NEXT NEQ MSOME MSET MONE MLONE MINUS LTE LT LPROJ LPAREN LONE_ARROW_SOME LONE_ARROW_SET LONE_ARROW_ONE LONE_ARROW_LONE LONE LET LBRACKET LBRACE INTER INT IN IMPLIES IFF IDENT IDEN HISTORICALLY GTE GT EVENTUALLY EQ DOT CARET CARD AT AND ALWAYS
** The following explanations concentrate on token UNTIL.
** This state is reached from file after reading:

option(module_decl) list(import) FACT option(IDENT) LBRACE expr MINUS NUMBER

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

file 
specification EOF 
option(module_decl) list(import) list(paragraph_or_cmd) 
                                 paragraph_or_cmd list(paragraph_or_cmd) 
                                 paragraph 
                                 factDecl 
                                 FACT option(IDENT) block 
                                                    LBRACE list(expr) RBRACE 
                                                           (?)

** In state 238, looking ahead at UNTIL, reducing production
** prim_expr -> NUMBER
** is permitted because of the following sub-derivation:

expr list(expr) 
prim_expr 
expr MINUS expr 
           prim_expr 
           expr UNTIL expr // lookahead token appears
           prim_expr // lookahead token is inherited
           NUMBER . 

** In state 238, looking ahead at UNTIL, reducing production
** prim_expr -> MINUS NUMBER
** is permitted because of the following sub-derivation:

expr list(expr) 
     expr list(expr) 
     prim_expr 
     expr UNTIL expr // lookahead token appears
     prim_expr // lookahead token is inherited
     MINUS NUMBER . 
