
** Conflict (shift/reduce) in state 82.
** Token involved: IDENT
** This state is reached from execfile after reading:

IGNORE IDENT 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

execfile 
items 
(?)

** In state 82, looking ahead at IDENT, shifting is permitted
** because of the following sub-derivation:

item items 
IGNORE checks 
       IDENT checks 
             . IDENT 

** In state 82, looking ahead at IDENT, reducing production
** checks -> IDENT 
** is permitted because of the following sub-derivation:

item items // lookahead token appears because items can begin with IDENT
IGNORE checks // lookahead token is inherited
       IDENT . 
