State 0:
## Known stack suffix:
##
## LR(1) items:
start' -> . start [ # ]
## Transitions:
-- On C shift to state 1
-- On start shift to state 2
-- On ignore(foo(bar(A))) shift to state 3
-- On foo(A) shift to state 4
## Reductions:

State 1:
## Known stack suffix:
## C
## LR(1) items:
ignore(foo(bar(A))) -> C . [ # ]
## Transitions:
## Reductions:
-- On #
--   reduce production ignore(foo(bar(A))) -> C

State 2:
## Known stack suffix:
## start
## LR(1) items:
start' -> start . [ # ]
## Transitions:
## Reductions:
-- On #
--   accept start

State 3:
## Known stack suffix:
## ignore(foo(bar(A)))
## LR(1) items:
foo(A) -> ignore(foo(bar(A))) . [ # ]
## Transitions:
## Reductions:
-- On #
--   reduce production foo(A) -> ignore(foo(bar(A)))

State 4:
## Known stack suffix:
## foo(A)
## LR(1) items:
start -> foo(A) . [ # ]
## Transitions:
## Reductions:
-- On #
--   reduce production start -> foo(A)

