State 0:
## Known stack suffix:
##
## LR(1) items:
file' -> . file [ # ]
## Transitions:
-- On TERMINATE shift to state 1
-- On OPEN shift to state 2
-- On EOF shift to state 11
-- On file shift to state 14
## Reductions:

State 1:
## Known stack suffix:
## TERMINATE
## LR(1) items:
file -> TERMINATE . file [ # ]
## Transitions:
-- On TERMINATE shift to state 1
-- On OPEN shift to state 2
-- On EOF shift to state 11
-- On file shift to state 13
## Reductions:

State 2:
## Known stack suffix:
## OPEN
## LR(1) items:
file -> OPEN . ftext CLOSE file [ # ]
## Transitions:
-- On ftext shift to state 3
## Reductions:
-- On VERB reduce production ftext ->
-- On TEXT reduce production ftext ->
-- On LBRACE reduce production ftext ->
-- On DIRECTIVE reduce production ftext ->
-- On CLOSE reduce production ftext ->

State 3:
## Known stack suffix:
## OPEN ftext
## LR(1) items:
file -> OPEN ftext . CLOSE file [ # ]
ftext -> ftext . DIRECTIVE [ VERB TEXT LBRACE DIRECTIVE CLOSE ]
ftext -> ftext . TEXT [ VERB TEXT LBRACE DIRECTIVE CLOSE ]
ftext -> ftext . LBRACE ftext RBRACE [ VERB TEXT LBRACE DIRECTIVE CLOSE ]
ftext -> ftext . VERB [ VERB TEXT LBRACE DIRECTIVE CLOSE ]
## Transitions:
-- On VERB shift to state 4
-- On TEXT shift to state 5
-- On LBRACE shift to state 6
-- On DIRECTIVE shift to state 9
-- On CLOSE shift to state 10
## Reductions:

State 4:
## Known stack suffix:
## ftext VERB
## LR(1) items:
ftext -> ftext VERB . [ VERB TEXT RBRACE LBRACE DIRECTIVE CLOSE ]
## Transitions:
## Reductions:
-- On VERB reduce production ftext -> ftext VERB
-- On TEXT reduce production ftext -> ftext VERB
-- On RBRACE reduce production ftext -> ftext VERB
-- On LBRACE reduce production ftext -> ftext VERB
-- On DIRECTIVE reduce production ftext -> ftext VERB
-- On CLOSE reduce production ftext -> ftext VERB

State 5:
## Known stack suffix:
## ftext TEXT
## LR(1) items:
ftext -> ftext TEXT . [ VERB TEXT RBRACE LBRACE DIRECTIVE CLOSE ]
## Transitions:
## Reductions:
-- On VERB reduce production ftext -> ftext TEXT
-- On TEXT reduce production ftext -> ftext TEXT
-- On RBRACE reduce production ftext -> ftext TEXT
-- On LBRACE reduce production ftext -> ftext TEXT
-- On DIRECTIVE reduce production ftext -> ftext TEXT
-- On CLOSE reduce production ftext -> ftext TEXT

State 6:
## Known stack suffix:
## ftext LBRACE
## LR(1) items:
ftext -> ftext LBRACE . ftext RBRACE [ VERB TEXT RBRACE LBRACE DIRECTIVE CLOSE ]
## Transitions:
-- On ftext shift to state 7
## Reductions:
-- On VERB reduce production ftext ->
-- On TEXT reduce production ftext ->
-- On RBRACE reduce production ftext ->
-- On LBRACE reduce production ftext ->
-- On DIRECTIVE reduce production ftext ->

State 7:
## Known stack suffix:
## ftext LBRACE ftext
## LR(1) items:
ftext -> ftext . DIRECTIVE [ VERB TEXT RBRACE LBRACE DIRECTIVE ]
ftext -> ftext . TEXT [ VERB TEXT RBRACE LBRACE DIRECTIVE ]
ftext -> ftext . LBRACE ftext RBRACE [ VERB TEXT RBRACE LBRACE DIRECTIVE ]
ftext -> ftext LBRACE ftext . RBRACE [ VERB TEXT RBRACE LBRACE DIRECTIVE CLOSE ]
ftext -> ftext . VERB [ VERB TEXT RBRACE LBRACE DIRECTIVE ]
## Transitions:
-- On VERB shift to state 4
-- On TEXT shift to state 5
-- On RBRACE shift to state 8
-- On LBRACE shift to state 6
-- On DIRECTIVE shift to state 9
## Reductions:

State 8:
## Known stack suffix:
## ftext LBRACE ftext RBRACE
## LR(1) items:
ftext -> ftext LBRACE ftext RBRACE . [ VERB TEXT RBRACE LBRACE DIRECTIVE CLOSE ]
## Transitions:
## Reductions:
-- On VERB reduce production ftext -> ftext LBRACE ftext RBRACE
-- On TEXT reduce production ftext -> ftext LBRACE ftext RBRACE
-- On RBRACE reduce production ftext -> ftext LBRACE ftext RBRACE
-- On LBRACE reduce production ftext -> ftext LBRACE ftext RBRACE
-- On DIRECTIVE reduce production ftext -> ftext LBRACE ftext RBRACE
-- On CLOSE reduce production ftext -> ftext LBRACE ftext RBRACE

State 9:
## Known stack suffix:
## ftext DIRECTIVE
## LR(1) items:
ftext -> ftext DIRECTIVE . [ VERB TEXT RBRACE LBRACE DIRECTIVE CLOSE ]
## Transitions:
## Reductions:
-- On VERB reduce production ftext -> ftext DIRECTIVE
-- On TEXT reduce production ftext -> ftext DIRECTIVE
-- On RBRACE reduce production ftext -> ftext DIRECTIVE
-- On LBRACE reduce production ftext -> ftext DIRECTIVE
-- On DIRECTIVE reduce production ftext -> ftext DIRECTIVE
-- On CLOSE reduce production ftext -> ftext DIRECTIVE

State 10:
## Known stack suffix:
## OPEN ftext CLOSE
## LR(1) items:
file -> OPEN ftext CLOSE . file [ # ]
## Transitions:
-- On TERMINATE shift to state 1
-- On OPEN shift to state 2
-- On EOF shift to state 11
-- On file shift to state 12
## Reductions:

State 11:
## Known stack suffix:
## EOF
## LR(1) items:
file -> EOF . [ # ]
## Transitions:
## Reductions:
-- On # reduce production file -> EOF

State 12:
## Known stack suffix:
## OPEN ftext CLOSE file
## LR(1) items:
file -> OPEN ftext CLOSE file . [ # ]
## Transitions:
## Reductions:
-- On # reduce production file -> OPEN ftext CLOSE file

State 13:
## Known stack suffix:
## TERMINATE file
## LR(1) items:
file -> TERMINATE file . [ # ]
## Transitions:
## Reductions:
-- On # reduce production file -> TERMINATE file

State 14:
## Known stack suffix:
## file
## LR(1) items:
file' -> file . [ # ]
## Transitions:
## Reductions:
-- On # accept file

