File "fsyaccpars.mly", line 11, characters 83-86:
Warning: the token EOF is unused.
File "fsyaccpars.mly", line 11, characters 59-66:
Warning: the token GREATER is unused.
File "fsyaccpars.mly", line 11, characters 54-58:
Warning: the token LESS is unused.
Grammar has 13 nonterminal symbols, among which 1 start symbols.
Grammar has 18 terminal symbols.
Grammar has 28 productions.
nullable(syms) = true
nullable(spec) = false
nullable(rules) = false
nullable(rule) = false
nullable(optsemi) = true
nullable(optprec) = true
nullable(optbar) = true
nullable(idents) = true
nullable(headeropt) = true
nullable(decls) = true
nullable(decl) = false
nullable(clauses) = false
nullable(clause) = false
first(syms) = IDENT ERROR
first(spec) = TYPE TOKEN START RIGHT PERCENT_PERCENT NONASSOC LEFT HEADER
first(rules) = IDENT
first(rule) = IDENT
first(optsemi) = SEMI
first(optprec) = PREC
first(optbar) = BAR
first(idents) = IDENT
first(headeropt) = HEADER
first(decls) = TYPE TOKEN START RIGHT NONASSOC LEFT
first(decl) = TYPE TOKEN START RIGHT NONASSOC LEFT
first(clauses) = PREC IDENT ERROR CODE
first(clause) = PREC IDENT ERROR CODE
minimal(syms) = (* 0 *)
minimal(spec) = (* 4 *) PERCENT_PERCENT IDENT COLON CODE
minimal(rules) = (* 3 *) IDENT COLON CODE
minimal(rule) = (* 3 *) IDENT COLON CODE
minimal(optsemi) = (* 0 *)
minimal(optprec) = (* 0 *)
minimal(optbar) = (* 0 *)
minimal(idents) = (* 0 *)
minimal(headeropt) = (* 0 *)
minimal(decls) = (* 0 *)
minimal(decl) = (* 1 *) TOKEN
minimal(clauses) = (* 1 *) CODE
minimal(clause) = (* 1 *) CODE
maximal(syms) = infinity
maximal(spec) = infinity
maximal(rules) = infinity
maximal(rule) = infinity
maximal(optsemi) = 1
maximal(optprec) = 2
maximal(optbar) = 1
maximal(idents) = infinity
maximal(headeropt) = 1
maximal(decls) = infinity
maximal(decl) = infinity
maximal(clauses) = infinity
maximal(clause) = infinity
follow(syms) = PREC CODE
follow(spec) = #
follow(rules) = #
follow(rule) = IDENT #
follow(optsemi) = IDENT #
follow(optprec) = CODE
follow(optbar) = PREC IDENT ERROR CODE
follow(idents) = TYPE TOKEN START RIGHT PERCENT_PERCENT NONASSOC LEFT
follow(headeropt) = TYPE TOKEN START RIGHT PERCENT_PERCENT NONASSOC LEFT
follow(decls) = PERCENT_PERCENT
follow(decl) = TYPE TOKEN START RIGHT PERCENT_PERCENT NONASSOC LEFT
follow(clauses) = SEMI IDENT #
follow(clause) = SEMI IDENT BAR #
Built an LR(0) automaton with 44 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 44 states.
File "fsyaccpars.mly", line 15, characters 0-5:
Warning: the precedence level assigned to BAR is never useful.
Warning: 7 end-of-stream conflicts were arbitrarily resolved.
File "fsyaccpars.mly", line 30, characters 33-37:
Warning: production rules -> rule is never reduced.
Warning: in total, 1 production is never reduced.
20 out of 44 states have a default reduction.
The action table is 836 entries; 112 non-zero; 91 compressed.
The action table occupies roughly 184 bytes.
The goto table is 616 entries; 28 non-zero; 72 compressed.
The goto table occupies roughly 168 bytes.
The error table occupies roughly 144 bytes.
The default_reduction table occupies roughly 80 bytes.
The lhs table occupies roughly 48 bytes.
The trace table occupies roughly 8 bytes.
