File "gromit.mly", line 33, characters 7-10:
Warning: the token EOF is unused.
Grammar has 13 nonterminal symbols, among which 1 start symbols.
Grammar has 23 terminal symbols.
Grammar has 60 productions.
nullable(variance) = false
nullable(signature) = false
nullable(next_label_or_token) = false
nullable(lattice_list) = false
nullable(lattice_component_list) = false
nullable(lattice) = false
nullable(label_or_token_list0) = true
nullable(label_or_token_list) = false
nullable(label_comma_list) = false
nullable(first_label_or_token) = false
nullable(constructor_list) = true
nullable(component) = false
nullable(arity) = true
first(variance) = COVARIANT CONTRAVARIANT
first(signature) = error SIGNATURE
first(next_label_or_token) = error QUOTE LPAREN LIDENT
first(lattice_list) = error LATTICE
first(lattice_component_list) = error LET COVARIANT CONTRAVARIANT CONSTRUCTOR
first(lattice) = LATTICE
first(label_or_token_list0) = error QUOTE LPAREN LIDENT
first(label_or_token_list) = error QUOTE LPAREN LIDENT
first(label_comma_list) = error LIDENT
first(first_label_or_token) = error QUOTE LPAREN LIDENT
first(constructor_list) = error UIDENT
first(component) = LET COVARIANT CONTRAVARIANT CONSTRUCTOR
first(arity) = error LBRACE
minimal(variance) = (* 1 *) COVARIANT
minimal(signature) = (* 11 *) SIGNATURE BEGIN LATTICE UIDENT BEGIN COVARIANT UIDENT LIDENT END END PRIORITY
minimal(next_label_or_token) = (* 1 *) LIDENT
minimal(lattice_list) = (* 7 *) LATTICE UIDENT BEGIN COVARIANT UIDENT LIDENT END
minimal(lattice_component_list) = (* 3 *) COVARIANT UIDENT LIDENT
minimal(lattice) = (* 7 *) LATTICE UIDENT BEGIN COVARIANT UIDENT LIDENT END
minimal(label_or_token_list0) = (* 0 *)
minimal(label_or_token_list) = (* 1 *) LIDENT
minimal(label_comma_list) = (* 1 *) LIDENT
minimal(first_label_or_token) = (* 1 *) LIDENT
minimal(constructor_list) = (* 0 *)
minimal(component) = (* 3 *) COVARIANT UIDENT LIDENT
minimal(arity) = (* 0 *)
maximal(variance) = 1
maximal(signature) = infinity
maximal(next_label_or_token) = 3
maximal(lattice_list) = infinity
maximal(lattice_component_list) = infinity
maximal(lattice) = infinity
maximal(label_or_token_list0) = infinity
maximal(label_or_token_list) = infinity
maximal(label_comma_list) = infinity
maximal(first_label_or_token) = 3
maximal(constructor_list) = infinity
maximal(component) = infinity
maximal(arity) = infinity
follow(variance) = error UIDENT LESS
follow(signature) = #
follow(next_label_or_token) = error QUOTE LPAREN LIDENT LBRACK
follow(lattice_list) = END
follow(lattice_component_list) = END
follow(lattice) = error LATTICE END
follow(label_or_token_list0) = error LBRACK
follow(label_or_token_list) = error LBRACK
follow(label_comma_list) = RBRACE
follow(first_label_or_token) = error QUOTE LPAREN LIDENT LBRACK
follow(constructor_list) = #
follow(component) = error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR
follow(arity) = error PRINTED
Built an LR(0) automaton with 96 states.
The grammar is not SLR(1) -- 3 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 96 states.
Warning: 3 states have shift/reduce conflicts.
Warning: 3 shift/reduce conflicts were arbitrarily resolved.
Warning: 2 end-of-stream conflicts were arbitrarily resolved.
File "gromit.mly", line 210, characters 17-17:
Warning: production constructor_list -> is never reduced.
Warning: in total, 1 production is never reduced.
55 out of 96 states have a default reduction.
The action table is 2304 entries; 98 non-zero; 181 compressed.
The action table occupies roughly 360 bytes.
The goto table is 1344 entries; 22 non-zero; 118 compressed.
The goto table occupies roughly 208 bytes.
The error table occupies roughly 320 bytes.
The default_reduction table occupies roughly 128 bytes.
The lhs table occupies roughly 64 bytes.
The trace table occupies roughly 8 bytes.
