State 0:
signature' -> . signature [ # ]
-- On error shift to state 1
-- On SIGNATURE shift to state 2
-- On signature shift to state 95

State 1:
signature -> error . [ # ]
-- On # reduce production signature -> error

State 2:
signature -> SIGNATURE . BEGIN lattice_list END PRIORITY constructor_list [ # ]
signature -> SIGNATURE . BEGIN lattice_list END error [ # ]
signature -> SIGNATURE . error [ # ]
-- On error shift to state 3
-- On BEGIN shift to state 4

State 3:
signature -> SIGNATURE error . [ # ]
-- On # reduce production signature -> SIGNATURE error

State 4:
signature -> SIGNATURE BEGIN . lattice_list END PRIORITY constructor_list [ # ]
signature -> SIGNATURE BEGIN . lattice_list END error [ # ]
-- On error shift to state 5
-- On LATTICE shift to state 6
-- On lattice_list shift to state 85
-- On lattice shift to state 93

State 5:
lattice_list -> error . [ END ]
-- On END reduce production lattice_list -> error

State 6:
lattice -> LATTICE . UIDENT BEGIN lattice_component_list END [ error LATTICE END ]
lattice -> LATTICE . UIDENT error [ error LATTICE END ]
lattice -> LATTICE . error [ error LATTICE END ]
-- On error shift to state 7
-- On UIDENT shift to state 8

State 7:
lattice -> LATTICE error . [ error LATTICE END ]
-- On error reduce production lattice -> LATTICE error
-- On LATTICE reduce production lattice -> LATTICE error
-- On END reduce production lattice -> LATTICE error

State 8:
lattice -> LATTICE UIDENT . BEGIN lattice_component_list END [ error LATTICE END ]
lattice -> LATTICE UIDENT . error [ error LATTICE END ]
-- On error shift to state 9
-- On BEGIN shift to state 10

State 9:
lattice -> LATTICE UIDENT error . [ error LATTICE END ]
-- On error reduce production lattice -> LATTICE UIDENT error
-- On LATTICE reduce production lattice -> LATTICE UIDENT error
-- On END reduce production lattice -> LATTICE UIDENT error

State 10:
lattice -> LATTICE UIDENT BEGIN . lattice_component_list END [ error LATTICE END ]
-- On error shift to state 11
-- On LET shift to state 12
-- On COVARIANT shift to state 19
-- On CONTRAVARIANT shift to state 20
-- On CONSTRUCTOR shift to state 21
-- On variance shift to state 69
-- On lattice_component_list shift to state 81
-- On component shift to state 83

State 11:
lattice_component_list -> error . [ END ]
-- On END reduce production lattice_component_list -> error

State 12:
component -> LET . UIDENT LESS UIDENT [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> LET . UIDENT LESS error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> LET . UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> LET . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 13
-- On UIDENT shift to state 14

State 13:
component -> LET error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> LET error
-- On LET reduce production component -> LET error
-- On END reduce production component -> LET error
-- On COVARIANT reduce production component -> LET error
-- On CONTRAVARIANT reduce production component -> LET error
-- On CONSTRUCTOR reduce production component -> LET error

State 14:
component -> LET UIDENT . LESS UIDENT [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> LET UIDENT . LESS error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> LET UIDENT . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 15
-- On LESS shift to state 16

State 15:
component -> LET UIDENT error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> LET UIDENT error
-- On LET reduce production component -> LET UIDENT error
-- On END reduce production component -> LET UIDENT error
-- On COVARIANT reduce production component -> LET UIDENT error
-- On CONTRAVARIANT reduce production component -> LET UIDENT error
-- On CONSTRUCTOR reduce production component -> LET UIDENT error

State 16:
component -> LET UIDENT LESS . UIDENT [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> LET UIDENT LESS . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 17
-- On UIDENT shift to state 18

State 17:
component -> LET UIDENT LESS error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> LET UIDENT LESS error
-- On LET reduce production component -> LET UIDENT LESS error
-- On END reduce production component -> LET UIDENT LESS error
-- On COVARIANT reduce production component -> LET UIDENT LESS error
-- On CONTRAVARIANT reduce production component -> LET UIDENT LESS error
-- On CONSTRUCTOR reduce production component -> LET UIDENT LESS error

State 18:
component -> LET UIDENT LESS UIDENT . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> LET UIDENT LESS UIDENT
-- On LET reduce production component -> LET UIDENT LESS UIDENT
-- On END reduce production component -> LET UIDENT LESS UIDENT
-- On COVARIANT reduce production component -> LET UIDENT LESS UIDENT
-- On CONTRAVARIANT reduce production component -> LET UIDENT LESS UIDENT
-- On CONSTRUCTOR reduce production component -> LET UIDENT LESS UIDENT

State 19:
variance -> COVARIANT . [ error UIDENT LESS ]
-- On error reduce production variance -> COVARIANT
-- On UIDENT reduce production variance -> COVARIANT
-- On LESS reduce production variance -> COVARIANT

State 20:
variance -> CONTRAVARIANT . [ error UIDENT LESS ]
-- On error reduce production variance -> CONTRAVARIANT
-- On UIDENT reduce production variance -> CONTRAVARIANT
-- On LESS reduce production variance -> CONTRAVARIANT

State 21:
component -> CONSTRUCTOR . UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT RBRACK [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR . UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR . UIDENT arity PRINTED label_or_token_list LBRACK QUOTE error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR . UIDENT arity PRINTED label_or_token_list LBRACK error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR . UIDENT arity PRINTED label_or_token_list error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR . UIDENT arity error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 22
-- On UIDENT shift to state 23

State 22:
component -> CONSTRUCTOR error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> CONSTRUCTOR error
-- On LET reduce production component -> CONSTRUCTOR error
-- On END reduce production component -> CONSTRUCTOR error
-- On COVARIANT reduce production component -> CONSTRUCTOR error
-- On CONTRAVARIANT reduce production component -> CONSTRUCTOR error
-- On CONSTRUCTOR reduce production component -> CONSTRUCTOR error

State 23:
component -> CONSTRUCTOR UIDENT . arity PRINTED label_or_token_list LBRACK QUOTE UIDENT RBRACK [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT . arity PRINTED label_or_token_list LBRACK QUOTE UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT . arity PRINTED label_or_token_list LBRACK QUOTE error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT . arity PRINTED label_or_token_list LBRACK error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT . arity PRINTED label_or_token_list error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT . arity error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 24
-- On LBRACE shift to state 25
-- On arity shift to state 33
-- On PRINTED reduce production arity ->
** Conflict on error

State 24:
arity -> error . [ error PRINTED ]
-- On error reduce production arity -> error
-- On PRINTED reduce production arity -> error

State 25:
arity -> LBRACE . label_comma_list RBRACE [ error PRINTED ]
-- On error shift to state 26
-- On LIDENT shift to state 27
-- On label_comma_list shift to state 31

State 26:
label_comma_list -> error . [ RBRACE ]
-- On RBRACE reduce production label_comma_list -> error

State 27:
label_comma_list -> LIDENT . [ RBRACE ]
label_comma_list -> LIDENT . COMMA label_comma_list [ RBRACE ]
label_comma_list -> LIDENT . error [ RBRACE ]
-- On error shift to state 28
-- On COMMA shift to state 29
-- On RBRACE reduce production label_comma_list -> LIDENT

State 28:
label_comma_list -> LIDENT error . [ RBRACE ]
-- On RBRACE reduce production label_comma_list -> LIDENT error

State 29:
label_comma_list -> LIDENT COMMA . label_comma_list [ RBRACE ]
-- On error shift to state 26
-- On LIDENT shift to state 27
-- On label_comma_list shift to state 30

State 30:
label_comma_list -> LIDENT COMMA label_comma_list . [ RBRACE ]
-- On RBRACE reduce production label_comma_list -> LIDENT COMMA label_comma_list

State 31:
arity -> LBRACE label_comma_list . RBRACE [ error PRINTED ]
-- On RBRACE shift to state 32

State 32:
arity -> LBRACE label_comma_list RBRACE . [ error PRINTED ]
-- On error reduce production arity -> LBRACE label_comma_list RBRACE
-- On PRINTED reduce production arity -> LBRACE label_comma_list RBRACE

State 33:
component -> CONSTRUCTOR UIDENT arity . PRINTED label_or_token_list LBRACK QUOTE UIDENT RBRACK [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity . PRINTED label_or_token_list LBRACK QUOTE UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity . PRINTED label_or_token_list LBRACK QUOTE error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity . PRINTED label_or_token_list LBRACK error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity . PRINTED label_or_token_list error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 34
-- On PRINTED shift to state 35

State 34:
component -> CONSTRUCTOR UIDENT arity error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> CONSTRUCTOR UIDENT arity error
-- On LET reduce production component -> CONSTRUCTOR UIDENT arity error
-- On END reduce production component -> CONSTRUCTOR UIDENT arity error
-- On COVARIANT reduce production component -> CONSTRUCTOR UIDENT arity error
-- On CONTRAVARIANT reduce production component -> CONSTRUCTOR UIDENT arity error
-- On CONSTRUCTOR reduce production component -> CONSTRUCTOR UIDENT arity error

State 35:
component -> CONSTRUCTOR UIDENT arity PRINTED . label_or_token_list LBRACK QUOTE UIDENT RBRACK [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED . label_or_token_list LBRACK QUOTE UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED . label_or_token_list LBRACK QUOTE error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED . label_or_token_list LBRACK error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED . label_or_token_list error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 36
-- On QUOTE shift to state 37
-- On LPAREN shift to state 40
-- On LIDENT shift to state 45
-- On label_or_token_list shift to state 46
-- On first_label_or_token shift to state 55

State 36:
first_label_or_token -> error . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production first_label_or_token -> error
-- On QUOTE reduce production first_label_or_token -> error
-- On LPAREN reduce production first_label_or_token -> error
-- On LIDENT reduce production first_label_or_token -> error
-- On LBRACK reduce production first_label_or_token -> error

State 37:
first_label_or_token -> QUOTE . UIDENT [ error QUOTE LPAREN LIDENT LBRACK ]
first_label_or_token -> QUOTE . error [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error shift to state 38
-- On UIDENT shift to state 39

State 38:
first_label_or_token -> QUOTE error . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production first_label_or_token -> QUOTE error
-- On QUOTE reduce production first_label_or_token -> QUOTE error
-- On LPAREN reduce production first_label_or_token -> QUOTE error
-- On LIDENT reduce production first_label_or_token -> QUOTE error
-- On LBRACK reduce production first_label_or_token -> QUOTE error

State 39:
first_label_or_token -> QUOTE UIDENT . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production first_label_or_token -> QUOTE UIDENT
-- On QUOTE reduce production first_label_or_token -> QUOTE UIDENT
-- On LPAREN reduce production first_label_or_token -> QUOTE UIDENT
-- On LIDENT reduce production first_label_or_token -> QUOTE UIDENT
-- On LBRACK reduce production first_label_or_token -> QUOTE UIDENT

State 40:
first_label_or_token -> LPAREN . LIDENT RPAREN [ error QUOTE LPAREN LIDENT LBRACK ]
first_label_or_token -> LPAREN . LIDENT error [ error QUOTE LPAREN LIDENT LBRACK ]
first_label_or_token -> LPAREN . error [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error shift to state 41
-- On LIDENT shift to state 42

State 41:
first_label_or_token -> LPAREN error . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production first_label_or_token -> LPAREN error
-- On QUOTE reduce production first_label_or_token -> LPAREN error
-- On LPAREN reduce production first_label_or_token -> LPAREN error
-- On LIDENT reduce production first_label_or_token -> LPAREN error
-- On LBRACK reduce production first_label_or_token -> LPAREN error

State 42:
first_label_or_token -> LPAREN LIDENT . RPAREN [ error QUOTE LPAREN LIDENT LBRACK ]
first_label_or_token -> LPAREN LIDENT . error [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error shift to state 43
-- On RPAREN shift to state 44

State 43:
first_label_or_token -> LPAREN LIDENT error . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production first_label_or_token -> LPAREN LIDENT error
-- On QUOTE reduce production first_label_or_token -> LPAREN LIDENT error
-- On LPAREN reduce production first_label_or_token -> LPAREN LIDENT error
-- On LIDENT reduce production first_label_or_token -> LPAREN LIDENT error
-- On LBRACK reduce production first_label_or_token -> LPAREN LIDENT error

State 44:
first_label_or_token -> LPAREN LIDENT RPAREN . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production first_label_or_token -> LPAREN LIDENT RPAREN
-- On QUOTE reduce production first_label_or_token -> LPAREN LIDENT RPAREN
-- On LPAREN reduce production first_label_or_token -> LPAREN LIDENT RPAREN
-- On LIDENT reduce production first_label_or_token -> LPAREN LIDENT RPAREN
-- On LBRACK reduce production first_label_or_token -> LPAREN LIDENT RPAREN

State 45:
first_label_or_token -> LIDENT . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production first_label_or_token -> LIDENT
-- On QUOTE reduce production first_label_or_token -> LIDENT
-- On LPAREN reduce production first_label_or_token -> LIDENT
-- On LIDENT reduce production first_label_or_token -> LIDENT
-- On LBRACK reduce production first_label_or_token -> LIDENT

State 46:
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list . LBRACK QUOTE UIDENT RBRACK [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list . LBRACK QUOTE UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list . LBRACK QUOTE error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list . LBRACK error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 47
-- On LBRACK shift to state 48

State 47:
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list error
-- On LET reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list error
-- On END reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list error
-- On COVARIANT reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list error
-- On CONTRAVARIANT reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list error
-- On CONSTRUCTOR reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list error

State 48:
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK . QUOTE UIDENT RBRACK [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK . QUOTE UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK . QUOTE error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 49
-- On QUOTE shift to state 50

State 49:
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK error
-- On LET reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK error
-- On END reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK error
-- On COVARIANT reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK error
-- On CONTRAVARIANT reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK error
-- On CONSTRUCTOR reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK error

State 50:
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE . UIDENT RBRACK [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE . UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 51
-- On UIDENT shift to state 52

State 51:
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE error
-- On LET reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE error
-- On END reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE error
-- On COVARIANT reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE error
-- On CONTRAVARIANT reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE error
-- On CONSTRUCTOR reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE error

State 52:
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT . RBRACK [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 53
-- On RBRACK shift to state 54

State 53:
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT error
-- On LET reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT error
-- On END reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT error
-- On COVARIANT reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT error
-- On CONTRAVARIANT reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT error
-- On CONSTRUCTOR reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT error

State 54:
component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT RBRACK . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT RBRACK
-- On LET reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT RBRACK
-- On END reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT RBRACK
-- On COVARIANT reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT RBRACK
-- On CONTRAVARIANT reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT RBRACK
-- On CONSTRUCTOR reduce production component -> CONSTRUCTOR UIDENT arity PRINTED label_or_token_list LBRACK QUOTE UIDENT RBRACK

State 55:
label_or_token_list -> first_label_or_token . label_or_token_list0 [ error LBRACK ]
-- On error shift to state 56
-- On QUOTE shift to state 57
-- On LPAREN shift to state 60
-- On LIDENT shift to state 65
-- On next_label_or_token shift to state 66
-- On label_or_token_list0 shift to state 68
-- On LBRACK reduce production label_or_token_list0 ->
** Conflict on error

State 56:
next_label_or_token -> error . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production next_label_or_token -> error
-- On QUOTE reduce production next_label_or_token -> error
-- On LPAREN reduce production next_label_or_token -> error
-- On LIDENT reduce production next_label_or_token -> error
-- On LBRACK reduce production next_label_or_token -> error

State 57:
next_label_or_token -> QUOTE . UIDENT [ error QUOTE LPAREN LIDENT LBRACK ]
next_label_or_token -> QUOTE . error [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error shift to state 58
-- On UIDENT shift to state 59

State 58:
next_label_or_token -> QUOTE error . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production next_label_or_token -> QUOTE error
-- On QUOTE reduce production next_label_or_token -> QUOTE error
-- On LPAREN reduce production next_label_or_token -> QUOTE error
-- On LIDENT reduce production next_label_or_token -> QUOTE error
-- On LBRACK reduce production next_label_or_token -> QUOTE error

State 59:
next_label_or_token -> QUOTE UIDENT . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production next_label_or_token -> QUOTE UIDENT
-- On QUOTE reduce production next_label_or_token -> QUOTE UIDENT
-- On LPAREN reduce production next_label_or_token -> QUOTE UIDENT
-- On LIDENT reduce production next_label_or_token -> QUOTE UIDENT
-- On LBRACK reduce production next_label_or_token -> QUOTE UIDENT

State 60:
next_label_or_token -> LPAREN . LIDENT RPAREN [ error QUOTE LPAREN LIDENT LBRACK ]
next_label_or_token -> LPAREN . LIDENT error [ error QUOTE LPAREN LIDENT LBRACK ]
next_label_or_token -> LPAREN . error [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error shift to state 61
-- On LIDENT shift to state 62

State 61:
next_label_or_token -> LPAREN error . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production next_label_or_token -> LPAREN error
-- On QUOTE reduce production next_label_or_token -> LPAREN error
-- On LPAREN reduce production next_label_or_token -> LPAREN error
-- On LIDENT reduce production next_label_or_token -> LPAREN error
-- On LBRACK reduce production next_label_or_token -> LPAREN error

State 62:
next_label_or_token -> LPAREN LIDENT . RPAREN [ error QUOTE LPAREN LIDENT LBRACK ]
next_label_or_token -> LPAREN LIDENT . error [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error shift to state 63
-- On RPAREN shift to state 64

State 63:
next_label_or_token -> LPAREN LIDENT error . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production next_label_or_token -> LPAREN LIDENT error
-- On QUOTE reduce production next_label_or_token -> LPAREN LIDENT error
-- On LPAREN reduce production next_label_or_token -> LPAREN LIDENT error
-- On LIDENT reduce production next_label_or_token -> LPAREN LIDENT error
-- On LBRACK reduce production next_label_or_token -> LPAREN LIDENT error

State 64:
next_label_or_token -> LPAREN LIDENT RPAREN . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production next_label_or_token -> LPAREN LIDENT RPAREN
-- On QUOTE reduce production next_label_or_token -> LPAREN LIDENT RPAREN
-- On LPAREN reduce production next_label_or_token -> LPAREN LIDENT RPAREN
-- On LIDENT reduce production next_label_or_token -> LPAREN LIDENT RPAREN
-- On LBRACK reduce production next_label_or_token -> LPAREN LIDENT RPAREN

State 65:
next_label_or_token -> LIDENT . [ error QUOTE LPAREN LIDENT LBRACK ]
-- On error reduce production next_label_or_token -> LIDENT
-- On QUOTE reduce production next_label_or_token -> LIDENT
-- On LPAREN reduce production next_label_or_token -> LIDENT
-- On LIDENT reduce production next_label_or_token -> LIDENT
-- On LBRACK reduce production next_label_or_token -> LIDENT

State 66:
label_or_token_list0 -> next_label_or_token . label_or_token_list0 [ error LBRACK ]
-- On error shift to state 56
-- On QUOTE shift to state 57
-- On LPAREN shift to state 60
-- On LIDENT shift to state 65
-- On next_label_or_token shift to state 66
-- On label_or_token_list0 shift to state 67
-- On LBRACK reduce production label_or_token_list0 ->
** Conflict on error

State 67:
label_or_token_list0 -> next_label_or_token label_or_token_list0 . [ error LBRACK ]
-- On error reduce production label_or_token_list0 -> next_label_or_token label_or_token_list0
-- On LBRACK reduce production label_or_token_list0 -> next_label_or_token label_or_token_list0

State 68:
label_or_token_list -> first_label_or_token label_or_token_list0 . [ error LBRACK ]
-- On error reduce production label_or_token_list -> first_label_or_token label_or_token_list0
-- On LBRACK reduce production label_or_token_list -> first_label_or_token label_or_token_list0

State 69:
component -> variance . UIDENT LIDENT [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance . UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance . LESS UIDENT MORE LIDENT [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance . LESS UIDENT MORE error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance . LESS UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance . LESS error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 70
-- On UIDENT shift to state 71
-- On LESS shift to state 74

State 70:
component -> variance error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> variance error
-- On LET reduce production component -> variance error
-- On END reduce production component -> variance error
-- On COVARIANT reduce production component -> variance error
-- On CONTRAVARIANT reduce production component -> variance error
-- On CONSTRUCTOR reduce production component -> variance error

State 71:
component -> variance UIDENT . LIDENT [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance UIDENT . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 72
-- On LIDENT shift to state 73

State 72:
component -> variance UIDENT error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> variance UIDENT error
-- On LET reduce production component -> variance UIDENT error
-- On END reduce production component -> variance UIDENT error
-- On COVARIANT reduce production component -> variance UIDENT error
-- On CONTRAVARIANT reduce production component -> variance UIDENT error
-- On CONSTRUCTOR reduce production component -> variance UIDENT error

State 73:
component -> variance UIDENT LIDENT . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> variance UIDENT LIDENT
-- On LET reduce production component -> variance UIDENT LIDENT
-- On END reduce production component -> variance UIDENT LIDENT
-- On COVARIANT reduce production component -> variance UIDENT LIDENT
-- On CONTRAVARIANT reduce production component -> variance UIDENT LIDENT
-- On CONSTRUCTOR reduce production component -> variance UIDENT LIDENT

State 74:
component -> variance LESS . UIDENT MORE LIDENT [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance LESS . UIDENT MORE error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance LESS . UIDENT error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance LESS . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 75
-- On UIDENT shift to state 76

State 75:
component -> variance LESS error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> variance LESS error
-- On LET reduce production component -> variance LESS error
-- On END reduce production component -> variance LESS error
-- On COVARIANT reduce production component -> variance LESS error
-- On CONTRAVARIANT reduce production component -> variance LESS error
-- On CONSTRUCTOR reduce production component -> variance LESS error

State 76:
component -> variance LESS UIDENT . MORE LIDENT [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance LESS UIDENT . MORE error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance LESS UIDENT . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 77
-- On MORE shift to state 78

State 77:
component -> variance LESS UIDENT error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> variance LESS UIDENT error
-- On LET reduce production component -> variance LESS UIDENT error
-- On END reduce production component -> variance LESS UIDENT error
-- On COVARIANT reduce production component -> variance LESS UIDENT error
-- On CONTRAVARIANT reduce production component -> variance LESS UIDENT error
-- On CONSTRUCTOR reduce production component -> variance LESS UIDENT error

State 78:
component -> variance LESS UIDENT MORE . LIDENT [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
component -> variance LESS UIDENT MORE . error [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error shift to state 79
-- On LIDENT shift to state 80

State 79:
component -> variance LESS UIDENT MORE error . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> variance LESS UIDENT MORE error
-- On LET reduce production component -> variance LESS UIDENT MORE error
-- On END reduce production component -> variance LESS UIDENT MORE error
-- On COVARIANT reduce production component -> variance LESS UIDENT MORE error
-- On CONTRAVARIANT reduce production component -> variance LESS UIDENT MORE error
-- On CONSTRUCTOR reduce production component -> variance LESS UIDENT MORE error

State 80:
component -> variance LESS UIDENT MORE LIDENT . [ error LET END COVARIANT CONTRAVARIANT CONSTRUCTOR ]
-- On error reduce production component -> variance LESS UIDENT MORE LIDENT
-- On LET reduce production component -> variance LESS UIDENT MORE LIDENT
-- On END reduce production component -> variance LESS UIDENT MORE LIDENT
-- On COVARIANT reduce production component -> variance LESS UIDENT MORE LIDENT
-- On CONTRAVARIANT reduce production component -> variance LESS UIDENT MORE LIDENT
-- On CONSTRUCTOR reduce production component -> variance LESS UIDENT MORE LIDENT

State 81:
lattice -> LATTICE UIDENT BEGIN lattice_component_list . END [ error LATTICE END ]
-- On END shift to state 82

State 82:
lattice -> LATTICE UIDENT BEGIN lattice_component_list END . [ error LATTICE END ]
-- On error reduce production lattice -> LATTICE UIDENT BEGIN lattice_component_list END
-- On LATTICE reduce production lattice -> LATTICE UIDENT BEGIN lattice_component_list END
-- On END reduce production lattice -> LATTICE UIDENT BEGIN lattice_component_list END

State 83:
lattice_component_list -> component . [ END ]
lattice_component_list -> component . lattice_component_list [ END ]
-- On error shift to state 11
-- On LET shift to state 12
-- On COVARIANT shift to state 19
-- On CONTRAVARIANT shift to state 20
-- On CONSTRUCTOR shift to state 21
-- On variance shift to state 69
-- On lattice_component_list shift to state 84
-- On component shift to state 83
-- On END reduce production lattice_component_list -> component

State 84:
lattice_component_list -> component lattice_component_list . [ END ]
-- On END reduce production lattice_component_list -> component lattice_component_list

State 85:
signature -> SIGNATURE BEGIN lattice_list . END PRIORITY constructor_list [ # ]
signature -> SIGNATURE BEGIN lattice_list . END error [ # ]
-- On END shift to state 86

State 86:
signature -> SIGNATURE BEGIN lattice_list END . PRIORITY constructor_list [ # ]
signature -> SIGNATURE BEGIN lattice_list END . error [ # ]
-- On error shift to state 87
-- On PRIORITY shift to state 88

State 87:
signature -> SIGNATURE BEGIN lattice_list END error . [ # ]
-- On # reduce production signature -> SIGNATURE BEGIN lattice_list END error

State 88:
signature -> SIGNATURE BEGIN lattice_list END PRIORITY . constructor_list [ # ]
-- On error shift to state 89
-- On UIDENT shift to state 90
-- On constructor_list shift to state 92

State 89:
constructor_list -> error . [ # ]
-- On # reduce production constructor_list -> error

State 90:
constructor_list -> UIDENT . constructor_list [ # ]
-- On error shift to state 89
-- On UIDENT shift to state 90
-- On constructor_list shift to state 91

State 91:
constructor_list -> UIDENT constructor_list . [ # ]
-- On # reduce production constructor_list -> UIDENT constructor_list

State 92:
signature -> SIGNATURE BEGIN lattice_list END PRIORITY constructor_list . [ # ]
-- On # reduce production signature -> SIGNATURE BEGIN lattice_list END PRIORITY constructor_list

State 93:
lattice_list -> lattice . [ END ]
lattice_list -> lattice . lattice_list [ END ]
-- On error shift to state 5
-- On LATTICE shift to state 6
-- On lattice_list shift to state 94
-- On lattice shift to state 93
-- On END reduce production lattice_list -> lattice

State 94:
lattice_list -> lattice lattice_list . [ END ]
-- On END reduce production lattice_list -> lattice lattice_list

State 95:
signature' -> signature . [ # ]
-- On # accept signature

