State 0:
instr_option_seq' -> . instr_option_seq [ # ]
-- On XORI shift to state 1
-- On XORDOT shift to state 11
-- On XOR shift to state 17
-- On SYNC shift to state 23
-- On SUBI shift to state 24
-- On SUBFDOT shift to state 30
-- On SUBF shift to state 36
-- On SUBDOT shift to state 42
-- On SUB shift to state 48
-- On STWX shift to state 54
-- On STWU shift to state 60
-- On STWCX shift to state 71
-- On STW shift to state 77
-- On STMW shift to state 86
-- On STHX shift to state 93
-- On STH shift to state 99
-- On STDX shift to state 108
-- On STD shift to state 114
-- On STBX shift to state 123
-- On STB shift to state 129
-- On SRAWI shift to state 138
-- On SRAW shift to state 144
-- On SLW shift to state 150
-- On ORI shift to state 156
-- On ORDOT shift to state 162
-- On OR shift to state 168
-- On NORDOT shift to state 174
-- On NOR shift to state 180
-- On NEGDOT shift to state 186
-- On NEG shift to state 190
-- On NAME shift to state 194
-- On MULLI shift to state 202
-- On MULLDOT shift to state 208
-- On MULL shift to state 214
-- On MTLR shift to state 220
-- On MR shift to state 222
-- On MFLR shift to state 226
-- On LWZX shift to state 228
-- On LWZU shift to state 234
-- On LWZ shift to state 243
-- On LWSYNC shift to state 252
-- On LWARX shift to state 253
-- On LMW shift to state 259
-- On LI shift to state 266
-- On LHZX shift to state 270
-- On LHZ shift to state 276
-- On LDX shift to state 285
-- On LD shift to state 291
-- On LBZX shift to state 300
-- On LBZ shift to state 306
-- On ISYNC shift to state 315
-- On EIEIO shift to state 316
-- On DIVDOT shift to state 317
-- On DIV shift to state 323
-- On DCBF shift to state 329
-- On COMMENT shift to state 333
-- On CMPWI shift to state 335
-- On CMPW shift to state 345
-- On BNL shift to state 354
-- On BNG shift to state 356
-- On BNE shift to state 358
-- On BLT shift to state 360
-- On BLR shift to state 362
-- On BLE shift to state 363
-- On BL shift to state 365
-- On BGT shift to state 367
-- On BGE shift to state 369
-- On BEQ shift to state 371
-- On B shift to state 373
-- On ANDIDOT shift to state 375
-- On ANDDOT shift to state 381
-- On AND shift to state 387
-- On ADDI shift to state 393
-- On ADDDOT shift to state 399
-- On ADD shift to state 405
-- On instr_option_seq shift to state 413
-- On instr_option shift to state 414
-- On instr shift to state 412
-- On SEMI reduce production instr_option ->

State 1:
instr -> XORI . reg COMMA reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 4

State 2:
reg -> SYMB_REG . [ SEMI RPAR PIPE COMMA # ]
-- On SEMI reduce production reg -> SYMB_REG
-- On RPAR reduce production reg -> SYMB_REG
-- On PIPE reduce production reg -> SYMB_REG
-- On COMMA reduce production reg -> SYMB_REG

State 3:
reg -> ARCH_REG . [ SEMI RPAR PIPE COMMA # ]
-- On SEMI reduce production reg -> ARCH_REG
-- On RPAR reduce production reg -> ARCH_REG
-- On PIPE reduce production reg -> ARCH_REG
-- On COMMA reduce production reg -> ARCH_REG

State 4:
instr -> XORI reg . COMMA reg COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 5

State 5:
instr -> XORI reg COMMA . reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 6

State 6:
instr -> XORI reg COMMA reg . COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 7

State 7:
instr -> XORI reg COMMA reg COMMA . k [ SEMI PIPE # ]
-- On NUM shift to state 8
-- On CSTVAR shift to state 9
-- On k shift to state 10

State 8:
k -> NUM . [ SEMI PIPE # ]
-- On SEMI reduce production k -> NUM
-- On PIPE reduce production k -> NUM

State 9:
k -> CSTVAR . [ SEMI PIPE # ]
-- On SEMI reduce production k -> CSTVAR
-- On PIPE reduce production k -> CSTVAR

State 10:
instr -> XORI reg COMMA reg COMMA k . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> XORI reg COMMA reg COMMA k
-- On PIPE reduce production instr -> XORI reg COMMA reg COMMA k

State 11:
instr -> XORDOT . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 12

State 12:
instr -> XORDOT reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 13

State 13:
instr -> XORDOT reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 14

State 14:
instr -> XORDOT reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 15

State 15:
instr -> XORDOT reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 16

State 16:
instr -> XORDOT reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> XORDOT reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> XORDOT reg COMMA reg COMMA reg

State 17:
instr -> XOR . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 18

State 18:
instr -> XOR reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 19

State 19:
instr -> XOR reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 20

State 20:
instr -> XOR reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 21

State 21:
instr -> XOR reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 22

State 22:
instr -> XOR reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> XOR reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> XOR reg COMMA reg COMMA reg

State 23:
instr -> SYNC . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> SYNC
-- On PIPE reduce production instr -> SYNC

State 24:
instr -> SUBI . reg COMMA reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 25

State 25:
instr -> SUBI reg . COMMA reg COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 26

State 26:
instr -> SUBI reg COMMA . reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 27

State 27:
instr -> SUBI reg COMMA reg . COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 28

State 28:
instr -> SUBI reg COMMA reg COMMA . k [ SEMI PIPE # ]
-- On NUM shift to state 8
-- On CSTVAR shift to state 9
-- On k shift to state 29

State 29:
instr -> SUBI reg COMMA reg COMMA k . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> SUBI reg COMMA reg COMMA k
-- On PIPE reduce production instr -> SUBI reg COMMA reg COMMA k

State 30:
instr -> SUBFDOT . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 31

State 31:
instr -> SUBFDOT reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 32

State 32:
instr -> SUBFDOT reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 33

State 33:
instr -> SUBFDOT reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 34

State 34:
instr -> SUBFDOT reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 35

State 35:
instr -> SUBFDOT reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> SUBFDOT reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> SUBFDOT reg COMMA reg COMMA reg

State 36:
instr -> SUBF . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 37

State 37:
instr -> SUBF reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 38

State 38:
instr -> SUBF reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 39

State 39:
instr -> SUBF reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 40

State 40:
instr -> SUBF reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 41

State 41:
instr -> SUBF reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> SUBF reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> SUBF reg COMMA reg COMMA reg

State 42:
instr -> SUBDOT . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 43

State 43:
instr -> SUBDOT reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 44

State 44:
instr -> SUBDOT reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 45

State 45:
instr -> SUBDOT reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 46

State 46:
instr -> SUBDOT reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 47

State 47:
instr -> SUBDOT reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> SUBDOT reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> SUBDOT reg COMMA reg COMMA reg

State 48:
instr -> SUB . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 49

State 49:
instr -> SUB reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 50

State 50:
instr -> SUB reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 51

State 51:
instr -> SUB reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 52

State 52:
instr -> SUB reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 53

State 53:
instr -> SUB reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> SUB reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> SUB reg COMMA reg COMMA reg

State 54:
instr -> STWX . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 55

State 55:
instr -> STWX reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 56

State 56:
instr -> STWX reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 57

State 57:
instr -> STWX reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 58

State 58:
instr -> STWX reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 59

State 59:
instr -> STWX reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STWX reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> STWX reg COMMA reg COMMA reg

State 60:
instr -> STWU . reg COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> STWU . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 61

State 61:
instr -> STWU reg . COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> STWU reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 62

State 62:
instr -> STWU reg COMMA . idx COMMA reg [ SEMI PIPE # ]
instr -> STWU reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 65

State 63:
idx -> NUM . [ LPAR COMMA ]
-- On LPAR reduce production idx -> NUM
-- On COMMA reduce production idx -> NUM

State 64:
idx -> CSTVAR . [ LPAR COMMA ]
-- On LPAR reduce production idx -> CSTVAR
-- On COMMA reduce production idx -> CSTVAR

State 65:
instr -> STWU reg COMMA idx . COMMA reg [ SEMI PIPE # ]
instr -> STWU reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 66
-- On COMMA shift to state 69

State 66:
instr -> STWU reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 67

State 67:
instr -> STWU reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 68

State 68:
instr -> STWU reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STWU reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> STWU reg COMMA idx LPAR reg RPAR

State 69:
instr -> STWU reg COMMA idx COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 70

State 70:
instr -> STWU reg COMMA idx COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STWU reg COMMA idx COMMA reg
-- On PIPE reduce production instr -> STWU reg COMMA idx COMMA reg

State 71:
instr -> STWCX . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 72

State 72:
instr -> STWCX reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 73

State 73:
instr -> STWCX reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 74

State 74:
instr -> STWCX reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 75

State 75:
instr -> STWCX reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 76

State 76:
instr -> STWCX reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STWCX reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> STWCX reg COMMA reg COMMA reg

State 77:
instr -> STW . reg COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> STW . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 78

State 78:
instr -> STW reg . COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> STW reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 79

State 79:
instr -> STW reg COMMA . idx COMMA reg [ SEMI PIPE # ]
instr -> STW reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 80

State 80:
instr -> STW reg COMMA idx . COMMA reg [ SEMI PIPE # ]
instr -> STW reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 81
-- On COMMA shift to state 84

State 81:
instr -> STW reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 82

State 82:
instr -> STW reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 83

State 83:
instr -> STW reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STW reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> STW reg COMMA idx LPAR reg RPAR

State 84:
instr -> STW reg COMMA idx COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 85

State 85:
instr -> STW reg COMMA idx COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STW reg COMMA idx COMMA reg
-- On PIPE reduce production instr -> STW reg COMMA idx COMMA reg

State 86:
instr -> STMW . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 87

State 87:
instr -> STMW reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 88

State 88:
instr -> STMW reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 89

State 89:
instr -> STMW reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 90

State 90:
instr -> STMW reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 91

State 91:
instr -> STMW reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 92

State 92:
instr -> STMW reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STMW reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> STMW reg COMMA idx LPAR reg RPAR

State 93:
instr -> STHX . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 94

State 94:
instr -> STHX reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 95

State 95:
instr -> STHX reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 96

State 96:
instr -> STHX reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 97

State 97:
instr -> STHX reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 98

State 98:
instr -> STHX reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STHX reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> STHX reg COMMA reg COMMA reg

State 99:
instr -> STH . reg COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> STH . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 100

State 100:
instr -> STH reg . COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> STH reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 101

State 101:
instr -> STH reg COMMA . idx COMMA reg [ SEMI PIPE # ]
instr -> STH reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 102

State 102:
instr -> STH reg COMMA idx . COMMA reg [ SEMI PIPE # ]
instr -> STH reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 103
-- On COMMA shift to state 106

State 103:
instr -> STH reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 104

State 104:
instr -> STH reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 105

State 105:
instr -> STH reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STH reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> STH reg COMMA idx LPAR reg RPAR

State 106:
instr -> STH reg COMMA idx COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 107

State 107:
instr -> STH reg COMMA idx COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STH reg COMMA idx COMMA reg
-- On PIPE reduce production instr -> STH reg COMMA idx COMMA reg

State 108:
instr -> STDX . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 109

State 109:
instr -> STDX reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 110

State 110:
instr -> STDX reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 111

State 111:
instr -> STDX reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 112

State 112:
instr -> STDX reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 113

State 113:
instr -> STDX reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STDX reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> STDX reg COMMA reg COMMA reg

State 114:
instr -> STD . reg COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> STD . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 115

State 115:
instr -> STD reg . COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> STD reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 116

State 116:
instr -> STD reg COMMA . idx COMMA reg [ SEMI PIPE # ]
instr -> STD reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 117

State 117:
instr -> STD reg COMMA idx . COMMA reg [ SEMI PIPE # ]
instr -> STD reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 118
-- On COMMA shift to state 121

State 118:
instr -> STD reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 119

State 119:
instr -> STD reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 120

State 120:
instr -> STD reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STD reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> STD reg COMMA idx LPAR reg RPAR

State 121:
instr -> STD reg COMMA idx COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 122

State 122:
instr -> STD reg COMMA idx COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STD reg COMMA idx COMMA reg
-- On PIPE reduce production instr -> STD reg COMMA idx COMMA reg

State 123:
instr -> STBX . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 124

State 124:
instr -> STBX reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 125

State 125:
instr -> STBX reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 126

State 126:
instr -> STBX reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 127

State 127:
instr -> STBX reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 128

State 128:
instr -> STBX reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STBX reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> STBX reg COMMA reg COMMA reg

State 129:
instr -> STB . reg COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> STB . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 130

State 130:
instr -> STB reg . COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> STB reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 131

State 131:
instr -> STB reg COMMA . idx COMMA reg [ SEMI PIPE # ]
instr -> STB reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 132

State 132:
instr -> STB reg COMMA idx . COMMA reg [ SEMI PIPE # ]
instr -> STB reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 133
-- On COMMA shift to state 136

State 133:
instr -> STB reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 134

State 134:
instr -> STB reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 135

State 135:
instr -> STB reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STB reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> STB reg COMMA idx LPAR reg RPAR

State 136:
instr -> STB reg COMMA idx COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 137

State 137:
instr -> STB reg COMMA idx COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> STB reg COMMA idx COMMA reg
-- On PIPE reduce production instr -> STB reg COMMA idx COMMA reg

State 138:
instr -> SRAWI . reg COMMA reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 139

State 139:
instr -> SRAWI reg . COMMA reg COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 140

State 140:
instr -> SRAWI reg COMMA . reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 141

State 141:
instr -> SRAWI reg COMMA reg . COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 142

State 142:
instr -> SRAWI reg COMMA reg COMMA . k [ SEMI PIPE # ]
-- On NUM shift to state 8
-- On CSTVAR shift to state 9
-- On k shift to state 143

State 143:
instr -> SRAWI reg COMMA reg COMMA k . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> SRAWI reg COMMA reg COMMA k
-- On PIPE reduce production instr -> SRAWI reg COMMA reg COMMA k

State 144:
instr -> SRAW . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 145

State 145:
instr -> SRAW reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 146

State 146:
instr -> SRAW reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 147

State 147:
instr -> SRAW reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 148

State 148:
instr -> SRAW reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 149

State 149:
instr -> SRAW reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> SRAW reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> SRAW reg COMMA reg COMMA reg

State 150:
instr -> SLW . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 151

State 151:
instr -> SLW reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 152

State 152:
instr -> SLW reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 153

State 153:
instr -> SLW reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 154

State 154:
instr -> SLW reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 155

State 155:
instr -> SLW reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> SLW reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> SLW reg COMMA reg COMMA reg

State 156:
instr -> ORI . reg COMMA reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 157

State 157:
instr -> ORI reg . COMMA reg COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 158

State 158:
instr -> ORI reg COMMA . reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 159

State 159:
instr -> ORI reg COMMA reg . COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 160

State 160:
instr -> ORI reg COMMA reg COMMA . k [ SEMI PIPE # ]
-- On NUM shift to state 8
-- On CSTVAR shift to state 9
-- On k shift to state 161

State 161:
instr -> ORI reg COMMA reg COMMA k . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> ORI reg COMMA reg COMMA k
-- On PIPE reduce production instr -> ORI reg COMMA reg COMMA k

State 162:
instr -> ORDOT . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 163

State 163:
instr -> ORDOT reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 164

State 164:
instr -> ORDOT reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 165

State 165:
instr -> ORDOT reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 166

State 166:
instr -> ORDOT reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 167

State 167:
instr -> ORDOT reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> ORDOT reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> ORDOT reg COMMA reg COMMA reg

State 168:
instr -> OR . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 169

State 169:
instr -> OR reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 170

State 170:
instr -> OR reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 171

State 171:
instr -> OR reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 172

State 172:
instr -> OR reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 173

State 173:
instr -> OR reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> OR reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> OR reg COMMA reg COMMA reg

State 174:
instr -> NORDOT . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 175

State 175:
instr -> NORDOT reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 176

State 176:
instr -> NORDOT reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 177

State 177:
instr -> NORDOT reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 178

State 178:
instr -> NORDOT reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 179

State 179:
instr -> NORDOT reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> NORDOT reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> NORDOT reg COMMA reg COMMA reg

State 180:
instr -> NOR . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 181

State 181:
instr -> NOR reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 182

State 182:
instr -> NOR reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 183

State 183:
instr -> NOR reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 184

State 184:
instr -> NOR reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 185

State 185:
instr -> NOR reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> NOR reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> NOR reg COMMA reg COMMA reg

State 186:
instr -> NEGDOT . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 187

State 187:
instr -> NEGDOT reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 188

State 188:
instr -> NEGDOT reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 189

State 189:
instr -> NEGDOT reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> NEGDOT reg COMMA reg
-- On PIPE reduce production instr -> NEGDOT reg COMMA reg

State 190:
instr -> NEG . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 191

State 191:
instr -> NEG reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 192

State 192:
instr -> NEG reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 193

State 193:
instr -> NEG reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> NEG reg COMMA reg
-- On PIPE reduce production instr -> NEG reg COMMA reg

State 194:
instr_option -> NAME . COLON instr_option [ SEMI PIPE # ]
instr_option -> NAME . LPAR reg_list RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 195
-- On COLON shift to state 201

State 195:
instr_option -> NAME LPAR . reg_list RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg_list shift to state 196
-- On reg shift to state 198
-- On RPAR reduce production reg_list ->

State 196:
instr_option -> NAME LPAR reg_list . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 197

State 197:
instr_option -> NAME LPAR reg_list RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr_option -> NAME LPAR reg_list RPAR
-- On PIPE reduce production instr_option -> NAME LPAR reg_list RPAR

State 198:
reg_list -> reg . [ RPAR ]
reg_list -> reg . COMMA reg_list [ RPAR ]
-- On COMMA shift to state 199
-- On RPAR reduce production reg_list -> reg

State 199:
reg_list -> reg COMMA . reg_list [ RPAR ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg_list shift to state 200
-- On reg shift to state 198
-- On RPAR reduce production reg_list ->

State 200:
reg_list -> reg COMMA reg_list . [ RPAR ]
-- On RPAR reduce production reg_list -> reg COMMA reg_list

State 201:
instr_option -> NAME COLON . instr_option [ SEMI PIPE # ]
-- On XORI shift to state 1
-- On XORDOT shift to state 11
-- On XOR shift to state 17
-- On SYNC shift to state 23
-- On SUBI shift to state 24
-- On SUBFDOT shift to state 30
-- On SUBF shift to state 36
-- On SUBDOT shift to state 42
-- On SUB shift to state 48
-- On STWX shift to state 54
-- On STWU shift to state 60
-- On STWCX shift to state 71
-- On STW shift to state 77
-- On STMW shift to state 86
-- On STHX shift to state 93
-- On STH shift to state 99
-- On STDX shift to state 108
-- On STD shift to state 114
-- On STBX shift to state 123
-- On STB shift to state 129
-- On SRAWI shift to state 138
-- On SRAW shift to state 144
-- On SLW shift to state 150
-- On ORI shift to state 156
-- On ORDOT shift to state 162
-- On OR shift to state 168
-- On NORDOT shift to state 174
-- On NOR shift to state 180
-- On NEGDOT shift to state 186
-- On NEG shift to state 190
-- On NAME shift to state 194
-- On MULLI shift to state 202
-- On MULLDOT shift to state 208
-- On MULL shift to state 214
-- On MTLR shift to state 220
-- On MR shift to state 222
-- On MFLR shift to state 226
-- On LWZX shift to state 228
-- On LWZU shift to state 234
-- On LWZ shift to state 243
-- On LWSYNC shift to state 252
-- On LWARX shift to state 253
-- On LMW shift to state 259
-- On LI shift to state 266
-- On LHZX shift to state 270
-- On LHZ shift to state 276
-- On LDX shift to state 285
-- On LD shift to state 291
-- On LBZX shift to state 300
-- On LBZ shift to state 306
-- On ISYNC shift to state 315
-- On EIEIO shift to state 316
-- On DIVDOT shift to state 317
-- On DIV shift to state 323
-- On DCBF shift to state 329
-- On COMMENT shift to state 333
-- On CMPWI shift to state 335
-- On CMPW shift to state 345
-- On BNL shift to state 354
-- On BNG shift to state 356
-- On BNE shift to state 358
-- On BLT shift to state 360
-- On BLR shift to state 362
-- On BLE shift to state 363
-- On BL shift to state 365
-- On BGT shift to state 367
-- On BGE shift to state 369
-- On BEQ shift to state 371
-- On B shift to state 373
-- On ANDIDOT shift to state 375
-- On ANDDOT shift to state 381
-- On AND shift to state 387
-- On ADDI shift to state 393
-- On ADDDOT shift to state 399
-- On ADD shift to state 405
-- On instr_option shift to state 411
-- On instr shift to state 412
-- On SEMI reduce production instr_option ->
-- On PIPE reduce production instr_option ->

State 202:
instr -> MULLI . reg COMMA reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 203

State 203:
instr -> MULLI reg . COMMA reg COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 204

State 204:
instr -> MULLI reg COMMA . reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 205

State 205:
instr -> MULLI reg COMMA reg . COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 206

State 206:
instr -> MULLI reg COMMA reg COMMA . k [ SEMI PIPE # ]
-- On NUM shift to state 8
-- On CSTVAR shift to state 9
-- On k shift to state 207

State 207:
instr -> MULLI reg COMMA reg COMMA k . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> MULLI reg COMMA reg COMMA k
-- On PIPE reduce production instr -> MULLI reg COMMA reg COMMA k

State 208:
instr -> MULLDOT . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 209

State 209:
instr -> MULLDOT reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 210

State 210:
instr -> MULLDOT reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 211

State 211:
instr -> MULLDOT reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 212

State 212:
instr -> MULLDOT reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 213

State 213:
instr -> MULLDOT reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> MULLDOT reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> MULLDOT reg COMMA reg COMMA reg

State 214:
instr -> MULL . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 215

State 215:
instr -> MULL reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 216

State 216:
instr -> MULL reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 217

State 217:
instr -> MULL reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 218

State 218:
instr -> MULL reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 219

State 219:
instr -> MULL reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> MULL reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> MULL reg COMMA reg COMMA reg

State 220:
instr -> MTLR . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 221

State 221:
instr -> MTLR reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> MTLR reg
-- On PIPE reduce production instr -> MTLR reg

State 222:
instr -> MR . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 223

State 223:
instr -> MR reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 224

State 224:
instr -> MR reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 225

State 225:
instr -> MR reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> MR reg COMMA reg
-- On PIPE reduce production instr -> MR reg COMMA reg

State 226:
instr -> MFLR . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 227

State 227:
instr -> MFLR reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> MFLR reg
-- On PIPE reduce production instr -> MFLR reg

State 228:
instr -> LWZX . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 229

State 229:
instr -> LWZX reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 230

State 230:
instr -> LWZX reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 231

State 231:
instr -> LWZX reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 232

State 232:
instr -> LWZX reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 233

State 233:
instr -> LWZX reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LWZX reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> LWZX reg COMMA reg COMMA reg

State 234:
instr -> LWZU . reg COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> LWZU . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 235

State 235:
instr -> LWZU reg . COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> LWZU reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 236

State 236:
instr -> LWZU reg COMMA . idx COMMA reg [ SEMI PIPE # ]
instr -> LWZU reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 237

State 237:
instr -> LWZU reg COMMA idx . COMMA reg [ SEMI PIPE # ]
instr -> LWZU reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 238
-- On COMMA shift to state 241

State 238:
instr -> LWZU reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 239

State 239:
instr -> LWZU reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 240

State 240:
instr -> LWZU reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LWZU reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> LWZU reg COMMA idx LPAR reg RPAR

State 241:
instr -> LWZU reg COMMA idx COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 242

State 242:
instr -> LWZU reg COMMA idx COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LWZU reg COMMA idx COMMA reg
-- On PIPE reduce production instr -> LWZU reg COMMA idx COMMA reg

State 243:
instr -> LWZ . reg COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> LWZ . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 244

State 244:
instr -> LWZ reg . COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> LWZ reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 245

State 245:
instr -> LWZ reg COMMA . idx COMMA reg [ SEMI PIPE # ]
instr -> LWZ reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 246

State 246:
instr -> LWZ reg COMMA idx . COMMA reg [ SEMI PIPE # ]
instr -> LWZ reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 247
-- On COMMA shift to state 250

State 247:
instr -> LWZ reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 248

State 248:
instr -> LWZ reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 249

State 249:
instr -> LWZ reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LWZ reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> LWZ reg COMMA idx LPAR reg RPAR

State 250:
instr -> LWZ reg COMMA idx COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 251

State 251:
instr -> LWZ reg COMMA idx COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LWZ reg COMMA idx COMMA reg
-- On PIPE reduce production instr -> LWZ reg COMMA idx COMMA reg

State 252:
instr -> LWSYNC . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LWSYNC
-- On PIPE reduce production instr -> LWSYNC

State 253:
instr -> LWARX . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 254

State 254:
instr -> LWARX reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 255

State 255:
instr -> LWARX reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 256

State 256:
instr -> LWARX reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 257

State 257:
instr -> LWARX reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 258

State 258:
instr -> LWARX reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LWARX reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> LWARX reg COMMA reg COMMA reg

State 259:
instr -> LMW . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 260

State 260:
instr -> LMW reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 261

State 261:
instr -> LMW reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 262

State 262:
instr -> LMW reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 263

State 263:
instr -> LMW reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 264

State 264:
instr -> LMW reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 265

State 265:
instr -> LMW reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LMW reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> LMW reg COMMA idx LPAR reg RPAR

State 266:
instr -> LI . reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 267

State 267:
instr -> LI reg . COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 268

State 268:
instr -> LI reg COMMA . k [ SEMI PIPE # ]
-- On NUM shift to state 8
-- On CSTVAR shift to state 9
-- On k shift to state 269

State 269:
instr -> LI reg COMMA k . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LI reg COMMA k
-- On PIPE reduce production instr -> LI reg COMMA k

State 270:
instr -> LHZX . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 271

State 271:
instr -> LHZX reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 272

State 272:
instr -> LHZX reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 273

State 273:
instr -> LHZX reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 274

State 274:
instr -> LHZX reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 275

State 275:
instr -> LHZX reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LHZX reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> LHZX reg COMMA reg COMMA reg

State 276:
instr -> LHZ . reg COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> LHZ . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 277

State 277:
instr -> LHZ reg . COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> LHZ reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 278

State 278:
instr -> LHZ reg COMMA . idx COMMA reg [ SEMI PIPE # ]
instr -> LHZ reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 279

State 279:
instr -> LHZ reg COMMA idx . COMMA reg [ SEMI PIPE # ]
instr -> LHZ reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 280
-- On COMMA shift to state 283

State 280:
instr -> LHZ reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 281

State 281:
instr -> LHZ reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 282

State 282:
instr -> LHZ reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LHZ reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> LHZ reg COMMA idx LPAR reg RPAR

State 283:
instr -> LHZ reg COMMA idx COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 284

State 284:
instr -> LHZ reg COMMA idx COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LHZ reg COMMA idx COMMA reg
-- On PIPE reduce production instr -> LHZ reg COMMA idx COMMA reg

State 285:
instr -> LDX . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 286

State 286:
instr -> LDX reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 287

State 287:
instr -> LDX reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 288

State 288:
instr -> LDX reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 289

State 289:
instr -> LDX reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 290

State 290:
instr -> LDX reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LDX reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> LDX reg COMMA reg COMMA reg

State 291:
instr -> LD . reg COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> LD . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 292

State 292:
instr -> LD reg . COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> LD reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 293

State 293:
instr -> LD reg COMMA . idx COMMA reg [ SEMI PIPE # ]
instr -> LD reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 294

State 294:
instr -> LD reg COMMA idx . COMMA reg [ SEMI PIPE # ]
instr -> LD reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 295
-- On COMMA shift to state 298

State 295:
instr -> LD reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 296

State 296:
instr -> LD reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 297

State 297:
instr -> LD reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LD reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> LD reg COMMA idx LPAR reg RPAR

State 298:
instr -> LD reg COMMA idx COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 299

State 299:
instr -> LD reg COMMA idx COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LD reg COMMA idx COMMA reg
-- On PIPE reduce production instr -> LD reg COMMA idx COMMA reg

State 300:
instr -> LBZX . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 301

State 301:
instr -> LBZX reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 302

State 302:
instr -> LBZX reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 303

State 303:
instr -> LBZX reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 304

State 304:
instr -> LBZX reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 305

State 305:
instr -> LBZX reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LBZX reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> LBZX reg COMMA reg COMMA reg

State 306:
instr -> LBZ . reg COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> LBZ . reg COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 307

State 307:
instr -> LBZ reg . COMMA idx COMMA reg [ SEMI PIPE # ]
instr -> LBZ reg . COMMA idx LPAR reg RPAR [ SEMI PIPE # ]
-- On COMMA shift to state 308

State 308:
instr -> LBZ reg COMMA . idx COMMA reg [ SEMI PIPE # ]
instr -> LBZ reg COMMA . idx LPAR reg RPAR [ SEMI PIPE # ]
-- On NUM shift to state 63
-- On CSTVAR shift to state 64
-- On idx shift to state 309

State 309:
instr -> LBZ reg COMMA idx . COMMA reg [ SEMI PIPE # ]
instr -> LBZ reg COMMA idx . LPAR reg RPAR [ SEMI PIPE # ]
-- On LPAR shift to state 310
-- On COMMA shift to state 313

State 310:
instr -> LBZ reg COMMA idx LPAR . reg RPAR [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 311

State 311:
instr -> LBZ reg COMMA idx LPAR reg . RPAR [ SEMI PIPE # ]
-- On RPAR shift to state 312

State 312:
instr -> LBZ reg COMMA idx LPAR reg RPAR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LBZ reg COMMA idx LPAR reg RPAR
-- On PIPE reduce production instr -> LBZ reg COMMA idx LPAR reg RPAR

State 313:
instr -> LBZ reg COMMA idx COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 314

State 314:
instr -> LBZ reg COMMA idx COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> LBZ reg COMMA idx COMMA reg
-- On PIPE reduce production instr -> LBZ reg COMMA idx COMMA reg

State 315:
instr -> ISYNC . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> ISYNC
-- On PIPE reduce production instr -> ISYNC

State 316:
instr -> EIEIO . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> EIEIO
-- On PIPE reduce production instr -> EIEIO

State 317:
instr -> DIVDOT . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 318

State 318:
instr -> DIVDOT reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 319

State 319:
instr -> DIVDOT reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 320

State 320:
instr -> DIVDOT reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 321

State 321:
instr -> DIVDOT reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 322

State 322:
instr -> DIVDOT reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> DIVDOT reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> DIVDOT reg COMMA reg COMMA reg

State 323:
instr -> DIV . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 324

State 324:
instr -> DIV reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 325

State 325:
instr -> DIV reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 326

State 326:
instr -> DIV reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 327

State 327:
instr -> DIV reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 328

State 328:
instr -> DIV reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> DIV reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> DIV reg COMMA reg COMMA reg

State 329:
instr -> DCBF . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 330

State 330:
instr -> DCBF reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 331

State 331:
instr -> DCBF reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 332

State 332:
instr -> DCBF reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> DCBF reg COMMA reg
-- On PIPE reduce production instr -> DCBF reg COMMA reg

State 333:
instr -> COMMENT . STRING [ SEMI PIPE # ]
-- On STRING shift to state 334

State 334:
instr -> COMMENT STRING . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> COMMENT STRING
-- On PIPE reduce production instr -> COMMENT STRING

State 335:
instr -> CMPWI . reg COMMA k [ SEMI PIPE # ]
instr -> CMPWI . crindex COMMA reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On CRK shift to state 336
-- On ARCH_REG shift to state 3
-- On reg shift to state 337
-- On crindex shift to state 340

State 336:
crindex -> CRK . [ COMMA ]
-- On COMMA reduce production crindex -> CRK

State 337:
instr -> CMPWI reg . COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 338

State 338:
instr -> CMPWI reg COMMA . k [ SEMI PIPE # ]
-- On NUM shift to state 8
-- On CSTVAR shift to state 9
-- On k shift to state 339

State 339:
instr -> CMPWI reg COMMA k . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> CMPWI reg COMMA k
-- On PIPE reduce production instr -> CMPWI reg COMMA k

State 340:
instr -> CMPWI crindex . COMMA reg COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 341

State 341:
instr -> CMPWI crindex COMMA . reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 342

State 342:
instr -> CMPWI crindex COMMA reg . COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 343

State 343:
instr -> CMPWI crindex COMMA reg COMMA . k [ SEMI PIPE # ]
-- On NUM shift to state 8
-- On CSTVAR shift to state 9
-- On k shift to state 344

State 344:
instr -> CMPWI crindex COMMA reg COMMA k . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> CMPWI crindex COMMA reg COMMA k
-- On PIPE reduce production instr -> CMPWI crindex COMMA reg COMMA k

State 345:
instr -> CMPW . crindex COMMA reg COMMA reg [ SEMI PIPE # ]
instr -> CMPW . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On CRK shift to state 336
-- On ARCH_REG shift to state 3
-- On reg shift to state 346
-- On crindex shift to state 349

State 346:
instr -> CMPW reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 347

State 347:
instr -> CMPW reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 348

State 348:
instr -> CMPW reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> CMPW reg COMMA reg
-- On PIPE reduce production instr -> CMPW reg COMMA reg

State 349:
instr -> CMPW crindex . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 350

State 350:
instr -> CMPW crindex COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 351

State 351:
instr -> CMPW crindex COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 352

State 352:
instr -> CMPW crindex COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 353

State 353:
instr -> CMPW crindex COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> CMPW crindex COMMA reg COMMA reg
-- On PIPE reduce production instr -> CMPW crindex COMMA reg COMMA reg

State 354:
instr -> BNL . NAME [ SEMI PIPE # ]
-- On NAME shift to state 355

State 355:
instr -> BNL NAME . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> BNL NAME
-- On PIPE reduce production instr -> BNL NAME

State 356:
instr -> BNG . NAME [ SEMI PIPE # ]
-- On NAME shift to state 357

State 357:
instr -> BNG NAME . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> BNG NAME
-- On PIPE reduce production instr -> BNG NAME

State 358:
instr -> BNE . NAME [ SEMI PIPE # ]
-- On NAME shift to state 359

State 359:
instr -> BNE NAME . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> BNE NAME
-- On PIPE reduce production instr -> BNE NAME

State 360:
instr -> BLT . NAME [ SEMI PIPE # ]
-- On NAME shift to state 361

State 361:
instr -> BLT NAME . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> BLT NAME
-- On PIPE reduce production instr -> BLT NAME

State 362:
instr -> BLR . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> BLR
-- On PIPE reduce production instr -> BLR

State 363:
instr -> BLE . NAME [ SEMI PIPE # ]
-- On NAME shift to state 364

State 364:
instr -> BLE NAME . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> BLE NAME
-- On PIPE reduce production instr -> BLE NAME

State 365:
instr -> BL . NAME [ SEMI PIPE # ]
-- On NAME shift to state 366

State 366:
instr -> BL NAME . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> BL NAME
-- On PIPE reduce production instr -> BL NAME

State 367:
instr -> BGT . NAME [ SEMI PIPE # ]
-- On NAME shift to state 368

State 368:
instr -> BGT NAME . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> BGT NAME
-- On PIPE reduce production instr -> BGT NAME

State 369:
instr -> BGE . NAME [ SEMI PIPE # ]
-- On NAME shift to state 370

State 370:
instr -> BGE NAME . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> BGE NAME
-- On PIPE reduce production instr -> BGE NAME

State 371:
instr -> BEQ . NAME [ SEMI PIPE # ]
-- On NAME shift to state 372

State 372:
instr -> BEQ NAME . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> BEQ NAME
-- On PIPE reduce production instr -> BEQ NAME

State 373:
instr -> B . NAME [ SEMI PIPE # ]
-- On NAME shift to state 374

State 374:
instr -> B NAME . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> B NAME
-- On PIPE reduce production instr -> B NAME

State 375:
instr -> ANDIDOT . reg COMMA reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 376

State 376:
instr -> ANDIDOT reg . COMMA reg COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 377

State 377:
instr -> ANDIDOT reg COMMA . reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 378

State 378:
instr -> ANDIDOT reg COMMA reg . COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 379

State 379:
instr -> ANDIDOT reg COMMA reg COMMA . k [ SEMI PIPE # ]
-- On NUM shift to state 8
-- On CSTVAR shift to state 9
-- On k shift to state 380

State 380:
instr -> ANDIDOT reg COMMA reg COMMA k . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> ANDIDOT reg COMMA reg COMMA k
-- On PIPE reduce production instr -> ANDIDOT reg COMMA reg COMMA k

State 381:
instr -> ANDDOT . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 382

State 382:
instr -> ANDDOT reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 383

State 383:
instr -> ANDDOT reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 384

State 384:
instr -> ANDDOT reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 385

State 385:
instr -> ANDDOT reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 386

State 386:
instr -> ANDDOT reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> ANDDOT reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> ANDDOT reg COMMA reg COMMA reg

State 387:
instr -> AND . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 388

State 388:
instr -> AND reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 389

State 389:
instr -> AND reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 390

State 390:
instr -> AND reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 391

State 391:
instr -> AND reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 392

State 392:
instr -> AND reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> AND reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> AND reg COMMA reg COMMA reg

State 393:
instr -> ADDI . reg COMMA reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 394

State 394:
instr -> ADDI reg . COMMA reg COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 395

State 395:
instr -> ADDI reg COMMA . reg COMMA k [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 396

State 396:
instr -> ADDI reg COMMA reg . COMMA k [ SEMI PIPE # ]
-- On COMMA shift to state 397

State 397:
instr -> ADDI reg COMMA reg COMMA . k [ SEMI PIPE # ]
-- On NUM shift to state 8
-- On CSTVAR shift to state 9
-- On k shift to state 398

State 398:
instr -> ADDI reg COMMA reg COMMA k . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> ADDI reg COMMA reg COMMA k
-- On PIPE reduce production instr -> ADDI reg COMMA reg COMMA k

State 399:
instr -> ADDDOT . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 400

State 400:
instr -> ADDDOT reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 401

State 401:
instr -> ADDDOT reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 402

State 402:
instr -> ADDDOT reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 403

State 403:
instr -> ADDDOT reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 404

State 404:
instr -> ADDDOT reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> ADDDOT reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> ADDDOT reg COMMA reg COMMA reg

State 405:
instr -> ADD . reg COMMA reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 406

State 406:
instr -> ADD reg . COMMA reg COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 407

State 407:
instr -> ADD reg COMMA . reg COMMA reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 408

State 408:
instr -> ADD reg COMMA reg . COMMA reg [ SEMI PIPE # ]
-- On COMMA shift to state 409

State 409:
instr -> ADD reg COMMA reg COMMA . reg [ SEMI PIPE # ]
-- On SYMB_REG shift to state 2
-- On ARCH_REG shift to state 3
-- On reg shift to state 410

State 410:
instr -> ADD reg COMMA reg COMMA reg . [ SEMI PIPE # ]
-- On SEMI reduce production instr -> ADD reg COMMA reg COMMA reg
-- On PIPE reduce production instr -> ADD reg COMMA reg COMMA reg

State 411:
instr_option -> NAME COLON instr_option . [ SEMI PIPE # ]
-- On SEMI reduce production instr_option -> NAME COLON instr_option
-- On PIPE reduce production instr_option -> NAME COLON instr_option

State 412:
instr_option -> instr . [ SEMI PIPE # ]
-- On SEMI reduce production instr_option -> instr
-- On PIPE reduce production instr_option -> instr

State 413:
instr_option_seq' -> instr_option_seq . [ # ]
-- On # accept instr_option_seq

State 414:
instr_option_seq -> instr_option . [ # ]
instr_option_seq -> instr_option . SEMI instr_option_seq [ # ]
-- On SEMI shift to state 415

State 415:
instr_option_seq -> instr_option SEMI . instr_option_seq [ # ]
-- On XORI shift to state 1
-- On XORDOT shift to state 11
-- On XOR shift to state 17
-- On SYNC shift to state 23
-- On SUBI shift to state 24
-- On SUBFDOT shift to state 30
-- On SUBF shift to state 36
-- On SUBDOT shift to state 42
-- On SUB shift to state 48
-- On STWX shift to state 54
-- On STWU shift to state 60
-- On STWCX shift to state 71
-- On STW shift to state 77
-- On STMW shift to state 86
-- On STHX shift to state 93
-- On STH shift to state 99
-- On STDX shift to state 108
-- On STD shift to state 114
-- On STBX shift to state 123
-- On STB shift to state 129
-- On SRAWI shift to state 138
-- On SRAW shift to state 144
-- On SLW shift to state 150
-- On ORI shift to state 156
-- On ORDOT shift to state 162
-- On OR shift to state 168
-- On NORDOT shift to state 174
-- On NOR shift to state 180
-- On NEGDOT shift to state 186
-- On NEG shift to state 190
-- On NAME shift to state 194
-- On MULLI shift to state 202
-- On MULLDOT shift to state 208
-- On MULL shift to state 214
-- On MTLR shift to state 220
-- On MR shift to state 222
-- On MFLR shift to state 226
-- On LWZX shift to state 228
-- On LWZU shift to state 234
-- On LWZ shift to state 243
-- On LWSYNC shift to state 252
-- On LWARX shift to state 253
-- On LMW shift to state 259
-- On LI shift to state 266
-- On LHZX shift to state 270
-- On LHZ shift to state 276
-- On LDX shift to state 285
-- On LD shift to state 291
-- On LBZX shift to state 300
-- On LBZ shift to state 306
-- On ISYNC shift to state 315
-- On EIEIO shift to state 316
-- On DIVDOT shift to state 317
-- On DIV shift to state 323
-- On DCBF shift to state 329
-- On COMMENT shift to state 333
-- On CMPWI shift to state 335
-- On CMPW shift to state 345
-- On BNL shift to state 354
-- On BNG shift to state 356
-- On BNE shift to state 358
-- On BLT shift to state 360
-- On BLR shift to state 362
-- On BLE shift to state 363
-- On BL shift to state 365
-- On BGT shift to state 367
-- On BGE shift to state 369
-- On BEQ shift to state 371
-- On B shift to state 373
-- On ANDIDOT shift to state 375
-- On ANDDOT shift to state 381
-- On AND shift to state 387
-- On ADDI shift to state 393
-- On ADDDOT shift to state 399
-- On ADD shift to state 405
-- On instr_option_seq shift to state 416
-- On instr_option shift to state 414
-- On instr shift to state 412
-- On SEMI reduce production instr_option ->

State 416:
instr_option_seq -> instr_option SEMI instr_option_seq . [ # ]
-- On # reduce production instr_option_seq -> instr_option SEMI instr_option_seq

State 417:
main' -> . main [ # ]
-- On SEMI shift to state 418
-- On semi_opt shift to state 419
-- On main shift to state 434
-- On PROC reduce production semi_opt ->

State 418:
semi_opt -> SEMI . [ PROC ]
-- On PROC reduce production semi_opt -> SEMI

State 419:
main -> semi_opt . proc_list iol_list EOF [ # ]
main -> semi_opt . proc_list EOF [ # ]
-- On PROC shift to state 420
-- On proc_list shift to state 424

State 420:
proc_list -> PROC . SEMI [ XORI XORDOT XOR SYNC SUBI SUBFDOT SUBF SUBDOT SUB STWX STWU STWCX STW STMW STHX STH STDX STD STBX STB SRAWI SRAW SLW SEMI PIPE ORI ORDOT OR NORDOT NOR NEGDOT NEG NAME MULLI MULLDOT MULL MTLR MR MFLR LWZX LWZU LWZ LWSYNC LWARX LMW LI LHZX LHZ LDX LD LBZX LBZ ISYNC EOF EIEIO DIVDOT DIV DCBF COMMENT CMPWI CMPW BNL BNG BNE BLT BLR BLE BL BGT BGE BEQ B ANDIDOT ANDDOT AND ADDI ADDDOT ADD ]
proc_list -> PROC . PIPE proc_list [ XORI XORDOT XOR SYNC SUBI SUBFDOT SUBF SUBDOT SUB STWX STWU STWCX STW STMW STHX STH STDX STD STBX STB SRAWI SRAW SLW SEMI PIPE ORI ORDOT OR NORDOT NOR NEGDOT NEG NAME MULLI MULLDOT MULL MTLR MR MFLR LWZX LWZU LWZ LWSYNC LWARX LMW LI LHZX LHZ LDX LD LBZX LBZ ISYNC EOF EIEIO DIVDOT DIV DCBF COMMENT CMPWI CMPW BNL BNG BNE BLT BLR BLE BL BGT BGE BEQ B ANDIDOT ANDDOT AND ADDI ADDDOT ADD ]
-- On SEMI shift to state 421
-- On PIPE shift to state 422

State 421:
proc_list -> PROC SEMI . [ XORI XORDOT XOR SYNC SUBI SUBFDOT SUBF SUBDOT SUB STWX STWU STWCX STW STMW STHX STH STDX STD STBX STB SRAWI SRAW SLW SEMI PIPE ORI ORDOT OR NORDOT NOR NEGDOT NEG NAME MULLI MULLDOT MULL MTLR MR MFLR LWZX LWZU LWZ LWSYNC LWARX LMW LI LHZX LHZ LDX LD LBZX LBZ ISYNC EOF EIEIO DIVDOT DIV DCBF COMMENT CMPWI CMPW BNL BNG BNE BLT BLR BLE BL BGT BGE BEQ B ANDIDOT ANDDOT AND ADDI ADDDOT ADD ]
-- On XORI reduce production proc_list -> PROC SEMI
-- On XORDOT reduce production proc_list -> PROC SEMI
-- On XOR reduce production proc_list -> PROC SEMI
-- On SYNC reduce production proc_list -> PROC SEMI
-- On SUBI reduce production proc_list -> PROC SEMI
-- On SUBFDOT reduce production proc_list -> PROC SEMI
-- On SUBF reduce production proc_list -> PROC SEMI
-- On SUBDOT reduce production proc_list -> PROC SEMI
-- On SUB reduce production proc_list -> PROC SEMI
-- On STWX reduce production proc_list -> PROC SEMI
-- On STWU reduce production proc_list -> PROC SEMI
-- On STWCX reduce production proc_list -> PROC SEMI
-- On STW reduce production proc_list -> PROC SEMI
-- On STMW reduce production proc_list -> PROC SEMI
-- On STHX reduce production proc_list -> PROC SEMI
-- On STH reduce production proc_list -> PROC SEMI
-- On STDX reduce production proc_list -> PROC SEMI
-- On STD reduce production proc_list -> PROC SEMI
-- On STBX reduce production proc_list -> PROC SEMI
-- On STB reduce production proc_list -> PROC SEMI
-- On SRAWI reduce production proc_list -> PROC SEMI
-- On SRAW reduce production proc_list -> PROC SEMI
-- On SLW reduce production proc_list -> PROC SEMI
-- On SEMI reduce production proc_list -> PROC SEMI
-- On PIPE reduce production proc_list -> PROC SEMI
-- On ORI reduce production proc_list -> PROC SEMI
-- On ORDOT reduce production proc_list -> PROC SEMI
-- On OR reduce production proc_list -> PROC SEMI
-- On NORDOT reduce production proc_list -> PROC SEMI
-- On NOR reduce production proc_list -> PROC SEMI
-- On NEGDOT reduce production proc_list -> PROC SEMI
-- On NEG reduce production proc_list -> PROC SEMI
-- On NAME reduce production proc_list -> PROC SEMI
-- On MULLI reduce production proc_list -> PROC SEMI
-- On MULLDOT reduce production proc_list -> PROC SEMI
-- On MULL reduce production proc_list -> PROC SEMI
-- On MTLR reduce production proc_list -> PROC SEMI
-- On MR reduce production proc_list -> PROC SEMI
-- On MFLR reduce production proc_list -> PROC SEMI
-- On LWZX reduce production proc_list -> PROC SEMI
-- On LWZU reduce production proc_list -> PROC SEMI
-- On LWZ reduce production proc_list -> PROC SEMI
-- On LWSYNC reduce production proc_list -> PROC SEMI
-- On LWARX reduce production proc_list -> PROC SEMI
-- On LMW reduce production proc_list -> PROC SEMI
-- On LI reduce production proc_list -> PROC SEMI
-- On LHZX reduce production proc_list -> PROC SEMI
-- On LHZ reduce production proc_list -> PROC SEMI
-- On LDX reduce production proc_list -> PROC SEMI
-- On LD reduce production proc_list -> PROC SEMI
-- On LBZX reduce production proc_list -> PROC SEMI
-- On LBZ reduce production proc_list -> PROC SEMI
-- On ISYNC reduce production proc_list -> PROC SEMI
-- On EOF reduce production proc_list -> PROC SEMI
-- On EIEIO reduce production proc_list -> PROC SEMI
-- On DIVDOT reduce production proc_list -> PROC SEMI
-- On DIV reduce production proc_list -> PROC SEMI
-- On DCBF reduce production proc_list -> PROC SEMI
-- On COMMENT reduce production proc_list -> PROC SEMI
-- On CMPWI reduce production proc_list -> PROC SEMI
-- On CMPW reduce production proc_list -> PROC SEMI
-- On BNL reduce production proc_list -> PROC SEMI
-- On BNG reduce production proc_list -> PROC SEMI
-- On BNE reduce production proc_list -> PROC SEMI
-- On BLT reduce production proc_list -> PROC SEMI
-- On BLR reduce production proc_list -> PROC SEMI
-- On BLE reduce production proc_list -> PROC SEMI
-- On BL reduce production proc_list -> PROC SEMI
-- On BGT reduce production proc_list -> PROC SEMI
-- On BGE reduce production proc_list -> PROC SEMI
-- On BEQ reduce production proc_list -> PROC SEMI
-- On B reduce production proc_list -> PROC SEMI
-- On ANDIDOT reduce production proc_list -> PROC SEMI
-- On ANDDOT reduce production proc_list -> PROC SEMI
-- On AND reduce production proc_list -> PROC SEMI
-- On ADDI reduce production proc_list -> PROC SEMI
-- On ADDDOT reduce production proc_list -> PROC SEMI
-- On ADD reduce production proc_list -> PROC SEMI

State 422:
proc_list -> PROC PIPE . proc_list [ XORI XORDOT XOR SYNC SUBI SUBFDOT SUBF SUBDOT SUB STWX STWU STWCX STW STMW STHX STH STDX STD STBX STB SRAWI SRAW SLW SEMI PIPE ORI ORDOT OR NORDOT NOR NEGDOT NEG NAME MULLI MULLDOT MULL MTLR MR MFLR LWZX LWZU LWZ LWSYNC LWARX LMW LI LHZX LHZ LDX LD LBZX LBZ ISYNC EOF EIEIO DIVDOT DIV DCBF COMMENT CMPWI CMPW BNL BNG BNE BLT BLR BLE BL BGT BGE BEQ B ANDIDOT ANDDOT AND ADDI ADDDOT ADD ]
-- On PROC shift to state 420
-- On proc_list shift to state 423

State 423:
proc_list -> PROC PIPE proc_list . [ XORI XORDOT XOR SYNC SUBI SUBFDOT SUBF SUBDOT SUB STWX STWU STWCX STW STMW STHX STH STDX STD STBX STB SRAWI SRAW SLW SEMI PIPE ORI ORDOT OR NORDOT NOR NEGDOT NEG NAME MULLI MULLDOT MULL MTLR MR MFLR LWZX LWZU LWZ LWSYNC LWARX LMW LI LHZX LHZ LDX LD LBZX LBZ ISYNC EOF EIEIO DIVDOT DIV DCBF COMMENT CMPWI CMPW BNL BNG BNE BLT BLR BLE BL BGT BGE BEQ B ANDIDOT ANDDOT AND ADDI ADDDOT ADD ]
-- On XORI reduce production proc_list -> PROC PIPE proc_list
-- On XORDOT reduce production proc_list -> PROC PIPE proc_list
-- On XOR reduce production proc_list -> PROC PIPE proc_list
-- On SYNC reduce production proc_list -> PROC PIPE proc_list
-- On SUBI reduce production proc_list -> PROC PIPE proc_list
-- On SUBFDOT reduce production proc_list -> PROC PIPE proc_list
-- On SUBF reduce production proc_list -> PROC PIPE proc_list
-- On SUBDOT reduce production proc_list -> PROC PIPE proc_list
-- On SUB reduce production proc_list -> PROC PIPE proc_list
-- On STWX reduce production proc_list -> PROC PIPE proc_list
-- On STWU reduce production proc_list -> PROC PIPE proc_list
-- On STWCX reduce production proc_list -> PROC PIPE proc_list
-- On STW reduce production proc_list -> PROC PIPE proc_list
-- On STMW reduce production proc_list -> PROC PIPE proc_list
-- On STHX reduce production proc_list -> PROC PIPE proc_list
-- On STH reduce production proc_list -> PROC PIPE proc_list
-- On STDX reduce production proc_list -> PROC PIPE proc_list
-- On STD reduce production proc_list -> PROC PIPE proc_list
-- On STBX reduce production proc_list -> PROC PIPE proc_list
-- On STB reduce production proc_list -> PROC PIPE proc_list
-- On SRAWI reduce production proc_list -> PROC PIPE proc_list
-- On SRAW reduce production proc_list -> PROC PIPE proc_list
-- On SLW reduce production proc_list -> PROC PIPE proc_list
-- On SEMI reduce production proc_list -> PROC PIPE proc_list
-- On PIPE reduce production proc_list -> PROC PIPE proc_list
-- On ORI reduce production proc_list -> PROC PIPE proc_list
-- On ORDOT reduce production proc_list -> PROC PIPE proc_list
-- On OR reduce production proc_list -> PROC PIPE proc_list
-- On NORDOT reduce production proc_list -> PROC PIPE proc_list
-- On NOR reduce production proc_list -> PROC PIPE proc_list
-- On NEGDOT reduce production proc_list -> PROC PIPE proc_list
-- On NEG reduce production proc_list -> PROC PIPE proc_list
-- On NAME reduce production proc_list -> PROC PIPE proc_list
-- On MULLI reduce production proc_list -> PROC PIPE proc_list
-- On MULLDOT reduce production proc_list -> PROC PIPE proc_list
-- On MULL reduce production proc_list -> PROC PIPE proc_list
-- On MTLR reduce production proc_list -> PROC PIPE proc_list
-- On MR reduce production proc_list -> PROC PIPE proc_list
-- On MFLR reduce production proc_list -> PROC PIPE proc_list
-- On LWZX reduce production proc_list -> PROC PIPE proc_list
-- On LWZU reduce production proc_list -> PROC PIPE proc_list
-- On LWZ reduce production proc_list -> PROC PIPE proc_list
-- On LWSYNC reduce production proc_list -> PROC PIPE proc_list
-- On LWARX reduce production proc_list -> PROC PIPE proc_list
-- On LMW reduce production proc_list -> PROC PIPE proc_list
-- On LI reduce production proc_list -> PROC PIPE proc_list
-- On LHZX reduce production proc_list -> PROC PIPE proc_list
-- On LHZ reduce production proc_list -> PROC PIPE proc_list
-- On LDX reduce production proc_list -> PROC PIPE proc_list
-- On LD reduce production proc_list -> PROC PIPE proc_list
-- On LBZX reduce production proc_list -> PROC PIPE proc_list
-- On LBZ reduce production proc_list -> PROC PIPE proc_list
-- On ISYNC reduce production proc_list -> PROC PIPE proc_list
-- On EOF reduce production proc_list -> PROC PIPE proc_list
-- On EIEIO reduce production proc_list -> PROC PIPE proc_list
-- On DIVDOT reduce production proc_list -> PROC PIPE proc_list
-- On DIV reduce production proc_list -> PROC PIPE proc_list
-- On DCBF reduce production proc_list -> PROC PIPE proc_list
-- On COMMENT reduce production proc_list -> PROC PIPE proc_list
-- On CMPWI reduce production proc_list -> PROC PIPE proc_list
-- On CMPW reduce production proc_list -> PROC PIPE proc_list
-- On BNL reduce production proc_list -> PROC PIPE proc_list
-- On BNG reduce production proc_list -> PROC PIPE proc_list
-- On BNE reduce production proc_list -> PROC PIPE proc_list
-- On BLT reduce production proc_list -> PROC PIPE proc_list
-- On BLR reduce production proc_list -> PROC PIPE proc_list
-- On BLE reduce production proc_list -> PROC PIPE proc_list
-- On BL reduce production proc_list -> PROC PIPE proc_list
-- On BGT reduce production proc_list -> PROC PIPE proc_list
-- On BGE reduce production proc_list -> PROC PIPE proc_list
-- On BEQ reduce production proc_list -> PROC PIPE proc_list
-- On B reduce production proc_list -> PROC PIPE proc_list
-- On ANDIDOT reduce production proc_list -> PROC PIPE proc_list
-- On ANDDOT reduce production proc_list -> PROC PIPE proc_list
-- On AND reduce production proc_list -> PROC PIPE proc_list
-- On ADDI reduce production proc_list -> PROC PIPE proc_list
-- On ADDDOT reduce production proc_list -> PROC PIPE proc_list
-- On ADD reduce production proc_list -> PROC PIPE proc_list

State 424:
main -> semi_opt proc_list . iol_list EOF [ # ]
main -> semi_opt proc_list . EOF [ # ]
-- On XORI shift to state 1
-- On XORDOT shift to state 11
-- On XOR shift to state 17
-- On SYNC shift to state 23
-- On SUBI shift to state 24
-- On SUBFDOT shift to state 30
-- On SUBF shift to state 36
-- On SUBDOT shift to state 42
-- On SUB shift to state 48
-- On STWX shift to state 54
-- On STWU shift to state 60
-- On STWCX shift to state 71
-- On STW shift to state 77
-- On STMW shift to state 86
-- On STHX shift to state 93
-- On STH shift to state 99
-- On STDX shift to state 108
-- On STD shift to state 114
-- On STBX shift to state 123
-- On STB shift to state 129
-- On SRAWI shift to state 138
-- On SRAW shift to state 144
-- On SLW shift to state 150
-- On ORI shift to state 156
-- On ORDOT shift to state 162
-- On OR shift to state 168
-- On NORDOT shift to state 174
-- On NOR shift to state 180
-- On NEGDOT shift to state 186
-- On NEG shift to state 190
-- On NAME shift to state 194
-- On MULLI shift to state 202
-- On MULLDOT shift to state 208
-- On MULL shift to state 214
-- On MTLR shift to state 220
-- On MR shift to state 222
-- On MFLR shift to state 226
-- On LWZX shift to state 228
-- On LWZU shift to state 234
-- On LWZ shift to state 243
-- On LWSYNC shift to state 252
-- On LWARX shift to state 253
-- On LMW shift to state 259
-- On LI shift to state 266
-- On LHZX shift to state 270
-- On LHZ shift to state 276
-- On LDX shift to state 285
-- On LD shift to state 291
-- On LBZX shift to state 300
-- On LBZ shift to state 306
-- On ISYNC shift to state 315
-- On EOF shift to state 425
-- On EIEIO shift to state 316
-- On DIVDOT shift to state 317
-- On DIV shift to state 323
-- On DCBF shift to state 329
-- On COMMENT shift to state 333
-- On CMPWI shift to state 335
-- On CMPW shift to state 345
-- On BNL shift to state 354
-- On BNG shift to state 356
-- On BNE shift to state 358
-- On BLT shift to state 360
-- On BLR shift to state 362
-- On BLE shift to state 363
-- On BL shift to state 365
-- On BGT shift to state 367
-- On BGE shift to state 369
-- On BEQ shift to state 371
-- On B shift to state 373
-- On ANDIDOT shift to state 375
-- On ANDDOT shift to state 381
-- On AND shift to state 387
-- On ADDI shift to state 393
-- On ADDDOT shift to state 399
-- On ADD shift to state 405
-- On iol_list shift to state 426
-- On instr_option_list shift to state 428
-- On instr_option shift to state 431
-- On instr shift to state 412
-- On SEMI reduce production instr_option ->
-- On PIPE reduce production instr_option ->

State 425:
main -> semi_opt proc_list EOF . [ # ]
-- On # reduce production main -> semi_opt proc_list EOF

State 426:
main -> semi_opt proc_list iol_list . EOF [ # ]
-- On EOF shift to state 427

State 427:
main -> semi_opt proc_list iol_list EOF . [ # ]
-- On # reduce production main -> semi_opt proc_list iol_list EOF

State 428:
iol_list -> instr_option_list . SEMI [ EOF ]
iol_list -> instr_option_list . SEMI iol_list [ EOF ]
-- On SEMI shift to state 429

State 429:
iol_list -> instr_option_list SEMI . [ EOF ]
iol_list -> instr_option_list SEMI . iol_list [ EOF ]
-- On XORI shift to state 1
-- On XORDOT shift to state 11
-- On XOR shift to state 17
-- On SYNC shift to state 23
-- On SUBI shift to state 24
-- On SUBFDOT shift to state 30
-- On SUBF shift to state 36
-- On SUBDOT shift to state 42
-- On SUB shift to state 48
-- On STWX shift to state 54
-- On STWU shift to state 60
-- On STWCX shift to state 71
-- On STW shift to state 77
-- On STMW shift to state 86
-- On STHX shift to state 93
-- On STH shift to state 99
-- On STDX shift to state 108
-- On STD shift to state 114
-- On STBX shift to state 123
-- On STB shift to state 129
-- On SRAWI shift to state 138
-- On SRAW shift to state 144
-- On SLW shift to state 150
-- On ORI shift to state 156
-- On ORDOT shift to state 162
-- On OR shift to state 168
-- On NORDOT shift to state 174
-- On NOR shift to state 180
-- On NEGDOT shift to state 186
-- On NEG shift to state 190
-- On NAME shift to state 194
-- On MULLI shift to state 202
-- On MULLDOT shift to state 208
-- On MULL shift to state 214
-- On MTLR shift to state 220
-- On MR shift to state 222
-- On MFLR shift to state 226
-- On LWZX shift to state 228
-- On LWZU shift to state 234
-- On LWZ shift to state 243
-- On LWSYNC shift to state 252
-- On LWARX shift to state 253
-- On LMW shift to state 259
-- On LI shift to state 266
-- On LHZX shift to state 270
-- On LHZ shift to state 276
-- On LDX shift to state 285
-- On LD shift to state 291
-- On LBZX shift to state 300
-- On LBZ shift to state 306
-- On ISYNC shift to state 315
-- On EIEIO shift to state 316
-- On DIVDOT shift to state 317
-- On DIV shift to state 323
-- On DCBF shift to state 329
-- On COMMENT shift to state 333
-- On CMPWI shift to state 335
-- On CMPW shift to state 345
-- On BNL shift to state 354
-- On BNG shift to state 356
-- On BNE shift to state 358
-- On BLT shift to state 360
-- On BLR shift to state 362
-- On BLE shift to state 363
-- On BL shift to state 365
-- On BGT shift to state 367
-- On BGE shift to state 369
-- On BEQ shift to state 371
-- On B shift to state 373
-- On ANDIDOT shift to state 375
-- On ANDDOT shift to state 381
-- On AND shift to state 387
-- On ADDI shift to state 393
-- On ADDDOT shift to state 399
-- On ADD shift to state 405
-- On iol_list shift to state 430
-- On instr_option_list shift to state 428
-- On instr_option shift to state 431
-- On instr shift to state 412
-- On SEMI reduce production instr_option ->
-- On PIPE reduce production instr_option ->
-- On EOF reduce production iol_list -> instr_option_list SEMI

State 430:
iol_list -> instr_option_list SEMI iol_list . [ EOF ]
-- On EOF reduce production iol_list -> instr_option_list SEMI iol_list

State 431:
instr_option_list -> instr_option . [ SEMI ]
instr_option_list -> instr_option . PIPE instr_option_list [ SEMI ]
-- On PIPE shift to state 432
-- On SEMI reduce production instr_option_list -> instr_option

State 432:
instr_option_list -> instr_option PIPE . instr_option_list [ SEMI ]
-- On XORI shift to state 1
-- On XORDOT shift to state 11
-- On XOR shift to state 17
-- On SYNC shift to state 23
-- On SUBI shift to state 24
-- On SUBFDOT shift to state 30
-- On SUBF shift to state 36
-- On SUBDOT shift to state 42
-- On SUB shift to state 48
-- On STWX shift to state 54
-- On STWU shift to state 60
-- On STWCX shift to state 71
-- On STW shift to state 77
-- On STMW shift to state 86
-- On STHX shift to state 93
-- On STH shift to state 99
-- On STDX shift to state 108
-- On STD shift to state 114
-- On STBX shift to state 123
-- On STB shift to state 129
-- On SRAWI shift to state 138
-- On SRAW shift to state 144
-- On SLW shift to state 150
-- On ORI shift to state 156
-- On ORDOT shift to state 162
-- On OR shift to state 168
-- On NORDOT shift to state 174
-- On NOR shift to state 180
-- On NEGDOT shift to state 186
-- On NEG shift to state 190
-- On NAME shift to state 194
-- On MULLI shift to state 202
-- On MULLDOT shift to state 208
-- On MULL shift to state 214
-- On MTLR shift to state 220
-- On MR shift to state 222
-- On MFLR shift to state 226
-- On LWZX shift to state 228
-- On LWZU shift to state 234
-- On LWZ shift to state 243
-- On LWSYNC shift to state 252
-- On LWARX shift to state 253
-- On LMW shift to state 259
-- On LI shift to state 266
-- On LHZX shift to state 270
-- On LHZ shift to state 276
-- On LDX shift to state 285
-- On LD shift to state 291
-- On LBZX shift to state 300
-- On LBZ shift to state 306
-- On ISYNC shift to state 315
-- On EIEIO shift to state 316
-- On DIVDOT shift to state 317
-- On DIV shift to state 323
-- On DCBF shift to state 329
-- On COMMENT shift to state 333
-- On CMPWI shift to state 335
-- On CMPW shift to state 345
-- On BNL shift to state 354
-- On BNG shift to state 356
-- On BNE shift to state 358
-- On BLT shift to state 360
-- On BLR shift to state 362
-- On BLE shift to state 363
-- On BL shift to state 365
-- On BGT shift to state 367
-- On BGE shift to state 369
-- On BEQ shift to state 371
-- On B shift to state 373
-- On ANDIDOT shift to state 375
-- On ANDDOT shift to state 381
-- On AND shift to state 387
-- On ADDI shift to state 393
-- On ADDDOT shift to state 399
-- On ADD shift to state 405
-- On instr_option_list shift to state 433
-- On instr_option shift to state 431
-- On instr shift to state 412
-- On SEMI reduce production instr_option ->
-- On PIPE reduce production instr_option ->

State 433:
instr_option_list -> instr_option PIPE instr_option_list . [ SEMI ]
-- On SEMI reduce production instr_option_list -> instr_option PIPE instr_option_list

State 434:
main' -> main . [ # ]
-- On # accept main

