%start main
%token COMMA
%token EOF
%token INT
%token LBRACE
%token RBRACE
%token SEMI
%type <unit> main
%%

loption_separated_nonempty_list_COMMA_weird_separated_list_COMMA___:
  
    {    ( [] )} [@name none_separated_nonempty_list_COMMA_weird_separated_list_COMMA__]
| x = separated_nonempty_list_COMMA_weird_separated_list_COMMA__
    {    ( x )} [@name some_separated_nonempty_list_COMMA_weird_separated_list_COMMA__]

loption_separated_nonempty_list_SEMI_bizarre_nonseparated_list_SEMI___:
  
    {    ( [] )} [@name none_separated_nonempty_list_SEMI_bizarre_nonseparated_list_SEMI__]
| x = separated_nonempty_list_SEMI_bizarre_nonseparated_list_SEMI__
    {    ( x )} [@name some_separated_nonempty_list_SEMI_bizarre_nonseparated_list_SEMI__]

loption_separated_nonempty_list_SEMI_expr_separated_list_SEMI___:
  
    {    ( [] )} [@name none_separated_nonempty_list_SEMI_expr_separated_list_SEMI__]
| x = separated_nonempty_list_SEMI_expr_separated_list_SEMI__
    {    ( x )} [@name some_separated_nonempty_list_SEMI_expr_separated_list_SEMI__]

loption_separated_nonempty_list_SEMI_weird_separated_list_COMMA___:
  
    {    ( [] )} [@name none_separated_nonempty_list_SEMI_weird_separated_list_COMMA__]
| x = separated_nonempty_list_SEMI_weird_separated_list_COMMA__
    {    ( x )} [@name some_separated_nonempty_list_SEMI_weird_separated_list_COMMA__]

list_bizarre_nonseparated_list_SEMI__:
  
    {    ( [] )} [@name nil_bizarre_nonseparated_list_SEMI_]
| x = bizarre_nonseparated_list_SEMI_ xs = list_bizarre_nonseparated_list_SEMI__
    {    ( x :: xs )} [@name cons_bizarre_nonseparated_list_SEMI_]

separated_nonempty_list_COMMA_weird_separated_list_COMMA__:
  x = weird_separated_list_COMMA_
    {    ( [ x ] )} [@name one_COMMA_weird_separated_list_COMMA_]
| x = weird_separated_list_COMMA_ _2 = COMMA xs = separated_nonempty_list_COMMA_weird_separated_list_COMMA__
    {    ( x :: xs )} [@name more_COMMA_weird_separated_list_COMMA_]

separated_nonempty_list_SEMI_bizarre_nonseparated_list_SEMI__:
  x = bizarre_nonseparated_list_SEMI_
    {    ( [ x ] )} [@name one_SEMI_bizarre_nonseparated_list_SEMI_]
| x = bizarre_nonseparated_list_SEMI_ _2 = SEMI xs = separated_nonempty_list_SEMI_bizarre_nonseparated_list_SEMI__
    {    ( x :: xs )} [@name more_SEMI_bizarre_nonseparated_list_SEMI_]

separated_nonempty_list_SEMI_expr_separated_list_SEMI__:
  x = expr_separated_list_SEMI_
    {    ( [ x ] )} [@name one_SEMI_expr_separated_list_SEMI_]
| x = expr_separated_list_SEMI_ _2 = SEMI xs = separated_nonempty_list_SEMI_expr_separated_list_SEMI__
    {    ( x :: xs )} [@name more_SEMI_expr_separated_list_SEMI_]

separated_nonempty_list_SEMI_weird_separated_list_COMMA__:
  x = weird_separated_list_COMMA_
    {    ( [ x ] )} [@name one_SEMI_weird_separated_list_COMMA_]
| x = weird_separated_list_COMMA_ _2 = SEMI xs = separated_nonempty_list_SEMI_weird_separated_list_COMMA__
    {    ( x :: xs )} [@name more_SEMI_weird_separated_list_COMMA_]

main:
  _1 = expr_separated_list_SEMI_ _2 = weird_separated_list_SEMI_ _3 = bizarre_separated_list_SEMI_ _4 = EOF
    {    ()}

expr_separated_list_SEMI_:
  _1 = INT
    {    ()}
| _1 = LBRACE xs = loption_separated_nonempty_list_SEMI_expr_separated_list_SEMI___ _3 = RBRACE
    {let _2 =     ( xs ) in
    ()}

weird_separated_list_COMMA_:
  _1 = INT
    {    ()}
| _1 = LBRACE xs = loption_separated_nonempty_list_COMMA_weird_separated_list_COMMA___ _3 = RBRACE
    {let _2 =     ( xs ) in
    ()}

weird_separated_list_SEMI_:
  _1 = INT
    {    ()}
| _1 = LBRACE xs = loption_separated_nonempty_list_SEMI_weird_separated_list_COMMA___ _3 = RBRACE
    {let _2 =     ( xs ) in
    ()}

bizarre_nonseparated_list_SEMI_:
  _1 = INT
    {    ()}
| _1 = LBRACE _2 = nonseparated_list_SEMI_bizarre_nonseparated_list_SEMI__ _3 = RBRACE
    {    ()}

bizarre_separated_list_SEMI_:
  _1 = INT
    {    ()}
| _1 = LBRACE xs = loption_separated_nonempty_list_SEMI_bizarre_nonseparated_list_SEMI___ _3 = RBRACE
    {let _2 =     ( xs ) in
    ()}

nonseparated_list_SEMI_bizarre_nonseparated_list_SEMI__:
  _1 = list_bizarre_nonseparated_list_SEMI__
    {    ()}

%%
