Grammar has 2 nonterminal symbols, among which 1 start symbols.
Grammar has 1 terminal symbols.
Grammar has 2 productions.
nullable(c) = false
nullable(a) = false
first(c) = T
first(a) = T
minimal(c) = (* 1 *) T
minimal(a) = (* 2 *) T T
maximal(c) = 1
maximal(a) = 2
follow(c) = T #
follow(a) = #
Built an LR(0) automaton with 5 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 6 states.
4 out of 6 states have a default reduction.
The action table is 12 entries; 2 non-zero; 8 compressed.
The action table occupies roughly 104 bytes.
The goto table is 18 entries; 3 non-zero; 9 compressed.
The goto table occupies roughly 104 bytes.
The error table occupies roughly 40 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
