State 0:
a' -> . a [ # ]
-- On T shift to state 1
-- On d shift to state 2
-- On a shift to state 9

State 1:
d -> T . [ T ]
-- On T reduce production d -> T

State 2:
a -> d . T T T d T T [ # ]
-- On T shift to state 3

State 3:
a -> d T . T T d T T [ # ]
-- On T shift to state 4

State 4:
a -> d T T . T d T T [ # ]
-- On T shift to state 5

State 5:
a -> d T T T . d T T [ # ]
-- On T shift to state 1
-- On d shift to state 6

State 6:
a -> d T T T d . T T [ # ]
-- On T shift to state 7

State 7:
a -> d T T T d T . T [ # ]
-- On T shift to state 8

State 8:
a -> d T T T d T T . [ # ]
-- On # reduce production a -> d T T T d T T

State 9:
a' -> a . [ # ]
-- On # accept a

