Grammar has 5 nonterminal symbols, among which 1 start symbols.
Grammar has 18 terminal symbols.
Grammar has 19 productions.
nullable(str) = false
nullable(proc) = false
nullable(main) = false
nullable(ident) = false
nullable(capa) = false
first(str) = IDENT
first(proc) = ZERO STRING OUT OPEN NEW LPOINT LPAREN IN IDENT DOLLAR BANG
first(main) = ZERO STRING OUT OPEN NEW LPOINT LPAREN IN IDENT DOLLAR BANG
first(ident) = IDENT
first(capa) = STRING OUT OPEN IN IDENT
minimal(str) = (* 1 *) IDENT
minimal(proc) = (* 1 *) ZERO
minimal(main) = (* 2 *) ZERO SEMISEMI
minimal(ident) = (* 1 *) IDENT
minimal(capa) = (* 1 *) IDENT
maximal(str) = 1
maximal(proc) = infinity
maximal(main) = infinity
maximal(ident) = 1
maximal(capa) = infinity
follow(str) = RPAREN DOT
follow(proc) = SEMISEMI RPAREN RBRACKET PAR
follow(main) = #
follow(ident) = RPOINT LBRACKET DOT
follow(capa) = RPOINT DOT
Built an LR(0) automaton with 49 states.
The grammar is not SLR(1) -- 8 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 49 states.
7 shift/reduce conflicts were silently solved.
File "jocaml-ambients.mly", line 22, characters 0-9:
Warning: the precedence level assigned to DOLLAR is never useful.
18 out of 49 states have a default reduction.
The action table is 931 entries; 141 non-zero; 98 compressed.
The action table occupies roughly 200 bytes.
The goto table is 294 entries; 38 non-zero; 90 compressed.
The goto table occupies roughly 192 bytes.
The error table occupies roughly 152 bytes.
The default_reduction table occupies roughly 88 bytes.
The lhs table occupies roughly 48 bytes.
The trace table occupies roughly 8 bytes.
