Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 7 terminal symbols.
Grammar has 5 productions.
nullable(statement) = false
nullable(main) = false
nullable(expr) = false
first(statement) = TReturn TIf
first(main) = TReturn TIf
first(expr) = TIdent
minimal(statement) = (* 1 *) TReturn
minimal(main) = (* 2 *) TReturn EOF
minimal(expr) = (* 1 *) TIdent
maximal(statement) = infinity
maximal(main) = infinity
maximal(expr) = 1
follow(statement) = TElse EOF
follow(main) = #
follow(expr) = TCPar
Built an LR(0) automaton with 13 states.
The grammar is not SLR(1) -- 1 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 13 states.
One shift/reduce conflict was silently solved.
5 out of 13 states have a default reduction.
The action table is 104 entries; 12 non-zero; 21 compressed.
The action table occupies roughly 104 bytes.
The goto table is 52 entries; 5 non-zero; 18 compressed.
The goto table occupies roughly 104 bytes.
The error table occupies roughly 48 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
