Grammar has 1 nonterminal symbols, among which 1 start symbols.
Grammar has 1 terminal symbols.
Grammar has 1 productions.
nullable(s) = false
first(s) = X
minimal(s) = (* 1 *) X
maximal(s) = 1
follow(s) = #
Built an LR(0) automaton with 3 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 3 states.
2 out of 3 states have a default reduction.
The action table is 6 entries; 1 non-zero; 4 compressed.
The action table occupies roughly 104 bytes.
The goto table is 6 entries; 1 non-zero; 4 compressed.
The goto table occupies roughly 104 bytes.
The error table occupies roughly 40 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
