State 0:
## Known stack suffix:
##
## LR(1) items:
line' -> . line [ # ]
## Transitions:
-- On REQUIRE shift to state 1
-- On NAME shift to state 3
-- On LEFTSQU shift to state 5
-- On KW_THM shift to state 50
-- On KW_INJ shift to state 70
-- On KW_DEF shift to state 75
-- On INFER shift to state 95
-- On ID shift to state 107
-- On EVAL shift to state 114
-- On EOF shift to state 120
-- On CHECKNOT shift to state 121
-- On CHECK shift to state 129
-- On ASSERTNOT shift to state 137
-- On ASSERT shift to state 145
-- On rule shift to state 153
-- On nonempty_list(rule) shift to state 155
-- On line shift to state 157
## Reductions:

State 1:
## Known stack suffix:
## REQUIRE
## LR(1) items:
line -> REQUIRE . DOT [ # ]
## Transitions:
-- On DOT shift to state 2
## Reductions:

State 2:
## Known stack suffix:
## REQUIRE DOT
## LR(1) items:
line -> REQUIRE DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> REQUIRE DOT

State 3:
## Known stack suffix:
## NAME
## LR(1) items:
line -> NAME . DOT [ # ]
## Transitions:
-- On DOT shift to state 4
## Reductions:

State 4:
## Known stack suffix:
## NAME DOT
## LR(1) items:
line -> NAME DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> NAME DOT

State 5:
## Known stack suffix:
## LEFTSQU
## LR(1) items:
rule -> LEFTSQU . context RIGHTSQU term LONGARROW term [ LEFTSQU DOT ]
## Transitions:
-- On ID shift to state 6
-- On separated_nonempty_list(COMMA,context_item) shift to state 40
-- On loption(separated_nonempty_list(COMMA,context_item)) shift to state 41
-- On context_item shift to state 42
-- On context shift to state 45
## Reductions:
-- On RIGHTSQU
--   reduce production loption(separated_nonempty_list(COMMA,context_item)) ->

State 6:
## Known stack suffix:
## ID
## LR(1) items:
context_item -> ID . option(__anonymous_0) [ RIGHTSQU COMMA ]
## Transitions:
-- On COLON shift to state 7
-- On option(__anonymous_0) shift to state 39
## Reductions:
-- On RIGHTSQU COMMA
--   reduce production option(__anonymous_0) ->

State 7:
## Known stack suffix:
## COLON
## LR(1) items:
option(__anonymous_0) -> COLON . term [ RIGHTSQU COMMA ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 38
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 8:
## Known stack suffix:
## UNDERSCORE
## LR(1) items:
sterm -> UNDERSCORE . [ UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production sterm -> UNDERSCORE

State 9:
## Known stack suffix:
## TYPE
## LR(1) items:
sterm -> TYPE . [ UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production sterm -> TYPE

State 10:
## Known stack suffix:
## QID
## LR(1) items:
sterm -> QID . [ UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production sterm -> QID

State 11:
## Known stack suffix:
## LEFTPAR
## LR(1) items:
sterm -> LEFTPAR . term RIGHTPAR [ UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID DOT DEF COMMA ARROW ]
term -> LEFTPAR . ID COLON aterm RIGHTPAR ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 12
-- On term shift to state 17
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 12:
## Known stack suffix:
## LEFTPAR ID
## LR(1) items:
sterm -> ID . [ UNDERSCORE TYPE RIGHTPAR QID LEFTPAR ID ARROW ]
term -> ID . COLON aterm ARROW term [ RIGHTPAR ARROW ]
term -> LEFTPAR ID . COLON aterm RIGHTPAR ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> ID . FATARROW term [ RIGHTPAR ARROW ]
term -> ID . COLON aterm FATARROW term [ RIGHTPAR ARROW ]
## Transitions:
-- On FATARROW shift to state 13
-- On COLON shift to state 33
## Reductions:
-- On UNDERSCORE TYPE RIGHTPAR QID LEFTPAR ID ARROW
--   reduce production sterm -> ID

State 13:
## Known stack suffix:
## ID FATARROW
## LR(1) items:
term -> ID FATARROW . term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 32
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 14:
## Known stack suffix:
## ID
## LR(1) items:
sterm -> ID . [ UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID DOT DEF COMMA ARROW ]
term -> ID . COLON aterm ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> ID . FATARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> ID . COLON aterm FATARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On FATARROW shift to state 13
-- On COLON shift to state 15
## Reductions:
-- On UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID DOT DEF COMMA ARROW
--   reduce production sterm -> ID

State 15:
## Known stack suffix:
## ID COLON
## LR(1) items:
term -> ID COLON . aterm ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> ID COLON . aterm FATARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 16
-- On ID shift to state 22
-- On sterm shift to state 21
-- On aterm shift to state 27
## Reductions:

State 16:
## Known stack suffix:
## LEFTPAR
## LR(1) items:
sterm -> LEFTPAR . term RIGHTPAR [ UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 17
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 17:
## Known stack suffix:
## LEFTPAR term
## LR(1) items:
sterm -> LEFTPAR term . RIGHTPAR [ UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
term -> term . ARROW term [ RIGHTPAR ARROW ]
## Transitions:
-- On RIGHTPAR shift to state 18
-- On ARROW shift to state 19
## Reductions:

State 18:
## Known stack suffix:
## LEFTPAR term RIGHTPAR
## LR(1) items:
sterm -> LEFTPAR term RIGHTPAR . [ UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production sterm -> LEFTPAR term RIGHTPAR

State 19:
## Known stack suffix:
## term ARROW
## LR(1) items:
term -> term ARROW . term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 20
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 20:
## Known stack suffix:
## term ARROW term
## LR(1) items:
term -> term . ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> term ARROW term . [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On ARROW shift to state 19
## Reductions:
-- On RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA
--   reduce production term -> term ARROW term

State 21:
## Known stack suffix:
## sterm
## LR(1) items:
aterm -> sterm . list(sterm) [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 16
-- On ID shift to state 22
-- On sterm shift to state 23
-- On list(sterm) shift to state 25
## Reductions:
-- On RIGHTSQU RIGHTPAR LONGARROW LEFTSQU FATARROW EQUAL DOT DEF COMMA COLON ARROW
--   reduce production list(sterm) ->

State 22:
## Known stack suffix:
## ID
## LR(1) items:
sterm -> ID . [ UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production sterm -> ID

State 23:
## Known stack suffix:
## sterm
## LR(1) items:
list(sterm) -> sterm . list(sterm) [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 16
-- On ID shift to state 22
-- On sterm shift to state 23
-- On list(sterm) shift to state 24
## Reductions:
-- On RIGHTSQU RIGHTPAR LONGARROW LEFTSQU FATARROW EQUAL DOT DEF COMMA COLON ARROW
--   reduce production list(sterm) ->

State 24:
## Known stack suffix:
## sterm list(sterm)
## LR(1) items:
list(sterm) -> sterm list(sterm) . [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production list(sterm) -> sterm list(sterm)

State 25:
## Known stack suffix:
## sterm list(sterm)
## LR(1) items:
aterm -> sterm list(sterm) . [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU FATARROW EQUAL DOT DEF COMMA COLON ARROW ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production aterm -> sterm list(sterm)

State 26:
## Known stack suffix:
## aterm
## LR(1) items:
term -> aterm . [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production term -> aterm

State 27:
## Known stack suffix:
## ID COLON aterm
## LR(1) items:
term -> ID COLON aterm . ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> ID COLON aterm . FATARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On FATARROW shift to state 28
-- On ARROW shift to state 30
## Reductions:

State 28:
## Known stack suffix:
## ID COLON aterm FATARROW
## LR(1) items:
term -> ID COLON aterm FATARROW . term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 29
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 29:
## Known stack suffix:
## ID COLON aterm FATARROW term
## LR(1) items:
term -> term . ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> ID COLON aterm FATARROW term . [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On ARROW shift to state 19
## Reductions:
-- On RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA
--   reduce production term -> ID COLON aterm FATARROW term

State 30:
## Known stack suffix:
## ID COLON aterm ARROW
## LR(1) items:
term -> ID COLON aterm ARROW . term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 31
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 31:
## Known stack suffix:
## ID COLON aterm ARROW term
## LR(1) items:
term -> ID COLON aterm ARROW term . [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> term . ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On ARROW shift to state 19
## Reductions:
-- On RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA
--   reduce production term -> ID COLON aterm ARROW term

State 32:
## Known stack suffix:
## ID FATARROW term
## LR(1) items:
term -> term . ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> ID FATARROW term . [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On ARROW shift to state 19
## Reductions:
-- On RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA
--   reduce production term -> ID FATARROW term

State 33:
## Known stack suffix:
## LEFTPAR ID COLON
## LR(1) items:
term -> ID COLON . aterm ARROW term [ RIGHTPAR ARROW ]
term -> LEFTPAR ID COLON . aterm RIGHTPAR ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> ID COLON . aterm FATARROW term [ RIGHTPAR ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 16
-- On ID shift to state 22
-- On sterm shift to state 21
-- On aterm shift to state 34
## Reductions:

State 34:
## Known stack suffix:
## LEFTPAR ID COLON aterm
## LR(1) items:
term -> ID COLON aterm . ARROW term [ RIGHTPAR ARROW ]
term -> LEFTPAR ID COLON aterm . RIGHTPAR ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> ID COLON aterm . FATARROW term [ RIGHTPAR ARROW ]
## Transitions:
-- On RIGHTPAR shift to state 35
-- On FATARROW shift to state 28
-- On ARROW shift to state 30
## Reductions:

State 35:
## Known stack suffix:
## LEFTPAR ID COLON aterm RIGHTPAR
## LR(1) items:
term -> LEFTPAR ID COLON aterm RIGHTPAR . ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On ARROW shift to state 36
## Reductions:

State 36:
## Known stack suffix:
## LEFTPAR ID COLON aterm RIGHTPAR ARROW
## LR(1) items:
term -> LEFTPAR ID COLON aterm RIGHTPAR ARROW . term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 37
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 37:
## Known stack suffix:
## LEFTPAR ID COLON aterm RIGHTPAR ARROW term
## LR(1) items:
term -> LEFTPAR ID COLON aterm RIGHTPAR ARROW term . [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
term -> term . ARROW term [ RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW ]
## Transitions:
-- On ARROW shift to state 19
## Reductions:
-- On RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA
--   reduce production term -> LEFTPAR ID COLON aterm RIGHTPAR ARROW term

State 38:
## Known stack suffix:
## COLON term
## LR(1) items:
option(__anonymous_0) -> COLON term . [ RIGHTSQU COMMA ]
term -> term . ARROW term [ RIGHTSQU COMMA ARROW ]
## Transitions:
-- On ARROW shift to state 19
## Reductions:
-- On RIGHTSQU COMMA
--   reduce production option(__anonymous_0) -> COLON term

State 39:
## Known stack suffix:
## ID option(__anonymous_0)
## LR(1) items:
context_item -> ID option(__anonymous_0) . [ RIGHTSQU COMMA ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production context_item -> ID option(__anonymous_0)

State 40:
## Known stack suffix:
## separated_nonempty_list(COMMA,context_item)
## LR(1) items:
loption(separated_nonempty_list(COMMA,context_item)) -> separated_nonempty_list(COMMA,context_item) . [ RIGHTSQU ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production loption(separated_nonempty_list(COMMA,context_item)) -> separated_nonempty_list(COMMA,context_item)

State 41:
## Known stack suffix:
## loption(separated_nonempty_list(COMMA,context_item))
## LR(1) items:
context -> loption(separated_nonempty_list(COMMA,context_item)) . [ RIGHTSQU ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production context -> loption(separated_nonempty_list(COMMA,context_item))

State 42:
## Known stack suffix:
## context_item
## LR(1) items:
separated_nonempty_list(COMMA,context_item) -> context_item . [ RIGHTSQU ]
separated_nonempty_list(COMMA,context_item) -> context_item . COMMA separated_nonempty_list(COMMA,context_item) [ RIGHTSQU ]
## Transitions:
-- On COMMA shift to state 43
## Reductions:
-- On RIGHTSQU
--   reduce production separated_nonempty_list(COMMA,context_item) -> context_item

State 43:
## Known stack suffix:
## context_item COMMA
## LR(1) items:
separated_nonempty_list(COMMA,context_item) -> context_item COMMA . separated_nonempty_list(COMMA,context_item) [ RIGHTSQU ]
## Transitions:
-- On ID shift to state 6
-- On separated_nonempty_list(COMMA,context_item) shift to state 44
-- On context_item shift to state 42
## Reductions:

State 44:
## Known stack suffix:
## context_item COMMA separated_nonempty_list(COMMA,context_item)
## LR(1) items:
separated_nonempty_list(COMMA,context_item) -> context_item COMMA separated_nonempty_list(COMMA,context_item) . [ RIGHTSQU ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production separated_nonempty_list(COMMA,context_item) -> context_item COMMA separated_nonempty_list(COMMA,context_item)

State 45:
## Known stack suffix:
## LEFTSQU context
## LR(1) items:
rule -> LEFTSQU context . RIGHTSQU term LONGARROW term [ LEFTSQU DOT ]
## Transitions:
-- On RIGHTSQU shift to state 46
## Reductions:

State 46:
## Known stack suffix:
## LEFTSQU context RIGHTSQU
## LR(1) items:
rule -> LEFTSQU context RIGHTSQU . term LONGARROW term [ LEFTSQU DOT ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 47
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 47:
## Known stack suffix:
## LEFTSQU context RIGHTSQU term
## LR(1) items:
rule -> LEFTSQU context RIGHTSQU term . LONGARROW term [ LEFTSQU DOT ]
term -> term . ARROW term [ LONGARROW ARROW ]
## Transitions:
-- On LONGARROW shift to state 48
-- On ARROW shift to state 19
## Reductions:

State 48:
## Known stack suffix:
## LEFTSQU context RIGHTSQU term LONGARROW
## LR(1) items:
rule -> LEFTSQU context RIGHTSQU term LONGARROW . term [ LEFTSQU DOT ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 49
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 49:
## Known stack suffix:
## LEFTSQU context RIGHTSQU term LONGARROW term
## LR(1) items:
rule -> LEFTSQU context RIGHTSQU term LONGARROW term . [ LEFTSQU DOT ]
term -> term . ARROW term [ LEFTSQU DOT ARROW ]
## Transitions:
-- On ARROW shift to state 19
## Reductions:
-- On LEFTSQU DOT
--   reduce production rule -> LEFTSQU context RIGHTSQU term LONGARROW term

State 50:
## Known stack suffix:
## KW_THM
## LR(1) items:
line -> KW_THM . ID COLON term DEF term DOT [ # ]
line -> KW_THM . ID nonempty_list(param) COLON term DEF term DOT [ # ]
## Transitions:
-- On ID shift to state 51
## Reductions:

State 51:
## Known stack suffix:
## KW_THM ID
## LR(1) items:
line -> KW_THM ID . COLON term DEF term DOT [ # ]
line -> KW_THM ID . nonempty_list(param) COLON term DEF term DOT [ # ]
## Transitions:
-- On LEFTPAR shift to state 52
-- On COLON shift to state 57
-- On param shift to state 62
-- On nonempty_list(param) shift to state 64
## Reductions:

State 52:
## Known stack suffix:
## LEFTPAR
## LR(1) items:
param -> LEFTPAR . ID COLON term RIGHTPAR [ LEFTPAR DEF COLON ]
## Transitions:
-- On ID shift to state 53
## Reductions:

State 53:
## Known stack suffix:
## LEFTPAR ID
## LR(1) items:
param -> LEFTPAR ID . COLON term RIGHTPAR [ LEFTPAR DEF COLON ]
## Transitions:
-- On COLON shift to state 54
## Reductions:

State 54:
## Known stack suffix:
## LEFTPAR ID COLON
## LR(1) items:
param -> LEFTPAR ID COLON . term RIGHTPAR [ LEFTPAR DEF COLON ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 55
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 55:
## Known stack suffix:
## LEFTPAR ID COLON term
## LR(1) items:
param -> LEFTPAR ID COLON term . RIGHTPAR [ LEFTPAR DEF COLON ]
term -> term . ARROW term [ RIGHTPAR ARROW ]
## Transitions:
-- On RIGHTPAR shift to state 56
-- On ARROW shift to state 19
## Reductions:

State 56:
## Known stack suffix:
## LEFTPAR ID COLON term RIGHTPAR
## LR(1) items:
param -> LEFTPAR ID COLON term RIGHTPAR . [ LEFTPAR DEF COLON ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production param -> LEFTPAR ID COLON term RIGHTPAR

State 57:
## Known stack suffix:
## KW_THM ID COLON
## LR(1) items:
line -> KW_THM ID COLON . term DEF term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 58
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 58:
## Known stack suffix:
## KW_THM ID COLON term
## LR(1) items:
line -> KW_THM ID COLON term . DEF term DOT [ # ]
term -> term . ARROW term [ DEF ARROW ]
## Transitions:
-- On DEF shift to state 59
-- On ARROW shift to state 19
## Reductions:

State 59:
## Known stack suffix:
## KW_THM ID COLON term DEF
## LR(1) items:
line -> KW_THM ID COLON term DEF . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 60
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 60:
## Known stack suffix:
## KW_THM ID COLON term DEF term
## LR(1) items:
line -> KW_THM ID COLON term DEF term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 61
-- On ARROW shift to state 19
## Reductions:

State 61:
## Known stack suffix:
## KW_THM ID COLON term DEF term DOT
## LR(1) items:
line -> KW_THM ID COLON term DEF term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> KW_THM ID COLON term DEF term DOT

State 62:
## Known stack suffix:
## param
## LR(1) items:
nonempty_list(param) -> param . [ DEF COLON ]
nonempty_list(param) -> param . nonempty_list(param) [ DEF COLON ]
## Transitions:
-- On LEFTPAR shift to state 52
-- On param shift to state 62
-- On nonempty_list(param) shift to state 63
## Reductions:
-- On DEF COLON
--   reduce production nonempty_list(param) -> param

State 63:
## Known stack suffix:
## param nonempty_list(param)
## LR(1) items:
nonempty_list(param) -> param nonempty_list(param) . [ DEF COLON ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production nonempty_list(param) -> param nonempty_list(param)

State 64:
## Known stack suffix:
## KW_THM ID nonempty_list(param)
## LR(1) items:
line -> KW_THM ID nonempty_list(param) . COLON term DEF term DOT [ # ]
## Transitions:
-- On COLON shift to state 65
## Reductions:

State 65:
## Known stack suffix:
## KW_THM ID nonempty_list(param) COLON
## LR(1) items:
line -> KW_THM ID nonempty_list(param) COLON . term DEF term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 66
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 66:
## Known stack suffix:
## KW_THM ID nonempty_list(param) COLON term
## LR(1) items:
line -> KW_THM ID nonempty_list(param) COLON term . DEF term DOT [ # ]
term -> term . ARROW term [ DEF ARROW ]
## Transitions:
-- On DEF shift to state 67
-- On ARROW shift to state 19
## Reductions:

State 67:
## Known stack suffix:
## KW_THM ID nonempty_list(param) COLON term DEF
## LR(1) items:
line -> KW_THM ID nonempty_list(param) COLON term DEF . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 68
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 68:
## Known stack suffix:
## KW_THM ID nonempty_list(param) COLON term DEF term
## LR(1) items:
line -> KW_THM ID nonempty_list(param) COLON term DEF term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 69
-- On ARROW shift to state 19
## Reductions:

State 69:
## Known stack suffix:
## KW_THM ID nonempty_list(param) COLON term DEF term DOT
## LR(1) items:
line -> KW_THM ID nonempty_list(param) COLON term DEF term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> KW_THM ID nonempty_list(param) COLON term DEF term DOT

State 70:
## Known stack suffix:
## KW_INJ
## LR(1) items:
line -> KW_INJ . ID COLON term DOT [ # ]
## Transitions:
-- On ID shift to state 71
## Reductions:

State 71:
## Known stack suffix:
## KW_INJ ID
## LR(1) items:
line -> KW_INJ ID . COLON term DOT [ # ]
## Transitions:
-- On COLON shift to state 72
## Reductions:

State 72:
## Known stack suffix:
## KW_INJ ID COLON
## LR(1) items:
line -> KW_INJ ID COLON . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 73
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 73:
## Known stack suffix:
## KW_INJ ID COLON term
## LR(1) items:
line -> KW_INJ ID COLON term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 74
-- On ARROW shift to state 19
## Reductions:

State 74:
## Known stack suffix:
## KW_INJ ID COLON term DOT
## LR(1) items:
line -> KW_INJ ID COLON term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> KW_INJ ID COLON term DOT

State 75:
## Known stack suffix:
## KW_DEF
## LR(1) items:
line -> KW_DEF . ID COLON term DOT [ # ]
line -> KW_DEF . ID COLON term DEF term DOT [ # ]
line -> KW_DEF . ID DEF term DOT [ # ]
line -> KW_DEF . ID nonempty_list(param) COLON term DEF term DOT [ # ]
line -> KW_DEF . ID nonempty_list(param) DEF term DOT [ # ]
## Transitions:
-- On ID shift to state 76
## Reductions:

State 76:
## Known stack suffix:
## KW_DEF ID
## LR(1) items:
line -> KW_DEF ID . COLON term DOT [ # ]
line -> KW_DEF ID . COLON term DEF term DOT [ # ]
line -> KW_DEF ID . DEF term DOT [ # ]
line -> KW_DEF ID . nonempty_list(param) COLON term DEF term DOT [ # ]
line -> KW_DEF ID . nonempty_list(param) DEF term DOT [ # ]
## Transitions:
-- On LEFTPAR shift to state 52
-- On DEF shift to state 77
-- On COLON shift to state 80
-- On param shift to state 62
-- On nonempty_list(param) shift to state 86
## Reductions:

State 77:
## Known stack suffix:
## KW_DEF ID DEF
## LR(1) items:
line -> KW_DEF ID DEF . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 78
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 78:
## Known stack suffix:
## KW_DEF ID DEF term
## LR(1) items:
line -> KW_DEF ID DEF term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 79
-- On ARROW shift to state 19
## Reductions:

State 79:
## Known stack suffix:
## KW_DEF ID DEF term DOT
## LR(1) items:
line -> KW_DEF ID DEF term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> KW_DEF ID DEF term DOT

State 80:
## Known stack suffix:
## KW_DEF ID COLON
## LR(1) items:
line -> KW_DEF ID COLON . term DOT [ # ]
line -> KW_DEF ID COLON . term DEF term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 81
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 81:
## Known stack suffix:
## KW_DEF ID COLON term
## LR(1) items:
line -> KW_DEF ID COLON term . DOT [ # ]
line -> KW_DEF ID COLON term . DEF term DOT [ # ]
term -> term . ARROW term [ DOT DEF ARROW ]
## Transitions:
-- On DOT shift to state 82
-- On DEF shift to state 83
-- On ARROW shift to state 19
## Reductions:

State 82:
## Known stack suffix:
## KW_DEF ID COLON term DOT
## LR(1) items:
line -> KW_DEF ID COLON term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> KW_DEF ID COLON term DOT

State 83:
## Known stack suffix:
## KW_DEF ID COLON term DEF
## LR(1) items:
line -> KW_DEF ID COLON term DEF . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 84
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 84:
## Known stack suffix:
## KW_DEF ID COLON term DEF term
## LR(1) items:
line -> KW_DEF ID COLON term DEF term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 85
-- On ARROW shift to state 19
## Reductions:

State 85:
## Known stack suffix:
## KW_DEF ID COLON term DEF term DOT
## LR(1) items:
line -> KW_DEF ID COLON term DEF term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> KW_DEF ID COLON term DEF term DOT

State 86:
## Known stack suffix:
## KW_DEF ID nonempty_list(param)
## LR(1) items:
line -> KW_DEF ID nonempty_list(param) . COLON term DEF term DOT [ # ]
line -> KW_DEF ID nonempty_list(param) . DEF term DOT [ # ]
## Transitions:
-- On DEF shift to state 87
-- On COLON shift to state 90
## Reductions:

State 87:
## Known stack suffix:
## KW_DEF ID nonempty_list(param) DEF
## LR(1) items:
line -> KW_DEF ID nonempty_list(param) DEF . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 88
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 88:
## Known stack suffix:
## KW_DEF ID nonempty_list(param) DEF term
## LR(1) items:
line -> KW_DEF ID nonempty_list(param) DEF term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 89
-- On ARROW shift to state 19
## Reductions:

State 89:
## Known stack suffix:
## KW_DEF ID nonempty_list(param) DEF term DOT
## LR(1) items:
line -> KW_DEF ID nonempty_list(param) DEF term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> KW_DEF ID nonempty_list(param) DEF term DOT

State 90:
## Known stack suffix:
## KW_DEF ID nonempty_list(param) COLON
## LR(1) items:
line -> KW_DEF ID nonempty_list(param) COLON . term DEF term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 91
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 91:
## Known stack suffix:
## KW_DEF ID nonempty_list(param) COLON term
## LR(1) items:
line -> KW_DEF ID nonempty_list(param) COLON term . DEF term DOT [ # ]
term -> term . ARROW term [ DEF ARROW ]
## Transitions:
-- On DEF shift to state 92
-- On ARROW shift to state 19
## Reductions:

State 92:
## Known stack suffix:
## KW_DEF ID nonempty_list(param) COLON term DEF
## LR(1) items:
line -> KW_DEF ID nonempty_list(param) COLON term DEF . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 93
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 93:
## Known stack suffix:
## KW_DEF ID nonempty_list(param) COLON term DEF term
## LR(1) items:
line -> KW_DEF ID nonempty_list(param) COLON term DEF term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 94
-- On ARROW shift to state 19
## Reductions:

State 94:
## Known stack suffix:
## KW_DEF ID nonempty_list(param) COLON term DEF term DOT
## LR(1) items:
line -> KW_DEF ID nonempty_list(param) COLON term DEF term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> KW_DEF ID nonempty_list(param) COLON term DEF term DOT

State 95:
## Known stack suffix:
## INFER
## LR(1) items:
line -> INFER . term DOT [ # ]
line -> INFER . eval_config term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTSQU shift to state 96
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 102
-- On sterm shift to state 21
-- On eval_config shift to state 104
-- On aterm shift to state 26
## Reductions:

State 96:
## Known stack suffix:
## LEFTSQU
## LR(1) items:
eval_config -> LEFTSQU . ID RIGHTSQU [ UNDERSCORE TYPE QID LEFTPAR ID ]
eval_config -> LEFTSQU . ID COMMA ID RIGHTSQU [ UNDERSCORE TYPE QID LEFTPAR ID ]
## Transitions:
-- On ID shift to state 97
## Reductions:

State 97:
## Known stack suffix:
## LEFTSQU ID
## LR(1) items:
eval_config -> LEFTSQU ID . RIGHTSQU [ UNDERSCORE TYPE QID LEFTPAR ID ]
eval_config -> LEFTSQU ID . COMMA ID RIGHTSQU [ UNDERSCORE TYPE QID LEFTPAR ID ]
## Transitions:
-- On RIGHTSQU shift to state 98
-- On COMMA shift to state 99
## Reductions:

State 98:
## Known stack suffix:
## LEFTSQU ID RIGHTSQU
## LR(1) items:
eval_config -> LEFTSQU ID RIGHTSQU . [ UNDERSCORE TYPE QID LEFTPAR ID ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production eval_config -> LEFTSQU ID RIGHTSQU

State 99:
## Known stack suffix:
## LEFTSQU ID COMMA
## LR(1) items:
eval_config -> LEFTSQU ID COMMA . ID RIGHTSQU [ UNDERSCORE TYPE QID LEFTPAR ID ]
## Transitions:
-- On ID shift to state 100
## Reductions:

State 100:
## Known stack suffix:
## LEFTSQU ID COMMA ID
## LR(1) items:
eval_config -> LEFTSQU ID COMMA ID . RIGHTSQU [ UNDERSCORE TYPE QID LEFTPAR ID ]
## Transitions:
-- On RIGHTSQU shift to state 101
## Reductions:

State 101:
## Known stack suffix:
## LEFTSQU ID COMMA ID RIGHTSQU
## LR(1) items:
eval_config -> LEFTSQU ID COMMA ID RIGHTSQU . [ UNDERSCORE TYPE QID LEFTPAR ID ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production eval_config -> LEFTSQU ID COMMA ID RIGHTSQU

State 102:
## Known stack suffix:
## INFER term
## LR(1) items:
line -> INFER term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 103
-- On ARROW shift to state 19
## Reductions:

State 103:
## Known stack suffix:
## INFER term DOT
## LR(1) items:
line -> INFER term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> INFER term DOT

State 104:
## Known stack suffix:
## INFER eval_config
## LR(1) items:
line -> INFER eval_config . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 105
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 105:
## Known stack suffix:
## INFER eval_config term
## LR(1) items:
line -> INFER eval_config term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 106
-- On ARROW shift to state 19
## Reductions:

State 106:
## Known stack suffix:
## INFER eval_config term DOT
## LR(1) items:
line -> INFER eval_config term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> INFER eval_config term DOT

State 107:
## Known stack suffix:
## ID
## LR(1) items:
line -> ID . list(param) COLON term DOT [ # ]
## Transitions:
-- On LEFTPAR shift to state 52
-- On param shift to state 108
-- On list(param) shift to state 110
## Reductions:
-- On COLON
--   reduce production list(param) ->

State 108:
## Known stack suffix:
## param
## LR(1) items:
list(param) -> param . list(param) [ COLON ]
## Transitions:
-- On LEFTPAR shift to state 52
-- On param shift to state 108
-- On list(param) shift to state 109
## Reductions:
-- On COLON
--   reduce production list(param) ->

State 109:
## Known stack suffix:
## param list(param)
## LR(1) items:
list(param) -> param list(param) . [ COLON ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production list(param) -> param list(param)

State 110:
## Known stack suffix:
## ID list(param)
## LR(1) items:
line -> ID list(param) . COLON term DOT [ # ]
## Transitions:
-- On COLON shift to state 111
## Reductions:

State 111:
## Known stack suffix:
## ID list(param) COLON
## LR(1) items:
line -> ID list(param) COLON . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 112
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 112:
## Known stack suffix:
## ID list(param) COLON term
## LR(1) items:
line -> ID list(param) COLON term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 113
-- On ARROW shift to state 19
## Reductions:

State 113:
## Known stack suffix:
## ID list(param) COLON term DOT
## LR(1) items:
line -> ID list(param) COLON term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> ID list(param) COLON term DOT

State 114:
## Known stack suffix:
## EVAL
## LR(1) items:
line -> EVAL . term DOT [ # ]
line -> EVAL . eval_config term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTSQU shift to state 96
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 115
-- On sterm shift to state 21
-- On eval_config shift to state 117
-- On aterm shift to state 26
## Reductions:

State 115:
## Known stack suffix:
## EVAL term
## LR(1) items:
line -> EVAL term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 116
-- On ARROW shift to state 19
## Reductions:

State 116:
## Known stack suffix:
## EVAL term DOT
## LR(1) items:
line -> EVAL term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> EVAL term DOT

State 117:
## Known stack suffix:
## EVAL eval_config
## LR(1) items:
line -> EVAL eval_config . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 118
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 118:
## Known stack suffix:
## EVAL eval_config term
## LR(1) items:
line -> EVAL eval_config term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 119
-- On ARROW shift to state 19
## Reductions:

State 119:
## Known stack suffix:
## EVAL eval_config term DOT
## LR(1) items:
line -> EVAL eval_config term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> EVAL eval_config term DOT

State 120:
## Known stack suffix:
## EOF
## LR(1) items:
line -> EOF . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> EOF

State 121:
## Known stack suffix:
## CHECKNOT
## LR(1) items:
line -> CHECKNOT . aterm COLON term DOT [ # ]
line -> CHECKNOT . aterm EQUAL term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 16
-- On ID shift to state 22
-- On sterm shift to state 21
-- On aterm shift to state 122
## Reductions:

State 122:
## Known stack suffix:
## CHECKNOT aterm
## LR(1) items:
line -> CHECKNOT aterm . COLON term DOT [ # ]
line -> CHECKNOT aterm . EQUAL term DOT [ # ]
## Transitions:
-- On EQUAL shift to state 123
-- On COLON shift to state 126
## Reductions:

State 123:
## Known stack suffix:
## CHECKNOT aterm EQUAL
## LR(1) items:
line -> CHECKNOT aterm EQUAL . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 124
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 124:
## Known stack suffix:
## CHECKNOT aterm EQUAL term
## LR(1) items:
line -> CHECKNOT aterm EQUAL term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 125
-- On ARROW shift to state 19
## Reductions:

State 125:
## Known stack suffix:
## CHECKNOT aterm EQUAL term DOT
## LR(1) items:
line -> CHECKNOT aterm EQUAL term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> CHECKNOT aterm EQUAL term DOT

State 126:
## Known stack suffix:
## CHECKNOT aterm COLON
## LR(1) items:
line -> CHECKNOT aterm COLON . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 127
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 127:
## Known stack suffix:
## CHECKNOT aterm COLON term
## LR(1) items:
line -> CHECKNOT aterm COLON term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 128
-- On ARROW shift to state 19
## Reductions:

State 128:
## Known stack suffix:
## CHECKNOT aterm COLON term DOT
## LR(1) items:
line -> CHECKNOT aterm COLON term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> CHECKNOT aterm COLON term DOT

State 129:
## Known stack suffix:
## CHECK
## LR(1) items:
line -> CHECK . aterm COLON term DOT [ # ]
line -> CHECK . aterm EQUAL term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 16
-- On ID shift to state 22
-- On sterm shift to state 21
-- On aterm shift to state 130
## Reductions:

State 130:
## Known stack suffix:
## CHECK aterm
## LR(1) items:
line -> CHECK aterm . COLON term DOT [ # ]
line -> CHECK aterm . EQUAL term DOT [ # ]
## Transitions:
-- On EQUAL shift to state 131
-- On COLON shift to state 134
## Reductions:

State 131:
## Known stack suffix:
## CHECK aterm EQUAL
## LR(1) items:
line -> CHECK aterm EQUAL . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 132
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 132:
## Known stack suffix:
## CHECK aterm EQUAL term
## LR(1) items:
line -> CHECK aterm EQUAL term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 133
-- On ARROW shift to state 19
## Reductions:

State 133:
## Known stack suffix:
## CHECK aterm EQUAL term DOT
## LR(1) items:
line -> CHECK aterm EQUAL term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> CHECK aterm EQUAL term DOT

State 134:
## Known stack suffix:
## CHECK aterm COLON
## LR(1) items:
line -> CHECK aterm COLON . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 135
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 135:
## Known stack suffix:
## CHECK aterm COLON term
## LR(1) items:
line -> CHECK aterm COLON term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 136
-- On ARROW shift to state 19
## Reductions:

State 136:
## Known stack suffix:
## CHECK aterm COLON term DOT
## LR(1) items:
line -> CHECK aterm COLON term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> CHECK aterm COLON term DOT

State 137:
## Known stack suffix:
## ASSERTNOT
## LR(1) items:
line -> ASSERTNOT . aterm COLON term DOT [ # ]
line -> ASSERTNOT . aterm EQUAL term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 16
-- On ID shift to state 22
-- On sterm shift to state 21
-- On aterm shift to state 138
## Reductions:

State 138:
## Known stack suffix:
## ASSERTNOT aterm
## LR(1) items:
line -> ASSERTNOT aterm . COLON term DOT [ # ]
line -> ASSERTNOT aterm . EQUAL term DOT [ # ]
## Transitions:
-- On EQUAL shift to state 139
-- On COLON shift to state 142
## Reductions:

State 139:
## Known stack suffix:
## ASSERTNOT aterm EQUAL
## LR(1) items:
line -> ASSERTNOT aterm EQUAL . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 140
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 140:
## Known stack suffix:
## ASSERTNOT aterm EQUAL term
## LR(1) items:
line -> ASSERTNOT aterm EQUAL term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 141
-- On ARROW shift to state 19
## Reductions:

State 141:
## Known stack suffix:
## ASSERTNOT aterm EQUAL term DOT
## LR(1) items:
line -> ASSERTNOT aterm EQUAL term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> ASSERTNOT aterm EQUAL term DOT

State 142:
## Known stack suffix:
## ASSERTNOT aterm COLON
## LR(1) items:
line -> ASSERTNOT aterm COLON . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 143
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 143:
## Known stack suffix:
## ASSERTNOT aterm COLON term
## LR(1) items:
line -> ASSERTNOT aterm COLON term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 144
-- On ARROW shift to state 19
## Reductions:

State 144:
## Known stack suffix:
## ASSERTNOT aterm COLON term DOT
## LR(1) items:
line -> ASSERTNOT aterm COLON term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> ASSERTNOT aterm COLON term DOT

State 145:
## Known stack suffix:
## ASSERT
## LR(1) items:
line -> ASSERT . aterm COLON term DOT [ # ]
line -> ASSERT . aterm EQUAL term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 16
-- On ID shift to state 22
-- On sterm shift to state 21
-- On aterm shift to state 146
## Reductions:

State 146:
## Known stack suffix:
## ASSERT aterm
## LR(1) items:
line -> ASSERT aterm . COLON term DOT [ # ]
line -> ASSERT aterm . EQUAL term DOT [ # ]
## Transitions:
-- On EQUAL shift to state 147
-- On COLON shift to state 150
## Reductions:

State 147:
## Known stack suffix:
## ASSERT aterm EQUAL
## LR(1) items:
line -> ASSERT aterm EQUAL . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 148
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 148:
## Known stack suffix:
## ASSERT aterm EQUAL term
## LR(1) items:
line -> ASSERT aterm EQUAL term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 149
-- On ARROW shift to state 19
## Reductions:

State 149:
## Known stack suffix:
## ASSERT aterm EQUAL term DOT
## LR(1) items:
line -> ASSERT aterm EQUAL term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> ASSERT aterm EQUAL term DOT

State 150:
## Known stack suffix:
## ASSERT aterm COLON
## LR(1) items:
line -> ASSERT aterm COLON . term DOT [ # ]
## Transitions:
-- On UNDERSCORE shift to state 8
-- On TYPE shift to state 9
-- On QID shift to state 10
-- On LEFTPAR shift to state 11
-- On ID shift to state 14
-- On term shift to state 151
-- On sterm shift to state 21
-- On aterm shift to state 26
## Reductions:

State 151:
## Known stack suffix:
## ASSERT aterm COLON term
## LR(1) items:
line -> ASSERT aterm COLON term . DOT [ # ]
term -> term . ARROW term [ DOT ARROW ]
## Transitions:
-- On DOT shift to state 152
-- On ARROW shift to state 19
## Reductions:

State 152:
## Known stack suffix:
## ASSERT aterm COLON term DOT
## LR(1) items:
line -> ASSERT aterm COLON term DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> ASSERT aterm COLON term DOT

State 153:
## Known stack suffix:
## rule
## LR(1) items:
nonempty_list(rule) -> rule . [ DOT ]
nonempty_list(rule) -> rule . nonempty_list(rule) [ DOT ]
## Transitions:
-- On LEFTSQU shift to state 5
-- On rule shift to state 153
-- On nonempty_list(rule) shift to state 154
## Reductions:
-- On DOT
--   reduce production nonempty_list(rule) -> rule

State 154:
## Known stack suffix:
## rule nonempty_list(rule)
## LR(1) items:
nonempty_list(rule) -> rule nonempty_list(rule) . [ DOT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production nonempty_list(rule) -> rule nonempty_list(rule)

State 155:
## Known stack suffix:
## nonempty_list(rule)
## LR(1) items:
line -> nonempty_list(rule) . DOT [ # ]
## Transitions:
-- On DOT shift to state 156
## Reductions:

State 156:
## Known stack suffix:
## nonempty_list(rule) DOT
## LR(1) items:
line -> nonempty_list(rule) DOT . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production line -> nonempty_list(rule) DOT

State 157:
## Known stack suffix:
## line
## LR(1) items:
line' -> line . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, accept line

