File "leap_IGraphParser.mly", line 54, characters 7-10:
Warning: the token EOF is unused.
Grammar has 41 nonterminal symbols, among which 3 start symbols.
Grammar has 28 terminal symbols.
Grammar has 84 productions.
nullable(tactics) = true
nullable(tactic_case_list) = true
nullable(tactic_case) = false
nullable(support_tactic_list) = false
nullable(support_tactic) = false
nullable(support_split_tactic_list) = false
nullable(support_split_tactic) = false
nullable(smp_strategy) = true
nullable(seq_cases) = true
nullable(seq_case_list) = false
nullable(seq_case) = false
nullable(rule_list) = false
nullable(rule) = false
nullable(pvd_support) = false
nullable(premise) = true
nullable(maybe_empty_tag_list) = true
nullable(maybe_empty_axiom_tag_list) = true
nullable(inv_list) = false
nullable(inv_group) = false
nullable(inv) = false
nullable(ident_list) = false
nullable(graph) = true
nullable(formula_tactic_list) = true
nullable(formula_tactic) = false
nullable(formula_split_tactic_list) = false
nullable(formula_split_tactic) = false
nullable(fact_list) = true
nullable(fact) = false
nullable(condition_list) = false
nullable(condition) = false
nullable(cases) = true
nullable(case_list) = false
nullable(case) = false
nullable(axioms) = true
nullable(axiom_rule_list) = false
nullable(axiom_rule) = false
nullable(axiom_list) = false
nullable(axiom_kind) = true
nullable(axiom_cases) = true
nullable(axiom_case_list) = false
nullable(axiom_case) = false
first(tactics) = OPEN_BRACE
first(tactic_case_list) = SEMICOLON OPEN_BRACE NUMBER
first(tactic_case) = SEMICOLON OPEN_BRACE NUMBER
first(support_tactic_list) = IDENT BAR
first(support_tactic) = IDENT
first(support_split_tactic_list) = IDENT BAR
first(support_split_tactic) = IDENT
first(smp_strategy) = SMP_UNION SMP_PRUNING SMP_DNF
first(seq_cases) = OPEN_BRACK
first(seq_case_list) = NUMBER
first(seq_case) = NUMBER
first(rule_list) = SEQ_ARROW IDENT CONC_ARROW
first(rule) = SEQ_ARROW IDENT CONC_ARROW
first(pvd_support) = TACTICS
first(premise) = SELF_PREMISE OTHERS_PREMISE
first(maybe_empty_tag_list) = IDENT
first(maybe_empty_axiom_tag_list) = IDENT
first(inv_list) = IDENT
first(inv_group) = IDENT
first(inv) = IDENT
first(ident_list) = IDENT
first(graph) = SEQ_ARROW IDENT CONC_ARROW
first(formula_tactic_list) = IDENT
first(formula_tactic) = IDENT
first(formula_split_tactic_list) = IDENT BAR
first(formula_split_tactic) = IDENT
first(fact_list) = NUMBER IDENT
first(fact) = NUMBER IDENT
first(condition_list) = COND_INITIATION COND_FAIRNESS COND_CONSECUTION COND_ACCEPTANCE
first(condition) = COND_INITIATION COND_FAIRNESS COND_CONSECUTION COND_ACCEPTANCE
first(cases) = OPEN_BRACK
first(case_list) = NUMBER
first(case) = NUMBER
first(axioms) = IDENT
first(axiom_rule_list) = IDENT
first(axiom_rule) = IDENT
first(axiom_list) = IDENT
first(axiom_kind) = OPEN_PAREN
first(axiom_cases) = OPEN_BRACK
first(axiom_case_list) = NUMBER
first(axiom_case) = NUMBER
minimal(tactics) = (* 0 *)
minimal(tactic_case_list) = (* 0 *)
minimal(tactic_case) = (* 1 *) SEMICOLON
minimal(support_tactic_list) = (* 1 *) BAR
minimal(support_tactic) = (* 1 *) IDENT
minimal(support_split_tactic_list) = (* 1 *) BAR
minimal(support_split_tactic) = (* 1 *) IDENT
minimal(smp_strategy) = (* 0 *)
minimal(seq_cases) = (* 0 *)
minimal(seq_case_list) = (* 2 *) NUMBER COLON
minimal(seq_case) = (* 2 *) NUMBER COLON
minimal(rule_list) = (* 2 *) CONC_ARROW IDENT
minimal(rule) = (* 2 *) CONC_ARROW IDENT
minimal(pvd_support) = (* 4 *) TACTICS COLON FACTS COLON
minimal(premise) = (* 0 *)
minimal(maybe_empty_tag_list) = (* 0 *)
minimal(maybe_empty_axiom_tag_list) = (* 0 *)
minimal(inv_list) = (* 1 *) IDENT
minimal(inv_group) = (* 5 *) IDENT DOUBLECOLON OPEN_BRACE IDENT CLOSE_BRACE
minimal(inv) = (* 1 *) IDENT
minimal(ident_list) = (* 1 *) IDENT
minimal(graph) = (* 0 *)
minimal(formula_tactic_list) = (* 0 *)
minimal(formula_tactic) = (* 1 *) IDENT
minimal(formula_split_tactic_list) = (* 1 *) BAR
minimal(formula_split_tactic) = (* 1 *) IDENT
minimal(fact_list) = (* 0 *)
minimal(fact) = (* 2 *) IDENT SEMICOLON
minimal(condition_list) = (* 1 *) COND_INITIATION
minimal(condition) = (* 1 *) COND_INITIATION
minimal(cases) = (* 0 *)
minimal(case_list) = (* 2 *) NUMBER COLON
minimal(case) = (* 2 *) NUMBER COLON
minimal(axioms) = (* 0 *)
minimal(axiom_rule_list) = (* 1 *) IDENT
minimal(axiom_rule) = (* 1 *) IDENT
minimal(axiom_list) = (* 1 *) IDENT
minimal(axiom_kind) = (* 0 *)
minimal(axiom_cases) = (* 0 *)
minimal(axiom_case_list) = (* 2 *) NUMBER COLON
minimal(axiom_case) = (* 2 *) NUMBER COLON
maximal(tactics) = infinity
maximal(tactic_case_list) = infinity
maximal(tactic_case) = infinity
maximal(support_tactic_list) = infinity
maximal(support_tactic) = 1
maximal(support_split_tactic_list) = infinity
maximal(support_split_tactic) = 1
maximal(smp_strategy) = 2
maximal(seq_cases) = infinity
maximal(seq_case_list) = infinity
maximal(seq_case) = infinity
maximal(rule_list) = infinity
maximal(rule) = infinity
maximal(pvd_support) = infinity
maximal(premise) = 2
maximal(maybe_empty_tag_list) = infinity
maximal(maybe_empty_axiom_tag_list) = infinity
maximal(inv_list) = infinity
maximal(inv_group) = infinity
maximal(inv) = 3
maximal(ident_list) = infinity
maximal(graph) = infinity
maximal(formula_tactic_list) = infinity
maximal(formula_tactic) = 1
maximal(formula_split_tactic_list) = infinity
maximal(formula_split_tactic) = 1
maximal(fact_list) = infinity
maximal(fact) = infinity
maximal(condition_list) = infinity
maximal(condition) = 1
maximal(cases) = infinity
maximal(case_list) = infinity
maximal(case) = infinity
maximal(axioms) = infinity
maximal(axiom_rule_list) = infinity
maximal(axiom_rule) = infinity
maximal(axiom_list) = infinity
maximal(axiom_kind) = 3
maximal(axiom_cases) = infinity
maximal(axiom_case_list) = infinity
maximal(axiom_case) = infinity
follow(tactics) = SEQ_ARROW SEMICOLON IDENT CONC_ARROW CLOSE_BRACK #
follow(tactic_case_list) = FACTS
follow(tactic_case) = SEMICOLON OPEN_BRACE NUMBER FACTS
follow(support_tactic_list) = IDENT BAR
follow(support_tactic) = IDENT BAR
follow(support_split_tactic_list) = IDENT BAR
follow(support_split_tactic) = IDENT BAR
follow(smp_strategy) = IDENT BAR
follow(seq_cases) = SEQ_ARROW OPEN_BRACE IDENT CONC_ARROW #
follow(seq_case_list) = CLOSE_BRACK
follow(seq_case) = SEMICOLON CLOSE_BRACK
follow(rule_list) = #
follow(rule) = SEQ_ARROW IDENT CONC_ARROW #
follow(pvd_support) = #
follow(premise) = SEMICOLON OPEN_BRACE IDENT CLOSE_BRACK
follow(maybe_empty_tag_list) = SEQ_ARROW SEMICOLON OPEN_BRACE CONC_ARROW CLOSE_BRACK
follow(maybe_empty_axiom_tag_list) = SEMICOLON CLOSE_BRACK
follow(inv_list) = SEQ_ARROW SEMICOLON OPEN_BRACE CONC_ARROW CLOSE_BRACK
follow(inv_group) = SEQ_ARROW SEMICOLON OPEN_PAREN OPEN_BRACE CONC_ARROW COMMA CLOSE_BRACK
follow(inv) = SEQ_ARROW SEMICOLON OPEN_PAREN OPEN_BRACK OPEN_BRACE IDENT CONC_ARROW COMMA CLOSE_BRACK #
follow(ident_list) = CLOSE_BRACE BAR
follow(graph) = #
follow(formula_tactic_list) = CLOSE_BRACE
follow(formula_tactic) = IDENT CLOSE_BRACE
follow(formula_split_tactic_list) = IDENT CLOSE_BRACE
follow(formula_split_tactic) = IDENT BAR
follow(fact_list) = #
follow(fact) = NUMBER IDENT #
follow(condition_list) = CLOSE_BRACK
follow(condition) = COMMA COLON CLOSE_BRACK
follow(cases) = SEQ_ARROW OPEN_BRACE IDENT CONC_ARROW #
follow(case_list) = CLOSE_BRACK
follow(case) = SEMICOLON CLOSE_BRACK
follow(axioms) = #
follow(axiom_rule_list) = #
follow(axiom_rule) = IDENT #
follow(axiom_list) = SEMICOLON CLOSE_BRACK
follow(axiom_kind) = SEMICOLON COMMA CLOSE_BRACK
follow(axiom_cases) = IDENT #
follow(axiom_case_list) = CLOSE_BRACK
follow(axiom_case) = SEMICOLON CLOSE_BRACK
Built an LR(0) automaton with 160 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 160 states.
Warning: 23 end-of-stream conflicts were arbitrarily resolved.
File "leap_IGraphParser.mly", line 117, characters 4-14:
Warning: production axiom_rule_list -> axiom_rule is never reduced.
File "leap_IGraphParser.mly", line 110, characters 3-3:
Warning: production axioms -> is never reduced.
File "leap_IGraphParser.mly", line 238, characters 3-3:
Warning: production fact_list -> is never reduced.
File "leap_IGraphParser.mly", line 256, characters 3-3:
Warning: production graph -> is never reduced.
File "leap_IGraphParser.mly", line 263, characters 4-8:
Warning: production rule_list -> rule is never reduced.
Warning: in total, 5 productions are never reduced.
61 out of 160 states have a default reduction.
The action table is 4640 entries; 213 non-zero; 309 compressed.
The action table occupies roughly 712 bytes.
The goto table is 7040 entries; 120 non-zero; 293 compressed.
The goto table occupies roughly 384 bytes.
The error table occupies roughly 616 bytes.
The default_reduction table occupies roughly 192 bytes.
The lhs table occupies roughly 120 bytes.
The trace table occupies roughly 8 bytes.
