State 0:
main' -> . main [ # ]
-- On VDASH shift to state 1
-- On VAR shift to state 2
-- On OP shift to state 3
-- On DIRECTIVE shift to state 22
-- On sequent shift to state 24
-- On main shift to state 26
-- On formimp shift to state 27

State 1:
sequent -> VDASH . formimp [ END ]
-- On VAR shift to state 2
-- On OP shift to state 3
-- On formimp shift to state 21

State 2:
formimp -> VAR . [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VDASH reduce production formimp -> VAR 
-- On TIMES reduce production formimp -> VAR 
-- On SEQ reduce production formimp -> VAR 
-- On RIMP reduce production formimp -> VAR 
-- On PAR reduce production formimp -> VAR 
-- On NEXT reduce production formimp -> VAR 
-- On NEG reduce production formimp -> VAR 
-- On LIMP reduce production formimp -> VAR 
-- On IMP reduce production formimp -> VAR 
-- On END reduce production formimp -> VAR 
-- On CP reduce production formimp -> VAR 

State 3:
formimp -> OP . formimp CP [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VAR shift to state 2
-- On OP shift to state 3
-- On formimp shift to state 4

State 4:
formimp -> formimp . PAR formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP CP ]
formimp -> formimp . TIMES formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP CP ]
formimp -> formimp . NEXT formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP CP ]
formimp -> formimp . SEQ formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP CP ]
formimp -> formimp . IMP formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP CP ]
formimp -> formimp . RIMP formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP CP ]
formimp -> formimp . LIMP formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP CP ]
formimp -> OP formimp . CP [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEG [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP CP ]
-- On TIMES shift to state 5
-- On SEQ shift to state 9
-- On RIMP shift to state 7
-- On PAR shift to state 16
-- On NEXT shift to state 11
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On CP shift to state 20

State 5:
formimp -> formimp TIMES . formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VAR shift to state 2
-- On OP shift to state 3
-- On formimp shift to state 6

State 6:
formimp -> formimp . PAR formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . TIMES formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp TIMES formimp . [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEXT formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . SEQ formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . IMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . RIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . LIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEG [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On RIMP shift to state 7
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On VDASH reduce production formimp -> formimp TIMES formimp 
-- On TIMES reduce production formimp -> formimp TIMES formimp 
-- On SEQ reduce production formimp -> formimp TIMES formimp 
-- On RIMP reduce production formimp -> formimp TIMES formimp 
-- On PAR reduce production formimp -> formimp TIMES formimp 
-- On NEXT reduce production formimp -> formimp TIMES formimp 
-- On LIMP reduce production formimp -> formimp TIMES formimp 
-- On IMP reduce production formimp -> formimp TIMES formimp 
-- On END reduce production formimp -> formimp TIMES formimp 
-- On CP reduce production formimp -> formimp TIMES formimp 
** Conflict on RIMP LIMP IMP

State 7:
formimp -> formimp RIMP . formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VAR shift to state 2
-- On OP shift to state 3
-- On formimp shift to state 8

State 8:
formimp -> formimp . PAR formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . TIMES formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEXT formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . SEQ formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . IMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . RIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp RIMP formimp . [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . LIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEG [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On TIMES shift to state 5
-- On SEQ shift to state 9
-- On RIMP shift to state 7
-- On PAR shift to state 16
-- On NEXT shift to state 11
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On VDASH reduce production formimp -> formimp RIMP formimp 
-- On TIMES reduce production formimp -> formimp RIMP formimp 
-- On SEQ reduce production formimp -> formimp RIMP formimp 
-- On RIMP reduce production formimp -> formimp RIMP formimp 
-- On PAR reduce production formimp -> formimp RIMP formimp 
-- On NEXT reduce production formimp -> formimp RIMP formimp 
-- On NEG reduce production formimp -> formimp RIMP formimp 
-- On LIMP reduce production formimp -> formimp RIMP formimp 
-- On IMP reduce production formimp -> formimp RIMP formimp 
-- On END reduce production formimp -> formimp RIMP formimp 
-- On CP reduce production formimp -> formimp RIMP formimp 
** Conflict on TIMES SEQ RIMP PAR NEXT NEG LIMP IMP

State 9:
formimp -> formimp SEQ . formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VAR shift to state 2
-- On OP shift to state 3
-- On formimp shift to state 10

State 10:
formimp -> formimp . PAR formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . TIMES formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEXT formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . SEQ formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp SEQ formimp . [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . IMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . RIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . LIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEG [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On TIMES shift to state 5
-- On RIMP shift to state 7
-- On NEXT shift to state 11
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On VDASH reduce production formimp -> formimp SEQ formimp 
-- On SEQ reduce production formimp -> formimp SEQ formimp 
-- On RIMP reduce production formimp -> formimp SEQ formimp 
-- On PAR reduce production formimp -> formimp SEQ formimp 
-- On LIMP reduce production formimp -> formimp SEQ formimp 
-- On IMP reduce production formimp -> formimp SEQ formimp 
-- On END reduce production formimp -> formimp SEQ formimp 
-- On CP reduce production formimp -> formimp SEQ formimp 
** Conflict on RIMP LIMP IMP

State 11:
formimp -> formimp NEXT . formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VAR shift to state 2
-- On OP shift to state 3
-- On formimp shift to state 12

State 12:
formimp -> formimp . PAR formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . TIMES formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEXT formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp NEXT formimp . [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . SEQ formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . IMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . RIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . LIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEG [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On RIMP shift to state 7
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On VDASH reduce production formimp -> formimp NEXT formimp 
-- On TIMES reduce production formimp -> formimp NEXT formimp 
-- On SEQ reduce production formimp -> formimp NEXT formimp 
-- On RIMP reduce production formimp -> formimp NEXT formimp 
-- On PAR reduce production formimp -> formimp NEXT formimp 
-- On NEXT reduce production formimp -> formimp NEXT formimp 
-- On LIMP reduce production formimp -> formimp NEXT formimp 
-- On IMP reduce production formimp -> formimp NEXT formimp 
-- On END reduce production formimp -> formimp NEXT formimp 
-- On CP reduce production formimp -> formimp NEXT formimp 
** Conflict on RIMP LIMP IMP

State 13:
formimp -> formimp NEG . [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VDASH reduce production formimp -> formimp NEG 
-- On TIMES reduce production formimp -> formimp NEG 
-- On SEQ reduce production formimp -> formimp NEG 
-- On RIMP reduce production formimp -> formimp NEG 
-- On PAR reduce production formimp -> formimp NEG 
-- On NEXT reduce production formimp -> formimp NEG 
-- On NEG reduce production formimp -> formimp NEG 
-- On LIMP reduce production formimp -> formimp NEG 
-- On IMP reduce production formimp -> formimp NEG 
-- On END reduce production formimp -> formimp NEG 
-- On CP reduce production formimp -> formimp NEG 

State 14:
formimp -> formimp LIMP . formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VAR shift to state 2
-- On OP shift to state 3
-- On formimp shift to state 15

State 15:
formimp -> formimp . PAR formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . TIMES formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEXT formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . SEQ formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . IMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . RIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . LIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp LIMP formimp . [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEG [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On TIMES shift to state 5
-- On SEQ shift to state 9
-- On RIMP shift to state 7
-- On PAR shift to state 16
-- On NEXT shift to state 11
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On VDASH reduce production formimp -> formimp LIMP formimp 
-- On TIMES reduce production formimp -> formimp LIMP formimp 
-- On SEQ reduce production formimp -> formimp LIMP formimp 
-- On RIMP reduce production formimp -> formimp LIMP formimp 
-- On PAR reduce production formimp -> formimp LIMP formimp 
-- On NEXT reduce production formimp -> formimp LIMP formimp 
-- On NEG reduce production formimp -> formimp LIMP formimp 
-- On LIMP reduce production formimp -> formimp LIMP formimp 
-- On IMP reduce production formimp -> formimp LIMP formimp 
-- On END reduce production formimp -> formimp LIMP formimp 
-- On CP reduce production formimp -> formimp LIMP formimp 
** Conflict on TIMES SEQ RIMP PAR NEXT NEG LIMP IMP

State 16:
formimp -> formimp PAR . formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VAR shift to state 2
-- On OP shift to state 3
-- On formimp shift to state 17

State 17:
formimp -> formimp . PAR formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp PAR formimp . [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . TIMES formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEXT formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . SEQ formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . IMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . RIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . LIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEG [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On TIMES shift to state 5
-- On RIMP shift to state 7
-- On NEXT shift to state 11
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On VDASH reduce production formimp -> formimp PAR formimp 
-- On SEQ reduce production formimp -> formimp PAR formimp 
-- On RIMP reduce production formimp -> formimp PAR formimp 
-- On PAR reduce production formimp -> formimp PAR formimp 
-- On LIMP reduce production formimp -> formimp PAR formimp 
-- On IMP reduce production formimp -> formimp PAR formimp 
-- On END reduce production formimp -> formimp PAR formimp 
-- On CP reduce production formimp -> formimp PAR formimp 
** Conflict on RIMP LIMP IMP

State 18:
formimp -> formimp IMP . formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VAR shift to state 2
-- On OP shift to state 3
-- On formimp shift to state 19

State 19:
formimp -> formimp . PAR formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . TIMES formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEXT formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . SEQ formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . IMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp IMP formimp . [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . RIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . LIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
formimp -> formimp . NEG [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On TIMES shift to state 5
-- On SEQ shift to state 9
-- On RIMP shift to state 7
-- On PAR shift to state 16
-- On NEXT shift to state 11
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On VDASH reduce production formimp -> formimp IMP formimp 
-- On TIMES reduce production formimp -> formimp IMP formimp 
-- On SEQ reduce production formimp -> formimp IMP formimp 
-- On RIMP reduce production formimp -> formimp IMP formimp 
-- On PAR reduce production formimp -> formimp IMP formimp 
-- On NEXT reduce production formimp -> formimp IMP formimp 
-- On NEG reduce production formimp -> formimp IMP formimp 
-- On LIMP reduce production formimp -> formimp IMP formimp 
-- On IMP reduce production formimp -> formimp IMP formimp 
-- On END reduce production formimp -> formimp IMP formimp 
-- On CP reduce production formimp -> formimp IMP formimp 
** Conflict on TIMES SEQ RIMP PAR NEXT NEG LIMP IMP

State 20:
formimp -> OP formimp CP . [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END CP ]
-- On VDASH reduce production formimp -> OP formimp CP 
-- On TIMES reduce production formimp -> OP formimp CP 
-- On SEQ reduce production formimp -> OP formimp CP 
-- On RIMP reduce production formimp -> OP formimp CP 
-- On PAR reduce production formimp -> OP formimp CP 
-- On NEXT reduce production formimp -> OP formimp CP 
-- On NEG reduce production formimp -> OP formimp CP 
-- On LIMP reduce production formimp -> OP formimp CP 
-- On IMP reduce production formimp -> OP formimp CP 
-- On END reduce production formimp -> OP formimp CP 
-- On CP reduce production formimp -> OP formimp CP 

State 21:
formimp -> formimp . PAR formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . TIMES formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . NEXT formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . SEQ formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . IMP formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . RIMP formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . LIMP formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . NEG [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
sequent -> VDASH formimp . [ END ]
-- On TIMES shift to state 5
-- On SEQ shift to state 9
-- On RIMP shift to state 7
-- On PAR shift to state 16
-- On NEXT shift to state 11
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On END reduce production sequent -> VDASH formimp 

State 22:
main -> DIRECTIVE . VAR [ # ]
-- On VAR shift to state 23

State 23:
main -> DIRECTIVE VAR . [ # ]
-- On # reduce production main -> DIRECTIVE VAR 

State 24:
main -> sequent . END [ # ]
-- On END shift to state 25

State 25:
main -> sequent END . [ # ]
-- On # reduce production main -> sequent END 

State 26:
main' -> main . [ # ]
-- On # accept main

State 27:
formimp -> formimp . PAR formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . TIMES formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . NEXT formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . SEQ formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . IMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . RIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . LIMP formimp [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . NEG [ VDASH TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
sequent -> formimp . VDASH formimp [ END ]
sequent -> formimp . [ END ]
-- On VDASH shift to state 28
-- On TIMES shift to state 5
-- On SEQ shift to state 9
-- On RIMP shift to state 7
-- On PAR shift to state 16
-- On NEXT shift to state 11
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On END reduce production sequent -> formimp 

State 28:
sequent -> formimp VDASH . formimp [ END ]
-- On VAR shift to state 2
-- On OP shift to state 3
-- On formimp shift to state 29

State 29:
formimp -> formimp . PAR formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . TIMES formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . NEXT formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . SEQ formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . IMP formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . RIMP formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . LIMP formimp [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
formimp -> formimp . NEG [ TIMES SEQ RIMP PAR NEXT NEG LIMP IMP END ]
sequent -> formimp VDASH formimp . [ END ]
-- On TIMES shift to state 5
-- On SEQ shift to state 9
-- On RIMP shift to state 7
-- On PAR shift to state 16
-- On NEXT shift to state 11
-- On NEG shift to state 13
-- On LIMP shift to state 14
-- On IMP shift to state 18
-- On END reduce production sequent -> formimp VDASH formimp 

