
** Conflict (shift/reduce) in state 227.
** Token involved: TK_IN
** This state is reached from lutFileTop after reading:

lutFile TK_LET lutIdent lutOptParams lutOptType TK_EQ TK_LET lutIdent lutOptParams lutOptType TK_EQ TK_RUN lutIdentTuple TK_ASSIGN lutExp 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

lutFileTop 
lutFile TK_EOF 
lutFile lutOneDecl 
        lutLetDecl 
        TK_LET lutIdent lutOptParams lutOptType TK_EQ lutTraceExp 
                                                      (?)

** In state 227, looking ahead at TK_IN, shifting is permitted
** because of the following sub-derivation:

lutLetDecl TK_IN lutTraceExp 
TK_LET lutIdent lutOptParams lutOptType TK_EQ lutTraceExp 
                                              TK_RUN lutIdentTuple TK_ASSIGN lutExp . TK_IN lutTraceExp 

** In state 227, looking ahead at TK_IN, reducing production
** lutTraceExp -> TK_RUN lutIdentTuple TK_ASSIGN lutExp 
** is permitted because of the following sub-derivation:

lutLetDecl TK_IN lutTraceExp // lookahead token appears
TK_LET lutIdent lutOptParams lutOptType TK_EQ lutTraceExp // lookahead token is inherited
                                              TK_RUN lutIdentTuple TK_ASSIGN lutExp . 
