State 0:
## Known stack suffix:
##
## LR(1) items:
entry_point' -> . entry_point [ # ]
## Transitions:
-- On NEWLINE shift to state 1
-- On program shift to state 2
-- On newline_list shift to state 4
-- On linebreak shift to state 6
-- On entry_point shift to state 186
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For EOF DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 1:
## Known stack suffix:
## NEWLINE
## LR(1) items:
newline_list -> NEWLINE . [ While WORD Until Then Rparen Rbrace NEWLINE NAME Lparen Lbrace LESSGREAT LESSAND LESS In If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production newline_list -> NEWLINE

State 2:
## Known stack suffix:
## program
## LR(1) items:
entry_point -> program . EOF [ # ]
## Transitions:
-- On EOF shift to state 3
## Reductions:

State 3:
## Known stack suffix:
## program EOF
## LR(1) items:
entry_point -> program EOF . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production entry_point -> program EOF

State 4:
## Known stack suffix:
## newline_list
## LR(1) items:
linebreak -> newline_list . [ While WORD Until Then Rparen Rbrace NAME Lparen Lbrace LESSGREAT LESSAND LESS In If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
newline_list -> newline_list . NEWLINE [ While WORD Until Then Rparen Rbrace NEWLINE NAME Lparen Lbrace LESSGREAT LESSAND LESS In If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
## Transitions:
-- On NEWLINE shift to state 5
## Reductions:
-- On While WORD Until Then Rparen Rbrace NAME Lparen Lbrace LESSGREAT LESSAND LESS In If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak -> newline_list

State 5:
## Known stack suffix:
## newline_list NEWLINE
## LR(1) items:
newline_list -> newline_list NEWLINE . [ While WORD Until Then Rparen Rbrace NEWLINE NAME Lparen Lbrace LESSGREAT LESSAND LESS In If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production newline_list -> newline_list NEWLINE

State 6:
## Known stack suffix:
## linebreak
## LR(1) items:
program -> linebreak . complete_commands linebreak [ EOF ]
program -> linebreak . [ EOF ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On Bang shift to state 93
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On pipeline shift to state 142
-- On pipe_sequence shift to state 143
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On complete_commands shift to state 177
-- On complete_command shift to state 185
-- On command shift to state 135
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On clist shift to state 180
-- On case_clause shift to state 118
-- On brace_group shift to state 119
-- On and_or shift to state 183
## Reductions:
-- On EOF
--   reduce production program -> linebreak

State 7:
## Known stack suffix:
## While
## LR(1) items:
while_clause -> While . compound_list do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 8
-- On compound_list shift to state 175
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 8:
## Known stack suffix:
## linebreak
## LR(1) items:
compound_list -> linebreak . term [ Then Rparen Rbrace Fi Else Elif Done Do ]
compound_list -> linebreak . term separator [ Then Rparen Rbrace Fi Else Elif Done Do ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On Bang shift to state 93
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On term shift to state 136
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On pipeline shift to state 142
-- On pipe_sequence shift to state 143
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On command shift to state 135
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On case_clause shift to state 118
-- On brace_group shift to state 119
-- On and_or shift to state 152
## Reductions:

State 9:
## Known stack suffix:
## WORD
## LR(1) items:
word -> WORD . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS In IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production word -> WORD

State 10:
## Known stack suffix:
## Until
## LR(1) items:
until_clause -> Until . compound_list do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 8
-- On compound_list shift to state 11
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 11:
## Known stack suffix:
## Until compound_list
## LR(1) items:
until_clause -> Until compound_list . do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Do shift to state 12
-- On do_group shift to state 15
## Reductions:

State 12:
## Known stack suffix:
## Do
## LR(1) items:
do_group -> Do . compound_list Done [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 8
-- On compound_list shift to state 13
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 13:
## Known stack suffix:
## Do compound_list
## LR(1) items:
do_group -> Do compound_list . Done [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Done shift to state 14
## Reductions:

State 14:
## Known stack suffix:
## Do compound_list Done
## LR(1) items:
do_group -> Do compound_list Done . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production do_group -> Do compound_list Done

State 15:
## Known stack suffix:
## Until compound_list do_group
## LR(1) items:
until_clause -> Until compound_list do_group . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production until_clause -> Until compound_list do_group

State 16:
## Known stack suffix:
## NAME
## LR(1) items:
fname -> NAME . [ Lparen ]
word -> NAME . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Reductions:
-- On Lparen
--   reduce production fname -> NAME
-- On WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF
--   reduce production word -> NAME

State 17:
## Known stack suffix:
## Lparen
## LR(1) items:
subshell -> Lparen . compound_list Rparen [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 8
-- On compound_list shift to state 18
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 18:
## Known stack suffix:
## Lparen compound_list
## LR(1) items:
subshell -> Lparen compound_list . Rparen [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Rparen shift to state 19
## Reductions:

State 19:
## Known stack suffix:
## Lparen compound_list Rparen
## LR(1) items:
subshell -> Lparen compound_list Rparen . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production subshell -> Lparen compound_list Rparen

State 20:
## Known stack suffix:
## Lbrace
## LR(1) items:
brace_group -> Lbrace . compound_list Rbrace [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 8
-- On compound_list shift to state 21
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 21:
## Known stack suffix:
## Lbrace compound_list
## LR(1) items:
brace_group -> Lbrace compound_list . Rbrace [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Rbrace shift to state 22
## Reductions:

State 22:
## Known stack suffix:
## Lbrace compound_list Rbrace
## LR(1) items:
brace_group -> Lbrace compound_list Rbrace . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production brace_group -> Lbrace compound_list Rbrace

State 23:
## Known stack suffix:
## LESSGREAT
## LR(1) items:
io_file -> LESSGREAT . filename [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 25
-- On filename shift to state 26
## Reductions:

State 24:
## Known stack suffix:
## NAME
## LR(1) items:
word -> NAME . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS In IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production word -> NAME

State 25:
## Known stack suffix:
## word
## LR(1) items:
filename -> word . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production filename -> word

State 26:
## Known stack suffix:
## LESSGREAT filename
## LR(1) items:
io_file -> LESSGREAT filename . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_file -> LESSGREAT filename

State 27:
## Known stack suffix:
## LESSAND
## LR(1) items:
io_file -> LESSAND . filename [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 25
-- On filename shift to state 28
## Reductions:

State 28:
## Known stack suffix:
## LESSAND filename
## LR(1) items:
io_file -> LESSAND filename . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_file -> LESSAND filename

State 29:
## Known stack suffix:
## LESS
## LR(1) items:
io_file -> LESS . filename [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 25
-- On filename shift to state 30
## Reductions:

State 30:
## Known stack suffix:
## LESS filename
## LR(1) items:
io_file -> LESS filename . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_file -> LESS filename

State 31:
## Known stack suffix:
## If
## LR(1) items:
if_clause -> If . compound_list Then compound_list else_part Fi [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
if_clause -> If . compound_list Then compound_list Fi [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 8
-- On compound_list shift to state 32
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 32:
## Known stack suffix:
## If compound_list
## LR(1) items:
if_clause -> If compound_list . Then compound_list else_part Fi [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
if_clause -> If compound_list . Then compound_list Fi [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Then shift to state 33
## Reductions:

State 33:
## Known stack suffix:
## If compound_list Then
## LR(1) items:
if_clause -> If compound_list Then . compound_list else_part Fi [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
if_clause -> If compound_list Then . compound_list Fi [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 8
-- On compound_list shift to state 34
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 34:
## Known stack suffix:
## If compound_list Then compound_list
## LR(1) items:
if_clause -> If compound_list Then compound_list . else_part Fi [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
if_clause -> If compound_list Then compound_list . Fi [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Fi shift to state 35
-- On Else shift to state 36
-- On Elif shift to state 38
-- On else_part shift to state 43
## Reductions:

State 35:
## Known stack suffix:
## If compound_list Then compound_list Fi
## LR(1) items:
if_clause -> If compound_list Then compound_list Fi . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production if_clause -> If compound_list Then compound_list Fi

State 36:
## Known stack suffix:
## Else
## LR(1) items:
else_part -> Else . compound_list [ Fi ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 8
-- On compound_list shift to state 37
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 37:
## Known stack suffix:
## Else compound_list
## LR(1) items:
else_part -> Else compound_list . [ Fi ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production else_part -> Else compound_list

State 38:
## Known stack suffix:
## Elif
## LR(1) items:
else_part -> Elif . compound_list Then compound_list [ Fi ]
else_part -> Elif . compound_list Then compound_list else_part [ Fi ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 8
-- On compound_list shift to state 39
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 39:
## Known stack suffix:
## Elif compound_list
## LR(1) items:
else_part -> Elif compound_list . Then compound_list [ Fi ]
else_part -> Elif compound_list . Then compound_list else_part [ Fi ]
## Transitions:
-- On Then shift to state 40
## Reductions:

State 40:
## Known stack suffix:
## Elif compound_list Then
## LR(1) items:
else_part -> Elif compound_list Then . compound_list [ Fi ]
else_part -> Elif compound_list Then . compound_list else_part [ Fi ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 8
-- On compound_list shift to state 41
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 41:
## Known stack suffix:
## Elif compound_list Then compound_list
## LR(1) items:
else_part -> Elif compound_list Then compound_list . [ Fi ]
else_part -> Elif compound_list Then compound_list . else_part [ Fi ]
## Transitions:
-- On Else shift to state 36
-- On Elif shift to state 38
-- On else_part shift to state 42
## Reductions:
-- On Fi
--   reduce production else_part -> Elif compound_list Then compound_list

State 42:
## Known stack suffix:
## Elif compound_list Then compound_list else_part
## LR(1) items:
else_part -> Elif compound_list Then compound_list else_part . [ Fi ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production else_part -> Elif compound_list Then compound_list else_part

State 43:
## Known stack suffix:
## If compound_list Then compound_list else_part
## LR(1) items:
if_clause -> If compound_list Then compound_list else_part . Fi [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Fi shift to state 44
## Reductions:

State 44:
## Known stack suffix:
## If compound_list Then compound_list else_part Fi
## LR(1) items:
if_clause -> If compound_list Then compound_list else_part Fi . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production if_clause -> If compound_list Then compound_list else_part Fi

State 45:
## Known stack suffix:
## IO_NUMBER
## LR(1) items:
io_redirect -> IO_NUMBER . io_file [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
io_redirect -> IO_NUMBER . io_here [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On CLOBBER shift to state 57
-- On io_here shift to state 59
-- On io_file shift to state 60
## Reductions:

State 46:
## Known stack suffix:
## GREATAND
## LR(1) items:
io_file -> GREATAND . filename [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 25
-- On filename shift to state 47
## Reductions:

State 47:
## Known stack suffix:
## GREATAND filename
## LR(1) items:
io_file -> GREATAND filename . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_file -> GREATAND filename

State 48:
## Known stack suffix:
## GREAT
## LR(1) items:
io_file -> GREAT . filename [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 25
-- On filename shift to state 49
## Reductions:

State 49:
## Known stack suffix:
## GREAT filename
## LR(1) items:
io_file -> GREAT filename . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_file -> GREAT filename

State 50:
## Known stack suffix:
## DLESSDASH
## LR(1) items:
io_here -> DLESSDASH . here_end [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 51
-- On here_end shift to state 52
## Reductions:

State 51:
## Known stack suffix:
## word
## LR(1) items:
here_end -> word . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production here_end -> word

State 52:
## Known stack suffix:
## DLESSDASH here_end
## LR(1) items:
io_here -> DLESSDASH here_end . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_here -> DLESSDASH here_end

State 53:
## Known stack suffix:
## DLESS
## LR(1) items:
io_here -> DLESS . here_end [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 51
-- On here_end shift to state 54
## Reductions:

State 54:
## Known stack suffix:
## DLESS here_end
## LR(1) items:
io_here -> DLESS here_end . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_here -> DLESS here_end

State 55:
## Known stack suffix:
## DGREAT
## LR(1) items:
io_file -> DGREAT . filename [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 25
-- On filename shift to state 56
## Reductions:

State 56:
## Known stack suffix:
## DGREAT filename
## LR(1) items:
io_file -> DGREAT filename . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_file -> DGREAT filename

State 57:
## Known stack suffix:
## CLOBBER
## LR(1) items:
io_file -> CLOBBER . filename [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 25
-- On filename shift to state 58
## Reductions:

State 58:
## Known stack suffix:
## CLOBBER filename
## LR(1) items:
io_file -> CLOBBER filename . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_file -> CLOBBER filename

State 59:
## Known stack suffix:
## IO_NUMBER io_here
## LR(1) items:
io_redirect -> IO_NUMBER io_here . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_redirect -> IO_NUMBER io_here

State 60:
## Known stack suffix:
## IO_NUMBER io_file
## LR(1) items:
io_redirect -> IO_NUMBER io_file . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_redirect -> IO_NUMBER io_file

State 61:
## Known stack suffix:
## For
## LR(1) items:
for_clause -> For . name do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
for_clause -> For . name sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
for_clause -> For . name linebreak cin sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
for_clause -> For . name linebreak cin wordlist sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On NAME shift to state 62
-- On name shift to state 63
## Reductions:

State 62:
## Known stack suffix:
## NAME
## LR(1) items:
name -> NAME . [ Semicolon NEWLINE In Do ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production name -> NAME

State 63:
## Known stack suffix:
## For name
## LR(1) items:
for_clause -> For name . do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
for_clause -> For name . sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
for_clause -> For name . linebreak cin sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
for_clause -> For name . linebreak cin wordlist sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Semicolon shift to state 64
-- On NEWLINE shift to state 1
-- On Do shift to state 12
-- On sequential_sep shift to state 66
-- On newline_list shift to state 68
-- On linebreak shift to state 69
-- On do_group shift to state 80
## Reductions:
-- On In
--   reduce production linebreak ->

State 64:
## Known stack suffix:
## Semicolon
## LR(1) items:
sequential_sep -> Semicolon . linebreak [ Do ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 65
## Reductions:
-- On Do
--   reduce production linebreak ->

State 65:
## Known stack suffix:
## Semicolon linebreak
## LR(1) items:
sequential_sep -> Semicolon linebreak . [ Do ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production sequential_sep -> Semicolon linebreak

State 66:
## Known stack suffix:
## For name sequential_sep
## LR(1) items:
for_clause -> For name sequential_sep . do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Do shift to state 12
-- On do_group shift to state 67
## Reductions:

State 67:
## Known stack suffix:
## For name sequential_sep do_group
## LR(1) items:
for_clause -> For name sequential_sep do_group . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production for_clause -> For name sequential_sep do_group

State 68:
## Known stack suffix:
## newline_list
## LR(1) items:
linebreak -> newline_list . [ In ]
newline_list -> newline_list . NEWLINE [ NEWLINE In Do ]
sequential_sep -> newline_list . [ Do ]
## Transitions:
-- On NEWLINE shift to state 5
## Reductions:
-- On In
--   reduce production linebreak -> newline_list
-- On Do
--   reduce production sequential_sep -> newline_list

State 69:
## Known stack suffix:
## For name linebreak
## LR(1) items:
for_clause -> For name linebreak . cin sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
for_clause -> For name linebreak . cin wordlist sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On In shift to state 70
-- On cin shift to state 71
## Reductions:

State 70:
## Known stack suffix:
## In
## LR(1) items:
cin -> In . [ WORD Semicolon NEWLINE NAME Lparen Esac ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cin -> In

State 71:
## Known stack suffix:
## For name linebreak cin
## LR(1) items:
for_clause -> For name linebreak cin . sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
for_clause -> For name linebreak cin . wordlist sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On Semicolon shift to state 64
-- On NEWLINE shift to state 1
-- On NAME shift to state 24
-- On wordlist shift to state 72
-- On word shift to state 77
-- On sequential_sep shift to state 78
-- On newline_list shift to state 76
## Reductions:

State 72:
## Known stack suffix:
## For name linebreak cin wordlist
## LR(1) items:
for_clause -> For name linebreak cin wordlist . sequential_sep do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
wordlist -> wordlist . word [ WORD Semicolon NEWLINE NAME ]
## Transitions:
-- On WORD shift to state 9
-- On Semicolon shift to state 64
-- On NEWLINE shift to state 1
-- On NAME shift to state 24
-- On word shift to state 73
-- On sequential_sep shift to state 74
-- On newline_list shift to state 76
## Reductions:

State 73:
## Known stack suffix:
## wordlist word
## LR(1) items:
wordlist -> wordlist word . [ WORD Semicolon NEWLINE NAME ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production wordlist -> wordlist word

State 74:
## Known stack suffix:
## For name linebreak cin wordlist sequential_sep
## LR(1) items:
for_clause -> For name linebreak cin wordlist sequential_sep . do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Do shift to state 12
-- On do_group shift to state 75
## Reductions:

State 75:
## Known stack suffix:
## For name linebreak cin wordlist sequential_sep do_group
## LR(1) items:
for_clause -> For name linebreak cin wordlist sequential_sep do_group . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production for_clause -> For name linebreak cin wordlist sequential_sep do_group

State 76:
## Known stack suffix:
## newline_list
## LR(1) items:
newline_list -> newline_list . NEWLINE [ NEWLINE Do ]
sequential_sep -> newline_list . [ Do ]
## Transitions:
-- On NEWLINE shift to state 5
## Reductions:
-- On Do
--   reduce production sequential_sep -> newline_list

State 77:
## Known stack suffix:
## word
## LR(1) items:
wordlist -> word . [ WORD Semicolon NEWLINE NAME ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production wordlist -> word

State 78:
## Known stack suffix:
## For name linebreak cin sequential_sep
## LR(1) items:
for_clause -> For name linebreak cin sequential_sep . do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Do shift to state 12
-- On do_group shift to state 79
## Reductions:

State 79:
## Known stack suffix:
## For name linebreak cin sequential_sep do_group
## LR(1) items:
for_clause -> For name linebreak cin sequential_sep do_group . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production for_clause -> For name linebreak cin sequential_sep do_group

State 80:
## Known stack suffix:
## For name do_group
## LR(1) items:
for_clause -> For name do_group . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production for_clause -> For name do_group

State 81:
## Known stack suffix:
## Case
## LR(1) items:
case_clause -> Case . word linebreak cin linebreak case_list Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_clause -> Case . word linebreak cin linebreak case_list_ns Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_clause -> Case . word linebreak cin linebreak Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 82
## Reductions:

State 82:
## Known stack suffix:
## Case word
## LR(1) items:
case_clause -> Case word . linebreak cin linebreak case_list Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_clause -> Case word . linebreak cin linebreak case_list_ns Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_clause -> Case word . linebreak cin linebreak Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 83
## Reductions:
-- On In
--   reduce production linebreak ->

State 83:
## Known stack suffix:
## Case word linebreak
## LR(1) items:
case_clause -> Case word linebreak . cin linebreak case_list Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_clause -> Case word linebreak . cin linebreak case_list_ns Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_clause -> Case word linebreak . cin linebreak Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On In shift to state 70
-- On cin shift to state 84
## Reductions:

State 84:
## Known stack suffix:
## Case word linebreak cin
## LR(1) items:
case_clause -> Case word linebreak cin . linebreak case_list Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_clause -> Case word linebreak cin . linebreak case_list_ns Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_clause -> Case word linebreak cin . linebreak Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 85
## Reductions:
-- On WORD NAME Lparen Esac
--   reduce production linebreak ->

State 85:
## Known stack suffix:
## Case word linebreak cin linebreak
## LR(1) items:
case_clause -> Case word linebreak cin linebreak . case_list Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_clause -> Case word linebreak cin linebreak . case_list_ns Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_clause -> Case word linebreak cin linebreak . Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On Lparen shift to state 86
-- On Esac shift to state 158
-- On word shift to state 87
-- On pattern shift to state 159
-- On case_list_ns shift to state 167
-- On case_list shift to state 169
-- On case_item_ns shift to state 173
-- On case_item shift to state 174
## Reductions:

State 86:
## Known stack suffix:
## Lparen
## LR(1) items:
case_item -> Lparen . pattern Rparen linebreak DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item -> Lparen . pattern Rparen compound_list DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item_ns -> Lparen . pattern Rparen linebreak [ Esac ]
case_item_ns -> Lparen . pattern Rparen compound_list [ Esac ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 87
-- On pattern shift to state 88
## Reductions:

State 87:
## Known stack suffix:
## word
## LR(1) items:
pattern -> word . [ Rparen Pipe ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production pattern -> word

State 88:
## Known stack suffix:
## Lparen pattern
## LR(1) items:
case_item -> Lparen pattern . Rparen linebreak DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item -> Lparen pattern . Rparen compound_list DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item_ns -> Lparen pattern . Rparen linebreak [ Esac ]
case_item_ns -> Lparen pattern . Rparen compound_list [ Esac ]
pattern -> pattern . Pipe word [ Rparen Pipe ]
## Transitions:
-- On Rparen shift to state 89
-- On Pipe shift to state 156
## Reductions:

State 89:
## Known stack suffix:
## Lparen pattern Rparen
## LR(1) items:
case_item -> Lparen pattern Rparen . linebreak DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item -> Lparen pattern Rparen . compound_list DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item_ns -> Lparen pattern Rparen . linebreak [ Esac ]
case_item_ns -> Lparen pattern Rparen . compound_list [ Esac ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 90
-- On compound_list shift to state 153
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For Esac DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 90:
## Known stack suffix:
## Lparen pattern Rparen linebreak
## LR(1) items:
case_item -> Lparen pattern Rparen linebreak . DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item_ns -> Lparen pattern Rparen linebreak . [ Esac ]
compound_list -> linebreak . term [ Esac DSEMI ]
compound_list -> linebreak . term separator [ Esac DSEMI ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DSEMI shift to state 91
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On Bang shift to state 93
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On term shift to state 136
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On pipeline shift to state 142
-- On pipe_sequence shift to state 143
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On command shift to state 135
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On case_clause shift to state 118
-- On brace_group shift to state 119
-- On and_or shift to state 152
## Reductions:
-- On Esac
--   reduce production case_item_ns -> Lparen pattern Rparen linebreak

State 91:
## Known stack suffix:
## Lparen pattern Rparen linebreak DSEMI
## LR(1) items:
case_item -> Lparen pattern Rparen linebreak DSEMI . linebreak [ WORD NAME Lparen Esac ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 92
## Reductions:
-- On WORD NAME Lparen Esac
--   reduce production linebreak ->

State 92:
## Known stack suffix:
## Lparen pattern Rparen linebreak DSEMI linebreak
## LR(1) items:
case_item -> Lparen pattern Rparen linebreak DSEMI linebreak . [ WORD NAME Lparen Esac ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_item -> Lparen pattern Rparen linebreak DSEMI linebreak

State 93:
## Known stack suffix:
## Bang
## LR(1) items:
pipeline -> Bang . pipe_sequence [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On pipe_sequence shift to state 100
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On command shift to state 135
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On case_clause shift to state 118
-- On brace_group shift to state 119
## Reductions:

State 94:
## Known stack suffix:
## ASSIGNMENT_WORD
## LR(1) items:
cmd_prefix -> ASSIGNMENT_WORD . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cmd_prefix -> ASSIGNMENT_WORD

State 95:
## Known stack suffix:
## word
## LR(1) items:
cmd_name -> word . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cmd_name -> word

State 96:
## Known stack suffix:
## while_clause
## LR(1) items:
compound_command -> while_clause . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production compound_command -> while_clause

State 97:
## Known stack suffix:
## until_clause
## LR(1) items:
compound_command -> until_clause . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production compound_command -> until_clause

State 98:
## Known stack suffix:
## subshell
## LR(1) items:
compound_command -> subshell . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production compound_command -> subshell

State 99:
## Known stack suffix:
## simple_command
## LR(1) items:
command -> simple_command . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production command -> simple_command

State 100:
## Known stack suffix:
## Bang pipe_sequence
## LR(1) items:
pipe_sequence -> pipe_sequence . Pipe linebreak command [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
pipeline -> Bang pipe_sequence . [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On Pipe shift to state 101
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production pipeline -> Bang pipe_sequence

State 101:
## Known stack suffix:
## pipe_sequence Pipe
## LR(1) items:
pipe_sequence -> pipe_sequence Pipe . linebreak command [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 102
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER ASSIGNMENT_WORD
--   reduce production linebreak ->

State 102:
## Known stack suffix:
## pipe_sequence Pipe linebreak
## LR(1) items:
pipe_sequence -> pipe_sequence Pipe linebreak . command [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On command shift to state 122
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On case_clause shift to state 118
-- On brace_group shift to state 119
## Reductions:

State 103:
## Known stack suffix:
## io_redirect
## LR(1) items:
cmd_prefix -> io_redirect . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cmd_prefix -> io_redirect

State 104:
## Known stack suffix:
## io_here
## LR(1) items:
io_redirect -> io_here . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_redirect -> io_here

State 105:
## Known stack suffix:
## io_file
## LR(1) items:
io_redirect -> io_file . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production io_redirect -> io_file

State 106:
## Known stack suffix:
## if_clause
## LR(1) items:
compound_command -> if_clause . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production compound_command -> if_clause

State 107:
## Known stack suffix:
## function_definition
## LR(1) items:
command -> function_definition . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production command -> function_definition

State 108:
## Known stack suffix:
## for_clause
## LR(1) items:
compound_command -> for_clause . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production compound_command -> for_clause

State 109:
## Known stack suffix:
## fname
## LR(1) items:
function_definition -> fname . Lparen Rparen linebreak function_body [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On Lparen shift to state 110
## Reductions:

State 110:
## Known stack suffix:
## fname Lparen
## LR(1) items:
function_definition -> fname Lparen . Rparen linebreak function_body [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On Rparen shift to state 111
## Reductions:

State 111:
## Known stack suffix:
## fname Lparen Rparen
## LR(1) items:
function_definition -> fname Lparen Rparen . linebreak function_body [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 112
## Reductions:
-- On While Until Lparen Lbrace If For Case
--   reduce production linebreak ->

State 112:
## Known stack suffix:
## fname Lparen Rparen linebreak
## LR(1) items:
function_definition -> fname Lparen Rparen linebreak . function_body [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On While shift to state 7
-- On Until shift to state 10
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On If shift to state 31
-- On For shift to state 61
-- On Case shift to state 81
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On subshell shift to state 98
-- On if_clause shift to state 106
-- On function_body shift to state 113
-- On for_clause shift to state 108
-- On compound_command shift to state 114
-- On case_clause shift to state 118
-- On brace_group shift to state 119
## Reductions:

State 113:
## Known stack suffix:
## fname Lparen Rparen linebreak function_body
## LR(1) items:
function_definition -> fname Lparen Rparen linebreak function_body . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production function_definition -> fname Lparen Rparen linebreak function_body

State 114:
## Known stack suffix:
## compound_command
## LR(1) items:
function_body -> compound_command . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
function_body -> compound_command . redirect_list [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On CLOBBER shift to state 57
-- On redirect_list shift to state 115
-- On io_redirect shift to state 117
-- On io_here shift to state 104
-- On io_file shift to state 105
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production function_body -> compound_command

State 115:
## Known stack suffix:
## compound_command redirect_list
## LR(1) items:
function_body -> compound_command redirect_list . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
redirect_list -> redirect_list . io_redirect [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On CLOBBER shift to state 57
-- On io_redirect shift to state 116
-- On io_here shift to state 104
-- On io_file shift to state 105
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production function_body -> compound_command redirect_list

State 116:
## Known stack suffix:
## redirect_list io_redirect
## LR(1) items:
redirect_list -> redirect_list io_redirect . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production redirect_list -> redirect_list io_redirect

State 117:
## Known stack suffix:
## io_redirect
## LR(1) items:
redirect_list -> io_redirect . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production redirect_list -> io_redirect

State 118:
## Known stack suffix:
## case_clause
## LR(1) items:
compound_command -> case_clause . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production compound_command -> case_clause

State 119:
## Known stack suffix:
## brace_group
## LR(1) items:
compound_command -> brace_group . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production compound_command -> brace_group

State 120:
## Known stack suffix:
## compound_command
## LR(1) items:
command -> compound_command . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
command -> compound_command . redirect_list [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On CLOBBER shift to state 57
-- On redirect_list shift to state 121
-- On io_redirect shift to state 117
-- On io_here shift to state 104
-- On io_file shift to state 105
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production command -> compound_command

State 121:
## Known stack suffix:
## compound_command redirect_list
## LR(1) items:
command -> compound_command redirect_list . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
redirect_list -> redirect_list . io_redirect [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On CLOBBER shift to state 57
-- On io_redirect shift to state 116
-- On io_here shift to state 104
-- On io_file shift to state 105
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production command -> compound_command redirect_list

State 122:
## Known stack suffix:
## pipe_sequence Pipe linebreak command
## LR(1) items:
pipe_sequence -> pipe_sequence Pipe linebreak command . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production pipe_sequence -> pipe_sequence Pipe linebreak command

State 123:
## Known stack suffix:
## cmd_prefix
## LR(1) items:
cmd_prefix -> cmd_prefix . io_redirect [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
cmd_prefix -> cmd_prefix . ASSIGNMENT_WORD [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
simple_command -> cmd_prefix . cmd_word cmd_suffix [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
simple_command -> cmd_prefix . cmd_word [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
simple_command -> cmd_prefix . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On CLOBBER shift to state 57
-- On ASSIGNMENT_WORD shift to state 124
-- On word shift to state 125
-- On io_redirect shift to state 126
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On cmd_word shift to state 127
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production simple_command -> cmd_prefix

State 124:
## Known stack suffix:
## cmd_prefix ASSIGNMENT_WORD
## LR(1) items:
cmd_prefix -> cmd_prefix ASSIGNMENT_WORD . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cmd_prefix -> cmd_prefix ASSIGNMENT_WORD

State 125:
## Known stack suffix:
## word
## LR(1) items:
cmd_word -> word . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cmd_word -> word

State 126:
## Known stack suffix:
## cmd_prefix io_redirect
## LR(1) items:
cmd_prefix -> cmd_prefix io_redirect . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER ASSIGNMENT_WORD AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cmd_prefix -> cmd_prefix io_redirect

State 127:
## Known stack suffix:
## cmd_prefix cmd_word
## LR(1) items:
simple_command -> cmd_prefix cmd_word . cmd_suffix [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
simple_command -> cmd_prefix cmd_word . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On CLOBBER shift to state 57
-- On word shift to state 128
-- On io_redirect shift to state 129
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On cmd_suffix shift to state 130
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production simple_command -> cmd_prefix cmd_word

State 128:
## Known stack suffix:
## word
## LR(1) items:
cmd_suffix -> word . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cmd_suffix -> word

State 129:
## Known stack suffix:
## io_redirect
## LR(1) items:
cmd_suffix -> io_redirect . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cmd_suffix -> io_redirect

State 130:
## Known stack suffix:
## cmd_prefix cmd_word cmd_suffix
## LR(1) items:
cmd_suffix -> cmd_suffix . io_redirect [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
cmd_suffix -> cmd_suffix . word [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
simple_command -> cmd_prefix cmd_word cmd_suffix . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On CLOBBER shift to state 57
-- On word shift to state 131
-- On io_redirect shift to state 132
-- On io_here shift to state 104
-- On io_file shift to state 105
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production simple_command -> cmd_prefix cmd_word cmd_suffix

State 131:
## Known stack suffix:
## cmd_suffix word
## LR(1) items:
cmd_suffix -> cmd_suffix word . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cmd_suffix -> cmd_suffix word

State 132:
## Known stack suffix:
## cmd_suffix io_redirect
## LR(1) items:
cmd_suffix -> cmd_suffix io_redirect . [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production cmd_suffix -> cmd_suffix io_redirect

State 133:
## Known stack suffix:
## cmd_name
## LR(1) items:
simple_command -> cmd_name . cmd_suffix [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
simple_command -> cmd_name . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On CLOBBER shift to state 57
-- On word shift to state 128
-- On io_redirect shift to state 129
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On cmd_suffix shift to state 134
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production simple_command -> cmd_name

State 134:
## Known stack suffix:
## cmd_name cmd_suffix
## LR(1) items:
cmd_suffix -> cmd_suffix . io_redirect [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
cmd_suffix -> cmd_suffix . word [ WORD Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE NAME LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
simple_command -> cmd_name cmd_suffix . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On CLOBBER shift to state 57
-- On word shift to state 131
-- On io_redirect shift to state 132
-- On io_here shift to state 104
-- On io_file shift to state 105
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production simple_command -> cmd_name cmd_suffix

State 135:
## Known stack suffix:
## command
## LR(1) items:
pipe_sequence -> command . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production pipe_sequence -> command

State 136:
## Known stack suffix:
## linebreak term
## LR(1) items:
compound_list -> linebreak term . [ Then Rparen Rbrace Fi Esac Else Elif Done Do DSEMI ]
compound_list -> linebreak term . separator [ Then Rparen Rbrace Fi Esac Else Elif Done Do DSEMI ]
term -> term . separator and_or [ Uppersand Then Semicolon Rparen Rbrace NEWLINE Fi Esac Else Elif Done Do DSEMI ]
## Transitions:
-- On Uppersand shift to state 137
-- On Semicolon shift to state 138
-- On NEWLINE shift to state 1
-- On separator_op shift to state 139
-- On separator shift to state 141
-- On newline_list shift to state 151
## Reductions:
-- On Then Rparen Rbrace Fi Esac Else Elif Done Do DSEMI
--   reduce production compound_list -> linebreak term

State 137:
## Known stack suffix:
## Uppersand
## LR(1) items:
separator_op -> Uppersand . [ While WORD Until Then Rparen Rbrace NEWLINE NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production separator_op -> Uppersand

State 138:
## Known stack suffix:
## Semicolon
## LR(1) items:
separator_op -> Semicolon . [ While WORD Until Then Rparen Rbrace NEWLINE NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production separator_op -> Semicolon

State 139:
## Known stack suffix:
## separator_op
## LR(1) items:
separator -> separator_op . linebreak [ While WORD Until Then Rparen Rbrace NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 140
## Reductions:
-- On While WORD Until Then Rparen Rbrace NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 140:
## Known stack suffix:
## separator_op linebreak
## LR(1) items:
separator -> separator_op linebreak . [ While WORD Until Then Rparen Rbrace NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production separator -> separator_op linebreak

State 141:
## Known stack suffix:
## linebreak term separator
## LR(1) items:
compound_list -> linebreak term separator . [ Then Rparen Rbrace Fi Esac Else Elif Done Do DSEMI ]
term -> term separator . and_or [ Uppersand Then Semicolon Rparen Rbrace NEWLINE Fi Esac Else Elif Done Do DSEMI ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On Bang shift to state 93
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On pipeline shift to state 142
-- On pipe_sequence shift to state 143
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On command shift to state 135
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On case_clause shift to state 118
-- On brace_group shift to state 119
-- On and_or shift to state 144
## Reductions:
-- On Then Rparen Rbrace Fi Esac Else Elif Done Do DSEMI
--   reduce production compound_list -> linebreak term separator

State 142:
## Known stack suffix:
## pipeline
## LR(1) items:
and_or -> pipeline . [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production and_or -> pipeline

State 143:
## Known stack suffix:
## pipe_sequence
## LR(1) items:
pipe_sequence -> pipe_sequence . Pipe linebreak command [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
pipeline -> pipe_sequence . [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On Pipe shift to state 101
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF
--   reduce production pipeline -> pipe_sequence

State 144:
## Known stack suffix:
## term separator and_or
## LR(1) items:
and_or -> and_or . AND_IF linebreak pipeline [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif Done Do DSEMI AND_IF ]
and_or -> and_or . OR_IF linebreak pipeline [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif Done Do DSEMI AND_IF ]
term -> term separator and_or . [ Uppersand Then Semicolon Rparen Rbrace NEWLINE Fi Esac Else Elif Done Do DSEMI ]
## Transitions:
-- On OR_IF shift to state 145
-- On AND_IF shift to state 148
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace NEWLINE Fi Esac Else Elif Done Do DSEMI
--   reduce production term -> term separator and_or

State 145:
## Known stack suffix:
## and_or OR_IF
## LR(1) items:
and_or -> and_or OR_IF . linebreak pipeline [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 146
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 146:
## Known stack suffix:
## and_or OR_IF linebreak
## LR(1) items:
and_or -> and_or OR_IF linebreak . pipeline [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On Bang shift to state 93
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On pipeline shift to state 147
-- On pipe_sequence shift to state 143
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On command shift to state 135
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On case_clause shift to state 118
-- On brace_group shift to state 119
## Reductions:

State 147:
## Known stack suffix:
## and_or OR_IF linebreak pipeline
## LR(1) items:
and_or -> and_or OR_IF linebreak pipeline . [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production and_or -> and_or OR_IF linebreak pipeline

State 148:
## Known stack suffix:
## and_or AND_IF
## LR(1) items:
and_or -> and_or AND_IF . linebreak pipeline [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 149
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 149:
## Known stack suffix:
## and_or AND_IF linebreak
## LR(1) items:
and_or -> and_or AND_IF linebreak . pipeline [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On Bang shift to state 93
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On pipeline shift to state 150
-- On pipe_sequence shift to state 143
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On command shift to state 135
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On case_clause shift to state 118
-- On brace_group shift to state 119
## Reductions:

State 150:
## Known stack suffix:
## and_or AND_IF linebreak pipeline
## LR(1) items:
and_or -> and_or AND_IF linebreak pipeline . [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif EOF Done Do DSEMI AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production and_or -> and_or AND_IF linebreak pipeline

State 151:
## Known stack suffix:
## newline_list
## LR(1) items:
newline_list -> newline_list . NEWLINE [ While WORD Until Then Rparen Rbrace NEWLINE NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
separator -> newline_list . [ While WORD Until Then Rparen Rbrace NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
## Transitions:
-- On NEWLINE shift to state 5
## Reductions:
-- On While WORD Until Then Rparen Rbrace NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For Fi Esac Else Elif Done Do DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production separator -> newline_list

State 152:
## Known stack suffix:
## and_or
## LR(1) items:
and_or -> and_or . AND_IF linebreak pipeline [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif Done Do DSEMI AND_IF ]
and_or -> and_or . OR_IF linebreak pipeline [ Uppersand Then Semicolon Rparen Rbrace OR_IF NEWLINE Fi Esac Else Elif Done Do DSEMI AND_IF ]
term -> and_or . [ Uppersand Then Semicolon Rparen Rbrace NEWLINE Fi Esac Else Elif Done Do DSEMI ]
## Transitions:
-- On OR_IF shift to state 145
-- On AND_IF shift to state 148
## Reductions:
-- On Uppersand Then Semicolon Rparen Rbrace NEWLINE Fi Esac Else Elif Done Do DSEMI
--   reduce production term -> and_or

State 153:
## Known stack suffix:
## Lparen pattern Rparen compound_list
## LR(1) items:
case_item -> Lparen pattern Rparen compound_list . DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item_ns -> Lparen pattern Rparen compound_list . [ Esac ]
## Transitions:
-- On DSEMI shift to state 154
## Reductions:
-- On Esac
--   reduce production case_item_ns -> Lparen pattern Rparen compound_list

State 154:
## Known stack suffix:
## Lparen pattern Rparen compound_list DSEMI
## LR(1) items:
case_item -> Lparen pattern Rparen compound_list DSEMI . linebreak [ WORD NAME Lparen Esac ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 155
## Reductions:
-- On WORD NAME Lparen Esac
--   reduce production linebreak ->

State 155:
## Known stack suffix:
## Lparen pattern Rparen compound_list DSEMI linebreak
## LR(1) items:
case_item -> Lparen pattern Rparen compound_list DSEMI linebreak . [ WORD NAME Lparen Esac ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_item -> Lparen pattern Rparen compound_list DSEMI linebreak

State 156:
## Known stack suffix:
## pattern Pipe
## LR(1) items:
pattern -> pattern Pipe . word [ Rparen Pipe ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On word shift to state 157
## Reductions:

State 157:
## Known stack suffix:
## pattern Pipe word
## LR(1) items:
pattern -> pattern Pipe word . [ Rparen Pipe ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production pattern -> pattern Pipe word

State 158:
## Known stack suffix:
## Case word linebreak cin linebreak Esac
## LR(1) items:
case_clause -> Case word linebreak cin linebreak Esac . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_clause -> Case word linebreak cin linebreak Esac

State 159:
## Known stack suffix:
## pattern
## LR(1) items:
case_item -> pattern . Rparen linebreak DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item -> pattern . Rparen compound_list DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item_ns -> pattern . Rparen linebreak [ Esac ]
case_item_ns -> pattern . Rparen compound_list [ Esac ]
pattern -> pattern . Pipe word [ Rparen Pipe ]
## Transitions:
-- On Rparen shift to state 160
-- On Pipe shift to state 156
## Reductions:

State 160:
## Known stack suffix:
## pattern Rparen
## LR(1) items:
case_item -> pattern Rparen . linebreak DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item -> pattern Rparen . compound_list DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item_ns -> pattern Rparen . linebreak [ Esac ]
case_item_ns -> pattern Rparen . compound_list [ Esac ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 161
-- On compound_list shift to state 164
## Reductions:
-- On While WORD Until NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For Esac DSEMI DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD
--   reduce production linebreak ->

State 161:
## Known stack suffix:
## pattern Rparen linebreak
## LR(1) items:
case_item -> pattern Rparen linebreak . DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item_ns -> pattern Rparen linebreak . [ Esac ]
compound_list -> linebreak . term [ Esac DSEMI ]
compound_list -> linebreak . term separator [ Esac DSEMI ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DSEMI shift to state 162
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On Bang shift to state 93
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On term shift to state 136
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On pipeline shift to state 142
-- On pipe_sequence shift to state 143
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On command shift to state 135
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On case_clause shift to state 118
-- On brace_group shift to state 119
-- On and_or shift to state 152
## Reductions:
-- On Esac
--   reduce production case_item_ns -> pattern Rparen linebreak

State 162:
## Known stack suffix:
## pattern Rparen linebreak DSEMI
## LR(1) items:
case_item -> pattern Rparen linebreak DSEMI . linebreak [ WORD NAME Lparen Esac ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 163
## Reductions:
-- On WORD NAME Lparen Esac
--   reduce production linebreak ->

State 163:
## Known stack suffix:
## pattern Rparen linebreak DSEMI linebreak
## LR(1) items:
case_item -> pattern Rparen linebreak DSEMI linebreak . [ WORD NAME Lparen Esac ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_item -> pattern Rparen linebreak DSEMI linebreak

State 164:
## Known stack suffix:
## pattern Rparen compound_list
## LR(1) items:
case_item -> pattern Rparen compound_list . DSEMI linebreak [ WORD NAME Lparen Esac ]
case_item_ns -> pattern Rparen compound_list . [ Esac ]
## Transitions:
-- On DSEMI shift to state 165
## Reductions:
-- On Esac
--   reduce production case_item_ns -> pattern Rparen compound_list

State 165:
## Known stack suffix:
## pattern Rparen compound_list DSEMI
## LR(1) items:
case_item -> pattern Rparen compound_list DSEMI . linebreak [ WORD NAME Lparen Esac ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 4
-- On linebreak shift to state 166
## Reductions:
-- On WORD NAME Lparen Esac
--   reduce production linebreak ->

State 166:
## Known stack suffix:
## pattern Rparen compound_list DSEMI linebreak
## LR(1) items:
case_item -> pattern Rparen compound_list DSEMI linebreak . [ WORD NAME Lparen Esac ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_item -> pattern Rparen compound_list DSEMI linebreak

State 167:
## Known stack suffix:
## Case word linebreak cin linebreak case_list_ns
## LR(1) items:
case_clause -> Case word linebreak cin linebreak case_list_ns . Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Esac shift to state 168
## Reductions:

State 168:
## Known stack suffix:
## Case word linebreak cin linebreak case_list_ns Esac
## LR(1) items:
case_clause -> Case word linebreak cin linebreak case_list_ns Esac . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_clause -> Case word linebreak cin linebreak case_list_ns Esac

State 169:
## Known stack suffix:
## Case word linebreak cin linebreak case_list
## LR(1) items:
case_clause -> Case word linebreak cin linebreak case_list . Esac [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
case_list -> case_list . case_item [ WORD NAME Lparen Esac ]
case_list_ns -> case_list . case_item_ns [ Esac ]
## Transitions:
-- On WORD shift to state 9
-- On NAME shift to state 24
-- On Lparen shift to state 86
-- On Esac shift to state 170
-- On word shift to state 87
-- On pattern shift to state 159
-- On case_item_ns shift to state 171
-- On case_item shift to state 172
## Reductions:

State 170:
## Known stack suffix:
## Case word linebreak cin linebreak case_list Esac
## LR(1) items:
case_clause -> Case word linebreak cin linebreak case_list Esac . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_clause -> Case word linebreak cin linebreak case_list Esac

State 171:
## Known stack suffix:
## case_list case_item_ns
## LR(1) items:
case_list_ns -> case_list case_item_ns . [ Esac ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_list_ns -> case_list case_item_ns

State 172:
## Known stack suffix:
## case_list case_item
## LR(1) items:
case_list -> case_list case_item . [ WORD NAME Lparen Esac ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_list -> case_list case_item

State 173:
## Known stack suffix:
## case_item_ns
## LR(1) items:
case_list_ns -> case_item_ns . [ Esac ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_list_ns -> case_item_ns

State 174:
## Known stack suffix:
## case_item
## LR(1) items:
case_list -> case_item . [ WORD NAME Lparen Esac ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production case_list -> case_item

State 175:
## Known stack suffix:
## While compound_list
## LR(1) items:
while_clause -> While compound_list . do_group [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
-- On Do shift to state 12
-- On do_group shift to state 176
## Reductions:

State 176:
## Known stack suffix:
## While compound_list do_group
## LR(1) items:
while_clause -> While compound_list do_group . [ Uppersand Then Semicolon Rparen Rbrace Pipe OR_IF NEWLINE LESSGREAT LESSAND LESS IO_NUMBER GREATAND GREAT Fi Esac Else Elif EOF Done Do DSEMI DLESSDASH DLESS DGREAT CLOBBER AND_IF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production while_clause -> While compound_list do_group

State 177:
## Known stack suffix:
## linebreak complete_commands
## LR(1) items:
complete_commands -> complete_commands . newline_list complete_command [ NEWLINE EOF ]
program -> linebreak complete_commands . linebreak [ EOF ]
## Transitions:
-- On NEWLINE shift to state 1
-- On newline_list shift to state 178
-- On linebreak shift to state 184
## Reductions:
-- On EOF
--   reduce production linebreak ->

State 178:
## Known stack suffix:
## complete_commands newline_list
## LR(1) items:
complete_commands -> complete_commands newline_list . complete_command [ NEWLINE EOF ]
linebreak -> newline_list . [ EOF ]
newline_list -> newline_list . NEWLINE [ While WORD Until NEWLINE NAME Lparen Lbrace LESSGREAT LESSAND LESS If IO_NUMBER GREATAND GREAT For EOF DLESSDASH DLESS DGREAT Case CLOBBER Bang ASSIGNMENT_WORD ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NEWLINE shift to state 5
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On Bang shift to state 93
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On pipeline shift to state 142
-- On pipe_sequence shift to state 143
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On complete_command shift to state 179
-- On command shift to state 135
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On clist shift to state 180
-- On case_clause shift to state 118
-- On brace_group shift to state 119
-- On and_or shift to state 183
## Reductions:
-- On EOF
--   reduce production linebreak -> newline_list

State 179:
## Known stack suffix:
## complete_commands newline_list complete_command
## LR(1) items:
complete_commands -> complete_commands newline_list complete_command . [ NEWLINE EOF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production complete_commands -> complete_commands newline_list complete_command

State 180:
## Known stack suffix:
## clist
## LR(1) items:
clist -> clist . separator_op and_or [ Uppersand Semicolon NEWLINE EOF ]
complete_command -> clist . separator_op [ NEWLINE EOF ]
complete_command -> clist . [ NEWLINE EOF ]
## Transitions:
-- On Uppersand shift to state 137
-- On Semicolon shift to state 138
-- On separator_op shift to state 181
## Reductions:
-- On NEWLINE EOF
--   reduce production complete_command -> clist

State 181:
## Known stack suffix:
## clist separator_op
## LR(1) items:
clist -> clist separator_op . and_or [ Uppersand Semicolon NEWLINE EOF ]
complete_command -> clist separator_op . [ NEWLINE EOF ]
## Transitions:
-- On While shift to state 7
-- On WORD shift to state 9
-- On Until shift to state 10
-- On NAME shift to state 16
-- On Lparen shift to state 17
-- On Lbrace shift to state 20
-- On LESSGREAT shift to state 23
-- On LESSAND shift to state 27
-- On LESS shift to state 29
-- On If shift to state 31
-- On IO_NUMBER shift to state 45
-- On GREATAND shift to state 46
-- On GREAT shift to state 48
-- On For shift to state 61
-- On DLESSDASH shift to state 50
-- On DLESS shift to state 53
-- On DGREAT shift to state 55
-- On Case shift to state 81
-- On CLOBBER shift to state 57
-- On Bang shift to state 93
-- On ASSIGNMENT_WORD shift to state 94
-- On word shift to state 95
-- On while_clause shift to state 96
-- On until_clause shift to state 97
-- On subshell shift to state 98
-- On simple_command shift to state 99
-- On pipeline shift to state 142
-- On pipe_sequence shift to state 143
-- On io_redirect shift to state 103
-- On io_here shift to state 104
-- On io_file shift to state 105
-- On if_clause shift to state 106
-- On function_definition shift to state 107
-- On for_clause shift to state 108
-- On fname shift to state 109
-- On compound_command shift to state 120
-- On command shift to state 135
-- On cmd_prefix shift to state 123
-- On cmd_name shift to state 133
-- On case_clause shift to state 118
-- On brace_group shift to state 119
-- On and_or shift to state 182
## Reductions:
-- On NEWLINE EOF
--   reduce production complete_command -> clist separator_op

State 182:
## Known stack suffix:
## clist separator_op and_or
## LR(1) items:
and_or -> and_or . AND_IF linebreak pipeline [ Uppersand Semicolon OR_IF NEWLINE EOF AND_IF ]
and_or -> and_or . OR_IF linebreak pipeline [ Uppersand Semicolon OR_IF NEWLINE EOF AND_IF ]
clist -> clist separator_op and_or . [ Uppersand Semicolon NEWLINE EOF ]
## Transitions:
-- On OR_IF shift to state 145
-- On AND_IF shift to state 148
## Reductions:
-- On Uppersand Semicolon NEWLINE EOF
--   reduce production clist -> clist separator_op and_or

State 183:
## Known stack suffix:
## and_or
## LR(1) items:
and_or -> and_or . AND_IF linebreak pipeline [ Uppersand Semicolon OR_IF NEWLINE EOF AND_IF ]
and_or -> and_or . OR_IF linebreak pipeline [ Uppersand Semicolon OR_IF NEWLINE EOF AND_IF ]
clist -> and_or . [ Uppersand Semicolon NEWLINE EOF ]
## Transitions:
-- On OR_IF shift to state 145
-- On AND_IF shift to state 148
## Reductions:
-- On Uppersand Semicolon NEWLINE EOF
--   reduce production clist -> and_or

State 184:
## Known stack suffix:
## linebreak complete_commands linebreak
## LR(1) items:
program -> linebreak complete_commands linebreak . [ EOF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production program -> linebreak complete_commands linebreak

State 185:
## Known stack suffix:
## complete_command
## LR(1) items:
complete_commands -> complete_command . [ NEWLINE EOF ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production complete_commands -> complete_command

State 186:
## Known stack suffix:
## entry_point
## LR(1) items:
entry_point' -> entry_point . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, accept entry_point

State 187:
## Known stack suffix:
##
## LR(1) items:
intended_error' -> . intended_error [ # ]
## Transitions:
-- On INTENDED_ERROR shift to state 188
-- On intended_error shift to state 189
## Reductions:

State 188:
## Known stack suffix:
## INTENDED_ERROR
## LR(1) items:
intended_error -> INTENDED_ERROR . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production intended_error -> INTENDED_ERROR

State 189:
## Known stack suffix:
## intended_error
## LR(1) items:
intended_error' -> intended_error . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, accept intended_error

