State 0:
## Known stack suffix:
##
## LR(1) items:
main' -> . main [ # ]
## Transitions:
-- On T shift to state 1
-- On main shift to state 3
## Reductions:

State 1:
## Known stack suffix:
## T
## LR(1) items:
main -> T . U [ # ]
## Transitions:
-- On U shift to state 2
## Reductions:

State 2:
## Known stack suffix:
## T U
## LR(1) items:
main -> T U . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production main -> T U

State 3:
## Known stack suffix:
## main
## LR(1) items:
main' -> main . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, accept main

