State 0:
main' -> . main [ # ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On EOF shift to state 119
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 120
-- On string shift to state 80
-- On main shift to state 122

State 1:
text_element -> VERB . string END_VERB [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 4

State 2:
string -> Char . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITEM ITALIC INDEX_LIST EXC_REF EOF ENUM END_VERB END_SHORTCUT_LIST END_LATEX END_CODE_PRE END_CODE END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
string -> Char . string [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITEM ITALIC INDEX_LIST EXC_REF EOF ENUM END_VERB END_SHORTCUT_LIST END_LATEX END_CODE_PRE END_CODE END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 3
-- On VERB reduce production string -> Char
-- On VAL_REF reduce production string -> Char
-- On Title reduce production string -> Char
-- On TYP_REF reduce production string -> Char
-- On SUPERSCRIPT reduce production string -> Char
-- On SUBSCRIPT reduce production string -> Char
-- On SHORTCUT_LIST_ITEM reduce production string -> Char
-- On SHORTCUT_ENUM_ITEM reduce production string -> Char
-- On SEC_REF reduce production string -> Char
-- On RIGHT reduce production string -> Char
-- On MOD_REF reduce production string -> Char
-- On MOD_LIST_REF reduce production string -> Char
-- On MODT_REF reduce production string -> Char
-- On MET_REF reduce production string -> Char
-- On LIST reduce production string -> Char
-- On LINK reduce production string -> Char
-- On LEFT reduce production string -> Char
-- On LATEX reduce production string -> Char
-- On ITEM reduce production string -> Char
-- On ITALIC reduce production string -> Char
-- On INDEX_LIST reduce production string -> Char
-- On EXC_REF reduce production string -> Char
-- On EOF reduce production string -> Char
-- On ENUM reduce production string -> Char
-- On END_VERB reduce production string -> Char
-- On END_SHORTCUT_LIST reduce production string -> Char
-- On END_LATEX reduce production string -> Char
-- On END_CODE_PRE reduce production string -> Char
-- On END_CODE reduce production string -> Char
-- On END reduce production string -> Char
-- On EMP reduce production string -> Char
-- On ELE_REF reduce production string -> Char
-- On CODE_PRE reduce production string -> Char
-- On CODE reduce production string -> Char
-- On CLT_REF reduce production string -> Char
-- On CLA_REF reduce production string -> Char
-- On CENTER reduce production string -> Char
-- On BOLD reduce production string -> Char
-- On BLANK_LINE reduce production string -> Char
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production string -> Char
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production string -> Char
-- On ATT_REF reduce production string -> Char

State 3:
string -> Char string . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITEM ITALIC INDEX_LIST EXC_REF EOF ENUM END_VERB END_SHORTCUT_LIST END_LATEX END_CODE_PRE END_CODE END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production string -> Char string
-- On VAL_REF reduce production string -> Char string
-- On Title reduce production string -> Char string
-- On TYP_REF reduce production string -> Char string
-- On SUPERSCRIPT reduce production string -> Char string
-- On SUBSCRIPT reduce production string -> Char string
-- On SHORTCUT_LIST_ITEM reduce production string -> Char string
-- On SHORTCUT_ENUM_ITEM reduce production string -> Char string
-- On SEC_REF reduce production string -> Char string
-- On RIGHT reduce production string -> Char string
-- On MOD_REF reduce production string -> Char string
-- On MOD_LIST_REF reduce production string -> Char string
-- On MODT_REF reduce production string -> Char string
-- On MET_REF reduce production string -> Char string
-- On LIST reduce production string -> Char string
-- On LINK reduce production string -> Char string
-- On LEFT reduce production string -> Char string
-- On LATEX reduce production string -> Char string
-- On ITEM reduce production string -> Char string
-- On ITALIC reduce production string -> Char string
-- On INDEX_LIST reduce production string -> Char string
-- On EXC_REF reduce production string -> Char string
-- On EOF reduce production string -> Char string
-- On ENUM reduce production string -> Char string
-- On END_VERB reduce production string -> Char string
-- On END_SHORTCUT_LIST reduce production string -> Char string
-- On END_LATEX reduce production string -> Char string
-- On END_CODE_PRE reduce production string -> Char string
-- On END_CODE reduce production string -> Char string
-- On END reduce production string -> Char string
-- On EMP reduce production string -> Char string
-- On ELE_REF reduce production string -> Char string
-- On Char reduce production string -> Char string
-- On CODE_PRE reduce production string -> Char string
-- On CODE reduce production string -> Char string
-- On CLT_REF reduce production string -> Char string
-- On CLA_REF reduce production string -> Char string
-- On CENTER reduce production string -> Char string
-- On BOLD reduce production string -> Char string
-- On BLANK_LINE reduce production string -> Char string
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production string -> Char string
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production string -> Char string
-- On ATT_REF reduce production string -> Char string

State 4:
text_element -> VERB string . END_VERB [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END_VERB shift to state 5

State 5:
text_element -> VERB string END_VERB . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> VERB string END_VERB
-- On VAL_REF reduce production text_element -> VERB string END_VERB
-- On Title reduce production text_element -> VERB string END_VERB
-- On TYP_REF reduce production text_element -> VERB string END_VERB
-- On SUPERSCRIPT reduce production text_element -> VERB string END_VERB
-- On SUBSCRIPT reduce production text_element -> VERB string END_VERB
-- On SHORTCUT_LIST_ITEM reduce production text_element -> VERB string END_VERB
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> VERB string END_VERB
-- On SEC_REF reduce production text_element -> VERB string END_VERB
-- On RIGHT reduce production text_element -> VERB string END_VERB
-- On MOD_REF reduce production text_element -> VERB string END_VERB
-- On MOD_LIST_REF reduce production text_element -> VERB string END_VERB
-- On MODT_REF reduce production text_element -> VERB string END_VERB
-- On MET_REF reduce production text_element -> VERB string END_VERB
-- On LIST reduce production text_element -> VERB string END_VERB
-- On LINK reduce production text_element -> VERB string END_VERB
-- On LEFT reduce production text_element -> VERB string END_VERB
-- On LATEX reduce production text_element -> VERB string END_VERB
-- On ITALIC reduce production text_element -> VERB string END_VERB
-- On INDEX_LIST reduce production text_element -> VERB string END_VERB
-- On EXC_REF reduce production text_element -> VERB string END_VERB
-- On EOF reduce production text_element -> VERB string END_VERB
-- On ENUM reduce production text_element -> VERB string END_VERB
-- On END_SHORTCUT_LIST reduce production text_element -> VERB string END_VERB
-- On END reduce production text_element -> VERB string END_VERB
-- On EMP reduce production text_element -> VERB string END_VERB
-- On ELE_REF reduce production text_element -> VERB string END_VERB
-- On Char reduce production text_element -> VERB string END_VERB
-- On CODE_PRE reduce production text_element -> VERB string END_VERB
-- On CODE reduce production text_element -> VERB string END_VERB
-- On CLT_REF reduce production text_element -> VERB string END_VERB
-- On CLA_REF reduce production text_element -> VERB string END_VERB
-- On CENTER reduce production text_element -> VERB string END_VERB
-- On BOLD reduce production text_element -> VERB string END_VERB
-- On BLANK_LINE reduce production text_element -> VERB string END_VERB
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> VERB string END_VERB
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> VERB string END_VERB
-- On ATT_REF reduce production text_element -> VERB string END_VERB

State 6:
text_element -> VAL_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 7

State 7:
text_element -> VAL_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 8

State 8:
text_element -> VAL_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> VAL_REF string END
-- On VAL_REF reduce production text_element -> VAL_REF string END
-- On Title reduce production text_element -> VAL_REF string END
-- On TYP_REF reduce production text_element -> VAL_REF string END
-- On SUPERSCRIPT reduce production text_element -> VAL_REF string END
-- On SUBSCRIPT reduce production text_element -> VAL_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> VAL_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> VAL_REF string END
-- On SEC_REF reduce production text_element -> VAL_REF string END
-- On RIGHT reduce production text_element -> VAL_REF string END
-- On MOD_REF reduce production text_element -> VAL_REF string END
-- On MOD_LIST_REF reduce production text_element -> VAL_REF string END
-- On MODT_REF reduce production text_element -> VAL_REF string END
-- On MET_REF reduce production text_element -> VAL_REF string END
-- On LIST reduce production text_element -> VAL_REF string END
-- On LINK reduce production text_element -> VAL_REF string END
-- On LEFT reduce production text_element -> VAL_REF string END
-- On LATEX reduce production text_element -> VAL_REF string END
-- On ITALIC reduce production text_element -> VAL_REF string END
-- On INDEX_LIST reduce production text_element -> VAL_REF string END
-- On EXC_REF reduce production text_element -> VAL_REF string END
-- On EOF reduce production text_element -> VAL_REF string END
-- On ENUM reduce production text_element -> VAL_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> VAL_REF string END
-- On END reduce production text_element -> VAL_REF string END
-- On EMP reduce production text_element -> VAL_REF string END
-- On ELE_REF reduce production text_element -> VAL_REF string END
-- On Char reduce production text_element -> VAL_REF string END
-- On CODE_PRE reduce production text_element -> VAL_REF string END
-- On CODE reduce production text_element -> VAL_REF string END
-- On CLT_REF reduce production text_element -> VAL_REF string END
-- On CLA_REF reduce production text_element -> VAL_REF string END
-- On CENTER reduce production text_element -> VAL_REF string END
-- On BOLD reduce production text_element -> VAL_REF string END
-- On BLANK_LINE reduce production text_element -> VAL_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> VAL_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> VAL_REF string END
-- On ATT_REF reduce production text_element -> VAL_REF string END

State 9:
text_element -> Title . text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 117
-- On string shift to state 80

State 10:
text_element -> TYP_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 11

State 11:
text_element -> TYP_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 12

State 12:
text_element -> TYP_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> TYP_REF string END
-- On VAL_REF reduce production text_element -> TYP_REF string END
-- On Title reduce production text_element -> TYP_REF string END
-- On TYP_REF reduce production text_element -> TYP_REF string END
-- On SUPERSCRIPT reduce production text_element -> TYP_REF string END
-- On SUBSCRIPT reduce production text_element -> TYP_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> TYP_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> TYP_REF string END
-- On SEC_REF reduce production text_element -> TYP_REF string END
-- On RIGHT reduce production text_element -> TYP_REF string END
-- On MOD_REF reduce production text_element -> TYP_REF string END
-- On MOD_LIST_REF reduce production text_element -> TYP_REF string END
-- On MODT_REF reduce production text_element -> TYP_REF string END
-- On MET_REF reduce production text_element -> TYP_REF string END
-- On LIST reduce production text_element -> TYP_REF string END
-- On LINK reduce production text_element -> TYP_REF string END
-- On LEFT reduce production text_element -> TYP_REF string END
-- On LATEX reduce production text_element -> TYP_REF string END
-- On ITALIC reduce production text_element -> TYP_REF string END
-- On INDEX_LIST reduce production text_element -> TYP_REF string END
-- On EXC_REF reduce production text_element -> TYP_REF string END
-- On EOF reduce production text_element -> TYP_REF string END
-- On ENUM reduce production text_element -> TYP_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> TYP_REF string END
-- On END reduce production text_element -> TYP_REF string END
-- On EMP reduce production text_element -> TYP_REF string END
-- On ELE_REF reduce production text_element -> TYP_REF string END
-- On Char reduce production text_element -> TYP_REF string END
-- On CODE_PRE reduce production text_element -> TYP_REF string END
-- On CODE reduce production text_element -> TYP_REF string END
-- On CLT_REF reduce production text_element -> TYP_REF string END
-- On CLA_REF reduce production text_element -> TYP_REF string END
-- On CENTER reduce production text_element -> TYP_REF string END
-- On BOLD reduce production text_element -> TYP_REF string END
-- On BLANK_LINE reduce production text_element -> TYP_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> TYP_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> TYP_REF string END
-- On ATT_REF reduce production text_element -> TYP_REF string END

State 13:
text_element -> SUPERSCRIPT . text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 115
-- On string shift to state 80

State 14:
text_element -> SUBSCRIPT . text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 113
-- On string shift to state 80

State 15:
text_element -> SEC_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 16

State 16:
text_element -> SEC_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 17

State 17:
text_element -> SEC_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> SEC_REF string END
-- On VAL_REF reduce production text_element -> SEC_REF string END
-- On Title reduce production text_element -> SEC_REF string END
-- On TYP_REF reduce production text_element -> SEC_REF string END
-- On SUPERSCRIPT reduce production text_element -> SEC_REF string END
-- On SUBSCRIPT reduce production text_element -> SEC_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> SEC_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> SEC_REF string END
-- On SEC_REF reduce production text_element -> SEC_REF string END
-- On RIGHT reduce production text_element -> SEC_REF string END
-- On MOD_REF reduce production text_element -> SEC_REF string END
-- On MOD_LIST_REF reduce production text_element -> SEC_REF string END
-- On MODT_REF reduce production text_element -> SEC_REF string END
-- On MET_REF reduce production text_element -> SEC_REF string END
-- On LIST reduce production text_element -> SEC_REF string END
-- On LINK reduce production text_element -> SEC_REF string END
-- On LEFT reduce production text_element -> SEC_REF string END
-- On LATEX reduce production text_element -> SEC_REF string END
-- On ITALIC reduce production text_element -> SEC_REF string END
-- On INDEX_LIST reduce production text_element -> SEC_REF string END
-- On EXC_REF reduce production text_element -> SEC_REF string END
-- On EOF reduce production text_element -> SEC_REF string END
-- On ENUM reduce production text_element -> SEC_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> SEC_REF string END
-- On END reduce production text_element -> SEC_REF string END
-- On EMP reduce production text_element -> SEC_REF string END
-- On ELE_REF reduce production text_element -> SEC_REF string END
-- On Char reduce production text_element -> SEC_REF string END
-- On CODE_PRE reduce production text_element -> SEC_REF string END
-- On CODE reduce production text_element -> SEC_REF string END
-- On CLT_REF reduce production text_element -> SEC_REF string END
-- On CLA_REF reduce production text_element -> SEC_REF string END
-- On CENTER reduce production text_element -> SEC_REF string END
-- On BOLD reduce production text_element -> SEC_REF string END
-- On BLANK_LINE reduce production text_element -> SEC_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> SEC_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> SEC_REF string END
-- On ATT_REF reduce production text_element -> SEC_REF string END

State 18:
text_element -> RIGHT . text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 111
-- On string shift to state 80

State 19:
text_element -> MOD_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 20

State 20:
text_element -> MOD_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 21

State 21:
text_element -> MOD_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> MOD_REF string END
-- On VAL_REF reduce production text_element -> MOD_REF string END
-- On Title reduce production text_element -> MOD_REF string END
-- On TYP_REF reduce production text_element -> MOD_REF string END
-- On SUPERSCRIPT reduce production text_element -> MOD_REF string END
-- On SUBSCRIPT reduce production text_element -> MOD_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> MOD_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> MOD_REF string END
-- On SEC_REF reduce production text_element -> MOD_REF string END
-- On RIGHT reduce production text_element -> MOD_REF string END
-- On MOD_REF reduce production text_element -> MOD_REF string END
-- On MOD_LIST_REF reduce production text_element -> MOD_REF string END
-- On MODT_REF reduce production text_element -> MOD_REF string END
-- On MET_REF reduce production text_element -> MOD_REF string END
-- On LIST reduce production text_element -> MOD_REF string END
-- On LINK reduce production text_element -> MOD_REF string END
-- On LEFT reduce production text_element -> MOD_REF string END
-- On LATEX reduce production text_element -> MOD_REF string END
-- On ITALIC reduce production text_element -> MOD_REF string END
-- On INDEX_LIST reduce production text_element -> MOD_REF string END
-- On EXC_REF reduce production text_element -> MOD_REF string END
-- On EOF reduce production text_element -> MOD_REF string END
-- On ENUM reduce production text_element -> MOD_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> MOD_REF string END
-- On END reduce production text_element -> MOD_REF string END
-- On EMP reduce production text_element -> MOD_REF string END
-- On ELE_REF reduce production text_element -> MOD_REF string END
-- On Char reduce production text_element -> MOD_REF string END
-- On CODE_PRE reduce production text_element -> MOD_REF string END
-- On CODE reduce production text_element -> MOD_REF string END
-- On CLT_REF reduce production text_element -> MOD_REF string END
-- On CLA_REF reduce production text_element -> MOD_REF string END
-- On CENTER reduce production text_element -> MOD_REF string END
-- On BOLD reduce production text_element -> MOD_REF string END
-- On BLANK_LINE reduce production text_element -> MOD_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> MOD_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> MOD_REF string END
-- On ATT_REF reduce production text_element -> MOD_REF string END

State 22:
text_element -> MOD_LIST_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 23

State 23:
text_element -> MOD_LIST_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 24

State 24:
text_element -> MOD_LIST_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> MOD_LIST_REF string END
-- On VAL_REF reduce production text_element -> MOD_LIST_REF string END
-- On Title reduce production text_element -> MOD_LIST_REF string END
-- On TYP_REF reduce production text_element -> MOD_LIST_REF string END
-- On SUPERSCRIPT reduce production text_element -> MOD_LIST_REF string END
-- On SUBSCRIPT reduce production text_element -> MOD_LIST_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> MOD_LIST_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> MOD_LIST_REF string END
-- On SEC_REF reduce production text_element -> MOD_LIST_REF string END
-- On RIGHT reduce production text_element -> MOD_LIST_REF string END
-- On MOD_REF reduce production text_element -> MOD_LIST_REF string END
-- On MOD_LIST_REF reduce production text_element -> MOD_LIST_REF string END
-- On MODT_REF reduce production text_element -> MOD_LIST_REF string END
-- On MET_REF reduce production text_element -> MOD_LIST_REF string END
-- On LIST reduce production text_element -> MOD_LIST_REF string END
-- On LINK reduce production text_element -> MOD_LIST_REF string END
-- On LEFT reduce production text_element -> MOD_LIST_REF string END
-- On LATEX reduce production text_element -> MOD_LIST_REF string END
-- On ITALIC reduce production text_element -> MOD_LIST_REF string END
-- On INDEX_LIST reduce production text_element -> MOD_LIST_REF string END
-- On EXC_REF reduce production text_element -> MOD_LIST_REF string END
-- On EOF reduce production text_element -> MOD_LIST_REF string END
-- On ENUM reduce production text_element -> MOD_LIST_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> MOD_LIST_REF string END
-- On END reduce production text_element -> MOD_LIST_REF string END
-- On EMP reduce production text_element -> MOD_LIST_REF string END
-- On ELE_REF reduce production text_element -> MOD_LIST_REF string END
-- On Char reduce production text_element -> MOD_LIST_REF string END
-- On CODE_PRE reduce production text_element -> MOD_LIST_REF string END
-- On CODE reduce production text_element -> MOD_LIST_REF string END
-- On CLT_REF reduce production text_element -> MOD_LIST_REF string END
-- On CLA_REF reduce production text_element -> MOD_LIST_REF string END
-- On CENTER reduce production text_element -> MOD_LIST_REF string END
-- On BOLD reduce production text_element -> MOD_LIST_REF string END
-- On BLANK_LINE reduce production text_element -> MOD_LIST_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> MOD_LIST_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> MOD_LIST_REF string END
-- On ATT_REF reduce production text_element -> MOD_LIST_REF string END

State 25:
text_element -> MODT_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 26

State 26:
text_element -> MODT_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 27

State 27:
text_element -> MODT_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> MODT_REF string END
-- On VAL_REF reduce production text_element -> MODT_REF string END
-- On Title reduce production text_element -> MODT_REF string END
-- On TYP_REF reduce production text_element -> MODT_REF string END
-- On SUPERSCRIPT reduce production text_element -> MODT_REF string END
-- On SUBSCRIPT reduce production text_element -> MODT_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> MODT_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> MODT_REF string END
-- On SEC_REF reduce production text_element -> MODT_REF string END
-- On RIGHT reduce production text_element -> MODT_REF string END
-- On MOD_REF reduce production text_element -> MODT_REF string END
-- On MOD_LIST_REF reduce production text_element -> MODT_REF string END
-- On MODT_REF reduce production text_element -> MODT_REF string END
-- On MET_REF reduce production text_element -> MODT_REF string END
-- On LIST reduce production text_element -> MODT_REF string END
-- On LINK reduce production text_element -> MODT_REF string END
-- On LEFT reduce production text_element -> MODT_REF string END
-- On LATEX reduce production text_element -> MODT_REF string END
-- On ITALIC reduce production text_element -> MODT_REF string END
-- On INDEX_LIST reduce production text_element -> MODT_REF string END
-- On EXC_REF reduce production text_element -> MODT_REF string END
-- On EOF reduce production text_element -> MODT_REF string END
-- On ENUM reduce production text_element -> MODT_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> MODT_REF string END
-- On END reduce production text_element -> MODT_REF string END
-- On EMP reduce production text_element -> MODT_REF string END
-- On ELE_REF reduce production text_element -> MODT_REF string END
-- On Char reduce production text_element -> MODT_REF string END
-- On CODE_PRE reduce production text_element -> MODT_REF string END
-- On CODE reduce production text_element -> MODT_REF string END
-- On CLT_REF reduce production text_element -> MODT_REF string END
-- On CLA_REF reduce production text_element -> MODT_REF string END
-- On CENTER reduce production text_element -> MODT_REF string END
-- On BOLD reduce production text_element -> MODT_REF string END
-- On BLANK_LINE reduce production text_element -> MODT_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> MODT_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> MODT_REF string END
-- On ATT_REF reduce production text_element -> MODT_REF string END

State 28:
text_element -> MET_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 29

State 29:
text_element -> MET_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 30

State 30:
text_element -> MET_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> MET_REF string END
-- On VAL_REF reduce production text_element -> MET_REF string END
-- On Title reduce production text_element -> MET_REF string END
-- On TYP_REF reduce production text_element -> MET_REF string END
-- On SUPERSCRIPT reduce production text_element -> MET_REF string END
-- On SUBSCRIPT reduce production text_element -> MET_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> MET_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> MET_REF string END
-- On SEC_REF reduce production text_element -> MET_REF string END
-- On RIGHT reduce production text_element -> MET_REF string END
-- On MOD_REF reduce production text_element -> MET_REF string END
-- On MOD_LIST_REF reduce production text_element -> MET_REF string END
-- On MODT_REF reduce production text_element -> MET_REF string END
-- On MET_REF reduce production text_element -> MET_REF string END
-- On LIST reduce production text_element -> MET_REF string END
-- On LINK reduce production text_element -> MET_REF string END
-- On LEFT reduce production text_element -> MET_REF string END
-- On LATEX reduce production text_element -> MET_REF string END
-- On ITALIC reduce production text_element -> MET_REF string END
-- On INDEX_LIST reduce production text_element -> MET_REF string END
-- On EXC_REF reduce production text_element -> MET_REF string END
-- On EOF reduce production text_element -> MET_REF string END
-- On ENUM reduce production text_element -> MET_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> MET_REF string END
-- On END reduce production text_element -> MET_REF string END
-- On EMP reduce production text_element -> MET_REF string END
-- On ELE_REF reduce production text_element -> MET_REF string END
-- On Char reduce production text_element -> MET_REF string END
-- On CODE_PRE reduce production text_element -> MET_REF string END
-- On CODE reduce production text_element -> MET_REF string END
-- On CLT_REF reduce production text_element -> MET_REF string END
-- On CLA_REF reduce production text_element -> MET_REF string END
-- On CENTER reduce production text_element -> MET_REF string END
-- On BOLD reduce production text_element -> MET_REF string END
-- On BLANK_LINE reduce production text_element -> MET_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> MET_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> MET_REF string END
-- On ATT_REF reduce production text_element -> MET_REF string END

State 31:
text_element -> LIST . ocamldoc_odoc_text_list END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On ITEM shift to state 32
-- On Char shift to state 2
-- On string shift to state 46
-- On ocamldoc_odoc_text_list shift to state 109
-- On item shift to state 49

State 32:
item -> ITEM . text END [ ITEM END Char ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 107
-- On string shift to state 80

State 33:
text_element -> LINK . string END text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 34

State 34:
text_element -> LINK string . END text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 35

State 35:
text_element -> LINK string END . text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 105
-- On string shift to state 80

State 36:
text_element -> LEFT . text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 103
-- On string shift to state 80

State 37:
text_element -> LATEX . string END_LATEX [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 38

State 38:
text_element -> LATEX string . END_LATEX [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END_LATEX shift to state 39

State 39:
text_element -> LATEX string END_LATEX . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> LATEX string END_LATEX
-- On VAL_REF reduce production text_element -> LATEX string END_LATEX
-- On Title reduce production text_element -> LATEX string END_LATEX
-- On TYP_REF reduce production text_element -> LATEX string END_LATEX
-- On SUPERSCRIPT reduce production text_element -> LATEX string END_LATEX
-- On SUBSCRIPT reduce production text_element -> LATEX string END_LATEX
-- On SHORTCUT_LIST_ITEM reduce production text_element -> LATEX string END_LATEX
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> LATEX string END_LATEX
-- On SEC_REF reduce production text_element -> LATEX string END_LATEX
-- On RIGHT reduce production text_element -> LATEX string END_LATEX
-- On MOD_REF reduce production text_element -> LATEX string END_LATEX
-- On MOD_LIST_REF reduce production text_element -> LATEX string END_LATEX
-- On MODT_REF reduce production text_element -> LATEX string END_LATEX
-- On MET_REF reduce production text_element -> LATEX string END_LATEX
-- On LIST reduce production text_element -> LATEX string END_LATEX
-- On LINK reduce production text_element -> LATEX string END_LATEX
-- On LEFT reduce production text_element -> LATEX string END_LATEX
-- On LATEX reduce production text_element -> LATEX string END_LATEX
-- On ITALIC reduce production text_element -> LATEX string END_LATEX
-- On INDEX_LIST reduce production text_element -> LATEX string END_LATEX
-- On EXC_REF reduce production text_element -> LATEX string END_LATEX
-- On EOF reduce production text_element -> LATEX string END_LATEX
-- On ENUM reduce production text_element -> LATEX string END_LATEX
-- On END_SHORTCUT_LIST reduce production text_element -> LATEX string END_LATEX
-- On END reduce production text_element -> LATEX string END_LATEX
-- On EMP reduce production text_element -> LATEX string END_LATEX
-- On ELE_REF reduce production text_element -> LATEX string END_LATEX
-- On Char reduce production text_element -> LATEX string END_LATEX
-- On CODE_PRE reduce production text_element -> LATEX string END_LATEX
-- On CODE reduce production text_element -> LATEX string END_LATEX
-- On CLT_REF reduce production text_element -> LATEX string END_LATEX
-- On CLA_REF reduce production text_element -> LATEX string END_LATEX
-- On CENTER reduce production text_element -> LATEX string END_LATEX
-- On BOLD reduce production text_element -> LATEX string END_LATEX
-- On BLANK_LINE reduce production text_element -> LATEX string END_LATEX
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> LATEX string END_LATEX
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> LATEX string END_LATEX
-- On ATT_REF reduce production text_element -> LATEX string END_LATEX

State 40:
text_element -> ITALIC . text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 101
-- On string shift to state 80

State 41:
text_element -> INDEX_LIST . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> INDEX_LIST
-- On VAL_REF reduce production text_element -> INDEX_LIST
-- On Title reduce production text_element -> INDEX_LIST
-- On TYP_REF reduce production text_element -> INDEX_LIST
-- On SUPERSCRIPT reduce production text_element -> INDEX_LIST
-- On SUBSCRIPT reduce production text_element -> INDEX_LIST
-- On SHORTCUT_LIST_ITEM reduce production text_element -> INDEX_LIST
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> INDEX_LIST
-- On SEC_REF reduce production text_element -> INDEX_LIST
-- On RIGHT reduce production text_element -> INDEX_LIST
-- On MOD_REF reduce production text_element -> INDEX_LIST
-- On MOD_LIST_REF reduce production text_element -> INDEX_LIST
-- On MODT_REF reduce production text_element -> INDEX_LIST
-- On MET_REF reduce production text_element -> INDEX_LIST
-- On LIST reduce production text_element -> INDEX_LIST
-- On LINK reduce production text_element -> INDEX_LIST
-- On LEFT reduce production text_element -> INDEX_LIST
-- On LATEX reduce production text_element -> INDEX_LIST
-- On ITALIC reduce production text_element -> INDEX_LIST
-- On INDEX_LIST reduce production text_element -> INDEX_LIST
-- On EXC_REF reduce production text_element -> INDEX_LIST
-- On EOF reduce production text_element -> INDEX_LIST
-- On ENUM reduce production text_element -> INDEX_LIST
-- On END_SHORTCUT_LIST reduce production text_element -> INDEX_LIST
-- On END reduce production text_element -> INDEX_LIST
-- On EMP reduce production text_element -> INDEX_LIST
-- On ELE_REF reduce production text_element -> INDEX_LIST
-- On Char reduce production text_element -> INDEX_LIST
-- On CODE_PRE reduce production text_element -> INDEX_LIST
-- On CODE reduce production text_element -> INDEX_LIST
-- On CLT_REF reduce production text_element -> INDEX_LIST
-- On CLA_REF reduce production text_element -> INDEX_LIST
-- On CENTER reduce production text_element -> INDEX_LIST
-- On BOLD reduce production text_element -> INDEX_LIST
-- On BLANK_LINE reduce production text_element -> INDEX_LIST
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> INDEX_LIST
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> INDEX_LIST
-- On ATT_REF reduce production text_element -> INDEX_LIST

State 42:
text_element -> EXC_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 43

State 43:
text_element -> EXC_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 44

State 44:
text_element -> EXC_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> EXC_REF string END
-- On VAL_REF reduce production text_element -> EXC_REF string END
-- On Title reduce production text_element -> EXC_REF string END
-- On TYP_REF reduce production text_element -> EXC_REF string END
-- On SUPERSCRIPT reduce production text_element -> EXC_REF string END
-- On SUBSCRIPT reduce production text_element -> EXC_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> EXC_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> EXC_REF string END
-- On SEC_REF reduce production text_element -> EXC_REF string END
-- On RIGHT reduce production text_element -> EXC_REF string END
-- On MOD_REF reduce production text_element -> EXC_REF string END
-- On MOD_LIST_REF reduce production text_element -> EXC_REF string END
-- On MODT_REF reduce production text_element -> EXC_REF string END
-- On MET_REF reduce production text_element -> EXC_REF string END
-- On LIST reduce production text_element -> EXC_REF string END
-- On LINK reduce production text_element -> EXC_REF string END
-- On LEFT reduce production text_element -> EXC_REF string END
-- On LATEX reduce production text_element -> EXC_REF string END
-- On ITALIC reduce production text_element -> EXC_REF string END
-- On INDEX_LIST reduce production text_element -> EXC_REF string END
-- On EXC_REF reduce production text_element -> EXC_REF string END
-- On EOF reduce production text_element -> EXC_REF string END
-- On ENUM reduce production text_element -> EXC_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> EXC_REF string END
-- On END reduce production text_element -> EXC_REF string END
-- On EMP reduce production text_element -> EXC_REF string END
-- On ELE_REF reduce production text_element -> EXC_REF string END
-- On Char reduce production text_element -> EXC_REF string END
-- On CODE_PRE reduce production text_element -> EXC_REF string END
-- On CODE reduce production text_element -> EXC_REF string END
-- On CLT_REF reduce production text_element -> EXC_REF string END
-- On CLA_REF reduce production text_element -> EXC_REF string END
-- On CENTER reduce production text_element -> EXC_REF string END
-- On BOLD reduce production text_element -> EXC_REF string END
-- On BLANK_LINE reduce production text_element -> EXC_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> EXC_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> EXC_REF string END
-- On ATT_REF reduce production text_element -> EXC_REF string END

State 45:
text_element -> ENUM . ocamldoc_odoc_text_list END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On ITEM shift to state 32
-- On Char shift to state 2
-- On string shift to state 46
-- On ocamldoc_odoc_text_list shift to state 51
-- On item shift to state 49

State 46:
ocamldoc_odoc_text_list -> string . [ END Char ]
ocamldoc_odoc_text_list -> string . ocamldoc_odoc_text_list [ END Char ]
-- On ITEM shift to state 32
-- On Char shift to state 2
-- On string shift to state 46
-- On ocamldoc_odoc_text_list shift to state 47
-- On item shift to state 49
-- On END reduce production ocamldoc_odoc_text_list -> string

State 47:
ocamldoc_odoc_text_list -> string ocamldoc_odoc_text_list . [ END Char ]
ocamldoc_odoc_text_list -> ocamldoc_odoc_text_list . string [ END Char ]
-- On Char shift to state 2
-- On string shift to state 48
-- On END reduce production ocamldoc_odoc_text_list -> string ocamldoc_odoc_text_list

State 48:
ocamldoc_odoc_text_list -> ocamldoc_odoc_text_list string . [ END Char ]
-- On END reduce production ocamldoc_odoc_text_list -> ocamldoc_odoc_text_list string
-- On Char reduce production ocamldoc_odoc_text_list -> ocamldoc_odoc_text_list string

State 49:
ocamldoc_odoc_text_list -> item . [ END Char ]
ocamldoc_odoc_text_list -> item . ocamldoc_odoc_text_list [ END Char ]
-- On ITEM shift to state 32
-- On Char shift to state 2
-- On string shift to state 46
-- On ocamldoc_odoc_text_list shift to state 50
-- On item shift to state 49
-- On END reduce production ocamldoc_odoc_text_list -> item

State 50:
ocamldoc_odoc_text_list -> ocamldoc_odoc_text_list . string [ END Char ]
ocamldoc_odoc_text_list -> item ocamldoc_odoc_text_list . [ END Char ]
-- On Char shift to state 2
-- On string shift to state 48
-- On END reduce production ocamldoc_odoc_text_list -> item ocamldoc_odoc_text_list

State 51:
ocamldoc_odoc_text_list -> ocamldoc_odoc_text_list . string [ END Char ]
text_element -> ENUM ocamldoc_odoc_text_list . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 52
-- On Char shift to state 2
-- On string shift to state 48

State 52:
text_element -> ENUM ocamldoc_odoc_text_list END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On VAL_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On Title reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On TYP_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On SUPERSCRIPT reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On SUBSCRIPT reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On SEC_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On RIGHT reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On MOD_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On MOD_LIST_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On MODT_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On MET_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On LIST reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On LINK reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On LEFT reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On LATEX reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On ITALIC reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On INDEX_LIST reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On EXC_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On EOF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On ENUM reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On END_SHORTCUT_LIST reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On END reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On EMP reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On ELE_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On Char reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On CODE_PRE reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On CODE reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On CLT_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On CLA_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On CENTER reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On BOLD reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On BLANK_LINE reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> ENUM ocamldoc_odoc_text_list END
-- On ATT_REF reduce production text_element -> ENUM ocamldoc_odoc_text_list END

State 53:
text_element -> EMP . text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 99
-- On string shift to state 80

State 54:
text_element -> ELE_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 55

State 55:
text_element -> ELE_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 56

State 56:
text_element -> ELE_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> ELE_REF string END
-- On VAL_REF reduce production text_element -> ELE_REF string END
-- On Title reduce production text_element -> ELE_REF string END
-- On TYP_REF reduce production text_element -> ELE_REF string END
-- On SUPERSCRIPT reduce production text_element -> ELE_REF string END
-- On SUBSCRIPT reduce production text_element -> ELE_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> ELE_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> ELE_REF string END
-- On SEC_REF reduce production text_element -> ELE_REF string END
-- On RIGHT reduce production text_element -> ELE_REF string END
-- On MOD_REF reduce production text_element -> ELE_REF string END
-- On MOD_LIST_REF reduce production text_element -> ELE_REF string END
-- On MODT_REF reduce production text_element -> ELE_REF string END
-- On MET_REF reduce production text_element -> ELE_REF string END
-- On LIST reduce production text_element -> ELE_REF string END
-- On LINK reduce production text_element -> ELE_REF string END
-- On LEFT reduce production text_element -> ELE_REF string END
-- On LATEX reduce production text_element -> ELE_REF string END
-- On ITALIC reduce production text_element -> ELE_REF string END
-- On INDEX_LIST reduce production text_element -> ELE_REF string END
-- On EXC_REF reduce production text_element -> ELE_REF string END
-- On EOF reduce production text_element -> ELE_REF string END
-- On ENUM reduce production text_element -> ELE_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> ELE_REF string END
-- On END reduce production text_element -> ELE_REF string END
-- On EMP reduce production text_element -> ELE_REF string END
-- On ELE_REF reduce production text_element -> ELE_REF string END
-- On Char reduce production text_element -> ELE_REF string END
-- On CODE_PRE reduce production text_element -> ELE_REF string END
-- On CODE reduce production text_element -> ELE_REF string END
-- On CLT_REF reduce production text_element -> ELE_REF string END
-- On CLA_REF reduce production text_element -> ELE_REF string END
-- On CENTER reduce production text_element -> ELE_REF string END
-- On BOLD reduce production text_element -> ELE_REF string END
-- On BLANK_LINE reduce production text_element -> ELE_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> ELE_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> ELE_REF string END
-- On ATT_REF reduce production text_element -> ELE_REF string END

State 57:
text_element -> CODE_PRE . string END_CODE_PRE [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 58

State 58:
text_element -> CODE_PRE string . END_CODE_PRE [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END_CODE_PRE shift to state 59

State 59:
text_element -> CODE_PRE string END_CODE_PRE . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On VAL_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On Title reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On TYP_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On SUPERSCRIPT reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On SUBSCRIPT reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On SHORTCUT_LIST_ITEM reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On SEC_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On RIGHT reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On MOD_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On MOD_LIST_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On MODT_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On MET_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On LIST reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On LINK reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On LEFT reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On LATEX reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On ITALIC reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On INDEX_LIST reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On EXC_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On EOF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On ENUM reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On END_SHORTCUT_LIST reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On END reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On EMP reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On ELE_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On Char reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On CODE_PRE reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On CODE reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On CLT_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On CLA_REF reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On CENTER reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On BOLD reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On BLANK_LINE reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> CODE_PRE string END_CODE_PRE
-- On ATT_REF reduce production text_element -> CODE_PRE string END_CODE_PRE

State 60:
text_element -> CODE . string END_CODE [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 61

State 61:
text_element -> CODE string . END_CODE [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END_CODE shift to state 62

State 62:
text_element -> CODE string END_CODE . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> CODE string END_CODE
-- On VAL_REF reduce production text_element -> CODE string END_CODE
-- On Title reduce production text_element -> CODE string END_CODE
-- On TYP_REF reduce production text_element -> CODE string END_CODE
-- On SUPERSCRIPT reduce production text_element -> CODE string END_CODE
-- On SUBSCRIPT reduce production text_element -> CODE string END_CODE
-- On SHORTCUT_LIST_ITEM reduce production text_element -> CODE string END_CODE
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> CODE string END_CODE
-- On SEC_REF reduce production text_element -> CODE string END_CODE
-- On RIGHT reduce production text_element -> CODE string END_CODE
-- On MOD_REF reduce production text_element -> CODE string END_CODE
-- On MOD_LIST_REF reduce production text_element -> CODE string END_CODE
-- On MODT_REF reduce production text_element -> CODE string END_CODE
-- On MET_REF reduce production text_element -> CODE string END_CODE
-- On LIST reduce production text_element -> CODE string END_CODE
-- On LINK reduce production text_element -> CODE string END_CODE
-- On LEFT reduce production text_element -> CODE string END_CODE
-- On LATEX reduce production text_element -> CODE string END_CODE
-- On ITALIC reduce production text_element -> CODE string END_CODE
-- On INDEX_LIST reduce production text_element -> CODE string END_CODE
-- On EXC_REF reduce production text_element -> CODE string END_CODE
-- On EOF reduce production text_element -> CODE string END_CODE
-- On ENUM reduce production text_element -> CODE string END_CODE
-- On END_SHORTCUT_LIST reduce production text_element -> CODE string END_CODE
-- On END reduce production text_element -> CODE string END_CODE
-- On EMP reduce production text_element -> CODE string END_CODE
-- On ELE_REF reduce production text_element -> CODE string END_CODE
-- On Char reduce production text_element -> CODE string END_CODE
-- On CODE_PRE reduce production text_element -> CODE string END_CODE
-- On CODE reduce production text_element -> CODE string END_CODE
-- On CLT_REF reduce production text_element -> CODE string END_CODE
-- On CLA_REF reduce production text_element -> CODE string END_CODE
-- On CENTER reduce production text_element -> CODE string END_CODE
-- On BOLD reduce production text_element -> CODE string END_CODE
-- On BLANK_LINE reduce production text_element -> CODE string END_CODE
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> CODE string END_CODE
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> CODE string END_CODE
-- On ATT_REF reduce production text_element -> CODE string END_CODE

State 63:
text_element -> CLT_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 64

State 64:
text_element -> CLT_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 65

State 65:
text_element -> CLT_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> CLT_REF string END
-- On VAL_REF reduce production text_element -> CLT_REF string END
-- On Title reduce production text_element -> CLT_REF string END
-- On TYP_REF reduce production text_element -> CLT_REF string END
-- On SUPERSCRIPT reduce production text_element -> CLT_REF string END
-- On SUBSCRIPT reduce production text_element -> CLT_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> CLT_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> CLT_REF string END
-- On SEC_REF reduce production text_element -> CLT_REF string END
-- On RIGHT reduce production text_element -> CLT_REF string END
-- On MOD_REF reduce production text_element -> CLT_REF string END
-- On MOD_LIST_REF reduce production text_element -> CLT_REF string END
-- On MODT_REF reduce production text_element -> CLT_REF string END
-- On MET_REF reduce production text_element -> CLT_REF string END
-- On LIST reduce production text_element -> CLT_REF string END
-- On LINK reduce production text_element -> CLT_REF string END
-- On LEFT reduce production text_element -> CLT_REF string END
-- On LATEX reduce production text_element -> CLT_REF string END
-- On ITALIC reduce production text_element -> CLT_REF string END
-- On INDEX_LIST reduce production text_element -> CLT_REF string END
-- On EXC_REF reduce production text_element -> CLT_REF string END
-- On EOF reduce production text_element -> CLT_REF string END
-- On ENUM reduce production text_element -> CLT_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> CLT_REF string END
-- On END reduce production text_element -> CLT_REF string END
-- On EMP reduce production text_element -> CLT_REF string END
-- On ELE_REF reduce production text_element -> CLT_REF string END
-- On Char reduce production text_element -> CLT_REF string END
-- On CODE_PRE reduce production text_element -> CLT_REF string END
-- On CODE reduce production text_element -> CLT_REF string END
-- On CLT_REF reduce production text_element -> CLT_REF string END
-- On CLA_REF reduce production text_element -> CLT_REF string END
-- On CENTER reduce production text_element -> CLT_REF string END
-- On BOLD reduce production text_element -> CLT_REF string END
-- On BLANK_LINE reduce production text_element -> CLT_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> CLT_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> CLT_REF string END
-- On ATT_REF reduce production text_element -> CLT_REF string END

State 66:
text_element -> CLA_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 67

State 67:
text_element -> CLA_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 68

State 68:
text_element -> CLA_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> CLA_REF string END
-- On VAL_REF reduce production text_element -> CLA_REF string END
-- On Title reduce production text_element -> CLA_REF string END
-- On TYP_REF reduce production text_element -> CLA_REF string END
-- On SUPERSCRIPT reduce production text_element -> CLA_REF string END
-- On SUBSCRIPT reduce production text_element -> CLA_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> CLA_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> CLA_REF string END
-- On SEC_REF reduce production text_element -> CLA_REF string END
-- On RIGHT reduce production text_element -> CLA_REF string END
-- On MOD_REF reduce production text_element -> CLA_REF string END
-- On MOD_LIST_REF reduce production text_element -> CLA_REF string END
-- On MODT_REF reduce production text_element -> CLA_REF string END
-- On MET_REF reduce production text_element -> CLA_REF string END
-- On LIST reduce production text_element -> CLA_REF string END
-- On LINK reduce production text_element -> CLA_REF string END
-- On LEFT reduce production text_element -> CLA_REF string END
-- On LATEX reduce production text_element -> CLA_REF string END
-- On ITALIC reduce production text_element -> CLA_REF string END
-- On INDEX_LIST reduce production text_element -> CLA_REF string END
-- On EXC_REF reduce production text_element -> CLA_REF string END
-- On EOF reduce production text_element -> CLA_REF string END
-- On ENUM reduce production text_element -> CLA_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> CLA_REF string END
-- On END reduce production text_element -> CLA_REF string END
-- On EMP reduce production text_element -> CLA_REF string END
-- On ELE_REF reduce production text_element -> CLA_REF string END
-- On Char reduce production text_element -> CLA_REF string END
-- On CODE_PRE reduce production text_element -> CLA_REF string END
-- On CODE reduce production text_element -> CLA_REF string END
-- On CLT_REF reduce production text_element -> CLA_REF string END
-- On CLA_REF reduce production text_element -> CLA_REF string END
-- On CENTER reduce production text_element -> CLA_REF string END
-- On BOLD reduce production text_element -> CLA_REF string END
-- On BLANK_LINE reduce production text_element -> CLA_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> CLA_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> CLA_REF string END
-- On ATT_REF reduce production text_element -> CLA_REF string END

State 69:
text_element -> CENTER . text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 97
-- On string shift to state 80

State 70:
text_element -> BOLD . text END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 95
-- On string shift to state 80

State 71:
text_element -> BLANK_LINE . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> BLANK_LINE
-- On VAL_REF reduce production text_element -> BLANK_LINE
-- On Title reduce production text_element -> BLANK_LINE
-- On TYP_REF reduce production text_element -> BLANK_LINE
-- On SUPERSCRIPT reduce production text_element -> BLANK_LINE
-- On SUBSCRIPT reduce production text_element -> BLANK_LINE
-- On SHORTCUT_LIST_ITEM reduce production text_element -> BLANK_LINE
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> BLANK_LINE
-- On SEC_REF reduce production text_element -> BLANK_LINE
-- On RIGHT reduce production text_element -> BLANK_LINE
-- On MOD_REF reduce production text_element -> BLANK_LINE
-- On MOD_LIST_REF reduce production text_element -> BLANK_LINE
-- On MODT_REF reduce production text_element -> BLANK_LINE
-- On MET_REF reduce production text_element -> BLANK_LINE
-- On LIST reduce production text_element -> BLANK_LINE
-- On LINK reduce production text_element -> BLANK_LINE
-- On LEFT reduce production text_element -> BLANK_LINE
-- On LATEX reduce production text_element -> BLANK_LINE
-- On ITALIC reduce production text_element -> BLANK_LINE
-- On INDEX_LIST reduce production text_element -> BLANK_LINE
-- On EXC_REF reduce production text_element -> BLANK_LINE
-- On EOF reduce production text_element -> BLANK_LINE
-- On ENUM reduce production text_element -> BLANK_LINE
-- On END_SHORTCUT_LIST reduce production text_element -> BLANK_LINE
-- On END reduce production text_element -> BLANK_LINE
-- On EMP reduce production text_element -> BLANK_LINE
-- On ELE_REF reduce production text_element -> BLANK_LINE
-- On Char reduce production text_element -> BLANK_LINE
-- On CODE_PRE reduce production text_element -> BLANK_LINE
-- On CODE reduce production text_element -> BLANK_LINE
-- On CLT_REF reduce production text_element -> BLANK_LINE
-- On CLA_REF reduce production text_element -> BLANK_LINE
-- On CENTER reduce production text_element -> BLANK_LINE
-- On BOLD reduce production text_element -> BLANK_LINE
-- On BLANK_LINE reduce production text_element -> BLANK_LINE
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> BLANK_LINE
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> BLANK_LINE
-- On ATT_REF reduce production text_element -> BLANK_LINE

State 72:
text_element -> BEGIN_SHORTCUT_LIST_ITEM . shortcut_list END_SHORTCUT_LIST [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
text_element -> BEGIN_SHORTCUT_LIST_ITEM . shortcut_list EOF [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 88
-- On string shift to state 80
-- On shortcut_list shift to state 92

State 73:
text_element -> BEGIN_SHORTCUT_ENUM_ITEM . shortcut_enum END_SHORTCUT_LIST [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
text_element -> BEGIN_SHORTCUT_ENUM_ITEM . shortcut_enum EOF [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 81
-- On string shift to state 80
-- On shortcut_enum shift to state 85

State 74:
text_element -> ATT_REF . string END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On Char shift to state 2
-- On string shift to state 75

State 75:
text_element -> ATT_REF string . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 76

State 76:
text_element -> ATT_REF string END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> ATT_REF string END
-- On VAL_REF reduce production text_element -> ATT_REF string END
-- On Title reduce production text_element -> ATT_REF string END
-- On TYP_REF reduce production text_element -> ATT_REF string END
-- On SUPERSCRIPT reduce production text_element -> ATT_REF string END
-- On SUBSCRIPT reduce production text_element -> ATT_REF string END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> ATT_REF string END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> ATT_REF string END
-- On SEC_REF reduce production text_element -> ATT_REF string END
-- On RIGHT reduce production text_element -> ATT_REF string END
-- On MOD_REF reduce production text_element -> ATT_REF string END
-- On MOD_LIST_REF reduce production text_element -> ATT_REF string END
-- On MODT_REF reduce production text_element -> ATT_REF string END
-- On MET_REF reduce production text_element -> ATT_REF string END
-- On LIST reduce production text_element -> ATT_REF string END
-- On LINK reduce production text_element -> ATT_REF string END
-- On LEFT reduce production text_element -> ATT_REF string END
-- On LATEX reduce production text_element -> ATT_REF string END
-- On ITALIC reduce production text_element -> ATT_REF string END
-- On INDEX_LIST reduce production text_element -> ATT_REF string END
-- On EXC_REF reduce production text_element -> ATT_REF string END
-- On EOF reduce production text_element -> ATT_REF string END
-- On ENUM reduce production text_element -> ATT_REF string END
-- On END_SHORTCUT_LIST reduce production text_element -> ATT_REF string END
-- On END reduce production text_element -> ATT_REF string END
-- On EMP reduce production text_element -> ATT_REF string END
-- On ELE_REF reduce production text_element -> ATT_REF string END
-- On Char reduce production text_element -> ATT_REF string END
-- On CODE_PRE reduce production text_element -> ATT_REF string END
-- On CODE reduce production text_element -> ATT_REF string END
-- On CLT_REF reduce production text_element -> ATT_REF string END
-- On CLA_REF reduce production text_element -> ATT_REF string END
-- On CENTER reduce production text_element -> ATT_REF string END
-- On BOLD reduce production text_element -> ATT_REF string END
-- On BLANK_LINE reduce production text_element -> ATT_REF string END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> ATT_REF string END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> ATT_REF string END
-- On ATT_REF reduce production text_element -> ATT_REF string END

State 77:
text -> text_element_list . [ SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM EOF END_SHORTCUT_LIST END ]
-- On SHORTCUT_LIST_ITEM reduce production text -> text_element_list
-- On SHORTCUT_ENUM_ITEM reduce production text -> text_element_list
-- On EOF reduce production text -> text_element_list
-- On END_SHORTCUT_LIST reduce production text -> text_element_list
-- On END reduce production text -> text_element_list

State 78:
text_element_list -> text_element . [ SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM EOF END_SHORTCUT_LIST END ]
text_element_list -> text_element . text_element_list [ SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM EOF END_SHORTCUT_LIST END ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 79
-- On text_element shift to state 78
-- On string shift to state 80
-- On SHORTCUT_LIST_ITEM reduce production text_element_list -> text_element
-- On SHORTCUT_ENUM_ITEM reduce production text_element_list -> text_element
-- On EOF reduce production text_element_list -> text_element
-- On END_SHORTCUT_LIST reduce production text_element_list -> text_element
-- On END reduce production text_element_list -> text_element

State 79:
text_element_list -> text_element text_element_list . [ SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM EOF END_SHORTCUT_LIST END ]
-- On SHORTCUT_LIST_ITEM reduce production text_element_list -> text_element text_element_list
-- On SHORTCUT_ENUM_ITEM reduce production text_element_list -> text_element text_element_list
-- On EOF reduce production text_element_list -> text_element text_element_list
-- On END_SHORTCUT_LIST reduce production text_element_list -> text_element text_element_list
-- On END reduce production text_element_list -> text_element text_element_list

State 80:
text_element -> string . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> string
-- On VAL_REF reduce production text_element -> string
-- On Title reduce production text_element -> string
-- On TYP_REF reduce production text_element -> string
-- On SUPERSCRIPT reduce production text_element -> string
-- On SUBSCRIPT reduce production text_element -> string
-- On SHORTCUT_LIST_ITEM reduce production text_element -> string
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> string
-- On SEC_REF reduce production text_element -> string
-- On RIGHT reduce production text_element -> string
-- On MOD_REF reduce production text_element -> string
-- On MOD_LIST_REF reduce production text_element -> string
-- On MODT_REF reduce production text_element -> string
-- On MET_REF reduce production text_element -> string
-- On LIST reduce production text_element -> string
-- On LINK reduce production text_element -> string
-- On LEFT reduce production text_element -> string
-- On LATEX reduce production text_element -> string
-- On ITALIC reduce production text_element -> string
-- On INDEX_LIST reduce production text_element -> string
-- On EXC_REF reduce production text_element -> string
-- On EOF reduce production text_element -> string
-- On ENUM reduce production text_element -> string
-- On END_SHORTCUT_LIST reduce production text_element -> string
-- On END reduce production text_element -> string
-- On EMP reduce production text_element -> string
-- On ELE_REF reduce production text_element -> string
-- On Char reduce production text_element -> string
-- On CODE_PRE reduce production text_element -> string
-- On CODE reduce production text_element -> string
-- On CLT_REF reduce production text_element -> string
-- On CLA_REF reduce production text_element -> string
-- On CENTER reduce production text_element -> string
-- On BOLD reduce production text_element -> string
-- On BLANK_LINE reduce production text_element -> string
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> string
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> string
-- On ATT_REF reduce production text_element -> string

State 81:
shortcut_enum -> text . shortcut_enum2 [ EOF END_SHORTCUT_LIST ]
shortcut_enum -> text . [ EOF END_SHORTCUT_LIST ]
-- On SHORTCUT_ENUM_ITEM shift to state 82
-- On shortcut_enum2 shift to state 84
-- On EOF reduce production shortcut_enum -> text
-- On END_SHORTCUT_LIST reduce production shortcut_enum -> text

State 82:
shortcut_enum2 -> SHORTCUT_ENUM_ITEM . shortcut_enum [ EOF END_SHORTCUT_LIST ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 81
-- On string shift to state 80
-- On shortcut_enum shift to state 83

State 83:
shortcut_enum2 -> SHORTCUT_ENUM_ITEM shortcut_enum . [ EOF END_SHORTCUT_LIST ]
-- On EOF reduce production shortcut_enum2 -> SHORTCUT_ENUM_ITEM shortcut_enum
-- On END_SHORTCUT_LIST reduce production shortcut_enum2 -> SHORTCUT_ENUM_ITEM shortcut_enum

State 84:
shortcut_enum -> text shortcut_enum2 . [ EOF END_SHORTCUT_LIST ]
-- On EOF reduce production shortcut_enum -> text shortcut_enum2
-- On END_SHORTCUT_LIST reduce production shortcut_enum -> text shortcut_enum2

State 85:
text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum . END_SHORTCUT_LIST [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum . EOF [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On EOF shift to state 86
-- On END_SHORTCUT_LIST shift to state 87

State 86:
text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On VAL_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On Title reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On TYP_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On SUPERSCRIPT reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On SUBSCRIPT reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On SHORTCUT_LIST_ITEM reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On SEC_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On RIGHT reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On MOD_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On MOD_LIST_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On MODT_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On MET_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On LIST reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On LINK reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On LEFT reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On LATEX reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On ITALIC reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On INDEX_LIST reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On EXC_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On EOF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On ENUM reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On END_SHORTCUT_LIST reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On END reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On EMP reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On ELE_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On Char reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On CODE_PRE reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On CODE reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On CLT_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On CLA_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On CENTER reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On BOLD reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On BLANK_LINE reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF
-- On ATT_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum EOF

State 87:
text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On VAL_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On Title reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On TYP_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On SUPERSCRIPT reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On SUBSCRIPT reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On SHORTCUT_LIST_ITEM reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On SEC_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On RIGHT reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On MOD_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On MOD_LIST_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On MODT_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On MET_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On LIST reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On LINK reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On LEFT reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On LATEX reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On ITALIC reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On INDEX_LIST reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On EXC_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On EOF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On ENUM reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On END_SHORTCUT_LIST reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On END reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On EMP reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On ELE_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On Char reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On CODE_PRE reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On CODE reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On CLT_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On CLA_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On CENTER reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On BOLD reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On BLANK_LINE reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST
-- On ATT_REF reduce production text_element -> BEGIN_SHORTCUT_ENUM_ITEM shortcut_enum END_SHORTCUT_LIST

State 88:
shortcut_list -> text . shortcut_list2 [ EOF END_SHORTCUT_LIST ]
shortcut_list -> text . [ EOF END_SHORTCUT_LIST ]
-- On SHORTCUT_LIST_ITEM shift to state 89
-- On shortcut_list2 shift to state 91
-- On EOF reduce production shortcut_list -> text
-- On END_SHORTCUT_LIST reduce production shortcut_list -> text

State 89:
shortcut_list2 -> SHORTCUT_LIST_ITEM . shortcut_list [ EOF END_SHORTCUT_LIST ]
-- On VERB shift to state 1
-- On VAL_REF shift to state 6
-- On Title shift to state 9
-- On TYP_REF shift to state 10
-- On SUPERSCRIPT shift to state 13
-- On SUBSCRIPT shift to state 14
-- On SEC_REF shift to state 15
-- On RIGHT shift to state 18
-- On MOD_REF shift to state 19
-- On MOD_LIST_REF shift to state 22
-- On MODT_REF shift to state 25
-- On MET_REF shift to state 28
-- On LIST shift to state 31
-- On LINK shift to state 33
-- On LEFT shift to state 36
-- On LATEX shift to state 37
-- On ITALIC shift to state 40
-- On INDEX_LIST shift to state 41
-- On EXC_REF shift to state 42
-- On ENUM shift to state 45
-- On EMP shift to state 53
-- On ELE_REF shift to state 54
-- On Char shift to state 2
-- On CODE_PRE shift to state 57
-- On CODE shift to state 60
-- On CLT_REF shift to state 63
-- On CLA_REF shift to state 66
-- On CENTER shift to state 69
-- On BOLD shift to state 70
-- On BLANK_LINE shift to state 71
-- On BEGIN_SHORTCUT_LIST_ITEM shift to state 72
-- On BEGIN_SHORTCUT_ENUM_ITEM shift to state 73
-- On ATT_REF shift to state 74
-- On text_element_list shift to state 77
-- On text_element shift to state 78
-- On text shift to state 88
-- On string shift to state 80
-- On shortcut_list shift to state 90

State 90:
shortcut_list2 -> SHORTCUT_LIST_ITEM shortcut_list . [ EOF END_SHORTCUT_LIST ]
-- On EOF reduce production shortcut_list2 -> SHORTCUT_LIST_ITEM shortcut_list
-- On END_SHORTCUT_LIST reduce production shortcut_list2 -> SHORTCUT_LIST_ITEM shortcut_list

State 91:
shortcut_list -> text shortcut_list2 . [ EOF END_SHORTCUT_LIST ]
-- On EOF reduce production shortcut_list -> text shortcut_list2
-- On END_SHORTCUT_LIST reduce production shortcut_list -> text shortcut_list2

State 92:
text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list . END_SHORTCUT_LIST [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list . EOF [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On EOF shift to state 93
-- On END_SHORTCUT_LIST shift to state 94

State 93:
text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On VAL_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On Title reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On TYP_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On SUPERSCRIPT reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On SUBSCRIPT reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On SHORTCUT_LIST_ITEM reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On SEC_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On RIGHT reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On MOD_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On MOD_LIST_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On MODT_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On MET_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On LIST reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On LINK reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On LEFT reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On LATEX reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On ITALIC reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On INDEX_LIST reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On EXC_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On EOF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On ENUM reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On END_SHORTCUT_LIST reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On END reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On EMP reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On ELE_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On Char reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On CODE_PRE reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On CODE reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On CLT_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On CLA_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On CENTER reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On BOLD reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On BLANK_LINE reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF
-- On ATT_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list EOF

State 94:
text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On VAL_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On Title reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On TYP_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On SUPERSCRIPT reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On SUBSCRIPT reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On SHORTCUT_LIST_ITEM reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On SEC_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On RIGHT reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On MOD_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On MOD_LIST_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On MODT_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On MET_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On LIST reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On LINK reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On LEFT reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On LATEX reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On ITALIC reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On INDEX_LIST reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On EXC_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On EOF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On ENUM reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On END_SHORTCUT_LIST reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On END reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On EMP reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On ELE_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On Char reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On CODE_PRE reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On CODE reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On CLT_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On CLA_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On CENTER reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On BOLD reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On BLANK_LINE reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST
-- On ATT_REF reduce production text_element -> BEGIN_SHORTCUT_LIST_ITEM shortcut_list END_SHORTCUT_LIST

State 95:
text_element -> BOLD text . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 96

State 96:
text_element -> BOLD text END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> BOLD text END
-- On VAL_REF reduce production text_element -> BOLD text END
-- On Title reduce production text_element -> BOLD text END
-- On TYP_REF reduce production text_element -> BOLD text END
-- On SUPERSCRIPT reduce production text_element -> BOLD text END
-- On SUBSCRIPT reduce production text_element -> BOLD text END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> BOLD text END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> BOLD text END
-- On SEC_REF reduce production text_element -> BOLD text END
-- On RIGHT reduce production text_element -> BOLD text END
-- On MOD_REF reduce production text_element -> BOLD text END
-- On MOD_LIST_REF reduce production text_element -> BOLD text END
-- On MODT_REF reduce production text_element -> BOLD text END
-- On MET_REF reduce production text_element -> BOLD text END
-- On LIST reduce production text_element -> BOLD text END
-- On LINK reduce production text_element -> BOLD text END
-- On LEFT reduce production text_element -> BOLD text END
-- On LATEX reduce production text_element -> BOLD text END
-- On ITALIC reduce production text_element -> BOLD text END
-- On INDEX_LIST reduce production text_element -> BOLD text END
-- On EXC_REF reduce production text_element -> BOLD text END
-- On EOF reduce production text_element -> BOLD text END
-- On ENUM reduce production text_element -> BOLD text END
-- On END_SHORTCUT_LIST reduce production text_element -> BOLD text END
-- On END reduce production text_element -> BOLD text END
-- On EMP reduce production text_element -> BOLD text END
-- On ELE_REF reduce production text_element -> BOLD text END
-- On Char reduce production text_element -> BOLD text END
-- On CODE_PRE reduce production text_element -> BOLD text END
-- On CODE reduce production text_element -> BOLD text END
-- On CLT_REF reduce production text_element -> BOLD text END
-- On CLA_REF reduce production text_element -> BOLD text END
-- On CENTER reduce production text_element -> BOLD text END
-- On BOLD reduce production text_element -> BOLD text END
-- On BLANK_LINE reduce production text_element -> BOLD text END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> BOLD text END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> BOLD text END
-- On ATT_REF reduce production text_element -> BOLD text END

State 97:
text_element -> CENTER text . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 98

State 98:
text_element -> CENTER text END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> CENTER text END
-- On VAL_REF reduce production text_element -> CENTER text END
-- On Title reduce production text_element -> CENTER text END
-- On TYP_REF reduce production text_element -> CENTER text END
-- On SUPERSCRIPT reduce production text_element -> CENTER text END
-- On SUBSCRIPT reduce production text_element -> CENTER text END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> CENTER text END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> CENTER text END
-- On SEC_REF reduce production text_element -> CENTER text END
-- On RIGHT reduce production text_element -> CENTER text END
-- On MOD_REF reduce production text_element -> CENTER text END
-- On MOD_LIST_REF reduce production text_element -> CENTER text END
-- On MODT_REF reduce production text_element -> CENTER text END
-- On MET_REF reduce production text_element -> CENTER text END
-- On LIST reduce production text_element -> CENTER text END
-- On LINK reduce production text_element -> CENTER text END
-- On LEFT reduce production text_element -> CENTER text END
-- On LATEX reduce production text_element -> CENTER text END
-- On ITALIC reduce production text_element -> CENTER text END
-- On INDEX_LIST reduce production text_element -> CENTER text END
-- On EXC_REF reduce production text_element -> CENTER text END
-- On EOF reduce production text_element -> CENTER text END
-- On ENUM reduce production text_element -> CENTER text END
-- On END_SHORTCUT_LIST reduce production text_element -> CENTER text END
-- On END reduce production text_element -> CENTER text END
-- On EMP reduce production text_element -> CENTER text END
-- On ELE_REF reduce production text_element -> CENTER text END
-- On Char reduce production text_element -> CENTER text END
-- On CODE_PRE reduce production text_element -> CENTER text END
-- On CODE reduce production text_element -> CENTER text END
-- On CLT_REF reduce production text_element -> CENTER text END
-- On CLA_REF reduce production text_element -> CENTER text END
-- On CENTER reduce production text_element -> CENTER text END
-- On BOLD reduce production text_element -> CENTER text END
-- On BLANK_LINE reduce production text_element -> CENTER text END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> CENTER text END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> CENTER text END
-- On ATT_REF reduce production text_element -> CENTER text END

State 99:
text_element -> EMP text . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 100

State 100:
text_element -> EMP text END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> EMP text END
-- On VAL_REF reduce production text_element -> EMP text END
-- On Title reduce production text_element -> EMP text END
-- On TYP_REF reduce production text_element -> EMP text END
-- On SUPERSCRIPT reduce production text_element -> EMP text END
-- On SUBSCRIPT reduce production text_element -> EMP text END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> EMP text END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> EMP text END
-- On SEC_REF reduce production text_element -> EMP text END
-- On RIGHT reduce production text_element -> EMP text END
-- On MOD_REF reduce production text_element -> EMP text END
-- On MOD_LIST_REF reduce production text_element -> EMP text END
-- On MODT_REF reduce production text_element -> EMP text END
-- On MET_REF reduce production text_element -> EMP text END
-- On LIST reduce production text_element -> EMP text END
-- On LINK reduce production text_element -> EMP text END
-- On LEFT reduce production text_element -> EMP text END
-- On LATEX reduce production text_element -> EMP text END
-- On ITALIC reduce production text_element -> EMP text END
-- On INDEX_LIST reduce production text_element -> EMP text END
-- On EXC_REF reduce production text_element -> EMP text END
-- On EOF reduce production text_element -> EMP text END
-- On ENUM reduce production text_element -> EMP text END
-- On END_SHORTCUT_LIST reduce production text_element -> EMP text END
-- On END reduce production text_element -> EMP text END
-- On EMP reduce production text_element -> EMP text END
-- On ELE_REF reduce production text_element -> EMP text END
-- On Char reduce production text_element -> EMP text END
-- On CODE_PRE reduce production text_element -> EMP text END
-- On CODE reduce production text_element -> EMP text END
-- On CLT_REF reduce production text_element -> EMP text END
-- On CLA_REF reduce production text_element -> EMP text END
-- On CENTER reduce production text_element -> EMP text END
-- On BOLD reduce production text_element -> EMP text END
-- On BLANK_LINE reduce production text_element -> EMP text END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> EMP text END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> EMP text END
-- On ATT_REF reduce production text_element -> EMP text END

State 101:
text_element -> ITALIC text . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 102

State 102:
text_element -> ITALIC text END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> ITALIC text END
-- On VAL_REF reduce production text_element -> ITALIC text END
-- On Title reduce production text_element -> ITALIC text END
-- On TYP_REF reduce production text_element -> ITALIC text END
-- On SUPERSCRIPT reduce production text_element -> ITALIC text END
-- On SUBSCRIPT reduce production text_element -> ITALIC text END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> ITALIC text END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> ITALIC text END
-- On SEC_REF reduce production text_element -> ITALIC text END
-- On RIGHT reduce production text_element -> ITALIC text END
-- On MOD_REF reduce production text_element -> ITALIC text END
-- On MOD_LIST_REF reduce production text_element -> ITALIC text END
-- On MODT_REF reduce production text_element -> ITALIC text END
-- On MET_REF reduce production text_element -> ITALIC text END
-- On LIST reduce production text_element -> ITALIC text END
-- On LINK reduce production text_element -> ITALIC text END
-- On LEFT reduce production text_element -> ITALIC text END
-- On LATEX reduce production text_element -> ITALIC text END
-- On ITALIC reduce production text_element -> ITALIC text END
-- On INDEX_LIST reduce production text_element -> ITALIC text END
-- On EXC_REF reduce production text_element -> ITALIC text END
-- On EOF reduce production text_element -> ITALIC text END
-- On ENUM reduce production text_element -> ITALIC text END
-- On END_SHORTCUT_LIST reduce production text_element -> ITALIC text END
-- On END reduce production text_element -> ITALIC text END
-- On EMP reduce production text_element -> ITALIC text END
-- On ELE_REF reduce production text_element -> ITALIC text END
-- On Char reduce production text_element -> ITALIC text END
-- On CODE_PRE reduce production text_element -> ITALIC text END
-- On CODE reduce production text_element -> ITALIC text END
-- On CLT_REF reduce production text_element -> ITALIC text END
-- On CLA_REF reduce production text_element -> ITALIC text END
-- On CENTER reduce production text_element -> ITALIC text END
-- On BOLD reduce production text_element -> ITALIC text END
-- On BLANK_LINE reduce production text_element -> ITALIC text END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> ITALIC text END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> ITALIC text END
-- On ATT_REF reduce production text_element -> ITALIC text END

State 103:
text_element -> LEFT text . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 104

State 104:
text_element -> LEFT text END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> LEFT text END
-- On VAL_REF reduce production text_element -> LEFT text END
-- On Title reduce production text_element -> LEFT text END
-- On TYP_REF reduce production text_element -> LEFT text END
-- On SUPERSCRIPT reduce production text_element -> LEFT text END
-- On SUBSCRIPT reduce production text_element -> LEFT text END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> LEFT text END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> LEFT text END
-- On SEC_REF reduce production text_element -> LEFT text END
-- On RIGHT reduce production text_element -> LEFT text END
-- On MOD_REF reduce production text_element -> LEFT text END
-- On MOD_LIST_REF reduce production text_element -> LEFT text END
-- On MODT_REF reduce production text_element -> LEFT text END
-- On MET_REF reduce production text_element -> LEFT text END
-- On LIST reduce production text_element -> LEFT text END
-- On LINK reduce production text_element -> LEFT text END
-- On LEFT reduce production text_element -> LEFT text END
-- On LATEX reduce production text_element -> LEFT text END
-- On ITALIC reduce production text_element -> LEFT text END
-- On INDEX_LIST reduce production text_element -> LEFT text END
-- On EXC_REF reduce production text_element -> LEFT text END
-- On EOF reduce production text_element -> LEFT text END
-- On ENUM reduce production text_element -> LEFT text END
-- On END_SHORTCUT_LIST reduce production text_element -> LEFT text END
-- On END reduce production text_element -> LEFT text END
-- On EMP reduce production text_element -> LEFT text END
-- On ELE_REF reduce production text_element -> LEFT text END
-- On Char reduce production text_element -> LEFT text END
-- On CODE_PRE reduce production text_element -> LEFT text END
-- On CODE reduce production text_element -> LEFT text END
-- On CLT_REF reduce production text_element -> LEFT text END
-- On CLA_REF reduce production text_element -> LEFT text END
-- On CENTER reduce production text_element -> LEFT text END
-- On BOLD reduce production text_element -> LEFT text END
-- On BLANK_LINE reduce production text_element -> LEFT text END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> LEFT text END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> LEFT text END
-- On ATT_REF reduce production text_element -> LEFT text END

State 105:
text_element -> LINK string END text . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 106

State 106:
text_element -> LINK string END text END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> LINK string END text END
-- On VAL_REF reduce production text_element -> LINK string END text END
-- On Title reduce production text_element -> LINK string END text END
-- On TYP_REF reduce production text_element -> LINK string END text END
-- On SUPERSCRIPT reduce production text_element -> LINK string END text END
-- On SUBSCRIPT reduce production text_element -> LINK string END text END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> LINK string END text END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> LINK string END text END
-- On SEC_REF reduce production text_element -> LINK string END text END
-- On RIGHT reduce production text_element -> LINK string END text END
-- On MOD_REF reduce production text_element -> LINK string END text END
-- On MOD_LIST_REF reduce production text_element -> LINK string END text END
-- On MODT_REF reduce production text_element -> LINK string END text END
-- On MET_REF reduce production text_element -> LINK string END text END
-- On LIST reduce production text_element -> LINK string END text END
-- On LINK reduce production text_element -> LINK string END text END
-- On LEFT reduce production text_element -> LINK string END text END
-- On LATEX reduce production text_element -> LINK string END text END
-- On ITALIC reduce production text_element -> LINK string END text END
-- On INDEX_LIST reduce production text_element -> LINK string END text END
-- On EXC_REF reduce production text_element -> LINK string END text END
-- On EOF reduce production text_element -> LINK string END text END
-- On ENUM reduce production text_element -> LINK string END text END
-- On END_SHORTCUT_LIST reduce production text_element -> LINK string END text END
-- On END reduce production text_element -> LINK string END text END
-- On EMP reduce production text_element -> LINK string END text END
-- On ELE_REF reduce production text_element -> LINK string END text END
-- On Char reduce production text_element -> LINK string END text END
-- On CODE_PRE reduce production text_element -> LINK string END text END
-- On CODE reduce production text_element -> LINK string END text END
-- On CLT_REF reduce production text_element -> LINK string END text END
-- On CLA_REF reduce production text_element -> LINK string END text END
-- On CENTER reduce production text_element -> LINK string END text END
-- On BOLD reduce production text_element -> LINK string END text END
-- On BLANK_LINE reduce production text_element -> LINK string END text END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> LINK string END text END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> LINK string END text END
-- On ATT_REF reduce production text_element -> LINK string END text END

State 107:
item -> ITEM text . END [ ITEM END Char ]
-- On END shift to state 108

State 108:
item -> ITEM text END . [ ITEM END Char ]
-- On ITEM reduce production item -> ITEM text END
-- On END reduce production item -> ITEM text END
-- On Char reduce production item -> ITEM text END

State 109:
ocamldoc_odoc_text_list -> ocamldoc_odoc_text_list . string [ END Char ]
text_element -> LIST ocamldoc_odoc_text_list . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 110
-- On Char shift to state 2
-- On string shift to state 48

State 110:
text_element -> LIST ocamldoc_odoc_text_list END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On VAL_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On Title reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On TYP_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On SUPERSCRIPT reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On SUBSCRIPT reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On SEC_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On RIGHT reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On MOD_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On MOD_LIST_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On MODT_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On MET_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On LIST reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On LINK reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On LEFT reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On LATEX reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On ITALIC reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On INDEX_LIST reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On EXC_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On EOF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On ENUM reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On END_SHORTCUT_LIST reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On END reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On EMP reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On ELE_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On Char reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On CODE_PRE reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On CODE reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On CLT_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On CLA_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On CENTER reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On BOLD reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On BLANK_LINE reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> LIST ocamldoc_odoc_text_list END
-- On ATT_REF reduce production text_element -> LIST ocamldoc_odoc_text_list END

State 111:
text_element -> RIGHT text . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 112

State 112:
text_element -> RIGHT text END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> RIGHT text END
-- On VAL_REF reduce production text_element -> RIGHT text END
-- On Title reduce production text_element -> RIGHT text END
-- On TYP_REF reduce production text_element -> RIGHT text END
-- On SUPERSCRIPT reduce production text_element -> RIGHT text END
-- On SUBSCRIPT reduce production text_element -> RIGHT text END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> RIGHT text END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> RIGHT text END
-- On SEC_REF reduce production text_element -> RIGHT text END
-- On RIGHT reduce production text_element -> RIGHT text END
-- On MOD_REF reduce production text_element -> RIGHT text END
-- On MOD_LIST_REF reduce production text_element -> RIGHT text END
-- On MODT_REF reduce production text_element -> RIGHT text END
-- On MET_REF reduce production text_element -> RIGHT text END
-- On LIST reduce production text_element -> RIGHT text END
-- On LINK reduce production text_element -> RIGHT text END
-- On LEFT reduce production text_element -> RIGHT text END
-- On LATEX reduce production text_element -> RIGHT text END
-- On ITALIC reduce production text_element -> RIGHT text END
-- On INDEX_LIST reduce production text_element -> RIGHT text END
-- On EXC_REF reduce production text_element -> RIGHT text END
-- On EOF reduce production text_element -> RIGHT text END
-- On ENUM reduce production text_element -> RIGHT text END
-- On END_SHORTCUT_LIST reduce production text_element -> RIGHT text END
-- On END reduce production text_element -> RIGHT text END
-- On EMP reduce production text_element -> RIGHT text END
-- On ELE_REF reduce production text_element -> RIGHT text END
-- On Char reduce production text_element -> RIGHT text END
-- On CODE_PRE reduce production text_element -> RIGHT text END
-- On CODE reduce production text_element -> RIGHT text END
-- On CLT_REF reduce production text_element -> RIGHT text END
-- On CLA_REF reduce production text_element -> RIGHT text END
-- On CENTER reduce production text_element -> RIGHT text END
-- On BOLD reduce production text_element -> RIGHT text END
-- On BLANK_LINE reduce production text_element -> RIGHT text END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> RIGHT text END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> RIGHT text END
-- On ATT_REF reduce production text_element -> RIGHT text END

State 113:
text_element -> SUBSCRIPT text . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 114

State 114:
text_element -> SUBSCRIPT text END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> SUBSCRIPT text END
-- On VAL_REF reduce production text_element -> SUBSCRIPT text END
-- On Title reduce production text_element -> SUBSCRIPT text END
-- On TYP_REF reduce production text_element -> SUBSCRIPT text END
-- On SUPERSCRIPT reduce production text_element -> SUBSCRIPT text END
-- On SUBSCRIPT reduce production text_element -> SUBSCRIPT text END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> SUBSCRIPT text END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> SUBSCRIPT text END
-- On SEC_REF reduce production text_element -> SUBSCRIPT text END
-- On RIGHT reduce production text_element -> SUBSCRIPT text END
-- On MOD_REF reduce production text_element -> SUBSCRIPT text END
-- On MOD_LIST_REF reduce production text_element -> SUBSCRIPT text END
-- On MODT_REF reduce production text_element -> SUBSCRIPT text END
-- On MET_REF reduce production text_element -> SUBSCRIPT text END
-- On LIST reduce production text_element -> SUBSCRIPT text END
-- On LINK reduce production text_element -> SUBSCRIPT text END
-- On LEFT reduce production text_element -> SUBSCRIPT text END
-- On LATEX reduce production text_element -> SUBSCRIPT text END
-- On ITALIC reduce production text_element -> SUBSCRIPT text END
-- On INDEX_LIST reduce production text_element -> SUBSCRIPT text END
-- On EXC_REF reduce production text_element -> SUBSCRIPT text END
-- On EOF reduce production text_element -> SUBSCRIPT text END
-- On ENUM reduce production text_element -> SUBSCRIPT text END
-- On END_SHORTCUT_LIST reduce production text_element -> SUBSCRIPT text END
-- On END reduce production text_element -> SUBSCRIPT text END
-- On EMP reduce production text_element -> SUBSCRIPT text END
-- On ELE_REF reduce production text_element -> SUBSCRIPT text END
-- On Char reduce production text_element -> SUBSCRIPT text END
-- On CODE_PRE reduce production text_element -> SUBSCRIPT text END
-- On CODE reduce production text_element -> SUBSCRIPT text END
-- On CLT_REF reduce production text_element -> SUBSCRIPT text END
-- On CLA_REF reduce production text_element -> SUBSCRIPT text END
-- On CENTER reduce production text_element -> SUBSCRIPT text END
-- On BOLD reduce production text_element -> SUBSCRIPT text END
-- On BLANK_LINE reduce production text_element -> SUBSCRIPT text END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> SUBSCRIPT text END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> SUBSCRIPT text END
-- On ATT_REF reduce production text_element -> SUBSCRIPT text END

State 115:
text_element -> SUPERSCRIPT text . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 116

State 116:
text_element -> SUPERSCRIPT text END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> SUPERSCRIPT text END
-- On VAL_REF reduce production text_element -> SUPERSCRIPT text END
-- On Title reduce production text_element -> SUPERSCRIPT text END
-- On TYP_REF reduce production text_element -> SUPERSCRIPT text END
-- On SUPERSCRIPT reduce production text_element -> SUPERSCRIPT text END
-- On SUBSCRIPT reduce production text_element -> SUPERSCRIPT text END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> SUPERSCRIPT text END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> SUPERSCRIPT text END
-- On SEC_REF reduce production text_element -> SUPERSCRIPT text END
-- On RIGHT reduce production text_element -> SUPERSCRIPT text END
-- On MOD_REF reduce production text_element -> SUPERSCRIPT text END
-- On MOD_LIST_REF reduce production text_element -> SUPERSCRIPT text END
-- On MODT_REF reduce production text_element -> SUPERSCRIPT text END
-- On MET_REF reduce production text_element -> SUPERSCRIPT text END
-- On LIST reduce production text_element -> SUPERSCRIPT text END
-- On LINK reduce production text_element -> SUPERSCRIPT text END
-- On LEFT reduce production text_element -> SUPERSCRIPT text END
-- On LATEX reduce production text_element -> SUPERSCRIPT text END
-- On ITALIC reduce production text_element -> SUPERSCRIPT text END
-- On INDEX_LIST reduce production text_element -> SUPERSCRIPT text END
-- On EXC_REF reduce production text_element -> SUPERSCRIPT text END
-- On EOF reduce production text_element -> SUPERSCRIPT text END
-- On ENUM reduce production text_element -> SUPERSCRIPT text END
-- On END_SHORTCUT_LIST reduce production text_element -> SUPERSCRIPT text END
-- On END reduce production text_element -> SUPERSCRIPT text END
-- On EMP reduce production text_element -> SUPERSCRIPT text END
-- On ELE_REF reduce production text_element -> SUPERSCRIPT text END
-- On Char reduce production text_element -> SUPERSCRIPT text END
-- On CODE_PRE reduce production text_element -> SUPERSCRIPT text END
-- On CODE reduce production text_element -> SUPERSCRIPT text END
-- On CLT_REF reduce production text_element -> SUPERSCRIPT text END
-- On CLA_REF reduce production text_element -> SUPERSCRIPT text END
-- On CENTER reduce production text_element -> SUPERSCRIPT text END
-- On BOLD reduce production text_element -> SUPERSCRIPT text END
-- On BLANK_LINE reduce production text_element -> SUPERSCRIPT text END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> SUPERSCRIPT text END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> SUPERSCRIPT text END
-- On ATT_REF reduce production text_element -> SUPERSCRIPT text END

State 117:
text_element -> Title text . END [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On END shift to state 118

State 118:
text_element -> Title text END . [ VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF ]
-- On VERB reduce production text_element -> Title text END
-- On VAL_REF reduce production text_element -> Title text END
-- On Title reduce production text_element -> Title text END
-- On TYP_REF reduce production text_element -> Title text END
-- On SUPERSCRIPT reduce production text_element -> Title text END
-- On SUBSCRIPT reduce production text_element -> Title text END
-- On SHORTCUT_LIST_ITEM reduce production text_element -> Title text END
-- On SHORTCUT_ENUM_ITEM reduce production text_element -> Title text END
-- On SEC_REF reduce production text_element -> Title text END
-- On RIGHT reduce production text_element -> Title text END
-- On MOD_REF reduce production text_element -> Title text END
-- On MOD_LIST_REF reduce production text_element -> Title text END
-- On MODT_REF reduce production text_element -> Title text END
-- On MET_REF reduce production text_element -> Title text END
-- On LIST reduce production text_element -> Title text END
-- On LINK reduce production text_element -> Title text END
-- On LEFT reduce production text_element -> Title text END
-- On LATEX reduce production text_element -> Title text END
-- On ITALIC reduce production text_element -> Title text END
-- On INDEX_LIST reduce production text_element -> Title text END
-- On EXC_REF reduce production text_element -> Title text END
-- On EOF reduce production text_element -> Title text END
-- On ENUM reduce production text_element -> Title text END
-- On END_SHORTCUT_LIST reduce production text_element -> Title text END
-- On END reduce production text_element -> Title text END
-- On EMP reduce production text_element -> Title text END
-- On ELE_REF reduce production text_element -> Title text END
-- On Char reduce production text_element -> Title text END
-- On CODE_PRE reduce production text_element -> Title text END
-- On CODE reduce production text_element -> Title text END
-- On CLT_REF reduce production text_element -> Title text END
-- On CLA_REF reduce production text_element -> Title text END
-- On CENTER reduce production text_element -> Title text END
-- On BOLD reduce production text_element -> Title text END
-- On BLANK_LINE reduce production text_element -> Title text END
-- On BEGIN_SHORTCUT_LIST_ITEM reduce production text_element -> Title text END
-- On BEGIN_SHORTCUT_ENUM_ITEM reduce production text_element -> Title text END
-- On ATT_REF reduce production text_element -> Title text END

State 119:
main -> EOF . [ # ]
-- On # reduce production main -> EOF

State 120:
main -> text . EOF [ # ]
-- On EOF shift to state 121

State 121:
main -> text EOF . [ # ]
-- On # reduce production main -> text EOF

State 122:
main' -> main . [ # ]
-- On # accept main

