State 0:
## Known stack suffix:
##
## LR(1) items:
phrase' -> . phrase [ # ]
## Transitions:
-- On LPAREN shift to state 1
-- On EOF shift to state 252
-- On phrase shift to state 253
-- On fundecl shift to state 254
-- On datadecl shift to state 255
## Reductions:

State 1:
## Known stack suffix:
## LPAREN
## LR(1) items:
datadecl -> LPAREN . datalist RPAREN [ # ]
datadecl -> LPAREN . DATA datalist RPAREN [ # ]
fundecl -> LPAREN . FUNCTION fun_name LPAREN params RPAREN sequence RPAREN [ # ]
## Transitions:
-- On FUNCTION shift to state 2
-- On DATA shift to state 224
-- On datalist shift to state 250
## Reductions:
-- On VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR
--   reduce production datalist ->

State 2:
## Known stack suffix:
## LPAREN FUNCTION
## LR(1) items:
fundecl -> LPAREN FUNCTION . fun_name LPAREN params RPAREN sequence RPAREN [ # ]
## Transitions:
-- On STRING shift to state 3
-- On IDENT shift to state 4
-- On fun_name shift to state 5
## Reductions:

State 3:
## Known stack suffix:
## STRING
## LR(1) items:
fun_name -> STRING . [ LPAREN ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production fun_name -> STRING

State 4:
## Known stack suffix:
## IDENT
## LR(1) items:
fun_name -> IDENT . [ LPAREN ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production fun_name -> IDENT

State 5:
## Known stack suffix:
## LPAREN FUNCTION fun_name
## LR(1) items:
fundecl -> LPAREN FUNCTION fun_name . LPAREN params RPAREN sequence RPAREN [ # ]
## Transitions:
-- On LPAREN shift to state 6
## Reductions:

State 6:
## Known stack suffix:
## LPAREN FUNCTION fun_name LPAREN
## LR(1) items:
fundecl -> LPAREN FUNCTION fun_name LPAREN . params RPAREN sequence RPAREN [ # ]
## Transitions:
-- On IDENT shift to state 7
-- On params shift to state 19
-- On oneparam shift to state 222
## Reductions:
-- On RPAREN
--   reduce production params ->

State 7:
## Known stack suffix:
## IDENT
## LR(1) items:
oneparam -> IDENT . COLON machtype [ RPAREN IDENT ]
## Transitions:
-- On COLON shift to state 8
## Reductions:

State 8:
## Known stack suffix:
## IDENT COLON
## LR(1) items:
oneparam -> IDENT COLON . machtype [ RPAREN IDENT ]
## Transitions:
-- On VAL shift to state 9
-- On UNIT shift to state 10
-- On INT shift to state 11
-- On FLOAT shift to state 12
-- On ADDR shift to state 13
-- On machtype shift to state 14
-- On componentlist shift to state 15
-- On component shift to state 18
## Reductions:

State 9:
## Known stack suffix:
## VAL
## LR(1) items:
component -> VAL . [ STAR RPAREN IDENT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production component -> VAL

State 10:
## Known stack suffix:
## UNIT
## LR(1) items:
machtype -> UNIT . [ RPAREN IDENT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production machtype -> UNIT

State 11:
## Known stack suffix:
## INT
## LR(1) items:
component -> INT . [ STAR RPAREN IDENT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production component -> INT

State 12:
## Known stack suffix:
## FLOAT
## LR(1) items:
component -> FLOAT . [ STAR RPAREN IDENT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production component -> FLOAT

State 13:
## Known stack suffix:
## ADDR
## LR(1) items:
component -> ADDR . [ STAR RPAREN IDENT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production component -> ADDR

State 14:
## Known stack suffix:
## IDENT COLON machtype
## LR(1) items:
oneparam -> IDENT COLON machtype . [ RPAREN IDENT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production oneparam -> IDENT COLON machtype

State 15:
## Known stack suffix:
## componentlist
## LR(1) items:
componentlist -> componentlist . STAR component [ STAR RPAREN IDENT ]
machtype -> componentlist . [ RPAREN IDENT ]
## Transitions:
-- On STAR shift to state 16
## Reductions:
-- On RPAREN IDENT
--   reduce production machtype -> componentlist

State 16:
## Known stack suffix:
## componentlist STAR
## LR(1) items:
componentlist -> componentlist STAR . component [ STAR RPAREN IDENT ]
## Transitions:
-- On VAL shift to state 9
-- On INT shift to state 11
-- On FLOAT shift to state 12
-- On ADDR shift to state 13
-- On component shift to state 17
## Reductions:

State 17:
## Known stack suffix:
## componentlist STAR component
## LR(1) items:
componentlist -> componentlist STAR component . [ STAR RPAREN IDENT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production componentlist -> componentlist STAR component

State 18:
## Known stack suffix:
## component
## LR(1) items:
componentlist -> component . [ STAR RPAREN IDENT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production componentlist -> component

State 19:
## Known stack suffix:
## LPAREN FUNCTION fun_name LPAREN params
## LR(1) items:
fundecl -> LPAREN FUNCTION fun_name LPAREN params . RPAREN sequence RPAREN [ # ]
## Transitions:
-- On RPAREN shift to state 20
## Reductions:

State 20:
## Known stack suffix:
## LPAREN FUNCTION fun_name LPAREN params RPAREN
## LR(1) items:
fundecl -> LPAREN FUNCTION fun_name LPAREN params RPAREN . sequence RPAREN [ # ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 220
-- On expr shift to state 35
## Reductions:

State 21:
## Known stack suffix:
## STRING
## LR(1) items:
expr -> STRING . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> STRING

State 22:
## Known stack suffix:
## POINTER
## LR(1) items:
expr -> POINTER . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> POINTER

State 23:
## Known stack suffix:
## LPAREN
## LR(1) items:
expr -> LPAREN . LET letdef sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . ASSIGN IDENT expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . APPLY location expr exprlist machtype RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . EXTCALL STRING exprlist machtype RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . ALLOC exprlist RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . SUBF expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . SUBF expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . unaryop expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . binaryop expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . SEQ sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . IF expr expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . SWITCH INTCONST expr caselist RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . WHILE expr sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . EXIT IDENT exprlist RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . CATCH sequence WITH catch_handlers RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . TRY sequence WITH bind_ident sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . VAL expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . ADDRAREF expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . INTAREF expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . FLOATAREF expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . ADDRASET expr expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . INTASET expr expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN . FLOATASET expr expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On XOR shift to state 24
-- On WHILE shift to state 25
-- On VAL shift to state 37
-- On TRY shift to state 41
-- On SWITCH shift to state 48
-- On SUBI shift to state 60
-- On SUBF shift to state 61
-- On STORE shift to state 66
-- On STAR shift to state 82
-- On SEQ shift to state 83
-- On RAISE shift to state 86
-- On OR shift to state 87
-- On NLTF shift to state 88
-- On NLEF shift to state 89
-- On NGTF shift to state 90
-- On NGEF shift to state 91
-- On NEI shift to state 92
-- On NEF shift to state 93
-- On NEA shift to state 94
-- On MULH shift to state 95
-- On MULF shift to state 96
-- On MODI shift to state 97
-- On LTI shift to state 98
-- On LTF shift to state 99
-- On LTA shift to state 100
-- On LSR shift to state 101
-- On LSL shift to state 102
-- On LOAD shift to state 103
-- On LET shift to state 105
-- On LEI shift to state 117
-- On LEF shift to state 118
-- On LEA shift to state 119
-- On INTOFFLOAT shift to state 120
-- On INTASET shift to state 121
-- On INTAREF shift to state 126
-- On IF shift to state 130
-- On GTI shift to state 135
-- On GTF shift to state 136
-- On GTA shift to state 137
-- On GEI shift to state 138
-- On GEF shift to state 139
-- On GEA shift to state 140
-- On FLOATOFINT shift to state 141
-- On FLOATASET shift to state 142
-- On FLOATAREF shift to state 147
-- On EXTCALL shift to state 151
-- On EXIT shift to state 157
-- On EQI shift to state 161
-- On EQF shift to state 162
-- On EQA shift to state 163
-- On DIVI shift to state 164
-- On DIVF shift to state 165
-- On CHECKBOUND shift to state 166
-- On CATCH shift to state 167
-- On ASSIGN shift to state 177
-- On ASR shift to state 181
-- On APPLY shift to state 182
-- On AND shift to state 189
-- On ALLOC shift to state 190
-- On ADDV shift to state 193
-- On ADDRASET shift to state 194
-- On ADDRAREF shift to state 199
-- On ADDI shift to state 203
-- On ADDF shift to state 204
-- On ADDA shift to state 205
-- On ABSF shift to state 206
-- On unaryop shift to state 207
-- On binaryop shift to state 210
## Reductions:

State 24:
## Known stack suffix:
## XOR
## LR(1) items:
binaryop -> XOR . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> XOR

State 25:
## Known stack suffix:
## LPAREN WHILE
## LR(1) items:
expr -> LPAREN WHILE . expr sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 32
## Reductions:

State 26:
## Known stack suffix:
## LBRACKET
## LR(1) items:
expr -> LBRACKET . RBRACKET [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RBRACKET shift to state 27
## Reductions:

State 27:
## Known stack suffix:
## LBRACKET RBRACKET
## LR(1) items:
expr -> LBRACKET RBRACKET . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LBRACKET RBRACKET

State 28:
## Known stack suffix:
## INTCONST
## LR(1) items:
expr -> INTCONST . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> INTCONST

State 29:
## Known stack suffix:
## IDENT
## LR(1) items:
expr -> IDENT . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> IDENT

State 30:
## Known stack suffix:
## FLOATCONST
## LR(1) items:
expr -> FLOATCONST . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> FLOATCONST

State 31:
## Known stack suffix:
## EXIT
## LR(1) items:
expr -> EXIT . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> EXIT

State 32:
## Known stack suffix:
## LPAREN WHILE expr
## LR(1) items:
expr -> LPAREN WHILE expr . sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 33
-- On expr shift to state 35
## Reductions:

State 33:
## Known stack suffix:
## LPAREN WHILE expr sequence
## LR(1) items:
expr -> LPAREN WHILE expr sequence . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 34
## Reductions:

State 34:
## Known stack suffix:
## LPAREN WHILE expr sequence RPAREN
## LR(1) items:
expr -> LPAREN WHILE expr sequence RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN WHILE expr sequence RPAREN

State 35:
## Known stack suffix:
## expr
## LR(1) items:
sequence -> expr . sequence [ WITH RPAREN CASE AND ]
sequence -> expr . [ WITH RPAREN CASE AND ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 36
-- On expr shift to state 35
## Reductions:
-- On WITH RPAREN CASE AND
--   reduce production sequence -> expr

State 36:
## Known stack suffix:
## expr sequence
## LR(1) items:
sequence -> expr sequence . [ WITH RPAREN CASE AND ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production sequence -> expr sequence

State 37:
## Known stack suffix:
## LPAREN VAL
## LR(1) items:
expr -> LPAREN VAL . expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 38
## Reductions:

State 38:
## Known stack suffix:
## LPAREN VAL expr
## LR(1) items:
expr -> LPAREN VAL expr . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 39
## Reductions:

State 39:
## Known stack suffix:
## LPAREN VAL expr expr
## LR(1) items:
expr -> LPAREN VAL expr expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 40
## Reductions:

State 40:
## Known stack suffix:
## LPAREN VAL expr expr RPAREN
## LR(1) items:
expr -> LPAREN VAL expr expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN VAL expr expr RPAREN

State 41:
## Known stack suffix:
## LPAREN TRY
## LR(1) items:
expr -> LPAREN TRY . sequence WITH bind_ident sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 42
-- On expr shift to state 35
## Reductions:

State 42:
## Known stack suffix:
## LPAREN TRY sequence
## LR(1) items:
expr -> LPAREN TRY sequence . WITH bind_ident sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On WITH shift to state 43
## Reductions:

State 43:
## Known stack suffix:
## LPAREN TRY sequence WITH
## LR(1) items:
expr -> LPAREN TRY sequence WITH . bind_ident sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On IDENT shift to state 44
-- On bind_ident shift to state 45
## Reductions:

State 44:
## Known stack suffix:
## IDENT
## LR(1) items:
bind_ident -> IDENT . [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production bind_ident -> IDENT

State 45:
## Known stack suffix:
## LPAREN TRY sequence WITH bind_ident
## LR(1) items:
expr -> LPAREN TRY sequence WITH bind_ident . sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 46
-- On expr shift to state 35
## Reductions:

State 46:
## Known stack suffix:
## LPAREN TRY sequence WITH bind_ident sequence
## LR(1) items:
expr -> LPAREN TRY sequence WITH bind_ident sequence . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 47
## Reductions:

State 47:
## Known stack suffix:
## LPAREN TRY sequence WITH bind_ident sequence RPAREN
## LR(1) items:
expr -> LPAREN TRY sequence WITH bind_ident sequence RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN TRY sequence WITH bind_ident sequence RPAREN

State 48:
## Known stack suffix:
## LPAREN SWITCH
## LR(1) items:
expr -> LPAREN SWITCH . INTCONST expr caselist RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On INTCONST shift to state 49
## Reductions:

State 49:
## Known stack suffix:
## LPAREN SWITCH INTCONST
## LR(1) items:
expr -> LPAREN SWITCH INTCONST . expr caselist RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 50
## Reductions:

State 50:
## Known stack suffix:
## LPAREN SWITCH INTCONST expr
## LR(1) items:
expr -> LPAREN SWITCH INTCONST expr . caselist RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On CASE shift to state 51
-- On onecase shift to state 55
-- On caselist shift to state 58
## Reductions:
-- On RPAREN
--   reduce production caselist ->

State 51:
## Known stack suffix:
## CASE
## LR(1) items:
onecase -> CASE . INTCONST COLON onecase [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
onecase -> CASE . INTCONST COLON [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On INTCONST shift to state 52
## Reductions:

State 52:
## Known stack suffix:
## CASE INTCONST
## LR(1) items:
onecase -> CASE INTCONST . COLON onecase [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
onecase -> CASE INTCONST . COLON [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On COLON shift to state 53
## Reductions:

State 53:
## Known stack suffix:
## CASE INTCONST COLON
## LR(1) items:
onecase -> CASE INTCONST COLON . onecase [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
onecase -> CASE INTCONST COLON . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On CASE shift to state 51
-- On onecase shift to state 54
## Reductions:
-- On STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT
--   reduce production onecase -> CASE INTCONST COLON

State 54:
## Known stack suffix:
## CASE INTCONST COLON onecase
## LR(1) items:
onecase -> CASE INTCONST COLON onecase . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production onecase -> CASE INTCONST COLON onecase

State 55:
## Known stack suffix:
## onecase
## LR(1) items:
caselist -> onecase . sequence caselist [ RPAREN ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 56
-- On expr shift to state 35
## Reductions:

State 56:
## Known stack suffix:
## onecase sequence
## LR(1) items:
caselist -> onecase sequence . caselist [ RPAREN ]
## Transitions:
-- On CASE shift to state 51
-- On onecase shift to state 55
-- On caselist shift to state 57
## Reductions:
-- On RPAREN
--   reduce production caselist ->

State 57:
## Known stack suffix:
## onecase sequence caselist
## LR(1) items:
caselist -> onecase sequence caselist . [ RPAREN ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production caselist -> onecase sequence caselist

State 58:
## Known stack suffix:
## LPAREN SWITCH INTCONST expr caselist
## LR(1) items:
expr -> LPAREN SWITCH INTCONST expr caselist . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 59
## Reductions:

State 59:
## Known stack suffix:
## LPAREN SWITCH INTCONST expr caselist RPAREN
## LR(1) items:
expr -> LPAREN SWITCH INTCONST expr caselist RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN SWITCH INTCONST expr caselist RPAREN

State 60:
## Known stack suffix:
## SUBI
## LR(1) items:
binaryop -> SUBI . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> SUBI

State 61:
## Known stack suffix:
## LPAREN SUBF
## LR(1) items:
expr -> LPAREN SUBF . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN SUBF . expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 62
## Reductions:

State 62:
## Known stack suffix:
## LPAREN SUBF expr
## LR(1) items:
expr -> LPAREN SUBF expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
expr -> LPAREN SUBF expr . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On RPAREN shift to state 63
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 64
## Reductions:

State 63:
## Known stack suffix:
## LPAREN SUBF expr RPAREN
## LR(1) items:
expr -> LPAREN SUBF expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN SUBF expr RPAREN

State 64:
## Known stack suffix:
## LPAREN SUBF expr expr
## LR(1) items:
expr -> LPAREN SUBF expr expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 65
## Reductions:

State 65:
## Known stack suffix:
## LPAREN SUBF expr expr RPAREN
## LR(1) items:
expr -> LPAREN SUBF expr expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN SUBF expr expr RPAREN

State 66:
## Known stack suffix:
## STORE
## LR(1) items:
binaryop -> STORE . chunk [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On VAL shift to state 67
-- On UNSIGNED shift to state 68
-- On SIGNED shift to state 72
-- On INT shift to state 76
-- On FLOAT64 shift to state 77
-- On FLOAT32 shift to state 78
-- On FLOAT shift to state 79
-- On ADDR shift to state 80
-- On chunk shift to state 81
## Reductions:

State 67:
## Known stack suffix:
## VAL
## LR(1) items:
chunk -> VAL . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> VAL

State 68:
## Known stack suffix:
## UNSIGNED
## LR(1) items:
chunk -> UNSIGNED . BYTE [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
chunk -> UNSIGNED . HALF [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
chunk -> UNSIGNED . INT32 [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On INT32 shift to state 69
-- On HALF shift to state 70
-- On BYTE shift to state 71
## Reductions:

State 69:
## Known stack suffix:
## UNSIGNED INT32
## LR(1) items:
chunk -> UNSIGNED INT32 . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> UNSIGNED INT32

State 70:
## Known stack suffix:
## UNSIGNED HALF
## LR(1) items:
chunk -> UNSIGNED HALF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> UNSIGNED HALF

State 71:
## Known stack suffix:
## UNSIGNED BYTE
## LR(1) items:
chunk -> UNSIGNED BYTE . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> UNSIGNED BYTE

State 72:
## Known stack suffix:
## SIGNED
## LR(1) items:
chunk -> SIGNED . BYTE [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
chunk -> SIGNED . HALF [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
chunk -> SIGNED . INT32 [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On INT32 shift to state 73
-- On HALF shift to state 74
-- On BYTE shift to state 75
## Reductions:

State 73:
## Known stack suffix:
## SIGNED INT32
## LR(1) items:
chunk -> SIGNED INT32 . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> SIGNED INT32

State 74:
## Known stack suffix:
## SIGNED HALF
## LR(1) items:
chunk -> SIGNED HALF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> SIGNED HALF

State 75:
## Known stack suffix:
## SIGNED BYTE
## LR(1) items:
chunk -> SIGNED BYTE . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> SIGNED BYTE

State 76:
## Known stack suffix:
## INT
## LR(1) items:
chunk -> INT . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> INT

State 77:
## Known stack suffix:
## FLOAT64
## LR(1) items:
chunk -> FLOAT64 . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> FLOAT64

State 78:
## Known stack suffix:
## FLOAT32
## LR(1) items:
chunk -> FLOAT32 . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> FLOAT32

State 79:
## Known stack suffix:
## FLOAT
## LR(1) items:
chunk -> FLOAT . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> FLOAT

State 80:
## Known stack suffix:
## ADDR
## LR(1) items:
chunk -> ADDR . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production chunk -> ADDR

State 81:
## Known stack suffix:
## STORE chunk
## LR(1) items:
binaryop -> STORE chunk . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> STORE chunk

State 82:
## Known stack suffix:
## STAR
## LR(1) items:
binaryop -> STAR . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> STAR

State 83:
## Known stack suffix:
## LPAREN SEQ
## LR(1) items:
expr -> LPAREN SEQ . sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 84
-- On expr shift to state 35
## Reductions:

State 84:
## Known stack suffix:
## LPAREN SEQ sequence
## LR(1) items:
expr -> LPAREN SEQ sequence . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 85
## Reductions:

State 85:
## Known stack suffix:
## LPAREN SEQ sequence RPAREN
## LR(1) items:
expr -> LPAREN SEQ sequence RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN SEQ sequence RPAREN

State 86:
## Known stack suffix:
## RAISE
## LR(1) items:
unaryop -> RAISE . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production unaryop -> RAISE

State 87:
## Known stack suffix:
## OR
## LR(1) items:
binaryop -> OR . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> OR

State 88:
## Known stack suffix:
## NLTF
## LR(1) items:
binaryop -> NLTF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> NLTF

State 89:
## Known stack suffix:
## NLEF
## LR(1) items:
binaryop -> NLEF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> NLEF

State 90:
## Known stack suffix:
## NGTF
## LR(1) items:
binaryop -> NGTF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> NGTF

State 91:
## Known stack suffix:
## NGEF
## LR(1) items:
binaryop -> NGEF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> NGEF

State 92:
## Known stack suffix:
## NEI
## LR(1) items:
binaryop -> NEI . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> NEI

State 93:
## Known stack suffix:
## NEF
## LR(1) items:
binaryop -> NEF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> NEF

State 94:
## Known stack suffix:
## NEA
## LR(1) items:
binaryop -> NEA . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> NEA

State 95:
## Known stack suffix:
## MULH
## LR(1) items:
binaryop -> MULH . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> MULH

State 96:
## Known stack suffix:
## MULF
## LR(1) items:
binaryop -> MULF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> MULF

State 97:
## Known stack suffix:
## MODI
## LR(1) items:
binaryop -> MODI . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> MODI

State 98:
## Known stack suffix:
## LTI
## LR(1) items:
binaryop -> LTI . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> LTI

State 99:
## Known stack suffix:
## LTF
## LR(1) items:
binaryop -> LTF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> LTF

State 100:
## Known stack suffix:
## LTA
## LR(1) items:
binaryop -> LTA . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> LTA

State 101:
## Known stack suffix:
## LSR
## LR(1) items:
binaryop -> LSR . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> LSR

State 102:
## Known stack suffix:
## LSL
## LR(1) items:
binaryop -> LSL . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> LSL

State 103:
## Known stack suffix:
## LOAD
## LR(1) items:
unaryop -> LOAD . chunk [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On VAL shift to state 67
-- On UNSIGNED shift to state 68
-- On SIGNED shift to state 72
-- On INT shift to state 76
-- On FLOAT64 shift to state 77
-- On FLOAT32 shift to state 78
-- On FLOAT shift to state 79
-- On ADDR shift to state 80
-- On chunk shift to state 104
## Reductions:

State 104:
## Known stack suffix:
## LOAD chunk
## LR(1) items:
unaryop -> LOAD chunk . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production unaryop -> LOAD chunk

State 105:
## Known stack suffix:
## LPAREN LET
## LR(1) items:
expr -> LPAREN LET . letdef sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On LPAREN shift to state 106
-- On IDENT shift to state 107
-- On oneletdef shift to state 113
-- On letdef shift to state 114
## Reductions:

State 106:
## Known stack suffix:
## LPAREN
## LR(1) items:
letdef -> LPAREN . letdefmult RPAREN [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On IDENT shift to state 107
-- On oneletdef shift to state 109
-- On letdefmult shift to state 111
## Reductions:
-- On RPAREN
--   reduce production letdefmult ->

State 107:
## Known stack suffix:
## IDENT
## LR(1) items:
oneletdef -> IDENT . expr [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 108
## Reductions:

State 108:
## Known stack suffix:
## IDENT expr
## LR(1) items:
oneletdef -> IDENT expr . [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production oneletdef -> IDENT expr

State 109:
## Known stack suffix:
## oneletdef
## LR(1) items:
letdefmult -> oneletdef . letdefmult [ RPAREN ]
## Transitions:
-- On IDENT shift to state 107
-- On oneletdef shift to state 109
-- On letdefmult shift to state 110
## Reductions:
-- On RPAREN
--   reduce production letdefmult ->

State 110:
## Known stack suffix:
## oneletdef letdefmult
## LR(1) items:
letdefmult -> oneletdef letdefmult . [ RPAREN ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production letdefmult -> oneletdef letdefmult

State 111:
## Known stack suffix:
## LPAREN letdefmult
## LR(1) items:
letdef -> LPAREN letdefmult . RPAREN [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On RPAREN shift to state 112
## Reductions:

State 112:
## Known stack suffix:
## LPAREN letdefmult RPAREN
## LR(1) items:
letdef -> LPAREN letdefmult RPAREN . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production letdef -> LPAREN letdefmult RPAREN

State 113:
## Known stack suffix:
## oneletdef
## LR(1) items:
letdef -> oneletdef . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production letdef -> oneletdef

State 114:
## Known stack suffix:
## LPAREN LET letdef
## LR(1) items:
expr -> LPAREN LET letdef . sequence RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 115
-- On expr shift to state 35
## Reductions:

State 115:
## Known stack suffix:
## LPAREN LET letdef sequence
## LR(1) items:
expr -> LPAREN LET letdef sequence . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 116
## Reductions:

State 116:
## Known stack suffix:
## LPAREN LET letdef sequence RPAREN
## LR(1) items:
expr -> LPAREN LET letdef sequence RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN LET letdef sequence RPAREN

State 117:
## Known stack suffix:
## LEI
## LR(1) items:
binaryop -> LEI . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> LEI

State 118:
## Known stack suffix:
## LEF
## LR(1) items:
binaryop -> LEF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> LEF

State 119:
## Known stack suffix:
## LEA
## LR(1) items:
binaryop -> LEA . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> LEA

State 120:
## Known stack suffix:
## INTOFFLOAT
## LR(1) items:
unaryop -> INTOFFLOAT . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production unaryop -> INTOFFLOAT

State 121:
## Known stack suffix:
## LPAREN INTASET
## LR(1) items:
expr -> LPAREN INTASET . expr expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 122
## Reductions:

State 122:
## Known stack suffix:
## LPAREN INTASET expr
## LR(1) items:
expr -> LPAREN INTASET expr . expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 123
## Reductions:

State 123:
## Known stack suffix:
## LPAREN INTASET expr expr
## LR(1) items:
expr -> LPAREN INTASET expr expr . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 124
## Reductions:

State 124:
## Known stack suffix:
## LPAREN INTASET expr expr expr
## LR(1) items:
expr -> LPAREN INTASET expr expr expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 125
## Reductions:

State 125:
## Known stack suffix:
## LPAREN INTASET expr expr expr RPAREN
## LR(1) items:
expr -> LPAREN INTASET expr expr expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN INTASET expr expr expr RPAREN

State 126:
## Known stack suffix:
## LPAREN INTAREF
## LR(1) items:
expr -> LPAREN INTAREF . expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 127
## Reductions:

State 127:
## Known stack suffix:
## LPAREN INTAREF expr
## LR(1) items:
expr -> LPAREN INTAREF expr . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 128
## Reductions:

State 128:
## Known stack suffix:
## LPAREN INTAREF expr expr
## LR(1) items:
expr -> LPAREN INTAREF expr expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 129
## Reductions:

State 129:
## Known stack suffix:
## LPAREN INTAREF expr expr RPAREN
## LR(1) items:
expr -> LPAREN INTAREF expr expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN INTAREF expr expr RPAREN

State 130:
## Known stack suffix:
## LPAREN IF
## LR(1) items:
expr -> LPAREN IF . expr expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 131
## Reductions:

State 131:
## Known stack suffix:
## LPAREN IF expr
## LR(1) items:
expr -> LPAREN IF expr . expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 132
## Reductions:

State 132:
## Known stack suffix:
## LPAREN IF expr expr
## LR(1) items:
expr -> LPAREN IF expr expr . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 133
## Reductions:

State 133:
## Known stack suffix:
## LPAREN IF expr expr expr
## LR(1) items:
expr -> LPAREN IF expr expr expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 134
## Reductions:

State 134:
## Known stack suffix:
## LPAREN IF expr expr expr RPAREN
## LR(1) items:
expr -> LPAREN IF expr expr expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN IF expr expr expr RPAREN

State 135:
## Known stack suffix:
## GTI
## LR(1) items:
binaryop -> GTI . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> GTI

State 136:
## Known stack suffix:
## GTF
## LR(1) items:
binaryop -> GTF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> GTF

State 137:
## Known stack suffix:
## GTA
## LR(1) items:
binaryop -> GTA . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> GTA

State 138:
## Known stack suffix:
## GEI
## LR(1) items:
binaryop -> GEI . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> GEI

State 139:
## Known stack suffix:
## GEF
## LR(1) items:
binaryop -> GEF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> GEF

State 140:
## Known stack suffix:
## GEA
## LR(1) items:
binaryop -> GEA . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> GEA

State 141:
## Known stack suffix:
## FLOATOFINT
## LR(1) items:
unaryop -> FLOATOFINT . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production unaryop -> FLOATOFINT

State 142:
## Known stack suffix:
## LPAREN FLOATASET
## LR(1) items:
expr -> LPAREN FLOATASET . expr expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 143
## Reductions:

State 143:
## Known stack suffix:
## LPAREN FLOATASET expr
## LR(1) items:
expr -> LPAREN FLOATASET expr . expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 144
## Reductions:

State 144:
## Known stack suffix:
## LPAREN FLOATASET expr expr
## LR(1) items:
expr -> LPAREN FLOATASET expr expr . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 145
## Reductions:

State 145:
## Known stack suffix:
## LPAREN FLOATASET expr expr expr
## LR(1) items:
expr -> LPAREN FLOATASET expr expr expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 146
## Reductions:

State 146:
## Known stack suffix:
## LPAREN FLOATASET expr expr expr RPAREN
## LR(1) items:
expr -> LPAREN FLOATASET expr expr expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN FLOATASET expr expr expr RPAREN

State 147:
## Known stack suffix:
## LPAREN FLOATAREF
## LR(1) items:
expr -> LPAREN FLOATAREF . expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 148
## Reductions:

State 148:
## Known stack suffix:
## LPAREN FLOATAREF expr
## LR(1) items:
expr -> LPAREN FLOATAREF expr . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 149
## Reductions:

State 149:
## Known stack suffix:
## LPAREN FLOATAREF expr expr
## LR(1) items:
expr -> LPAREN FLOATAREF expr expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 150
## Reductions:

State 150:
## Known stack suffix:
## LPAREN FLOATAREF expr expr RPAREN
## LR(1) items:
expr -> LPAREN FLOATAREF expr expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN FLOATAREF expr expr RPAREN

State 151:
## Known stack suffix:
## LPAREN EXTCALL
## LR(1) items:
expr -> LPAREN EXTCALL . STRING exprlist machtype RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 152
## Reductions:

State 152:
## Known stack suffix:
## LPAREN EXTCALL STRING
## LR(1) items:
expr -> LPAREN EXTCALL STRING . exprlist machtype RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On exprlist shift to state 153
## Default reduction:
-- After reading the next token, reduce production exprlist ->

State 153:
## Known stack suffix:
## LPAREN EXTCALL STRING exprlist
## LR(1) items:
expr -> LPAREN EXTCALL STRING exprlist . machtype RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
exprlist -> exprlist . expr [ VAL UNIT STRING POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT ADDR ]
## Transitions:
-- On VAL shift to state 9
-- On UNIT shift to state 10
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On INT shift to state 11
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On FLOAT shift to state 12
-- On EXIT shift to state 31
-- On ADDR shift to state 13
-- On machtype shift to state 154
-- On expr shift to state 156
-- On componentlist shift to state 15
-- On component shift to state 18
## Reductions:

State 154:
## Known stack suffix:
## LPAREN EXTCALL STRING exprlist machtype
## LR(1) items:
expr -> LPAREN EXTCALL STRING exprlist machtype . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 155
## Reductions:

State 155:
## Known stack suffix:
## LPAREN EXTCALL STRING exprlist machtype RPAREN
## LR(1) items:
expr -> LPAREN EXTCALL STRING exprlist machtype RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN EXTCALL STRING exprlist machtype RPAREN

State 156:
## Known stack suffix:
## exprlist expr
## LR(1) items:
exprlist -> exprlist expr . [ VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production exprlist -> exprlist expr

State 157:
## Known stack suffix:
## LPAREN EXIT
## LR(1) items:
expr -> LPAREN EXIT . IDENT exprlist RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On IDENT shift to state 158
## Reductions:

State 158:
## Known stack suffix:
## LPAREN EXIT IDENT
## LR(1) items:
expr -> LPAREN EXIT IDENT . exprlist RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On exprlist shift to state 159
## Default reduction:
-- After reading the next token, reduce production exprlist ->

State 159:
## Known stack suffix:
## LPAREN EXIT IDENT exprlist
## LR(1) items:
expr -> LPAREN EXIT IDENT exprlist . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
exprlist -> exprlist . expr [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On STRING shift to state 21
-- On RPAREN shift to state 160
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 156
## Reductions:

State 160:
## Known stack suffix:
## LPAREN EXIT IDENT exprlist RPAREN
## LR(1) items:
expr -> LPAREN EXIT IDENT exprlist RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN EXIT IDENT exprlist RPAREN

State 161:
## Known stack suffix:
## EQI
## LR(1) items:
binaryop -> EQI . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> EQI

State 162:
## Known stack suffix:
## EQF
## LR(1) items:
binaryop -> EQF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> EQF

State 163:
## Known stack suffix:
## EQA
## LR(1) items:
binaryop -> EQA . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> EQA

State 164:
## Known stack suffix:
## DIVI
## LR(1) items:
binaryop -> DIVI . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> DIVI

State 165:
## Known stack suffix:
## DIVF
## LR(1) items:
binaryop -> DIVF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> DIVF

State 166:
## Known stack suffix:
## CHECKBOUND
## LR(1) items:
binaryop -> CHECKBOUND . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> CHECKBOUND

State 167:
## Known stack suffix:
## LPAREN CATCH
## LR(1) items:
expr -> LPAREN CATCH . sequence WITH catch_handlers RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 168
-- On expr shift to state 35
## Reductions:

State 168:
## Known stack suffix:
## LPAREN CATCH sequence
## LR(1) items:
expr -> LPAREN CATCH sequence . WITH catch_handlers RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On WITH shift to state 169
## Reductions:

State 169:
## Known stack suffix:
## LPAREN CATCH sequence WITH
## LR(1) items:
expr -> LPAREN CATCH sequence WITH . catch_handlers RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 170
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 214
-- On expr shift to state 35
-- On catch_handlers shift to state 215
-- On catch_handler shift to state 217
## Reductions:

State 170:
## Known stack suffix:
## LPAREN
## LR(1) items:
catch_handler -> LPAREN . IDENT bind_identlist RPAREN sequence [ RPAREN AND ]
expr -> LPAREN . LET letdef sequence RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . ASSIGN IDENT expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . APPLY location expr exprlist machtype RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . EXTCALL STRING exprlist machtype RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . ALLOC exprlist RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . SUBF expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . SUBF expr expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . unaryop expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . binaryop expr expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . SEQ sequence RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . IF expr expr expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . SWITCH INTCONST expr caselist RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . WHILE expr sequence RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . EXIT IDENT exprlist RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . CATCH sequence WITH catch_handlers RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . TRY sequence WITH bind_ident sequence RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . VAL expr expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . ADDRAREF expr expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . INTAREF expr expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . FLOATAREF expr expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . ADDRASET expr expr expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . INTASET expr expr expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
expr -> LPAREN . FLOATASET expr expr expr RPAREN [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT AND ]
## Transitions:
-- On XOR shift to state 24
-- On WHILE shift to state 25
-- On VAL shift to state 37
-- On TRY shift to state 41
-- On SWITCH shift to state 48
-- On SUBI shift to state 60
-- On SUBF shift to state 61
-- On STORE shift to state 66
-- On STAR shift to state 82
-- On SEQ shift to state 83
-- On RAISE shift to state 86
-- On OR shift to state 87
-- On NLTF shift to state 88
-- On NLEF shift to state 89
-- On NGTF shift to state 90
-- On NGEF shift to state 91
-- On NEI shift to state 92
-- On NEF shift to state 93
-- On NEA shift to state 94
-- On MULH shift to state 95
-- On MULF shift to state 96
-- On MODI shift to state 97
-- On LTI shift to state 98
-- On LTF shift to state 99
-- On LTA shift to state 100
-- On LSR shift to state 101
-- On LSL shift to state 102
-- On LOAD shift to state 103
-- On LET shift to state 105
-- On LEI shift to state 117
-- On LEF shift to state 118
-- On LEA shift to state 119
-- On INTOFFLOAT shift to state 120
-- On INTASET shift to state 121
-- On INTAREF shift to state 126
-- On IF shift to state 130
-- On IDENT shift to state 171
-- On GTI shift to state 135
-- On GTF shift to state 136
-- On GTA shift to state 137
-- On GEI shift to state 138
-- On GEF shift to state 139
-- On GEA shift to state 140
-- On FLOATOFINT shift to state 141
-- On FLOATASET shift to state 142
-- On FLOATAREF shift to state 147
-- On EXTCALL shift to state 151
-- On EXIT shift to state 157
-- On EQI shift to state 161
-- On EQF shift to state 162
-- On EQA shift to state 163
-- On DIVI shift to state 164
-- On DIVF shift to state 165
-- On CHECKBOUND shift to state 166
-- On CATCH shift to state 167
-- On ASSIGN shift to state 177
-- On ASR shift to state 181
-- On APPLY shift to state 182
-- On AND shift to state 189
-- On ALLOC shift to state 190
-- On ADDV shift to state 193
-- On ADDRASET shift to state 194
-- On ADDRAREF shift to state 199
-- On ADDI shift to state 203
-- On ADDF shift to state 204
-- On ADDA shift to state 205
-- On ABSF shift to state 206
-- On unaryop shift to state 207
-- On binaryop shift to state 210
## Reductions:

State 171:
## Known stack suffix:
## LPAREN IDENT
## LR(1) items:
catch_handler -> LPAREN IDENT . bind_identlist RPAREN sequence [ RPAREN AND ]
## Transitions:
-- On IDENT shift to state 44
-- On bind_identlist shift to state 172
-- On bind_ident shift to state 175
## Reductions:
-- On RPAREN
--   reduce production bind_identlist ->

State 172:
## Known stack suffix:
## LPAREN IDENT bind_identlist
## LR(1) items:
catch_handler -> LPAREN IDENT bind_identlist . RPAREN sequence [ RPAREN AND ]
## Transitions:
-- On RPAREN shift to state 173
## Reductions:

State 173:
## Known stack suffix:
## LPAREN IDENT bind_identlist RPAREN
## LR(1) items:
catch_handler -> LPAREN IDENT bind_identlist RPAREN . sequence [ RPAREN AND ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 174
-- On expr shift to state 35
## Reductions:

State 174:
## Known stack suffix:
## LPAREN IDENT bind_identlist RPAREN sequence
## LR(1) items:
catch_handler -> LPAREN IDENT bind_identlist RPAREN sequence . [ RPAREN AND ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production catch_handler -> LPAREN IDENT bind_identlist RPAREN sequence

State 175:
## Known stack suffix:
## bind_ident
## LR(1) items:
bind_identlist -> bind_ident . bind_identlist [ RPAREN ]
## Transitions:
-- On IDENT shift to state 44
-- On bind_identlist shift to state 176
-- On bind_ident shift to state 175
## Reductions:
-- On RPAREN
--   reduce production bind_identlist ->

State 176:
## Known stack suffix:
## bind_ident bind_identlist
## LR(1) items:
bind_identlist -> bind_ident bind_identlist . [ RPAREN ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production bind_identlist -> bind_ident bind_identlist

State 177:
## Known stack suffix:
## LPAREN ASSIGN
## LR(1) items:
expr -> LPAREN ASSIGN . IDENT expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On IDENT shift to state 178
## Reductions:

State 178:
## Known stack suffix:
## LPAREN ASSIGN IDENT
## LR(1) items:
expr -> LPAREN ASSIGN IDENT . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 179
## Reductions:

State 179:
## Known stack suffix:
## LPAREN ASSIGN IDENT expr
## LR(1) items:
expr -> LPAREN ASSIGN IDENT expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 180
## Reductions:

State 180:
## Known stack suffix:
## LPAREN ASSIGN IDENT expr RPAREN
## LR(1) items:
expr -> LPAREN ASSIGN IDENT expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN ASSIGN IDENT expr RPAREN

State 181:
## Known stack suffix:
## ASR
## LR(1) items:
binaryop -> ASR . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> ASR

State 182:
## Known stack suffix:
## LPAREN APPLY
## LR(1) items:
expr -> LPAREN APPLY . location expr exprlist machtype RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On LOCATION shift to state 183
-- On location shift to state 184
## Reductions:
-- On STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT
--   reduce production location ->

State 183:
## Known stack suffix:
## LOCATION
## LR(1) items:
location -> LOCATION . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production location -> LOCATION

State 184:
## Known stack suffix:
## LPAREN APPLY location
## LR(1) items:
expr -> LPAREN APPLY location . expr exprlist machtype RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 185
## Reductions:

State 185:
## Known stack suffix:
## LPAREN APPLY location expr
## LR(1) items:
expr -> LPAREN APPLY location expr . exprlist machtype RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On exprlist shift to state 186
## Default reduction:
-- After reading the next token, reduce production exprlist ->

State 186:
## Known stack suffix:
## LPAREN APPLY location expr exprlist
## LR(1) items:
expr -> LPAREN APPLY location expr exprlist . machtype RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
exprlist -> exprlist . expr [ VAL UNIT STRING POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT ADDR ]
## Transitions:
-- On VAL shift to state 9
-- On UNIT shift to state 10
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On INT shift to state 11
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On FLOAT shift to state 12
-- On EXIT shift to state 31
-- On ADDR shift to state 13
-- On machtype shift to state 187
-- On expr shift to state 156
-- On componentlist shift to state 15
-- On component shift to state 18
## Reductions:

State 187:
## Known stack suffix:
## LPAREN APPLY location expr exprlist machtype
## LR(1) items:
expr -> LPAREN APPLY location expr exprlist machtype . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 188
## Reductions:

State 188:
## Known stack suffix:
## LPAREN APPLY location expr exprlist machtype RPAREN
## LR(1) items:
expr -> LPAREN APPLY location expr exprlist machtype RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN APPLY location expr exprlist machtype RPAREN

State 189:
## Known stack suffix:
## AND
## LR(1) items:
binaryop -> AND . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> AND

State 190:
## Known stack suffix:
## LPAREN ALLOC
## LR(1) items:
expr -> LPAREN ALLOC . exprlist RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On exprlist shift to state 191
## Default reduction:
-- After reading the next token, reduce production exprlist ->

State 191:
## Known stack suffix:
## LPAREN ALLOC exprlist
## LR(1) items:
expr -> LPAREN ALLOC exprlist . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
exprlist -> exprlist . expr [ STRING RPAREN POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
-- On STRING shift to state 21
-- On RPAREN shift to state 192
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 156
## Reductions:

State 192:
## Known stack suffix:
## LPAREN ALLOC exprlist RPAREN
## LR(1) items:
expr -> LPAREN ALLOC exprlist RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN ALLOC exprlist RPAREN

State 193:
## Known stack suffix:
## ADDV
## LR(1) items:
binaryop -> ADDV . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> ADDV

State 194:
## Known stack suffix:
## LPAREN ADDRASET
## LR(1) items:
expr -> LPAREN ADDRASET . expr expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 195
## Reductions:

State 195:
## Known stack suffix:
## LPAREN ADDRASET expr
## LR(1) items:
expr -> LPAREN ADDRASET expr . expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 196
## Reductions:

State 196:
## Known stack suffix:
## LPAREN ADDRASET expr expr
## LR(1) items:
expr -> LPAREN ADDRASET expr expr . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 197
## Reductions:

State 197:
## Known stack suffix:
## LPAREN ADDRASET expr expr expr
## LR(1) items:
expr -> LPAREN ADDRASET expr expr expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 198
## Reductions:

State 198:
## Known stack suffix:
## LPAREN ADDRASET expr expr expr RPAREN
## LR(1) items:
expr -> LPAREN ADDRASET expr expr expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN ADDRASET expr expr expr RPAREN

State 199:
## Known stack suffix:
## LPAREN ADDRAREF
## LR(1) items:
expr -> LPAREN ADDRAREF . expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 200
## Reductions:

State 200:
## Known stack suffix:
## LPAREN ADDRAREF expr
## LR(1) items:
expr -> LPAREN ADDRAREF expr . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 201
## Reductions:

State 201:
## Known stack suffix:
## LPAREN ADDRAREF expr expr
## LR(1) items:
expr -> LPAREN ADDRAREF expr expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 202
## Reductions:

State 202:
## Known stack suffix:
## LPAREN ADDRAREF expr expr RPAREN
## LR(1) items:
expr -> LPAREN ADDRAREF expr expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN ADDRAREF expr expr RPAREN

State 203:
## Known stack suffix:
## ADDI
## LR(1) items:
binaryop -> ADDI . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> ADDI

State 204:
## Known stack suffix:
## ADDF
## LR(1) items:
binaryop -> ADDF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> ADDF

State 205:
## Known stack suffix:
## ADDA
## LR(1) items:
binaryop -> ADDA . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production binaryop -> ADDA

State 206:
## Known stack suffix:
## ABSF
## LR(1) items:
unaryop -> ABSF . [ STRING POINTER LPAREN LBRACKET INTCONST IDENT FLOATCONST EXIT ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production unaryop -> ABSF

State 207:
## Known stack suffix:
## LPAREN unaryop
## LR(1) items:
expr -> LPAREN unaryop . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 208
## Reductions:

State 208:
## Known stack suffix:
## LPAREN unaryop expr
## LR(1) items:
expr -> LPAREN unaryop expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 209
## Reductions:

State 209:
## Known stack suffix:
## LPAREN unaryop expr RPAREN
## LR(1) items:
expr -> LPAREN unaryop expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN unaryop expr RPAREN

State 210:
## Known stack suffix:
## LPAREN binaryop
## LR(1) items:
expr -> LPAREN binaryop . expr expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 211
## Reductions:

State 211:
## Known stack suffix:
## LPAREN binaryop expr
## LR(1) items:
expr -> LPAREN binaryop expr . expr RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 23
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On expr shift to state 212
## Reductions:

State 212:
## Known stack suffix:
## LPAREN binaryop expr expr
## LR(1) items:
expr -> LPAREN binaryop expr expr . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 213
## Reductions:

State 213:
## Known stack suffix:
## LPAREN binaryop expr expr RPAREN
## LR(1) items:
expr -> LPAREN binaryop expr expr RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN binaryop expr expr RPAREN

State 214:
## Known stack suffix:
## sequence
## LR(1) items:
catch_handler -> sequence . [ RPAREN AND ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production catch_handler -> sequence

State 215:
## Known stack suffix:
## LPAREN CATCH sequence WITH catch_handlers
## LR(1) items:
expr -> LPAREN CATCH sequence WITH catch_handlers . RPAREN [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
-- On RPAREN shift to state 216
## Reductions:

State 216:
## Known stack suffix:
## LPAREN CATCH sequence WITH catch_handlers RPAREN
## LR(1) items:
expr -> LPAREN CATCH sequence WITH catch_handlers RPAREN . [ WITH VAL UNIT STRING RPAREN POINTER LPAREN LBRACKET INTCONST INT IDENT FLOATCONST FLOAT EXIT CASE AND ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production expr -> LPAREN CATCH sequence WITH catch_handlers RPAREN

State 217:
## Known stack suffix:
## catch_handler
## LR(1) items:
catch_handlers -> catch_handler . [ RPAREN ]
catch_handlers -> catch_handler . AND catch_handlers [ RPAREN ]
## Transitions:
-- On AND shift to state 218
## Reductions:
-- On RPAREN
--   reduce production catch_handlers -> catch_handler

State 218:
## Known stack suffix:
## catch_handler AND
## LR(1) items:
catch_handlers -> catch_handler AND . catch_handlers [ RPAREN ]
## Transitions:
-- On STRING shift to state 21
-- On POINTER shift to state 22
-- On LPAREN shift to state 170
-- On LBRACKET shift to state 26
-- On INTCONST shift to state 28
-- On IDENT shift to state 29
-- On FLOATCONST shift to state 30
-- On EXIT shift to state 31
-- On sequence shift to state 214
-- On expr shift to state 35
-- On catch_handlers shift to state 219
-- On catch_handler shift to state 217
## Reductions:

State 219:
## Known stack suffix:
## catch_handler AND catch_handlers
## LR(1) items:
catch_handlers -> catch_handler AND catch_handlers . [ RPAREN ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production catch_handlers -> catch_handler AND catch_handlers

State 220:
## Known stack suffix:
## LPAREN FUNCTION fun_name LPAREN params RPAREN sequence
## LR(1) items:
fundecl -> LPAREN FUNCTION fun_name LPAREN params RPAREN sequence . RPAREN [ # ]
## Transitions:
-- On RPAREN shift to state 221
## Reductions:

State 221:
## Known stack suffix:
## LPAREN FUNCTION fun_name LPAREN params RPAREN sequence RPAREN
## LR(1) items:
fundecl -> LPAREN FUNCTION fun_name LPAREN params RPAREN sequence RPAREN . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production fundecl -> LPAREN FUNCTION fun_name LPAREN params RPAREN sequence RPAREN

State 222:
## Known stack suffix:
## oneparam
## LR(1) items:
params -> oneparam . params [ RPAREN ]
## Transitions:
-- On IDENT shift to state 7
-- On params shift to state 223
-- On oneparam shift to state 222
## Reductions:
-- On RPAREN
--   reduce production params ->

State 223:
## Known stack suffix:
## oneparam params
## LR(1) items:
params -> oneparam params . [ RPAREN ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production params -> oneparam params

State 224:
## Known stack suffix:
## LPAREN DATA
## LR(1) items:
datadecl -> LPAREN DATA . datalist RPAREN [ # ]
## Transitions:
-- On datalist shift to state 225
## Default reduction:
-- After reading the next token, reduce production datalist ->

State 225:
## Known stack suffix:
## LPAREN DATA datalist
## LR(1) items:
datadecl -> LPAREN DATA datalist . RPAREN [ # ]
datalist -> datalist . dataitem [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On VAL shift to state 226
-- On STRING shift to state 228
-- On SKIP shift to state 230
-- On RPAREN shift to state 232
-- On KSTRING shift to state 233
-- On INT shift to state 235
-- On HALF shift to state 237
-- On GLOBAL shift to state 239
-- On FLOAT shift to state 241
-- On BYTE shift to state 243
-- On ALIGN shift to state 245
-- On ADDR shift to state 247
-- On dataitem shift to state 249
## Reductions:

State 226:
## Known stack suffix:
## VAL
## LR(1) items:
dataitem -> VAL . STRING [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On STRING shift to state 227
## Reductions:

State 227:
## Known stack suffix:
## VAL STRING
## LR(1) items:
dataitem -> VAL STRING . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> VAL STRING

State 228:
## Known stack suffix:
## STRING
## LR(1) items:
dataitem -> STRING . COLON [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On COLON shift to state 229
## Reductions:

State 229:
## Known stack suffix:
## STRING COLON
## LR(1) items:
dataitem -> STRING COLON . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> STRING COLON

State 230:
## Known stack suffix:
## SKIP
## LR(1) items:
dataitem -> SKIP . INTCONST [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On INTCONST shift to state 231
## Reductions:

State 231:
## Known stack suffix:
## SKIP INTCONST
## LR(1) items:
dataitem -> SKIP INTCONST . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> SKIP INTCONST

State 232:
## Known stack suffix:
## LPAREN DATA datalist RPAREN
## LR(1) items:
datadecl -> LPAREN DATA datalist RPAREN . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production datadecl -> LPAREN DATA datalist RPAREN

State 233:
## Known stack suffix:
## KSTRING
## LR(1) items:
dataitem -> KSTRING . STRING [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On STRING shift to state 234
## Reductions:

State 234:
## Known stack suffix:
## KSTRING STRING
## LR(1) items:
dataitem -> KSTRING STRING . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> KSTRING STRING

State 235:
## Known stack suffix:
## INT
## LR(1) items:
dataitem -> INT . INTCONST [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On INTCONST shift to state 236
## Reductions:

State 236:
## Known stack suffix:
## INT INTCONST
## LR(1) items:
dataitem -> INT INTCONST . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> INT INTCONST

State 237:
## Known stack suffix:
## HALF
## LR(1) items:
dataitem -> HALF . INTCONST [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On INTCONST shift to state 238
## Reductions:

State 238:
## Known stack suffix:
## HALF INTCONST
## LR(1) items:
dataitem -> HALF INTCONST . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> HALF INTCONST

State 239:
## Known stack suffix:
## GLOBAL
## LR(1) items:
dataitem -> GLOBAL . STRING [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On STRING shift to state 240
## Reductions:

State 240:
## Known stack suffix:
## GLOBAL STRING
## LR(1) items:
dataitem -> GLOBAL STRING . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> GLOBAL STRING

State 241:
## Known stack suffix:
## FLOAT
## LR(1) items:
dataitem -> FLOAT . FLOATCONST [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On FLOATCONST shift to state 242
## Reductions:

State 242:
## Known stack suffix:
## FLOAT FLOATCONST
## LR(1) items:
dataitem -> FLOAT FLOATCONST . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> FLOAT FLOATCONST

State 243:
## Known stack suffix:
## BYTE
## LR(1) items:
dataitem -> BYTE . INTCONST [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On INTCONST shift to state 244
## Reductions:

State 244:
## Known stack suffix:
## BYTE INTCONST
## LR(1) items:
dataitem -> BYTE INTCONST . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> BYTE INTCONST

State 245:
## Known stack suffix:
## ALIGN
## LR(1) items:
dataitem -> ALIGN . INTCONST [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On INTCONST shift to state 246
## Reductions:

State 246:
## Known stack suffix:
## ALIGN INTCONST
## LR(1) items:
dataitem -> ALIGN INTCONST . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> ALIGN INTCONST

State 247:
## Known stack suffix:
## ADDR
## LR(1) items:
dataitem -> ADDR . STRING [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On STRING shift to state 248
## Reductions:

State 248:
## Known stack suffix:
## ADDR STRING
## LR(1) items:
dataitem -> ADDR STRING . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production dataitem -> ADDR STRING

State 249:
## Known stack suffix:
## datalist dataitem
## LR(1) items:
datalist -> datalist dataitem . [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production datalist -> datalist dataitem

State 250:
## Known stack suffix:
## LPAREN datalist
## LR(1) items:
datadecl -> LPAREN datalist . RPAREN [ # ]
datalist -> datalist . dataitem [ VAL STRING SKIP RPAREN KSTRING INT HALF GLOBAL FLOAT BYTE ALIGN ADDR ]
## Transitions:
-- On VAL shift to state 226
-- On STRING shift to state 228
-- On SKIP shift to state 230
-- On RPAREN shift to state 251
-- On KSTRING shift to state 233
-- On INT shift to state 235
-- On HALF shift to state 237
-- On GLOBAL shift to state 239
-- On FLOAT shift to state 241
-- On BYTE shift to state 243
-- On ALIGN shift to state 245
-- On ADDR shift to state 247
-- On dataitem shift to state 249
## Reductions:

State 251:
## Known stack suffix:
## LPAREN datalist RPAREN
## LR(1) items:
datadecl -> LPAREN datalist RPAREN . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production datadecl -> LPAREN datalist RPAREN

State 252:
## Known stack suffix:
## EOF
## LR(1) items:
phrase -> EOF . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production phrase -> EOF

State 253:
## Known stack suffix:
## phrase
## LR(1) items:
phrase' -> phrase . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, accept phrase

State 254:
## Known stack suffix:
## fundecl
## LR(1) items:
phrase -> fundecl . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production phrase -> fundecl

State 255:
## Known stack suffix:
## datadecl
## LR(1) items:
phrase -> datadecl . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production phrase -> datadecl

