Grammar has 15 nonterminal symbols, among which 3 start symbols.
Grammar has 15 terminal symbols.
Grammar has 27 productions.
nullable(version) = false
nullable(since) = false
nullable(see_ref) = false
nullable(see_info) = false
nullable(see) = false
nullable(return) = false
nullable(raise_exc) = false
nullable(param) = false
nullable(main) = false
nullable(info_part2) = false
nullable(element_list) = false
nullable(element) = false
nullable(deprecated) = false
nullable(custom) = false
nullable(author) = false
first(version) = T_VERSION
first(since) = T_SINCE
first(see_ref) = See_url See_file See_doc
first(see_info) = See_url See_file See_doc
first(see) = T_SEE
first(return) = T_RETURN
first(raise_exc) = T_RAISES
first(param) = T_PARAM
first(main) = EOF Description
first(info_part2) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR
first(element_list) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR
first(element) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR
first(deprecated) = T_DEPRECATED
first(custom) = T_CUSTOM
first(author) = T_AUTHOR
minimal(version) = (* 2 *) T_VERSION Desc
minimal(since) = (* 2 *) T_SINCE Desc
minimal(see_ref) = (* 1 *) See_url
minimal(see_info) = (* 2 *) See_url Desc
minimal(see) = (* 2 *) T_SEE Desc
minimal(return) = (* 2 *) T_RETURN Desc
minimal(raise_exc) = (* 2 *) T_RAISES Desc
minimal(param) = (* 2 *) T_PARAM Desc
minimal(main) = (* 1 *) Description
minimal(info_part2) = (* 3 *) T_PARAM Desc EOF
minimal(element_list) = (* 2 *) T_PARAM Desc
minimal(element) = (* 2 *) T_PARAM Desc
minimal(deprecated) = (* 2 *) T_DEPRECATED Desc
minimal(custom) = (* 2 *) T_CUSTOM Desc
minimal(author) = (* 2 *) T_AUTHOR Desc
maximal(version) = 2
maximal(since) = 2
maximal(see_ref) = 1
maximal(see_info) = 2
maximal(see) = 2
maximal(return) = 2
maximal(raise_exc) = 2
maximal(param) = 2
maximal(main) = 1
maximal(info_part2) = infinity
maximal(element_list) = infinity
maximal(element) = 2
maximal(deprecated) = 2
maximal(custom) = 2
maximal(author) = 2
follow(version) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR EOF
follow(since) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR EOF
follow(see_ref) = Desc
follow(see_info) = #
follow(see) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR EOF
follow(return) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR EOF
follow(raise_exc) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR EOF
follow(param) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR EOF
follow(main) = #
follow(info_part2) = #
follow(element_list) = EOF
follow(element) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR EOF
follow(deprecated) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR EOF
follow(custom) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR EOF
follow(author) = T_VERSION T_SINCE T_SEE T_RETURN T_RAISES T_PARAM T_DEPRECATED T_CUSTOM T_AUTHOR EOF
Built an LR(0) automaton with 44 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 44 states.
29 out of 44 states have a default reduction.
The action table is 704 entries; 35 non-zero; 70 compressed.
The action table occupies roughly 168 bytes.
The goto table is 792 entries; 26 non-zero; 74 compressed.
The goto table occupies roughly 168 bytes.
The error table occupies roughly 120 bytes.
The default_reduction table occupies roughly 80 bytes.
The lhs table occupies roughly 64 bytes.
The trace table occupies roughly 8 bytes.
