State 0:
enum_' -> . enum_ [ # ]
-- On ENUM shift to state 1
-- On enum_ shift to state 36
-- On enum shift to state 37

State 1:
enum -> ENUM . IDENT LBRACE enum_values rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On IDENT shift to state 2

State 2:
enum -> ENUM IDENT . LBRACE enum_values rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On LBRACE shift to state 3

State 3:
enum -> ENUM IDENT LBRACE . enum_values rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On OPTION shift to state 4
-- On IDENT shift to state 21
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 28
-- On enum_values shift to state 29
-- On enum_value shift to state 33
-- On enum_body_content shift to state 34
-- On RBRACE reduce production enum_values -> 

State 4:
ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION . option_identifier EQUAL constant semicolon [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On LPAREN shift to state 5
-- On IDENT shift to state 8
-- On option_identifier_item shift to state 9
-- On option_identifier shift to state 10

State 5:
option_identifier_item -> LPAREN . IDENT RPAREN [ IDENT EQUAL ]
-- On IDENT shift to state 6

State 6:
option_identifier_item -> LPAREN IDENT . RPAREN [ IDENT EQUAL ]
-- On RPAREN shift to state 7

State 7:
option_identifier_item -> LPAREN IDENT RPAREN . [ IDENT EQUAL ]
-- On IDENT reduce production option_identifier_item -> LPAREN IDENT RPAREN 
-- On EQUAL reduce production option_identifier_item -> LPAREN IDENT RPAREN 

State 8:
option_identifier_item -> IDENT . [ IDENT EQUAL ]
-- On IDENT reduce production option_identifier_item -> IDENT 
-- On EQUAL reduce production option_identifier_item -> IDENT 

State 9:
option_identifier -> option_identifier_item . [ IDENT EQUAL ]
-- On IDENT reduce production option_identifier -> option_identifier_item 
-- On EQUAL reduce production option_identifier -> option_identifier_item 

State 10:
ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier . EQUAL constant semicolon [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
option_identifier -> option_identifier . IDENT [ IDENT EQUAL ]
-- On IDENT shift to state 11
-- On EQUAL shift to state 12

State 11:
option_identifier -> option_identifier IDENT . [ IDENT EQUAL ]
-- On IDENT reduce production option_identifier -> option_identifier IDENT 
-- On EQUAL reduce production option_identifier -> option_identifier IDENT 

State 12:
ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL . constant semicolon [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On STRING shift to state 13
-- On INT shift to state 14
-- On IDENT shift to state 15
-- On FLOAT shift to state 16
-- On constant shift to state 17

State 13:
constant -> STRING . [ SEMICOLON RBRACKET COMMA ]
-- On SEMICOLON reduce production constant -> STRING 
-- On RBRACKET reduce production constant -> STRING 
-- On COMMA reduce production constant -> STRING 

State 14:
constant -> INT . [ SEMICOLON RBRACKET COMMA ]
-- On SEMICOLON reduce production constant -> INT 
-- On RBRACKET reduce production constant -> INT 
-- On COMMA reduce production constant -> INT 

State 15:
constant -> IDENT . [ SEMICOLON RBRACKET COMMA ]
-- On SEMICOLON reduce production constant -> IDENT 
-- On RBRACKET reduce production constant -> IDENT 
-- On COMMA reduce production constant -> IDENT 

State 16:
constant -> FLOAT . [ SEMICOLON RBRACKET COMMA ]
-- On SEMICOLON reduce production constant -> FLOAT 
-- On RBRACKET reduce production constant -> FLOAT 
-- On COMMA reduce production constant -> FLOAT 

State 17:
ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant . semicolon [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 19

State 18:
semicolon -> SEMICOLON . [ SYNTAX SEMICOLON RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On SYNTAX reduce production semicolon -> SEMICOLON 
-- On SEMICOLON reduce production semicolon -> SEMICOLON 
-- On RESERVED reduce production semicolon -> SEMICOLON 
-- On REQUIRED reduce production semicolon -> SEMICOLON 
-- On REPEATED reduce production semicolon -> SEMICOLON 
-- On RBRACE reduce production semicolon -> SEMICOLON 
-- On PACKAGE reduce production semicolon -> SEMICOLON 
-- On OPTIONAL reduce production semicolon -> SEMICOLON 
-- On OPTION reduce production semicolon -> SEMICOLON 
-- On ONE_OF reduce production semicolon -> SEMICOLON 
-- On MESSAGE reduce production semicolon -> SEMICOLON 
-- On MAP reduce production semicolon -> SEMICOLON 
-- On IMPORT reduce production semicolon -> SEMICOLON 
-- On IDENT reduce production semicolon -> SEMICOLON 
-- On EXTENSIONS reduce production semicolon -> SEMICOLON 
-- On EXTEND reduce production semicolon -> SEMICOLON 
-- On EOF reduce production semicolon -> SEMICOLON 
-- On ENUM reduce production semicolon -> SEMICOLON 

State 19:
ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon . [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SYNTAX SEMICOLON RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On SYNTAX reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On RESERVED reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On REQUIRED reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On REPEATED reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On RBRACE reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On PACKAGE reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On OPTIONAL reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On OPTION reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On ONE_OF reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On MESSAGE reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On MAP reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On IMPORT reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On IDENT reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On EXTENSIONS reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On EXTEND reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On EOF reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 
-- On ENUM reduce production ocaml_protoc_1_2_0_pb_parsing_parser_option -> OPTION option_identifier EQUAL constant semicolon 

State 20:
semicolon -> semicolon SEMICOLON . [ SYNTAX SEMICOLON RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On SYNTAX reduce production semicolon -> semicolon SEMICOLON 
-- On SEMICOLON reduce production semicolon -> semicolon SEMICOLON 
-- On RESERVED reduce production semicolon -> semicolon SEMICOLON 
-- On REQUIRED reduce production semicolon -> semicolon SEMICOLON 
-- On REPEATED reduce production semicolon -> semicolon SEMICOLON 
-- On RBRACE reduce production semicolon -> semicolon SEMICOLON 
-- On PACKAGE reduce production semicolon -> semicolon SEMICOLON 
-- On OPTIONAL reduce production semicolon -> semicolon SEMICOLON 
-- On OPTION reduce production semicolon -> semicolon SEMICOLON 
-- On ONE_OF reduce production semicolon -> semicolon SEMICOLON 
-- On MESSAGE reduce production semicolon -> semicolon SEMICOLON 
-- On MAP reduce production semicolon -> semicolon SEMICOLON 
-- On IMPORT reduce production semicolon -> semicolon SEMICOLON 
-- On IDENT reduce production semicolon -> semicolon SEMICOLON 
-- On EXTENSIONS reduce production semicolon -> semicolon SEMICOLON 
-- On EXTEND reduce production semicolon -> semicolon SEMICOLON 
-- On EOF reduce production semicolon -> semicolon SEMICOLON 
-- On ENUM reduce production semicolon -> semicolon SEMICOLON 

State 21:
enum_value -> IDENT . EQUAL INT semicolon [ RBRACE OPTION IDENT EOF ]
enum_value -> IDENT . EQUAL INT [ RBRACE OPTION IDENT EOF ]
enum_value -> IDENT . EQUAL INT COMMA [ RBRACE OPTION IDENT EOF ]
enum_value -> IDENT . COMMA [ RBRACE OPTION IDENT EOF ]
enum_value -> IDENT . SEMICOLON [ RBRACE OPTION IDENT EOF ]
enum_value -> IDENT . [ RBRACE OPTION IDENT EOF ]
-- On SEMICOLON shift to state 22
-- On EQUAL shift to state 23
-- On COMMA shift to state 27
-- On RBRACE reduce production enum_value -> IDENT 
-- On OPTION reduce production enum_value -> IDENT 
-- On IDENT reduce production enum_value -> IDENT 
-- On EOF reduce production enum_value -> IDENT 

State 22:
enum_value -> IDENT SEMICOLON . [ RBRACE OPTION IDENT EOF ]
-- On RBRACE reduce production enum_value -> IDENT SEMICOLON 
-- On OPTION reduce production enum_value -> IDENT SEMICOLON 
-- On IDENT reduce production enum_value -> IDENT SEMICOLON 
-- On EOF reduce production enum_value -> IDENT SEMICOLON 

State 23:
enum_value -> IDENT EQUAL . INT semicolon [ RBRACE OPTION IDENT EOF ]
enum_value -> IDENT EQUAL . INT [ RBRACE OPTION IDENT EOF ]
enum_value -> IDENT EQUAL . INT COMMA [ RBRACE OPTION IDENT EOF ]
-- On INT shift to state 24

State 24:
enum_value -> IDENT EQUAL INT . semicolon [ RBRACE OPTION IDENT EOF ]
enum_value -> IDENT EQUAL INT . [ RBRACE OPTION IDENT EOF ]
enum_value -> IDENT EQUAL INT . COMMA [ RBRACE OPTION IDENT EOF ]
-- On SEMICOLON shift to state 18
-- On COMMA shift to state 25
-- On semicolon shift to state 26
-- On RBRACE reduce production enum_value -> IDENT EQUAL INT 
-- On OPTION reduce production enum_value -> IDENT EQUAL INT 
-- On IDENT reduce production enum_value -> IDENT EQUAL INT 
-- On EOF reduce production enum_value -> IDENT EQUAL INT 

State 25:
enum_value -> IDENT EQUAL INT COMMA . [ RBRACE OPTION IDENT EOF ]
-- On RBRACE reduce production enum_value -> IDENT EQUAL INT COMMA 
-- On OPTION reduce production enum_value -> IDENT EQUAL INT COMMA 
-- On IDENT reduce production enum_value -> IDENT EQUAL INT COMMA 
-- On EOF reduce production enum_value -> IDENT EQUAL INT COMMA 

State 26:
enum_value -> IDENT EQUAL INT semicolon . [ RBRACE OPTION IDENT EOF ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RBRACE OPTION IDENT EOF ]
-- On SEMICOLON shift to state 20
-- On RBRACE reduce production enum_value -> IDENT EQUAL INT semicolon 
-- On OPTION reduce production enum_value -> IDENT EQUAL INT semicolon 
-- On IDENT reduce production enum_value -> IDENT EQUAL INT semicolon 
-- On EOF reduce production enum_value -> IDENT EQUAL INT semicolon 

State 27:
enum_value -> IDENT COMMA . [ RBRACE OPTION IDENT EOF ]
-- On RBRACE reduce production enum_value -> IDENT COMMA 
-- On OPTION reduce production enum_value -> IDENT COMMA 
-- On IDENT reduce production enum_value -> IDENT COMMA 
-- On EOF reduce production enum_value -> IDENT COMMA 

State 28:
enum_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option . [ RBRACE OPTION IDENT ]
-- On RBRACE reduce production enum_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On OPTION reduce production enum_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On IDENT reduce production enum_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 

State 29:
enum -> ENUM IDENT LBRACE enum_values . rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On RBRACE shift to state 30
-- On rbrace shift to state 31

State 30:
rbrace -> RBRACE . [ SYNTAX SEMICOLON RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On SYNTAX reduce production rbrace -> RBRACE 
-- On SEMICOLON reduce production rbrace -> RBRACE 
-- On RESERVED reduce production rbrace -> RBRACE 
-- On REQUIRED reduce production rbrace -> RBRACE 
-- On REPEATED reduce production rbrace -> RBRACE 
-- On RBRACE reduce production rbrace -> RBRACE 
-- On PACKAGE reduce production rbrace -> RBRACE 
-- On OPTIONAL reduce production rbrace -> RBRACE 
-- On OPTION reduce production rbrace -> RBRACE 
-- On ONE_OF reduce production rbrace -> RBRACE 
-- On MESSAGE reduce production rbrace -> RBRACE 
-- On MAP reduce production rbrace -> RBRACE 
-- On IMPORT reduce production rbrace -> RBRACE 
-- On IDENT reduce production rbrace -> RBRACE 
-- On EXTENSIONS reduce production rbrace -> RBRACE 
-- On EXTEND reduce production rbrace -> RBRACE 
-- On EOF reduce production rbrace -> RBRACE 
-- On ENUM reduce production rbrace -> RBRACE 

State 31:
enum -> ENUM IDENT LBRACE enum_values rbrace . [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
rbrace -> rbrace . SEMICOLON [ SYNTAX SEMICOLON RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 32
-- On SYNTAX reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On RESERVED reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On REQUIRED reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On REPEATED reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On RBRACE reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On PACKAGE reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On OPTIONAL reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On OPTION reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On ONE_OF reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On MESSAGE reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On MAP reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On IMPORT reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On IDENT reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On EXTENSIONS reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On EXTEND reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On EOF reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 
-- On ENUM reduce production enum -> ENUM IDENT LBRACE enum_values rbrace 

State 32:
rbrace -> rbrace SEMICOLON . [ SYNTAX SEMICOLON RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On SYNTAX reduce production rbrace -> rbrace SEMICOLON 
-- On SEMICOLON reduce production rbrace -> rbrace SEMICOLON 
-- On RESERVED reduce production rbrace -> rbrace SEMICOLON 
-- On REQUIRED reduce production rbrace -> rbrace SEMICOLON 
-- On REPEATED reduce production rbrace -> rbrace SEMICOLON 
-- On RBRACE reduce production rbrace -> rbrace SEMICOLON 
-- On PACKAGE reduce production rbrace -> rbrace SEMICOLON 
-- On OPTIONAL reduce production rbrace -> rbrace SEMICOLON 
-- On OPTION reduce production rbrace -> rbrace SEMICOLON 
-- On ONE_OF reduce production rbrace -> rbrace SEMICOLON 
-- On MESSAGE reduce production rbrace -> rbrace SEMICOLON 
-- On MAP reduce production rbrace -> rbrace SEMICOLON 
-- On IMPORT reduce production rbrace -> rbrace SEMICOLON 
-- On IDENT reduce production rbrace -> rbrace SEMICOLON 
-- On EXTENSIONS reduce production rbrace -> rbrace SEMICOLON 
-- On EXTEND reduce production rbrace -> rbrace SEMICOLON 
-- On EOF reduce production rbrace -> rbrace SEMICOLON 
-- On ENUM reduce production rbrace -> rbrace SEMICOLON 

State 33:
enum_body_content -> enum_value . [ RBRACE OPTION IDENT ]
-- On RBRACE reduce production enum_body_content -> enum_value 
-- On OPTION reduce production enum_body_content -> enum_value 
-- On IDENT reduce production enum_body_content -> enum_value 

State 34:
enum_values -> enum_body_content . enum_values [ RBRACE ]
-- On OPTION shift to state 4
-- On IDENT shift to state 21
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 28
-- On enum_values shift to state 35
-- On enum_value shift to state 33
-- On enum_body_content shift to state 34
-- On RBRACE reduce production enum_values -> 

State 35:
enum_values -> enum_body_content enum_values . [ RBRACE ]
-- On RBRACE reduce production enum_values -> enum_body_content enum_values 

State 36:
enum_' -> enum_ . [ # ]
-- On # accept enum_

State 37:
enum_ -> enum . EOF [ # ]
-- On EOF shift to state 38

State 38:
enum_ -> enum EOF . [ # ]
-- On # reduce production enum_ -> enum EOF 

State 39:
enum_value_' -> . enum_value_ [ # ]
-- On IDENT shift to state 21
-- On enum_value_ shift to state 40
-- On enum_value shift to state 41

State 40:
enum_value_' -> enum_value_ . [ # ]
-- On # accept enum_value_

State 41:
enum_value_ -> enum_value . EOF [ # ]
-- On EOF shift to state 42

State 42:
enum_value_ -> enum_value EOF . [ # ]
-- On # reduce production enum_value_ -> enum_value EOF 

State 43:
extension_' -> . extension_ [ # ]
-- On EXTENSIONS shift to state 44
-- On extension_ shift to state 54
-- On extension shift to state 55

State 44:
extension -> EXTENSIONS . extension_range_list semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On INT shift to state 45
-- On extension_range_list shift to state 49
-- On extension_range shift to state 51

State 45:
extension_range -> INT . [ SEMICOLON EOF COMMA ]
extension_range -> INT . TO INT [ SEMICOLON EOF COMMA ]
extension_range -> INT . TO MAX [ SEMICOLON EOF COMMA ]
-- On TO shift to state 46
-- On SEMICOLON reduce production extension_range -> INT 
-- On EOF reduce production extension_range -> INT 
-- On COMMA reduce production extension_range -> INT 

State 46:
extension_range -> INT TO . INT [ SEMICOLON EOF COMMA ]
extension_range -> INT TO . MAX [ SEMICOLON EOF COMMA ]
-- On MAX shift to state 47
-- On INT shift to state 48

State 47:
extension_range -> INT TO MAX . [ SEMICOLON EOF COMMA ]
-- On SEMICOLON reduce production extension_range -> INT TO MAX 
-- On EOF reduce production extension_range -> INT TO MAX 
-- On COMMA reduce production extension_range -> INT TO MAX 

State 48:
extension_range -> INT TO INT . [ SEMICOLON EOF COMMA ]
-- On SEMICOLON reduce production extension_range -> INT TO INT 
-- On EOF reduce production extension_range -> INT TO INT 
-- On COMMA reduce production extension_range -> INT TO INT 

State 49:
extension -> EXTENSIONS extension_range_list . semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 50

State 50:
extension -> EXTENSIONS extension_range_list semicolon . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On RESERVED reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On REQUIRED reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On REPEATED reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On RBRACE reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On OPTIONAL reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On OPTION reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On ONE_OF reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On MESSAGE reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On MAP reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On IDENT reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On EXTENSIONS reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On EOF reduce production extension -> EXTENSIONS extension_range_list semicolon 
-- On ENUM reduce production extension -> EXTENSIONS extension_range_list semicolon 

State 51:
extension_range_list -> extension_range . [ SEMICOLON EOF ]
extension_range_list -> extension_range . COMMA extension_range_list [ SEMICOLON EOF ]
-- On COMMA shift to state 52
-- On SEMICOLON reduce production extension_range_list -> extension_range 
-- On EOF reduce production extension_range_list -> extension_range 

State 52:
extension_range_list -> extension_range COMMA . extension_range_list [ SEMICOLON EOF ]
-- On INT shift to state 45
-- On extension_range_list shift to state 53
-- On extension_range shift to state 51

State 53:
extension_range_list -> extension_range COMMA extension_range_list . [ SEMICOLON EOF ]
-- On SEMICOLON reduce production extension_range_list -> extension_range COMMA extension_range_list 
-- On EOF reduce production extension_range_list -> extension_range COMMA extension_range_list 

State 54:
extension_' -> extension_ . [ # ]
-- On # accept extension_

State 55:
extension_ -> extension . EOF [ # ]
-- On EOF shift to state 56

State 56:
extension_ -> extension EOF . [ # ]
-- On # reduce production extension_ -> extension EOF 

State 57:
extension_range_list_' -> . extension_range_list_ [ # ]
-- On INT shift to state 45
-- On extension_range_list_ shift to state 58
-- On extension_range_list shift to state 59
-- On extension_range shift to state 51

State 58:
extension_range_list_' -> extension_range_list_ . [ # ]
-- On # accept extension_range_list_

State 59:
extension_range_list_ -> extension_range_list . EOF [ # ]
-- On EOF shift to state 60

State 60:
extension_range_list_ -> extension_range_list EOF . [ # ]
-- On # reduce production extension_range_list_ -> extension_range_list EOF 

State 61:
field_options_' -> . field_options_ [ # ]
-- On LBRACKET shift to state 62
-- On field_options_ shift to state 77
-- On field_options shift to state 78

State 62:
field_options -> LBRACKET . field_option_list RBRACKET [ SEMICOLON EOF ]
field_options -> LBRACKET . RBRACKET [ SEMICOLON EOF ]
-- On RBRACKET shift to state 63
-- On LPAREN shift to state 64
-- On IDENT shift to state 69
-- On field_option_list shift to state 72
-- On field_option shift to state 74

State 63:
field_options -> LBRACKET RBRACKET . [ SEMICOLON EOF ]
-- On SEMICOLON reduce production field_options -> LBRACKET RBRACKET 
-- On EOF reduce production field_options -> LBRACKET RBRACKET 

State 64:
field_option -> LPAREN . IDENT RPAREN EQUAL constant [ RBRACKET COMMA ]
-- On IDENT shift to state 65

State 65:
field_option -> LPAREN IDENT . RPAREN EQUAL constant [ RBRACKET COMMA ]
-- On RPAREN shift to state 66

State 66:
field_option -> LPAREN IDENT RPAREN . EQUAL constant [ RBRACKET COMMA ]
-- On EQUAL shift to state 67

State 67:
field_option -> LPAREN IDENT RPAREN EQUAL . constant [ RBRACKET COMMA ]
-- On STRING shift to state 13
-- On INT shift to state 14
-- On IDENT shift to state 15
-- On FLOAT shift to state 16
-- On constant shift to state 68

State 68:
field_option -> LPAREN IDENT RPAREN EQUAL constant . [ RBRACKET COMMA ]
-- On RBRACKET reduce production field_option -> LPAREN IDENT RPAREN EQUAL constant 
-- On COMMA reduce production field_option -> LPAREN IDENT RPAREN EQUAL constant 

State 69:
field_option -> IDENT . EQUAL constant [ RBRACKET COMMA ]
-- On EQUAL shift to state 70

State 70:
field_option -> IDENT EQUAL . constant [ RBRACKET COMMA ]
-- On STRING shift to state 13
-- On INT shift to state 14
-- On IDENT shift to state 15
-- On FLOAT shift to state 16
-- On constant shift to state 71

State 71:
field_option -> IDENT EQUAL constant . [ RBRACKET COMMA ]
-- On RBRACKET reduce production field_option -> IDENT EQUAL constant 
-- On COMMA reduce production field_option -> IDENT EQUAL constant 

State 72:
field_options -> LBRACKET field_option_list . RBRACKET [ SEMICOLON EOF ]
-- On RBRACKET shift to state 73

State 73:
field_options -> LBRACKET field_option_list RBRACKET . [ SEMICOLON EOF ]
-- On SEMICOLON reduce production field_options -> LBRACKET field_option_list RBRACKET 
-- On EOF reduce production field_options -> LBRACKET field_option_list RBRACKET 

State 74:
field_option_list -> field_option . [ RBRACKET ]
field_option_list -> field_option . COMMA field_option_list [ RBRACKET ]
-- On COMMA shift to state 75
-- On RBRACKET reduce production field_option_list -> field_option 

State 75:
field_option_list -> field_option COMMA . field_option_list [ RBRACKET ]
-- On LPAREN shift to state 64
-- On IDENT shift to state 69
-- On field_option_list shift to state 76
-- On field_option shift to state 74

State 76:
field_option_list -> field_option COMMA field_option_list . [ RBRACKET ]
-- On RBRACKET reduce production field_option_list -> field_option COMMA field_option_list 

State 77:
field_options_' -> field_options_ . [ # ]
-- On # accept field_options_

State 78:
field_options_ -> field_options . EOF [ # ]
-- On EOF shift to state 79

State 79:
field_options_ -> field_options EOF . [ # ]
-- On # reduce production field_options_ -> field_options EOF 

State 80:
import_' -> . import_ [ # ]
-- On IMPORT shift to state 81
-- On import_ shift to state 90
-- On import shift to state 91

State 81:
import -> IMPORT . STRING semicolon [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
import -> IMPORT . PUBLIC STRING semicolon [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
import -> IMPORT . IDENT STRING semicolon [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On STRING shift to state 82
-- On PUBLIC shift to state 84
-- On IDENT shift to state 87

State 82:
import -> IMPORT STRING . semicolon [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 83

State 83:
import -> IMPORT STRING semicolon . [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SYNTAX SEMICOLON PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On SYNTAX reduce production import -> IMPORT STRING semicolon 
-- On PACKAGE reduce production import -> IMPORT STRING semicolon 
-- On OPTION reduce production import -> IMPORT STRING semicolon 
-- On MESSAGE reduce production import -> IMPORT STRING semicolon 
-- On IMPORT reduce production import -> IMPORT STRING semicolon 
-- On EXTEND reduce production import -> IMPORT STRING semicolon 
-- On EOF reduce production import -> IMPORT STRING semicolon 
-- On ENUM reduce production import -> IMPORT STRING semicolon 

State 84:
import -> IMPORT PUBLIC . STRING semicolon [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On STRING shift to state 85

State 85:
import -> IMPORT PUBLIC STRING . semicolon [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 86

State 86:
import -> IMPORT PUBLIC STRING semicolon . [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SYNTAX SEMICOLON PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On SYNTAX reduce production import -> IMPORT PUBLIC STRING semicolon 
-- On PACKAGE reduce production import -> IMPORT PUBLIC STRING semicolon 
-- On OPTION reduce production import -> IMPORT PUBLIC STRING semicolon 
-- On MESSAGE reduce production import -> IMPORT PUBLIC STRING semicolon 
-- On IMPORT reduce production import -> IMPORT PUBLIC STRING semicolon 
-- On EXTEND reduce production import -> IMPORT PUBLIC STRING semicolon 
-- On EOF reduce production import -> IMPORT PUBLIC STRING semicolon 
-- On ENUM reduce production import -> IMPORT PUBLIC STRING semicolon 

State 87:
import -> IMPORT IDENT . STRING semicolon [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On STRING shift to state 88

State 88:
import -> IMPORT IDENT STRING . semicolon [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 89

State 89:
import -> IMPORT IDENT STRING semicolon . [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SYNTAX SEMICOLON PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On SYNTAX reduce production import -> IMPORT IDENT STRING semicolon 
-- On PACKAGE reduce production import -> IMPORT IDENT STRING semicolon 
-- On OPTION reduce production import -> IMPORT IDENT STRING semicolon 
-- On MESSAGE reduce production import -> IMPORT IDENT STRING semicolon 
-- On IMPORT reduce production import -> IMPORT IDENT STRING semicolon 
-- On EXTEND reduce production import -> IMPORT IDENT STRING semicolon 
-- On EOF reduce production import -> IMPORT IDENT STRING semicolon 
-- On ENUM reduce production import -> IMPORT IDENT STRING semicolon 

State 90:
import_' -> import_ . [ # ]
-- On # accept import_

State 91:
import_ -> import . EOF [ # ]
-- On EOF shift to state 92

State 92:
import_ -> import EOF . [ # ]
-- On # reduce production import_ -> import EOF 

State 93:
message_' -> . message_ [ # ]
-- On MESSAGE shift to state 94
-- On message_ shift to state 178
-- On message shift to state 179

State 94:
message -> MESSAGE . IDENT LBRACE message_body_content_list rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
message -> MESSAGE . IDENT LBRACE rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On IDENT shift to state 95

State 95:
message -> MESSAGE IDENT . LBRACE message_body_content_list rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
message -> MESSAGE IDENT . LBRACE rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On LBRACE shift to state 96

State 96:
message -> MESSAGE IDENT LBRACE . message_body_content_list rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
message -> MESSAGE IDENT LBRACE . rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On RESERVED shift to state 97
-- On REQUIRED shift to state 100
-- On REPEATED shift to state 101
-- On RBRACE shift to state 30
-- On OPTIONAL shift to state 102
-- On OPTION shift to state 4
-- On ONE_OF shift to state 103
-- On MESSAGE shift to state 94
-- On MAP shift to state 138
-- On IDENT shift to state 150
-- On EXTENSIONS shift to state 44
-- On ENUM shift to state 1
-- On reserved shift to state 157
-- On rbrace shift to state 158
-- On oneof shift to state 159
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 160
-- On normal_field shift to state 161
-- On message_body_content_list shift to state 162
-- On message_body_content shift to state 164
-- On message shift to state 166
-- On map shift to state 167
-- On label shift to state 168
-- On extension shift to state 176
-- On enum shift to state 177

State 97:
reserved -> RESERVED . extension_range_list semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On INT shift to state 45
-- On extension_range_list shift to state 98
-- On extension_range shift to state 51

State 98:
reserved -> RESERVED extension_range_list . semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 99

State 99:
reserved -> RESERVED extension_range_list semicolon . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On RESERVED reduce production reserved -> RESERVED extension_range_list semicolon 
-- On REQUIRED reduce production reserved -> RESERVED extension_range_list semicolon 
-- On REPEATED reduce production reserved -> RESERVED extension_range_list semicolon 
-- On RBRACE reduce production reserved -> RESERVED extension_range_list semicolon 
-- On OPTIONAL reduce production reserved -> RESERVED extension_range_list semicolon 
-- On OPTION reduce production reserved -> RESERVED extension_range_list semicolon 
-- On ONE_OF reduce production reserved -> RESERVED extension_range_list semicolon 
-- On MESSAGE reduce production reserved -> RESERVED extension_range_list semicolon 
-- On MAP reduce production reserved -> RESERVED extension_range_list semicolon 
-- On IDENT reduce production reserved -> RESERVED extension_range_list semicolon 
-- On EXTENSIONS reduce production reserved -> RESERVED extension_range_list semicolon 
-- On EOF reduce production reserved -> RESERVED extension_range_list semicolon 
-- On ENUM reduce production reserved -> RESERVED extension_range_list semicolon 

State 100:
label -> REQUIRED . [ IDENT ]
-- On IDENT reduce production label -> REQUIRED 

State 101:
label -> REPEATED . [ IDENT ]
-- On IDENT reduce production label -> REPEATED 

State 102:
label -> OPTIONAL . [ IDENT ]
-- On IDENT reduce production label -> OPTIONAL 

State 103:
oneof -> ONE_OF . IDENT LBRACE oneof_field_list rbrace [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
oneof -> ONE_OF . LBRACE oneof_field_list rbrace [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On LBRACE shift to state 104
-- On IDENT shift to state 134

State 104:
oneof -> ONE_OF LBRACE . oneof_field_list rbrace [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On IDENT shift to state 105
-- On oneof_field_list shift to state 130
-- On oneof_field shift to state 132
-- On RBRACE reduce production oneof_field_list -> 

State 105:
oneof_field -> IDENT . field_name EQUAL INT field_options semicolon [ RBRACE IDENT ]
oneof_field -> IDENT . field_name EQUAL INT semicolon [ RBRACE IDENT ]
-- On TO shift to state 106
-- On SYNTAX shift to state 107
-- On RESERVED shift to state 108
-- On REQUIRED shift to state 109
-- On REPEATED shift to state 110
-- On PUBLIC shift to state 111
-- On PACKAGE shift to state 112
-- On OPTIONAL shift to state 113
-- On OPTION shift to state 114
-- On ONE_OF shift to state 115
-- On MESSAGE shift to state 116
-- On MAX shift to state 117
-- On MAP shift to state 118
-- On IMPORT shift to state 119
-- On IDENT shift to state 120
-- On EXTENSIONS shift to state 121
-- On EXTEND shift to state 122
-- On ENUM shift to state 123
-- On field_name shift to state 124

State 106:
field_name -> TO . [ EQUAL ]
-- On EQUAL reduce production field_name -> TO 

State 107:
field_name -> SYNTAX . [ EQUAL ]
-- On EQUAL reduce production field_name -> SYNTAX 

State 108:
field_name -> RESERVED . [ EQUAL ]
-- On EQUAL reduce production field_name -> RESERVED 

State 109:
field_name -> REQUIRED . [ EQUAL ]
-- On EQUAL reduce production field_name -> REQUIRED 

State 110:
field_name -> REPEATED . [ EQUAL ]
-- On EQUAL reduce production field_name -> REPEATED 

State 111:
field_name -> PUBLIC . [ EQUAL ]
-- On EQUAL reduce production field_name -> PUBLIC 

State 112:
field_name -> PACKAGE . [ EQUAL ]
-- On EQUAL reduce production field_name -> PACKAGE 

State 113:
field_name -> OPTIONAL . [ EQUAL ]
-- On EQUAL reduce production field_name -> OPTIONAL 

State 114:
field_name -> OPTION . [ EQUAL ]
-- On EQUAL reduce production field_name -> OPTION 

State 115:
field_name -> ONE_OF . [ EQUAL ]
-- On EQUAL reduce production field_name -> ONE_OF 

State 116:
field_name -> MESSAGE . [ EQUAL ]
-- On EQUAL reduce production field_name -> MESSAGE 

State 117:
field_name -> MAX . [ EQUAL ]
-- On EQUAL reduce production field_name -> MAX 

State 118:
field_name -> MAP . [ EQUAL ]
-- On EQUAL reduce production field_name -> MAP 

State 119:
field_name -> IMPORT . [ EQUAL ]
-- On EQUAL reduce production field_name -> IMPORT 

State 120:
field_name -> IDENT . [ EQUAL ]
-- On EQUAL reduce production field_name -> IDENT 

State 121:
field_name -> EXTENSIONS . [ EQUAL ]
-- On EQUAL reduce production field_name -> EXTENSIONS 

State 122:
field_name -> EXTEND . [ EQUAL ]
-- On EQUAL reduce production field_name -> EXTEND 

State 123:
field_name -> ENUM . [ EQUAL ]
-- On EQUAL reduce production field_name -> ENUM 

State 124:
oneof_field -> IDENT field_name . EQUAL INT field_options semicolon [ RBRACE IDENT ]
oneof_field -> IDENT field_name . EQUAL INT semicolon [ RBRACE IDENT ]
-- On EQUAL shift to state 125

State 125:
oneof_field -> IDENT field_name EQUAL . INT field_options semicolon [ RBRACE IDENT ]
oneof_field -> IDENT field_name EQUAL . INT semicolon [ RBRACE IDENT ]
-- On INT shift to state 126

State 126:
oneof_field -> IDENT field_name EQUAL INT . field_options semicolon [ RBRACE IDENT ]
oneof_field -> IDENT field_name EQUAL INT . semicolon [ RBRACE IDENT ]
-- On SEMICOLON shift to state 18
-- On LBRACKET shift to state 62
-- On semicolon shift to state 127
-- On field_options shift to state 128

State 127:
oneof_field -> IDENT field_name EQUAL INT semicolon . [ RBRACE IDENT ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RBRACE IDENT ]
-- On SEMICOLON shift to state 20
-- On RBRACE reduce production oneof_field -> IDENT field_name EQUAL INT semicolon 
-- On IDENT reduce production oneof_field -> IDENT field_name EQUAL INT semicolon 

State 128:
oneof_field -> IDENT field_name EQUAL INT field_options . semicolon [ RBRACE IDENT ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 129

State 129:
oneof_field -> IDENT field_name EQUAL INT field_options semicolon . [ RBRACE IDENT ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RBRACE IDENT ]
-- On SEMICOLON shift to state 20
-- On RBRACE reduce production oneof_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On IDENT reduce production oneof_field -> IDENT field_name EQUAL INT field_options semicolon 

State 130:
oneof -> ONE_OF LBRACE oneof_field_list . rbrace [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On RBRACE shift to state 30
-- On rbrace shift to state 131

State 131:
oneof -> ONE_OF LBRACE oneof_field_list rbrace . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
rbrace -> rbrace . SEMICOLON [ SEMICOLON RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 32
-- On RESERVED reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On REQUIRED reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On REPEATED reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On RBRACE reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On OPTIONAL reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On OPTION reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On ONE_OF reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On MESSAGE reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On MAP reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On IDENT reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On EXTENSIONS reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On EOF reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 
-- On ENUM reduce production oneof -> ONE_OF LBRACE oneof_field_list rbrace 

State 132:
oneof_field_list -> oneof_field . oneof_field_list [ RBRACE ]
-- On IDENT shift to state 105
-- On oneof_field_list shift to state 133
-- On oneof_field shift to state 132
-- On RBRACE reduce production oneof_field_list -> 

State 133:
oneof_field_list -> oneof_field oneof_field_list . [ RBRACE ]
-- On RBRACE reduce production oneof_field_list -> oneof_field oneof_field_list 

State 134:
oneof -> ONE_OF IDENT . LBRACE oneof_field_list rbrace [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On LBRACE shift to state 135

State 135:
oneof -> ONE_OF IDENT LBRACE . oneof_field_list rbrace [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On IDENT shift to state 105
-- On oneof_field_list shift to state 136
-- On oneof_field shift to state 132
-- On RBRACE reduce production oneof_field_list -> 

State 136:
oneof -> ONE_OF IDENT LBRACE oneof_field_list . rbrace [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On RBRACE shift to state 30
-- On rbrace shift to state 137

State 137:
oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
rbrace -> rbrace . SEMICOLON [ SEMICOLON RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 32
-- On RESERVED reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On REQUIRED reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On REPEATED reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On RBRACE reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On OPTIONAL reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On OPTION reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On ONE_OF reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On MESSAGE reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On MAP reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On IDENT reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On EXTENSIONS reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On EOF reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 
-- On ENUM reduce production oneof -> ONE_OF IDENT LBRACE oneof_field_list rbrace 

State 138:
map -> MAP . LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
map -> MAP . LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On LANGLEB shift to state 139

State 139:
map -> MAP LANGLEB . IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
map -> MAP LANGLEB . IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On IDENT shift to state 140

State 140:
map -> MAP LANGLEB IDENT . COMMA IDENT RANGLEB field_name EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
map -> MAP LANGLEB IDENT . COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On COMMA shift to state 141

State 141:
map -> MAP LANGLEB IDENT COMMA . IDENT RANGLEB field_name EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
map -> MAP LANGLEB IDENT COMMA . IDENT RANGLEB field_name EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On IDENT shift to state 142

State 142:
map -> MAP LANGLEB IDENT COMMA IDENT . RANGLEB field_name EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
map -> MAP LANGLEB IDENT COMMA IDENT . RANGLEB field_name EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On RANGLEB shift to state 143

State 143:
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB . field_name EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB . field_name EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On TO shift to state 106
-- On SYNTAX shift to state 107
-- On RESERVED shift to state 108
-- On REQUIRED shift to state 109
-- On REPEATED shift to state 110
-- On PUBLIC shift to state 111
-- On PACKAGE shift to state 112
-- On OPTIONAL shift to state 113
-- On OPTION shift to state 114
-- On ONE_OF shift to state 115
-- On MESSAGE shift to state 116
-- On MAX shift to state 117
-- On MAP shift to state 118
-- On IMPORT shift to state 119
-- On IDENT shift to state 120
-- On EXTENSIONS shift to state 121
-- On EXTEND shift to state 122
-- On ENUM shift to state 123
-- On field_name shift to state 144

State 144:
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name . EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name . EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On EQUAL shift to state 145

State 145:
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL . INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL . INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On INT shift to state 146

State 146:
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT . semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT . field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On SEMICOLON shift to state 18
-- On LBRACKET shift to state 62
-- On semicolon shift to state 147
-- On field_options shift to state 148

State 147:
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On SEMICOLON shift to state 20
-- On RESERVED reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On REQUIRED reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On REPEATED reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On RBRACE reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On OPTIONAL reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On OPTION reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On ONE_OF reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On MESSAGE reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On MAP reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On IDENT reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On EXTENSIONS reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 
-- On ENUM reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT semicolon 

State 148:
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options . semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 149

State 149:
map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On SEMICOLON shift to state 20
-- On RESERVED reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On REQUIRED reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On REPEATED reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On RBRACE reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On OPTIONAL reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On OPTION reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On ONE_OF reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On MESSAGE reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On MAP reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On IDENT reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On EXTENSIONS reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 
-- On ENUM reduce production map -> MAP LANGLEB IDENT COMMA IDENT RANGLEB field_name EQUAL INT field_options semicolon 

State 150:
normal_field -> IDENT . field_name EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
normal_field -> IDENT . field_name EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On TO shift to state 106
-- On SYNTAX shift to state 107
-- On RESERVED shift to state 108
-- On REQUIRED shift to state 109
-- On REPEATED shift to state 110
-- On PUBLIC shift to state 111
-- On PACKAGE shift to state 112
-- On OPTIONAL shift to state 113
-- On OPTION shift to state 114
-- On ONE_OF shift to state 115
-- On MESSAGE shift to state 116
-- On MAX shift to state 117
-- On MAP shift to state 118
-- On IMPORT shift to state 119
-- On IDENT shift to state 120
-- On EXTENSIONS shift to state 121
-- On EXTEND shift to state 122
-- On ENUM shift to state 123
-- On field_name shift to state 151

State 151:
normal_field -> IDENT field_name . EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
normal_field -> IDENT field_name . EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On EQUAL shift to state 152

State 152:
normal_field -> IDENT field_name EQUAL . INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
normal_field -> IDENT field_name EQUAL . INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On INT shift to state 153

State 153:
normal_field -> IDENT field_name EQUAL INT . field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
normal_field -> IDENT field_name EQUAL INT . semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On LBRACKET shift to state 62
-- On semicolon shift to state 154
-- On field_options shift to state 155

State 154:
normal_field -> IDENT field_name EQUAL INT semicolon . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On RESERVED reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On REQUIRED reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On REPEATED reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On RBRACE reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On OPTIONAL reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On OPTION reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On ONE_OF reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On MESSAGE reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On MAP reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On IDENT reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On EXTENSIONS reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On EOF reduce production normal_field -> IDENT field_name EQUAL INT semicolon 
-- On ENUM reduce production normal_field -> IDENT field_name EQUAL INT semicolon 

State 155:
normal_field -> IDENT field_name EQUAL INT field_options . semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 156

State 156:
normal_field -> IDENT field_name EQUAL INT field_options semicolon . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On RESERVED reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On REQUIRED reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On REPEATED reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On RBRACE reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On OPTIONAL reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On OPTION reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On ONE_OF reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On MESSAGE reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On MAP reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On IDENT reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On EXTENSIONS reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On EOF reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 
-- On ENUM reduce production normal_field -> IDENT field_name EQUAL INT field_options semicolon 

State 157:
message_body_content -> reserved . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On RESERVED reduce production message_body_content -> reserved 
-- On REQUIRED reduce production message_body_content -> reserved 
-- On REPEATED reduce production message_body_content -> reserved 
-- On RBRACE reduce production message_body_content -> reserved 
-- On OPTIONAL reduce production message_body_content -> reserved 
-- On OPTION reduce production message_body_content -> reserved 
-- On ONE_OF reduce production message_body_content -> reserved 
-- On MESSAGE reduce production message_body_content -> reserved 
-- On MAP reduce production message_body_content -> reserved 
-- On IDENT reduce production message_body_content -> reserved 
-- On EXTENSIONS reduce production message_body_content -> reserved 
-- On ENUM reduce production message_body_content -> reserved 

State 158:
message -> MESSAGE IDENT LBRACE rbrace . [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
rbrace -> rbrace . SEMICOLON [ SYNTAX SEMICOLON RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 32
-- On SYNTAX reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On RESERVED reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On REQUIRED reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On REPEATED reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On RBRACE reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On PACKAGE reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On OPTIONAL reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On OPTION reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On ONE_OF reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On MESSAGE reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On MAP reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On IMPORT reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On IDENT reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On EXTENSIONS reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On EXTEND reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On EOF reduce production message -> MESSAGE IDENT LBRACE rbrace 
-- On ENUM reduce production message -> MESSAGE IDENT LBRACE rbrace 

State 159:
message_body_content -> oneof . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On RESERVED reduce production message_body_content -> oneof 
-- On REQUIRED reduce production message_body_content -> oneof 
-- On REPEATED reduce production message_body_content -> oneof 
-- On RBRACE reduce production message_body_content -> oneof 
-- On OPTIONAL reduce production message_body_content -> oneof 
-- On OPTION reduce production message_body_content -> oneof 
-- On ONE_OF reduce production message_body_content -> oneof 
-- On MESSAGE reduce production message_body_content -> oneof 
-- On MAP reduce production message_body_content -> oneof 
-- On IDENT reduce production message_body_content -> oneof 
-- On EXTENSIONS reduce production message_body_content -> oneof 
-- On ENUM reduce production message_body_content -> oneof 

State 160:
message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On RESERVED reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On REQUIRED reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On REPEATED reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On RBRACE reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On OPTIONAL reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On OPTION reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On ONE_OF reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On MESSAGE reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On MAP reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On IDENT reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On EXTENSIONS reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 
-- On ENUM reduce production message_body_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 

State 161:
message_body_content -> normal_field . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On RESERVED reduce production message_body_content -> normal_field 
-- On REQUIRED reduce production message_body_content -> normal_field 
-- On REPEATED reduce production message_body_content -> normal_field 
-- On RBRACE reduce production message_body_content -> normal_field 
-- On OPTIONAL reduce production message_body_content -> normal_field 
-- On OPTION reduce production message_body_content -> normal_field 
-- On ONE_OF reduce production message_body_content -> normal_field 
-- On MESSAGE reduce production message_body_content -> normal_field 
-- On MAP reduce production message_body_content -> normal_field 
-- On IDENT reduce production message_body_content -> normal_field 
-- On EXTENSIONS reduce production message_body_content -> normal_field 
-- On ENUM reduce production message_body_content -> normal_field 

State 162:
message -> MESSAGE IDENT LBRACE message_body_content_list . rbrace [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On RBRACE shift to state 30
-- On rbrace shift to state 163

State 163:
message -> MESSAGE IDENT LBRACE message_body_content_list rbrace . [ SYNTAX RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
rbrace -> rbrace . SEMICOLON [ SYNTAX SEMICOLON RESERVED REQUIRED REPEATED RBRACE PACKAGE OPTIONAL OPTION ONE_OF MESSAGE MAP IMPORT IDENT EXTENSIONS EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 32
-- On SYNTAX reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On RESERVED reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On REQUIRED reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On REPEATED reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On RBRACE reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On PACKAGE reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On OPTIONAL reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On OPTION reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On ONE_OF reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On MESSAGE reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On MAP reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On IMPORT reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On IDENT reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On EXTENSIONS reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On EXTEND reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On EOF reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 
-- On ENUM reduce production message -> MESSAGE IDENT LBRACE message_body_content_list rbrace 

State 164:
message_body_content_list -> message_body_content . [ RBRACE ]
message_body_content_list -> message_body_content . message_body_content_list [ RBRACE ]
-- On RESERVED shift to state 97
-- On REQUIRED shift to state 100
-- On REPEATED shift to state 101
-- On OPTIONAL shift to state 102
-- On OPTION shift to state 4
-- On ONE_OF shift to state 103
-- On MESSAGE shift to state 94
-- On MAP shift to state 138
-- On IDENT shift to state 150
-- On EXTENSIONS shift to state 44
-- On ENUM shift to state 1
-- On reserved shift to state 157
-- On oneof shift to state 159
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 160
-- On normal_field shift to state 161
-- On message_body_content_list shift to state 165
-- On message_body_content shift to state 164
-- On message shift to state 166
-- On map shift to state 167
-- On label shift to state 168
-- On extension shift to state 176
-- On enum shift to state 177
-- On RBRACE reduce production message_body_content_list -> message_body_content 

State 165:
message_body_content_list -> message_body_content message_body_content_list . [ RBRACE ]
-- On RBRACE reduce production message_body_content_list -> message_body_content message_body_content_list 

State 166:
message_body_content -> message . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On RESERVED reduce production message_body_content -> message 
-- On REQUIRED reduce production message_body_content -> message 
-- On REPEATED reduce production message_body_content -> message 
-- On RBRACE reduce production message_body_content -> message 
-- On OPTIONAL reduce production message_body_content -> message 
-- On OPTION reduce production message_body_content -> message 
-- On ONE_OF reduce production message_body_content -> message 
-- On MESSAGE reduce production message_body_content -> message 
-- On MAP reduce production message_body_content -> message 
-- On IDENT reduce production message_body_content -> message 
-- On EXTENSIONS reduce production message_body_content -> message 
-- On ENUM reduce production message_body_content -> message 

State 167:
message_body_content -> map . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On RESERVED reduce production message_body_content -> map 
-- On REQUIRED reduce production message_body_content -> map 
-- On REPEATED reduce production message_body_content -> map 
-- On RBRACE reduce production message_body_content -> map 
-- On OPTIONAL reduce production message_body_content -> map 
-- On OPTION reduce production message_body_content -> map 
-- On ONE_OF reduce production message_body_content -> map 
-- On MESSAGE reduce production message_body_content -> map 
-- On MAP reduce production message_body_content -> map 
-- On IDENT reduce production message_body_content -> map 
-- On EXTENSIONS reduce production message_body_content -> map 
-- On ENUM reduce production message_body_content -> map 

State 168:
normal_field -> label . IDENT field_name EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
normal_field -> label . IDENT field_name EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On IDENT shift to state 169

State 169:
normal_field -> label IDENT . field_name EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
normal_field -> label IDENT . field_name EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On TO shift to state 106
-- On SYNTAX shift to state 107
-- On RESERVED shift to state 108
-- On REQUIRED shift to state 109
-- On REPEATED shift to state 110
-- On PUBLIC shift to state 111
-- On PACKAGE shift to state 112
-- On OPTIONAL shift to state 113
-- On OPTION shift to state 114
-- On ONE_OF shift to state 115
-- On MESSAGE shift to state 116
-- On MAX shift to state 117
-- On MAP shift to state 118
-- On IMPORT shift to state 119
-- On IDENT shift to state 120
-- On EXTENSIONS shift to state 121
-- On EXTEND shift to state 122
-- On ENUM shift to state 123
-- On field_name shift to state 170

State 170:
normal_field -> label IDENT field_name . EQUAL INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
normal_field -> label IDENT field_name . EQUAL INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On EQUAL shift to state 171

State 171:
normal_field -> label IDENT field_name EQUAL . INT field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
normal_field -> label IDENT field_name EQUAL . INT semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On INT shift to state 172

State 172:
normal_field -> label IDENT field_name EQUAL INT . field_options semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
normal_field -> label IDENT field_name EQUAL INT . semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On LBRACKET shift to state 62
-- On semicolon shift to state 173
-- On field_options shift to state 174

State 173:
normal_field -> label IDENT field_name EQUAL INT semicolon . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On RESERVED reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On REQUIRED reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On REPEATED reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On RBRACE reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On OPTIONAL reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On OPTION reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On ONE_OF reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On MESSAGE reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On MAP reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On IDENT reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On EXTENSIONS reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On EOF reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 
-- On ENUM reduce production normal_field -> label IDENT field_name EQUAL INT semicolon 

State 174:
normal_field -> label IDENT field_name EQUAL INT field_options . semicolon [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 175

State 175:
normal_field -> label IDENT field_name EQUAL INT field_options semicolon . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SEMICOLON RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On RESERVED reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On REQUIRED reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On REPEATED reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On RBRACE reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On OPTIONAL reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On OPTION reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On ONE_OF reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On MESSAGE reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On MAP reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On IDENT reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On EXTENSIONS reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On EOF reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 
-- On ENUM reduce production normal_field -> label IDENT field_name EQUAL INT field_options semicolon 

State 176:
message_body_content -> extension . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On RESERVED reduce production message_body_content -> extension 
-- On REQUIRED reduce production message_body_content -> extension 
-- On REPEATED reduce production message_body_content -> extension 
-- On RBRACE reduce production message_body_content -> extension 
-- On OPTIONAL reduce production message_body_content -> extension 
-- On OPTION reduce production message_body_content -> extension 
-- On ONE_OF reduce production message_body_content -> extension 
-- On MESSAGE reduce production message_body_content -> extension 
-- On MAP reduce production message_body_content -> extension 
-- On IDENT reduce production message_body_content -> extension 
-- On EXTENSIONS reduce production message_body_content -> extension 
-- On ENUM reduce production message_body_content -> extension 

State 177:
message_body_content -> enum . [ RESERVED REQUIRED REPEATED RBRACE OPTIONAL OPTION ONE_OF MESSAGE MAP IDENT EXTENSIONS ENUM ]
-- On RESERVED reduce production message_body_content -> enum 
-- On REQUIRED reduce production message_body_content -> enum 
-- On REPEATED reduce production message_body_content -> enum 
-- On RBRACE reduce production message_body_content -> enum 
-- On OPTIONAL reduce production message_body_content -> enum 
-- On OPTION reduce production message_body_content -> enum 
-- On ONE_OF reduce production message_body_content -> enum 
-- On MESSAGE reduce production message_body_content -> enum 
-- On MAP reduce production message_body_content -> enum 
-- On IDENT reduce production message_body_content -> enum 
-- On EXTENSIONS reduce production message_body_content -> enum 
-- On ENUM reduce production message_body_content -> enum 

State 178:
message_' -> message_ . [ # ]
-- On # accept message_

State 179:
message_ -> message . EOF [ # ]
-- On EOF shift to state 180

State 180:
message_ -> message EOF . [ # ]
-- On # reduce production message_ -> message EOF 

State 181:
normal_field_' -> . normal_field_ [ # ]
-- On REQUIRED shift to state 100
-- On REPEATED shift to state 101
-- On OPTIONAL shift to state 102
-- On IDENT shift to state 150
-- On normal_field_ shift to state 182
-- On normal_field shift to state 183
-- On label shift to state 168

State 182:
normal_field_' -> normal_field_ . [ # ]
-- On # accept normal_field_

State 183:
normal_field_ -> normal_field . EOF [ # ]
-- On EOF shift to state 184

State 184:
normal_field_ -> normal_field EOF . [ # ]
-- On # reduce production normal_field_ -> normal_field EOF 

State 185:
oneof_' -> . oneof_ [ # ]
-- On ONE_OF shift to state 103
-- On oneof_ shift to state 186
-- On oneof shift to state 187

State 186:
oneof_' -> oneof_ . [ # ]
-- On # accept oneof_

State 187:
oneof_ -> oneof . EOF [ # ]
-- On EOF shift to state 188

State 188:
oneof_ -> oneof EOF . [ # ]
-- On # reduce production oneof_ -> oneof EOF 

State 189:
option_' -> . option_ [ # ]
-- On OPTION shift to state 4
-- On option_ shift to state 190
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 191

State 190:
option_' -> option_ . [ # ]
-- On # accept option_

State 191:
option_ -> ocaml_protoc_1_2_0_pb_parsing_parser_option . EOF [ # ]
-- On EOF shift to state 192

State 192:
option_ -> ocaml_protoc_1_2_0_pb_parsing_parser_option EOF . [ # ]
-- On # reduce production option_ -> ocaml_protoc_1_2_0_pb_parsing_parser_option EOF 

State 193:
proto_' -> . proto_ [ # ]
-- On SYNTAX shift to state 194
-- On PACKAGE shift to state 198
-- On OPTION shift to state 4
-- On MESSAGE shift to state 94
-- On IMPORT shift to state 81
-- On EXTEND shift to state 201
-- On ENUM shift to state 1
-- On syntax shift to state 209
-- On proto_content shift to state 212
-- On proto_ shift to state 224
-- On proto shift to state 225
-- On package_declaration shift to state 211
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 214
-- On message shift to state 216
-- On import shift to state 218
-- On extend shift to state 220
-- On enum shift to state 222

State 194:
syntax -> SYNTAX . EQUAL STRING semicolon [ PACKAGE OPTION MESSAGE IMPORT EXTEND ENUM ]
-- On EQUAL shift to state 195

State 195:
syntax -> SYNTAX EQUAL . STRING semicolon [ PACKAGE OPTION MESSAGE IMPORT EXTEND ENUM ]
-- On STRING shift to state 196

State 196:
syntax -> SYNTAX EQUAL STRING . semicolon [ PACKAGE OPTION MESSAGE IMPORT EXTEND ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 197

State 197:
semicolon -> semicolon . SEMICOLON [ SEMICOLON PACKAGE OPTION MESSAGE IMPORT EXTEND ENUM ]
syntax -> SYNTAX EQUAL STRING semicolon . [ PACKAGE OPTION MESSAGE IMPORT EXTEND ENUM ]
-- On SEMICOLON shift to state 20
-- On PACKAGE reduce production syntax -> SYNTAX EQUAL STRING semicolon 
-- On OPTION reduce production syntax -> SYNTAX EQUAL STRING semicolon 
-- On MESSAGE reduce production syntax -> SYNTAX EQUAL STRING semicolon 
-- On IMPORT reduce production syntax -> SYNTAX EQUAL STRING semicolon 
-- On EXTEND reduce production syntax -> SYNTAX EQUAL STRING semicolon 
-- On ENUM reduce production syntax -> SYNTAX EQUAL STRING semicolon 

State 198:
package_declaration -> PACKAGE . IDENT semicolon [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On IDENT shift to state 199

State 199:
package_declaration -> PACKAGE IDENT . semicolon [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 18
-- On semicolon shift to state 200

State 200:
package_declaration -> PACKAGE IDENT semicolon . [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
semicolon -> semicolon . SEMICOLON [ SYNTAX SEMICOLON PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 20
-- On SYNTAX reduce production package_declaration -> PACKAGE IDENT semicolon 
-- On PACKAGE reduce production package_declaration -> PACKAGE IDENT semicolon 
-- On OPTION reduce production package_declaration -> PACKAGE IDENT semicolon 
-- On MESSAGE reduce production package_declaration -> PACKAGE IDENT semicolon 
-- On IMPORT reduce production package_declaration -> PACKAGE IDENT semicolon 
-- On EXTEND reduce production package_declaration -> PACKAGE IDENT semicolon 
-- On EOF reduce production package_declaration -> PACKAGE IDENT semicolon 
-- On ENUM reduce production package_declaration -> PACKAGE IDENT semicolon 

State 201:
extend -> EXTEND . IDENT LBRACE normal_field_list rbrace [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
extend -> EXTEND . IDENT LBRACE rbrace [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On IDENT shift to state 202

State 202:
extend -> EXTEND IDENT . LBRACE normal_field_list rbrace [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
extend -> EXTEND IDENT . LBRACE rbrace [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On LBRACE shift to state 203

State 203:
extend -> EXTEND IDENT LBRACE . normal_field_list rbrace [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
extend -> EXTEND IDENT LBRACE . rbrace [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On REQUIRED shift to state 100
-- On REPEATED shift to state 101
-- On RBRACE shift to state 30
-- On OPTIONAL shift to state 102
-- On IDENT shift to state 150
-- On rbrace shift to state 204
-- On normal_field_list shift to state 205
-- On normal_field shift to state 207
-- On label shift to state 168

State 204:
extend -> EXTEND IDENT LBRACE rbrace . [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
rbrace -> rbrace . SEMICOLON [ SYNTAX SEMICOLON PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 32
-- On SYNTAX reduce production extend -> EXTEND IDENT LBRACE rbrace 
-- On PACKAGE reduce production extend -> EXTEND IDENT LBRACE rbrace 
-- On OPTION reduce production extend -> EXTEND IDENT LBRACE rbrace 
-- On MESSAGE reduce production extend -> EXTEND IDENT LBRACE rbrace 
-- On IMPORT reduce production extend -> EXTEND IDENT LBRACE rbrace 
-- On EXTEND reduce production extend -> EXTEND IDENT LBRACE rbrace 
-- On EOF reduce production extend -> EXTEND IDENT LBRACE rbrace 
-- On ENUM reduce production extend -> EXTEND IDENT LBRACE rbrace 

State 205:
extend -> EXTEND IDENT LBRACE normal_field_list . rbrace [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On RBRACE shift to state 30
-- On rbrace shift to state 206

State 206:
extend -> EXTEND IDENT LBRACE normal_field_list rbrace . [ SYNTAX PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
rbrace -> rbrace . SEMICOLON [ SYNTAX SEMICOLON PACKAGE OPTION MESSAGE IMPORT EXTEND EOF ENUM ]
-- On SEMICOLON shift to state 32
-- On SYNTAX reduce production extend -> EXTEND IDENT LBRACE normal_field_list rbrace 
-- On PACKAGE reduce production extend -> EXTEND IDENT LBRACE normal_field_list rbrace 
-- On OPTION reduce production extend -> EXTEND IDENT LBRACE normal_field_list rbrace 
-- On MESSAGE reduce production extend -> EXTEND IDENT LBRACE normal_field_list rbrace 
-- On IMPORT reduce production extend -> EXTEND IDENT LBRACE normal_field_list rbrace 
-- On EXTEND reduce production extend -> EXTEND IDENT LBRACE normal_field_list rbrace 
-- On EOF reduce production extend -> EXTEND IDENT LBRACE normal_field_list rbrace 
-- On ENUM reduce production extend -> EXTEND IDENT LBRACE normal_field_list rbrace 

State 207:
normal_field_list -> normal_field . [ RBRACE ]
normal_field_list -> normal_field . normal_field_list [ RBRACE ]
-- On REQUIRED shift to state 100
-- On REPEATED shift to state 101
-- On OPTIONAL shift to state 102
-- On IDENT shift to state 150
-- On normal_field_list shift to state 208
-- On normal_field shift to state 207
-- On label shift to state 168
-- On RBRACE reduce production normal_field_list -> normal_field 

State 208:
normal_field_list -> normal_field normal_field_list . [ RBRACE ]
-- On RBRACE reduce production normal_field_list -> normal_field normal_field_list 

State 209:
proto -> syntax . proto_content [ EOF ]
-- On PACKAGE shift to state 198
-- On OPTION shift to state 4
-- On MESSAGE shift to state 94
-- On IMPORT shift to state 81
-- On EXTEND shift to state 201
-- On ENUM shift to state 1
-- On proto_content shift to state 210
-- On package_declaration shift to state 211
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 214
-- On message shift to state 216
-- On import shift to state 218
-- On extend shift to state 220
-- On enum shift to state 222

State 210:
proto -> syntax proto_content . [ EOF ]
-- On EOF reduce production proto -> syntax proto_content 

State 211:
proto_content -> package_declaration . [ EOF ]
proto_content -> package_declaration . proto [ EOF ]
-- On SYNTAX shift to state 194
-- On PACKAGE shift to state 198
-- On OPTION shift to state 4
-- On MESSAGE shift to state 94
-- On IMPORT shift to state 81
-- On EXTEND shift to state 201
-- On ENUM shift to state 1
-- On syntax shift to state 209
-- On proto_content shift to state 212
-- On proto shift to state 213
-- On package_declaration shift to state 211
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 214
-- On message shift to state 216
-- On import shift to state 218
-- On extend shift to state 220
-- On enum shift to state 222
-- On EOF reduce production proto_content -> package_declaration 

State 212:
proto -> proto_content . [ EOF ]
-- On EOF reduce production proto -> proto_content 

State 213:
proto_content -> package_declaration proto . [ EOF ]
-- On EOF reduce production proto_content -> package_declaration proto 

State 214:
proto_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option . [ EOF ]
proto_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option . proto [ EOF ]
-- On SYNTAX shift to state 194
-- On PACKAGE shift to state 198
-- On OPTION shift to state 4
-- On MESSAGE shift to state 94
-- On IMPORT shift to state 81
-- On EXTEND shift to state 201
-- On ENUM shift to state 1
-- On syntax shift to state 209
-- On proto_content shift to state 212
-- On proto shift to state 215
-- On package_declaration shift to state 211
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 214
-- On message shift to state 216
-- On import shift to state 218
-- On extend shift to state 220
-- On enum shift to state 222
-- On EOF reduce production proto_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option 

State 215:
proto_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option proto . [ EOF ]
-- On EOF reduce production proto_content -> ocaml_protoc_1_2_0_pb_parsing_parser_option proto 

State 216:
proto_content -> message . [ EOF ]
proto_content -> message . proto [ EOF ]
-- On SYNTAX shift to state 194
-- On PACKAGE shift to state 198
-- On OPTION shift to state 4
-- On MESSAGE shift to state 94
-- On IMPORT shift to state 81
-- On EXTEND shift to state 201
-- On ENUM shift to state 1
-- On syntax shift to state 209
-- On proto_content shift to state 212
-- On proto shift to state 217
-- On package_declaration shift to state 211
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 214
-- On message shift to state 216
-- On import shift to state 218
-- On extend shift to state 220
-- On enum shift to state 222
-- On EOF reduce production proto_content -> message 

State 217:
proto_content -> message proto . [ EOF ]
-- On EOF reduce production proto_content -> message proto 

State 218:
proto_content -> import . [ EOF ]
proto_content -> import . proto [ EOF ]
-- On SYNTAX shift to state 194
-- On PACKAGE shift to state 198
-- On OPTION shift to state 4
-- On MESSAGE shift to state 94
-- On IMPORT shift to state 81
-- On EXTEND shift to state 201
-- On ENUM shift to state 1
-- On syntax shift to state 209
-- On proto_content shift to state 212
-- On proto shift to state 219
-- On package_declaration shift to state 211
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 214
-- On message shift to state 216
-- On import shift to state 218
-- On extend shift to state 220
-- On enum shift to state 222
-- On EOF reduce production proto_content -> import 

State 219:
proto_content -> import proto . [ EOF ]
-- On EOF reduce production proto_content -> import proto 

State 220:
proto_content -> extend . [ EOF ]
proto_content -> extend . proto [ EOF ]
-- On SYNTAX shift to state 194
-- On PACKAGE shift to state 198
-- On OPTION shift to state 4
-- On MESSAGE shift to state 94
-- On IMPORT shift to state 81
-- On EXTEND shift to state 201
-- On ENUM shift to state 1
-- On syntax shift to state 209
-- On proto_content shift to state 212
-- On proto shift to state 221
-- On package_declaration shift to state 211
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 214
-- On message shift to state 216
-- On import shift to state 218
-- On extend shift to state 220
-- On enum shift to state 222
-- On EOF reduce production proto_content -> extend 

State 221:
proto_content -> extend proto . [ EOF ]
-- On EOF reduce production proto_content -> extend proto 

State 222:
proto_content -> enum . [ EOF ]
proto_content -> enum . proto [ EOF ]
-- On SYNTAX shift to state 194
-- On PACKAGE shift to state 198
-- On OPTION shift to state 4
-- On MESSAGE shift to state 94
-- On IMPORT shift to state 81
-- On EXTEND shift to state 201
-- On ENUM shift to state 1
-- On syntax shift to state 209
-- On proto_content shift to state 212
-- On proto shift to state 223
-- On package_declaration shift to state 211
-- On ocaml_protoc_1_2_0_pb_parsing_parser_option shift to state 214
-- On message shift to state 216
-- On import shift to state 218
-- On extend shift to state 220
-- On enum shift to state 222
-- On EOF reduce production proto_content -> enum 

State 223:
proto_content -> enum proto . [ EOF ]
-- On EOF reduce production proto_content -> enum proto 

State 224:
proto_' -> proto_ . [ # ]
-- On # accept proto_

State 225:
proto_ -> proto . EOF [ # ]
-- On EOF shift to state 226

State 226:
proto_ -> proto EOF . [ # ]
-- On # reduce production proto_ -> proto EOF 

State 227:
reserved_' -> . reserved_ [ # ]
-- On RESERVED shift to state 97
-- On reserved_ shift to state 228
-- On reserved shift to state 229

State 228:
reserved_' -> reserved_ . [ # ]
-- On # accept reserved_

State 229:
reserved_ -> reserved . EOF [ # ]
-- On EOF shift to state 230

State 230:
reserved_ -> reserved EOF . [ # ]
-- On # reduce production reserved_ -> reserved EOF 

