File "on-error-reduce-unreachable.mly", line 10, characters 0-3:
Warning: symbol bar is unreachable from any of the start symbol(s).
Grammar has 1 nonterminal symbols, among which 1 start symbols.
Grammar has 2 terminal symbols.
Grammar has 1 productions.
nullable(main) = false
first(main) = A
minimal(main) = (* 2 *) A B
maximal(main) = 2
follow(main) = #
Built an LR(0) automaton with 4 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 4 states.
2 out of 4 states have a default reduction.
The action table is 12 entries; 2 non-zero; 6 compressed.
The action table occupies roughly 104 bytes.
The goto table is 8 entries; 1 non-zero; 5 compressed.
The goto table occupies roughly 104 bytes.
The error table occupies roughly 40 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
