Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 2 terminal symbols.
Grammar has 5 productions.
nullable(option2(B)) = true
nullable(option1(A)) = true
nullable(main) = true
first(option2(B)) = B
first(option1(A)) = A
first(main) = B A
minimal(option2(B)) = (* 0 *)
minimal(option1(A)) = (* 0 *)
minimal(main) = (* 0 *)
maximal(option2(B)) = 1
maximal(option1(A)) = 1
maximal(main) = 2
follow(option2(B)) = #
follow(option1(A)) = B #
follow(main) = #
Built an LR(0) automaton with 6 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 6 states.
Warning: 3 end-of-stream conflicts were arbitrarily resolved.
File "options.mly", line 16, characters 11-19:
Warning: production option2(B) -> is never reduced.
Warning: in total, 1 production is never reduced.
4 out of 6 states have a default reduction.
The action table is 18 entries; 3 non-zero; 9 compressed.
The action table occupies roughly 104 bytes.
The goto table is 24 entries; 3 non-zero; 9 compressed.
The goto table occupies roughly 104 bytes.
The error table occupies roughly 40 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
