State 0:
## Known stack suffix:
##
## LR(1) items:
decode_data_deg' -> . decode_data_deg [ # ]
## Transitions:
-- On decode_data_deg shift to state 1
-- On datalist_deg shift to state 2
## Default reduction:
-- After reading the next token, reduce production datalist_deg ->

State 1:
## Known stack suffix:
## decode_data_deg
## LR(1) items:
decode_data_deg' -> decode_data_deg . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, accept decode_data_deg

State 2:
## Known stack suffix:
## datalist_deg
## LR(1) items:
datalist_deg -> datalist_deg . datagroup_deg [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
decode_data_deg -> datalist_deg . EOF [ # ]
## Transitions:
-- On VARIABLE shift to state 3
-- On INTEGER shift to state 4
-- On FLOAT shift to state 5
-- On EOF shift to state 7
-- On BEGINMATRIX shift to state 8
-- On BEGINCOMPLEX shift to state 34
-- On datagroup_deg shift to state 44
-- On data_deg shift to state 45
## Reductions:

State 3:
## Known stack suffix:
## VARIABLE
## LR(1) items:
data_deg -> VARIABLE . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_deg -> VARIABLE

State 4:
## Known stack suffix:
## INTEGER
## LR(1) items:
data_deg -> INTEGER . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_deg -> INTEGER

State 5:
## Known stack suffix:
## FLOAT
## LR(1) items:
data_deg -> FLOAT . UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> FLOAT . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On UNITS shift to state 6
## Reductions:
-- On VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX
--   reduce production data_deg -> FLOAT

State 6:
## Known stack suffix:
## FLOAT UNITS
## LR(1) items:
data_deg -> FLOAT UNITS . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_deg -> FLOAT UNITS

State 7:
## Known stack suffix:
## datalist_deg EOF
## LR(1) items:
decode_data_deg -> datalist_deg EOF . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production decode_data_deg -> datalist_deg EOF

State 8:
## Known stack suffix:
## BEGINMATRIX
## LR(1) items:
data_deg -> BEGINMATRIX . matrix_rows_deg ENDMATRIX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINMATRIX . matrix_rows_deg ENDMATRIX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On matrix_rows_deg shift to state 9
## Default reduction:
-- After reading the next token, reduce production matrix_rows_deg ->

State 9:
## Known stack suffix:
## BEGINMATRIX matrix_rows_deg
## LR(1) items:
data_deg -> BEGINMATRIX matrix_rows_deg . ENDMATRIX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINMATRIX matrix_rows_deg . ENDMATRIX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
matrix_rows_deg -> matrix_rows_deg . BEGINMATRIX matrix_row_elements_deg ENDMATRIX [ ENDMATRIX BEGINMATRIX ]
## Transitions:
-- On ENDMATRIX shift to state 10
-- On BEGINMATRIX shift to state 12
## Reductions:

State 10:
## Known stack suffix:
## BEGINMATRIX matrix_rows_deg ENDMATRIX
## LR(1) items:
data_deg -> BEGINMATRIX matrix_rows_deg ENDMATRIX . UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINMATRIX matrix_rows_deg ENDMATRIX . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On UNITS shift to state 11
## Reductions:
-- On VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX
--   reduce production data_deg -> BEGINMATRIX matrix_rows_deg ENDMATRIX

State 11:
## Known stack suffix:
## BEGINMATRIX matrix_rows_deg ENDMATRIX UNITS
## LR(1) items:
data_deg -> BEGINMATRIX matrix_rows_deg ENDMATRIX UNITS . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_deg -> BEGINMATRIX matrix_rows_deg ENDMATRIX UNITS

State 12:
## Known stack suffix:
## matrix_rows_deg BEGINMATRIX
## LR(1) items:
matrix_rows_deg -> matrix_rows_deg BEGINMATRIX . matrix_row_elements_deg ENDMATRIX [ ENDMATRIX BEGINMATRIX ]
## Transitions:
-- On FLOAT shift to state 13
-- On BEGINCOMPLEX shift to state 14
-- On matrix_row_elements_deg shift to state 22
## Reductions:

State 13:
## Known stack suffix:
## FLOAT
## LR(1) items:
matrix_row_elements_deg -> FLOAT . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_deg -> FLOAT

State 14:
## Known stack suffix:
## BEGINCOMPLEX
## LR(1) items:
matrix_row_elements_deg -> BEGINCOMPLEX . FLOAT SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_deg -> BEGINCOMPLEX . FLOAT ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 15
## Reductions:

State 15:
## Known stack suffix:
## BEGINCOMPLEX FLOAT
## LR(1) items:
matrix_row_elements_deg -> BEGINCOMPLEX FLOAT . SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_deg -> BEGINCOMPLEX FLOAT . ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On SEPARATOR shift to state 16
-- On ANGLE shift to state 19
## Reductions:

State 16:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR
## LR(1) items:
matrix_row_elements_deg -> BEGINCOMPLEX FLOAT SEPARATOR . FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 17
## Reductions:

State 17:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR FLOAT
## LR(1) items:
matrix_row_elements_deg -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT . ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On ENDCOMPLEX shift to state 18
## Reductions:

State 18:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX
## LR(1) items:
matrix_row_elements_deg -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_deg -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX

State 19:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE
## LR(1) items:
matrix_row_elements_deg -> BEGINCOMPLEX FLOAT ANGLE . FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 20
## Reductions:

State 20:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE FLOAT
## LR(1) items:
matrix_row_elements_deg -> BEGINCOMPLEX FLOAT ANGLE FLOAT . ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On ENDCOMPLEX shift to state 21
## Reductions:

State 21:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX
## LR(1) items:
matrix_row_elements_deg -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_deg -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX

State 22:
## Known stack suffix:
## matrix_rows_deg BEGINMATRIX matrix_row_elements_deg
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg . SEPARATOR FLOAT [ SEPARATOR ENDMATRIX ]
matrix_row_elements_deg -> matrix_row_elements_deg . SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_deg -> matrix_row_elements_deg . SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_rows_deg -> matrix_rows_deg BEGINMATRIX matrix_row_elements_deg . ENDMATRIX [ ENDMATRIX BEGINMATRIX ]
## Transitions:
-- On SEPARATOR shift to state 23
-- On ENDMATRIX shift to state 33
## Reductions:

State 23:
## Known stack suffix:
## matrix_row_elements_deg SEPARATOR
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR . FLOAT [ SEPARATOR ENDMATRIX ]
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR . BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR . BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 24
-- On BEGINCOMPLEX shift to state 25
## Reductions:

State 24:
## Known stack suffix:
## matrix_row_elements_deg SEPARATOR FLOAT
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR FLOAT . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR FLOAT

State 25:
## Known stack suffix:
## matrix_row_elements_deg SEPARATOR BEGINCOMPLEX
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX . FLOAT SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX . FLOAT ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 26
## Reductions:

State 26:
## Known stack suffix:
## matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT . SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT . ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On SEPARATOR shift to state 27
-- On ANGLE shift to state 30
## Reductions:

State 27:
## Known stack suffix:
## matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR . FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 28
## Reductions:

State 28:
## Known stack suffix:
## matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT . ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On ENDCOMPLEX shift to state 29
## Reductions:

State 29:
## Known stack suffix:
## matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX

State 30:
## Known stack suffix:
## matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT ANGLE
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT ANGLE . FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 31
## Reductions:

State 31:
## Known stack suffix:
## matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT . ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On ENDCOMPLEX shift to state 32
## Reductions:

State 32:
## Known stack suffix:
## matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX
## LR(1) items:
matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_deg -> matrix_row_elements_deg SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX

State 33:
## Known stack suffix:
## matrix_rows_deg BEGINMATRIX matrix_row_elements_deg ENDMATRIX
## LR(1) items:
matrix_rows_deg -> matrix_rows_deg BEGINMATRIX matrix_row_elements_deg ENDMATRIX . [ ENDMATRIX BEGINMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_rows_deg -> matrix_rows_deg BEGINMATRIX matrix_row_elements_deg ENDMATRIX

State 34:
## Known stack suffix:
## BEGINCOMPLEX
## LR(1) items:
data_deg -> BEGINCOMPLEX . FLOAT SEPARATOR FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX . FLOAT SEPARATOR FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX . FLOAT ANGLE FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX . FLOAT ANGLE FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On FLOAT shift to state 35
## Reductions:

State 35:
## Known stack suffix:
## BEGINCOMPLEX FLOAT
## LR(1) items:
data_deg -> BEGINCOMPLEX FLOAT . SEPARATOR FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX FLOAT . SEPARATOR FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX FLOAT . ANGLE FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX FLOAT . ANGLE FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On SEPARATOR shift to state 36
-- On ANGLE shift to state 40
## Reductions:

State 36:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR
## LR(1) items:
data_deg -> BEGINCOMPLEX FLOAT SEPARATOR . FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX FLOAT SEPARATOR . FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On FLOAT shift to state 37
## Reductions:

State 37:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR FLOAT
## LR(1) items:
data_deg -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT . ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT . ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On ENDCOMPLEX shift to state 38
## Reductions:

State 38:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX
## LR(1) items:
data_deg -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX . UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On UNITS shift to state 39
## Reductions:
-- On VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX
--   reduce production data_deg -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX

State 39:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX UNITS
## LR(1) items:
data_deg -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX UNITS . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_deg -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX UNITS

State 40:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE
## LR(1) items:
data_deg -> BEGINCOMPLEX FLOAT ANGLE . FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX FLOAT ANGLE . FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On FLOAT shift to state 41
## Reductions:

State 41:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE FLOAT
## LR(1) items:
data_deg -> BEGINCOMPLEX FLOAT ANGLE FLOAT . ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX FLOAT ANGLE FLOAT . ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On ENDCOMPLEX shift to state 42
## Reductions:

State 42:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX
## LR(1) items:
data_deg -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX . UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_deg -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On UNITS shift to state 43
## Reductions:
-- On VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX
--   reduce production data_deg -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX

State 43:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX UNITS
## LR(1) items:
data_deg -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX UNITS . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_deg -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX UNITS

State 44:
## Known stack suffix:
## datalist_deg datagroup_deg
## LR(1) items:
datalist_deg -> datalist_deg datagroup_deg . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production datalist_deg -> datalist_deg datagroup_deg

State 45:
## Known stack suffix:
## data_deg
## LR(1) items:
datagroup_deg -> data_deg . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production datagroup_deg -> data_deg

State 46:
## Known stack suffix:
##
## LR(1) items:
decode_data_rad' -> . decode_data_rad [ # ]
## Transitions:
-- On decode_data_rad shift to state 47
-- On datalist_rad shift to state 48
## Default reduction:
-- After reading the next token, reduce production datalist_rad ->

State 47:
## Known stack suffix:
## decode_data_rad
## LR(1) items:
decode_data_rad' -> decode_data_rad . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, accept decode_data_rad

State 48:
## Known stack suffix:
## datalist_rad
## LR(1) items:
datalist_rad -> datalist_rad . datagroup_rad [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
decode_data_rad -> datalist_rad . EOF [ # ]
## Transitions:
-- On VARIABLE shift to state 49
-- On INTEGER shift to state 50
-- On FLOAT shift to state 51
-- On EOF shift to state 53
-- On BEGINMATRIX shift to state 54
-- On BEGINCOMPLEX shift to state 80
-- On datagroup_rad shift to state 90
-- On data_rad shift to state 91
## Reductions:

State 49:
## Known stack suffix:
## VARIABLE
## LR(1) items:
data_rad -> VARIABLE . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_rad -> VARIABLE

State 50:
## Known stack suffix:
## INTEGER
## LR(1) items:
data_rad -> INTEGER . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_rad -> INTEGER

State 51:
## Known stack suffix:
## FLOAT
## LR(1) items:
data_rad -> FLOAT . UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> FLOAT . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On UNITS shift to state 52
## Reductions:
-- On VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX
--   reduce production data_rad -> FLOAT

State 52:
## Known stack suffix:
## FLOAT UNITS
## LR(1) items:
data_rad -> FLOAT UNITS . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_rad -> FLOAT UNITS

State 53:
## Known stack suffix:
## datalist_rad EOF
## LR(1) items:
decode_data_rad -> datalist_rad EOF . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production decode_data_rad -> datalist_rad EOF

State 54:
## Known stack suffix:
## BEGINMATRIX
## LR(1) items:
data_rad -> BEGINMATRIX . matrix_rows_rad ENDMATRIX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINMATRIX . matrix_rows_rad ENDMATRIX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On matrix_rows_rad shift to state 55
## Default reduction:
-- After reading the next token, reduce production matrix_rows_rad ->

State 55:
## Known stack suffix:
## BEGINMATRIX matrix_rows_rad
## LR(1) items:
data_rad -> BEGINMATRIX matrix_rows_rad . ENDMATRIX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINMATRIX matrix_rows_rad . ENDMATRIX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
matrix_rows_rad -> matrix_rows_rad . BEGINMATRIX matrix_row_elements_rad ENDMATRIX [ ENDMATRIX BEGINMATRIX ]
## Transitions:
-- On ENDMATRIX shift to state 56
-- On BEGINMATRIX shift to state 58
## Reductions:

State 56:
## Known stack suffix:
## BEGINMATRIX matrix_rows_rad ENDMATRIX
## LR(1) items:
data_rad -> BEGINMATRIX matrix_rows_rad ENDMATRIX . UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINMATRIX matrix_rows_rad ENDMATRIX . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On UNITS shift to state 57
## Reductions:
-- On VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX
--   reduce production data_rad -> BEGINMATRIX matrix_rows_rad ENDMATRIX

State 57:
## Known stack suffix:
## BEGINMATRIX matrix_rows_rad ENDMATRIX UNITS
## LR(1) items:
data_rad -> BEGINMATRIX matrix_rows_rad ENDMATRIX UNITS . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_rad -> BEGINMATRIX matrix_rows_rad ENDMATRIX UNITS

State 58:
## Known stack suffix:
## matrix_rows_rad BEGINMATRIX
## LR(1) items:
matrix_rows_rad -> matrix_rows_rad BEGINMATRIX . matrix_row_elements_rad ENDMATRIX [ ENDMATRIX BEGINMATRIX ]
## Transitions:
-- On FLOAT shift to state 59
-- On BEGINCOMPLEX shift to state 60
-- On matrix_row_elements_rad shift to state 68
## Reductions:

State 59:
## Known stack suffix:
## FLOAT
## LR(1) items:
matrix_row_elements_rad -> FLOAT . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_rad -> FLOAT

State 60:
## Known stack suffix:
## BEGINCOMPLEX
## LR(1) items:
matrix_row_elements_rad -> BEGINCOMPLEX . FLOAT SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_rad -> BEGINCOMPLEX . FLOAT ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 61
## Reductions:

State 61:
## Known stack suffix:
## BEGINCOMPLEX FLOAT
## LR(1) items:
matrix_row_elements_rad -> BEGINCOMPLEX FLOAT . SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_rad -> BEGINCOMPLEX FLOAT . ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On SEPARATOR shift to state 62
-- On ANGLE shift to state 65
## Reductions:

State 62:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR
## LR(1) items:
matrix_row_elements_rad -> BEGINCOMPLEX FLOAT SEPARATOR . FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 63
## Reductions:

State 63:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR FLOAT
## LR(1) items:
matrix_row_elements_rad -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT . ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On ENDCOMPLEX shift to state 64
## Reductions:

State 64:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX
## LR(1) items:
matrix_row_elements_rad -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_rad -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX

State 65:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE
## LR(1) items:
matrix_row_elements_rad -> BEGINCOMPLEX FLOAT ANGLE . FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 66
## Reductions:

State 66:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE FLOAT
## LR(1) items:
matrix_row_elements_rad -> BEGINCOMPLEX FLOAT ANGLE FLOAT . ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On ENDCOMPLEX shift to state 67
## Reductions:

State 67:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX
## LR(1) items:
matrix_row_elements_rad -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_rad -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX

State 68:
## Known stack suffix:
## matrix_rows_rad BEGINMATRIX matrix_row_elements_rad
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad . SEPARATOR FLOAT [ SEPARATOR ENDMATRIX ]
matrix_row_elements_rad -> matrix_row_elements_rad . SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_rad -> matrix_row_elements_rad . SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_rows_rad -> matrix_rows_rad BEGINMATRIX matrix_row_elements_rad . ENDMATRIX [ ENDMATRIX BEGINMATRIX ]
## Transitions:
-- On SEPARATOR shift to state 69
-- On ENDMATRIX shift to state 79
## Reductions:

State 69:
## Known stack suffix:
## matrix_row_elements_rad SEPARATOR
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR . FLOAT [ SEPARATOR ENDMATRIX ]
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR . BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR . BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 70
-- On BEGINCOMPLEX shift to state 71
## Reductions:

State 70:
## Known stack suffix:
## matrix_row_elements_rad SEPARATOR FLOAT
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR FLOAT . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR FLOAT

State 71:
## Known stack suffix:
## matrix_row_elements_rad SEPARATOR BEGINCOMPLEX
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX . FLOAT SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX . FLOAT ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 72
## Reductions:

State 72:
## Known stack suffix:
## matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT . SEPARATOR FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT . ANGLE FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On SEPARATOR shift to state 73
-- On ANGLE shift to state 76
## Reductions:

State 73:
## Known stack suffix:
## matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR . FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 74
## Reductions:

State 74:
## Known stack suffix:
## matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT . ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On ENDCOMPLEX shift to state 75
## Reductions:

State 75:
## Known stack suffix:
## matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX

State 76:
## Known stack suffix:
## matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT ANGLE
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT ANGLE . FLOAT ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On FLOAT shift to state 77
## Reductions:

State 77:
## Known stack suffix:
## matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT . ENDCOMPLEX [ SEPARATOR ENDMATRIX ]
## Transitions:
-- On ENDCOMPLEX shift to state 78
## Reductions:

State 78:
## Known stack suffix:
## matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX
## LR(1) items:
matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX . [ SEPARATOR ENDMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_row_elements_rad -> matrix_row_elements_rad SEPARATOR BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX

State 79:
## Known stack suffix:
## matrix_rows_rad BEGINMATRIX matrix_row_elements_rad ENDMATRIX
## LR(1) items:
matrix_rows_rad -> matrix_rows_rad BEGINMATRIX matrix_row_elements_rad ENDMATRIX . [ ENDMATRIX BEGINMATRIX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production matrix_rows_rad -> matrix_rows_rad BEGINMATRIX matrix_row_elements_rad ENDMATRIX

State 80:
## Known stack suffix:
## BEGINCOMPLEX
## LR(1) items:
data_rad -> BEGINCOMPLEX . FLOAT SEPARATOR FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX . FLOAT SEPARATOR FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX . FLOAT ANGLE FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX . FLOAT ANGLE FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On FLOAT shift to state 81
## Reductions:

State 81:
## Known stack suffix:
## BEGINCOMPLEX FLOAT
## LR(1) items:
data_rad -> BEGINCOMPLEX FLOAT . SEPARATOR FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX FLOAT . SEPARATOR FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX FLOAT . ANGLE FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX FLOAT . ANGLE FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On SEPARATOR shift to state 82
-- On ANGLE shift to state 86
## Reductions:

State 82:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR
## LR(1) items:
data_rad -> BEGINCOMPLEX FLOAT SEPARATOR . FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX FLOAT SEPARATOR . FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On FLOAT shift to state 83
## Reductions:

State 83:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR FLOAT
## LR(1) items:
data_rad -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT . ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT . ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On ENDCOMPLEX shift to state 84
## Reductions:

State 84:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX
## LR(1) items:
data_rad -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX . UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On UNITS shift to state 85
## Reductions:
-- On VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX
--   reduce production data_rad -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX

State 85:
## Known stack suffix:
## BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX UNITS
## LR(1) items:
data_rad -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX UNITS . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_rad -> BEGINCOMPLEX FLOAT SEPARATOR FLOAT ENDCOMPLEX UNITS

State 86:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE
## LR(1) items:
data_rad -> BEGINCOMPLEX FLOAT ANGLE . FLOAT ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX FLOAT ANGLE . FLOAT ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On FLOAT shift to state 87
## Reductions:

State 87:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE FLOAT
## LR(1) items:
data_rad -> BEGINCOMPLEX FLOAT ANGLE FLOAT . ENDCOMPLEX UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX FLOAT ANGLE FLOAT . ENDCOMPLEX [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On ENDCOMPLEX shift to state 88
## Reductions:

State 88:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX
## LR(1) items:
data_rad -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX . UNITS [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
data_rad -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
-- On UNITS shift to state 89
## Reductions:
-- On VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX
--   reduce production data_rad -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX

State 89:
## Known stack suffix:
## BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX UNITS
## LR(1) items:
data_rad -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX UNITS . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production data_rad -> BEGINCOMPLEX FLOAT ANGLE FLOAT ENDCOMPLEX UNITS

State 90:
## Known stack suffix:
## datalist_rad datagroup_rad
## LR(1) items:
datalist_rad -> datalist_rad datagroup_rad . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production datalist_rad -> datalist_rad datagroup_rad

State 91:
## Known stack suffix:
## data_rad
## LR(1) items:
datagroup_rad -> data_rad . [ VARIABLE INTEGER FLOAT EOF BEGINMATRIX BEGINCOMPLEX ]
## Transitions:
## Default reduction:
-- After reading the next token, reduce production datagroup_rad -> data_rad

