
** Conflict (shift/reduce) in state 188.
** Token involved: TOBRACE
** This state is reached from sgrep_spatch_pattern after reading:

qualified_class_name

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

sgrep_spatch_pattern 
expr EOF 
simple_expr 
(?)

** In state 188, looking ahead at TOBRACE, reducing production
** primary_expr -> qualified_class_name
** is permitted because of the following sub-derivation:

new_expr 
member_expr 
member_expr TOBRACE expr TCBRACE // lookahead token appears
primary_expr // lookahead token is inherited
qualified_class_name . 

** In state 188, looking ahead at TOBRACE, shifting is permitted
** because of the following sub-derivation:

qualified_class_name . TOBRACE array_pair_list TCBRACE 
