
** Conflict (shift/reduce) in state 442.
** Token involved: TIdent
** This state is reached from toplevel after reading:

Ttemplate TInf_Template decl_spec_seq TOPar

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

toplevel 
toplevel_aux 
declaration 
template_declaration 
Ttemplate TInf_Template listc(template_parameter) TSup_Template declaration 
                        template_parameter 
                        parameter_decl 
                        (?)

** In state 442, looking ahead at TIdent, reducing production
** option(TColCol) ->
** is permitted because of the following sub-derivation:

decl_spec_seq declarator 
              direct_d 
              TOPar declarator TCPar 
                    direct_d 
                    declarator_id 
                    option(TColCol) id_expression // lookahead token appears because id_expression can begin with TIdent
                    . 

** In state 442, looking ahead at TIdent, shifting is permitted
** because of the following sub-derivation:

decl_spec_seq abstract_declarator 
              direct_abstract_declarator 
              TOPar parameter_type_list TCPar 
                    parameter_list 
                    parameter_decl2 
                    . TIdent 

** Conflict (shift/reduce) in state 299.
** Token involved: TCol
** This state is reached from main after reading:

class_head TOBrace class_key ident

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

main 
translation_unit EOF 
nonempty_list(external_declaration) 
external_declaration 
function_definition 
decl_spec_seq declarator function_body 
decl_spec 
type_spec 
class_specifier 
class_head TOBrace optl(member_specification) TCBrace 
                   member_specification 
                   member_declaration optl(member_specification) 
                   field_declaration 
                   (?)

** In state 299, looking ahead at TCol, shifting is permitted
** because of the following sub-derivation:

decl_spec_seq TPtVirg 
decl_spec 
type_spec 
class_specifier 
class_head TOBrace optl(member_specification) TCBrace 
class_key ident option(base_clause) 
                base_clause 
                . TCol listc(base_specifier) 

** In state 299, looking ahead at TCol, reducing production
** elaborated_type_specifier -> class_key ident
** is permitted because of the following sub-derivation:

decl_spec_seq listc(member_declarator) TPtVirg // lookahead token appears because listc(member_declarator) can begin with TCol
decl_spec // lookahead token is inherited
type_spec // lookahead token is inherited
elaborated_type_specifier // lookahead token is inherited
class_key ident . 
