
** Conflict (shift/reduce) in state 127.
** Token involved: OR
** This state is reached from command after reading:

REC ID ParamSeq MaybeTy DARROW term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 127, looking ahead at OR, reducing production
** ident_free_term -> REC ID ParamSeq MaybeTy DARROW term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
REC ID ParamSeq MaybeTy DARROW term . 

** In state 127, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

REC ID ParamSeq MaybeTy DARROW term 
                               ident_free_term 
                               term . OR term 

** Conflict (shift/reduce) in state 99.
** Token involved: OR
** This state is reached from command after reading:

LAMBDA ID COLON ident_free_term DOT term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 99, looking ahead at OR, reducing production
** ident_free_term -> LAMBDA ID COLON ident_free_term DOT term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
LAMBDA ID COLON ident_free_term DOT term . 

** In state 99, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

LAMBDA ID COLON ident_free_term DOT term 
                                    ident_free_term 
                                    term . OR term 

** Conflict (shift/reduce) in state 96.
** Token involved: OR
** This state is reached from command after reading:

IF term THEN term ELSE term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 96, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

IF term THEN term ELSE term 
                       ident_free_term 
                       term . OR term 

** In state 96, looking ahead at OR, reducing production
** ident_free_term -> IF term THEN term ELSE term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
IF term THEN term ELSE term . 

** Conflict (shift/reduce) in state 91.
** Token involved: OR
** This state is reached from command after reading:

IF LSQUARE Type RSQUARE term THEN term ELSE term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 91, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

IF LSQUARE Type RSQUARE term THEN term ELSE term 
                                            ident_free_term 
                                            term . OR term 

** In state 91, looking ahead at OR, reducing production
** ident_free_term -> IF LSQUARE Type RSQUARE term THEN term ELSE term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
IF LSQUARE Type RSQUARE term THEN term ELSE term . 

** Conflict (shift/reduce) in state 78.
** Token involved: OR
** This state is reached from command after reading:

term LT term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 78, looking ahead at OR, reducing production
** ident_free_term -> term LT term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term LT term . 

** In state 78, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term LT term 
        ident_free_term 
        term . OR term 

** Conflict (shift/reduce) in state 72.
** Token involved: OR
** This state is reached from command after reading:

ID COLON ident_free_term ARROW term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
(?)

** In state 72, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

ID COLON ident_free_term ARROW term 
                               ident_free_term 
                               term . OR term 

** In state 72, looking ahead at OR, reducing production
** term -> ID COLON ident_free_term ARROW term 
** is permitted because of the following sub-derivation:

ident_free_term 
term OR term // lookahead token appears
ID COLON ident_free_term ARROW term . 

** Conflict (shift/reduce) in state 70.
** Token involved: OR
** This state is reached from command after reading:

ID COLON ident_free_term DOT term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
(?)

** In state 70, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

ID COLON ident_free_term DOT term 
                             ident_free_term 
                             term . OR term 

** In state 70, looking ahead at OR, reducing production
** term -> ID COLON ident_free_term DOT term 
** is permitted because of the following sub-derivation:

ident_free_term 
term OR term // lookahead token appears
ID COLON ident_free_term DOT term . 

** Conflict (shift/reduce) in state 67.
** Token involved: OR
** This state is reached from command after reading:

term ARROW term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 67, looking ahead at OR, reducing production
** ident_free_term -> term ARROW term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term ARROW term . 

** In state 67, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term ARROW term 
           ident_free_term 
           term . OR term 

** Conflict (shift/reduce) in state 65.
** Token involved: OR
** This state is reached from command after reading:

term AS term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 65, looking ahead at OR, reducing production
** ident_free_term -> term AS term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term AS term . 

** In state 65, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term AS term 
        ident_free_term 
        term . OR term 

** Conflict (shift/reduce) in state 63.
** Token involved: OR
** This state is reached from command after reading:

term EQ term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 63, looking ahead at OR, reducing production
** ident_free_term -> term EQ term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term EQ term . 

** In state 63, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term EQ term 
        ident_free_term 
        term . OR term 

** Conflict (shift/reduce) in state 61.
** Token involved: OR
** This state is reached from command after reading:

term GEQ term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 61, looking ahead at OR, reducing production
** ident_free_term -> term GEQ term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term GEQ term . 

** In state 61, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term GEQ term 
         ident_free_term 
         term . OR term 

** Conflict (shift/reduce) in state 59.
** Token involved: OR
** This state is reached from command after reading:

term GT term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 59, looking ahead at OR, reducing production
** ident_free_term -> term GT term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term GT term . 

** In state 59, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term GT term 
        ident_free_term 
        term . OR term 

** Conflict (shift/reduce) in state 57.
** Token involved: OR
** This state is reached from command after reading:

term IFF term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 57, looking ahead at OR, reducing production
** ident_free_term -> term IFF term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term IFF term . 

** In state 57, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term IFF term 
         ident_free_term 
         term . OR term 

** Conflict (shift/reduce) in state 55.
** Token involved: OR
** This state is reached from command after reading:

term AND term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 55, looking ahead at OR, reducing production
** ident_free_term -> term AND term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term AND term . 

** In state 55, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term AND term 
         ident_free_term 
         term . OR term 

** Conflict (shift/reduce) in state 53.
** Token involved: OR
** This state is reached from command after reading:

term LEQ term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 53, looking ahead at OR, reducing production
** ident_free_term -> term LEQ term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term LEQ term . 

** In state 53, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term LEQ term 
         ident_free_term 
         term . OR term 

** Conflict (shift/reduce) in state 47.
** Token involved: OR
** This state is reached from command after reading:

Let IN term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 47, looking ahead at OR, reducing production
** ident_free_term -> Let IN term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
Let IN term . 

** In state 47, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

Let IN term 
       ident_free_term 
       term . OR term 

** Conflict (shift/reduce) in state 43.
** Token involved: OR
** This state is reached from command after reading:

term term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 43, looking ahead at OR, reducing production
** ident_free_term -> term term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term term . 

** In state 43, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term term 
     ident_free_term 
     term . OR term 

** Conflict (shift/reduce) in state 42.
** Token involved: OR
** This state is reached from command after reading:

term MINUS term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 42, looking ahead at OR, reducing production
** ident_free_term -> term MINUS term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term MINUS term . 

** In state 42, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term MINUS term 
           ident_free_term 
           term . OR term 

** Conflict (shift/reduce) in state 40.
** Tokens involved: STRINGV STAR SEMI REC QUESTION PLUS OR MINUS LT LPAREN LET LEQ LCURLY LAMBDA INTV IFF IF ID GT GEQ FN EQ AS ARROW AND
** The following explanations concentrate on token STRINGV.
** This state is reached from command after reading:

term OR term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 40, looking ahead at STRINGV, shifting is permitted
** because of the following sub-derivation:

term OR term 
        ident_free_term 
        term term 
             ident_free_term 
             . STRINGV 

** In state 40, looking ahead at STRINGV, reducing production
** ident_free_term -> term OR term 
** is permitted because of the following sub-derivation:

term term // lookahead token appears because term can begin with STRINGV
ident_free_term // lookahead token is inherited
term OR term . 

** Conflict (shift/reduce) in state 38.
** Token involved: OR
** This state is reached from command after reading:

term PLUS term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 38, looking ahead at OR, reducing production
** ident_free_term -> term PLUS term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term PLUS term . 

** In state 38, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term PLUS term 
          ident_free_term 
          term . OR term 

** Conflict (shift/reduce) in state 36.
** Token involved: OR
** This state is reached from command after reading:

term SEMI term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 36, looking ahead at OR, reducing production
** ident_free_term -> term SEMI term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
term SEMI term . 

** In state 36, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

term SEMI term 
          ident_free_term 
          term . OR term 

** Conflict (shift/reduce) in state 34.
** Token involved: OR
** This state is reached from command after reading:

FN ParamSeq MaybeTy DARROW term 

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

command 
term 
ident_free_term 
(?)

** In state 34, looking ahead at OR, reducing production
** ident_free_term -> FN ParamSeq MaybeTy DARROW term 
** is permitted because of the following sub-derivation:

term OR term // lookahead token appears
ident_free_term // lookahead token is inherited
FN ParamSeq MaybeTy DARROW term . 

** In state 34, looking ahead at OR, shifting is permitted
** because of the following sub-derivation:

FN ParamSeq MaybeTy DARROW term 
                           ident_free_term 
                           term . OR term 
