State 0:
## Known stack suffix:
##
## LR(1) items:
dummy' -> . dummy [ # ]
## Transitions:
-- On A shift to state 1
-- On dummy shift to state 2
## Reductions:

State 1:
## Known stack suffix:
## A
## LR(1) items:
dummy -> A . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, reduce production dummy -> A

State 2:
## Known stack suffix:
## dummy
## LR(1) items:
dummy' -> dummy . [ # ]
## Transitions:
## Default reduction:
-- Without reading the next token, accept dummy

