Grammar has 5 nonterminal symbols, among which 1 start symbols.
Grammar has 10 terminal symbols.
Grammar has 15 productions.
nullable(sexpr) = false
nullable(sexp) = false
nullable(pairs) = false
nullable(option(PLUS)) = true
nullable(list(sexpr)) = true
first(sexpr) = STRING PLUS MINUS INT ID BRA AT
first(sexp) = STRING PLUS MINUS INT ID EOF BRA AT
first(pairs) = STRING PLUS MINUS INT ID DOT BRA AT
first(option(PLUS)) = PLUS
first(list(sexpr)) = STRING PLUS MINUS INT ID BRA AT
minimal(sexpr) = (* 1 *) STRING
minimal(sexp) = (* 1 *) STRING
minimal(pairs) = (* 1 *) STRING
minimal(option(PLUS)) = (* 0 *)
minimal(list(sexpr)) = (* 0 *)
follow(sexpr) = STRING PLUS MINUS KET INT ID DOT BRA AT #
follow(sexp) = #
follow(pairs) = KET
follow(option(PLUS)) = INT
follow(list(sexpr)) = KET DOT
Built an LR(0) automaton with 25 states.
The grammar is not SLR(1) -- 1 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 39 states.
20 out of 39 states have a default reduction.
10 out of 39 states are represented.
1 out of 18 symbols keep track of their start position.
5 out of 18 symbols keep track of their end position.
9 out of 16 productions exploit shiftreduce optimization.
0 out of 39 states can peek at an error.
104 functions before inlining, 29 functions after inlining.
