Grammar has 2 nonterminal symbols, among which 1 start symbols.
Grammar has 6 terminal symbols.
Grammar has 5 productions.
nullable(phrase) = false
nullable(expression) = false
first(phrase) = TRUE IF FALSE
first(expression) = TRUE IF FALSE
minimal(phrase) = (* 2 *) TRUE EOF
minimal(expression) = (* 1 *) TRUE
maximal(phrase) = infinity
maximal(expression) = infinity
follow(phrase) = #
follow(expression) = THEN EOF ELSE
Built an LR(0) automaton with 12 states.
The grammar is not SLR(1) -- 1 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 12 states.
Warning: one state has shift/reduce conflicts.
Warning: one shift/reduce conflict was arbitrarily resolved.
5 out of 12 states have a default reduction.
The action table is 84 entries; 17 non-zero; 20 compressed.
The action table occupies roughly 104 bytes.
The goto table is 36 entries; 5 non-zero; 17 compressed.
The goto table occupies roughly 104 bytes.
The error table occupies roughly 48 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
