Grammar has 2 nonterminal symbols, among which 1 start symbols.
Grammar has 3 terminal symbols.
Grammar has 3 productions.
nullable(main) = false
nullable(liste(A)) = true
first(main) = B A
first(liste(A)) = A
minimal(main) = (* 2 *) B EOF
minimal(liste(A)) = (* 0 *)
maximal(main) = infinity
maximal(liste(A)) = infinity
follow(main) = #
follow(liste(A)) = B
Built an LR(0) automaton with 8 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 8 states.
3 out of 8 states have a default reduction.
The action table is 32 entries; 7 non-zero; 13 compressed.
The action table occupies roughly 104 bytes.
The goto table is 24 entries; 3 non-zero; 11 compressed.
The goto table occupies roughly 104 bytes.
The error table occupies roughly 40 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
