File "subiso.mly", line 34, characters 10-17:
Warning: the token ASSIGNS is unused.
File "subiso.mly", line 24, characters 7-11:
Warning: the token PLUS is unused.
File "subiso.mly", line 23, characters 16-20:
Warning: the token TVAR is unused.
Grammar has 4 nonterminal symbols, among which 1 start symbols.
Grammar has 11 terminal symbols.
Grammar has 9 productions.
nullable(type_binding_list) = false
nullable(type_binding) = false
nullable(texpr) = false
nullable(main) = false
first(type_binding_list) = IDENT
first(type_binding) = IDENT
first(texpr) = TYPE LPAR IDENT
first(main) = TYPE LPAR IDENT
minimal(type_binding_list) = (* 3 *) IDENT EQ IDENT
minimal(type_binding) = (* 3 *) IDENT EQ IDENT
minimal(texpr) = (* 1 *) IDENT
minimal(main) = (* 2 *) IDENT Eof
maximal(type_binding_list) = infinity
maximal(type_binding) = infinity
maximal(texpr) = infinity
maximal(main) = infinity
follow(type_binding_list) = TIMES RPAR Eof ARROW AND
follow(type_binding) = TIMES RPAR Eof ARROW AND
follow(texpr) = TIMES RPAR Eof ARROW AND
follow(main) = #
Built an LR(0) automaton with 20 states.
The grammar is not SLR(1) -- 4 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 20 states.
7 shift/reduce conflicts were silently solved.
File "subiso.mly", line 34, characters 0-9:
Warning: the precedence level assigned to ASSIGNS is never useful.
6 out of 20 states have a default reduction.
The action table is 240 entries; 44 non-zero; 57 compressed.
The action table occupies roughly 152 bytes.
The goto table is 100 entries; 9 non-zero; 29 compressed.
The goto table occupies roughly 120 bytes.
The error table occupies roughly 64 bytes.
The default_reduction table occupies roughly 48 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
