
** Conflict (shift/reduce) in state 143.
** Token involved: Tnot
** This state is reached from tal_pre_mod after reading:

prolog Tjecxz coerce Tvirtual Tlab Tletroll tvar Tcomma con10

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

tal_pre_mod 
prolog imp_items epilog 
       imp_item imp_items 
       instruction Teol 
       Tjecxz coerce Tvirtual Tlab instructionlist Trab 
                                   (?)

** In state 143, looking ahead at Tnot, reducing production
** con9 -> con10
** is permitted because of the following sub-derivation:

instruction instructionlist // lookahead token appears because instructionlist can begin with Tnot
Tletroll tvar Tcomma con // lookahead token is inherited
                     con1 // lookahead token is inherited
                     con2 // lookahead token is inherited
                     con3 // lookahead token is inherited
                     con4 // lookahead token is inherited
                     con5 // lookahead token is inherited
                     con6 // lookahead token is inherited
                     con7 // lookahead token is inherited
                     con8 // lookahead token is inherited
                     con9 // lookahead token is inherited
                     con10 . 

** In state 143, looking ahead at Tnot, shifting is permitted
** because of the following sub-derivation:

instruction 
Tletroll tvar Tcomma con 
                     con1 
                     con2 
                     con3 
                     con4 
                     con5 
                     con6 
                     con7 
                     con8 
                     con9 
                     con10 . Tnot Tequal con9 
