State 0:
## Known stack suffix:
##
## LR(1) items:
a' -> . a [ # ]
## Transitions:
-- On A shift to state 1
-- On a shift to state 2
## Reductions:

State 1:
## Known stack suffix:
## A
## LR(1) items:
a -> A . [ # ]
## Transitions:
## Reductions:
-- On # reduce production a -> A

State 2:
## Known stack suffix:
## a
## LR(1) items:
a' -> a . [ # ]
## Transitions:
## Reductions:
-- On # accept a

