State 0:
## Known stack suffix:
##
## LR(1) items:
main' -> . main [ # ]
## Transitions:
-- On FOO shift to state 1
-- On main shift to state 2
## Reductions:

State 1:
## Known stack suffix:
## FOO
## LR(1) items:
main -> FOO . [ # ]
## Transitions:
## Reductions:
-- On # reduce production main -> FOO

State 2:
## Known stack suffix:
## main
## LR(1) items:
main' -> main . [ # ]
## Transitions:
## Reductions:
-- On # accept main

