Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 4 terminal symbols.
Grammar has 5 productions.
nullable(op) = false
nullable(main) = false
nullable(expression) = false
first(op) = TIMES PLUS
first(main) = INT
first(expression) = INT
minimal(op) = (* 1 *) PLUS
minimal(main) = (* 2 *) INT EOF
minimal(expression) = (* 1 *) INT
maximal(op) = 1
maximal(main) = infinity
maximal(expression) = infinity
follow(op) = INT
follow(main) = #
follow(expression) = TIMES PLUS EOF
Built an LR(0) automaton with 9 states.
The grammar is not SLR(1) -- 1 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 9 states.
File "useless-priorities.mly", line 3, characters 0-5:
Warning: the precedence level assigned to PLUS is never useful.
File "useless-priorities.mly", line 4, characters 0-5:
Warning: the precedence level assigned to TIMES is never useful.
Warning: one state has shift/reduce conflicts.
Warning: 2 shift/reduce conflicts were arbitrarily resolved.
5 out of 9 states have a default reduction.
The action table is 45 entries; 8 non-zero; 17 compressed.
The action table occupies roughly 104 bytes.
The goto table is 36 entries; 5 non-zero; 13 compressed.
The goto table occupies roughly 104 bytes.
The error table occupies roughly 40 bytes.
The default_reduction table occupies roughly 40 bytes.
The lhs table occupies roughly 40 bytes.
The trace table occupies roughly 8 bytes.
