
** Conflict (shift/reduce) in state 8.
** Tokens involved: TIMES PLUS
** The following explanations concentrate on token TIMES.
** This state is reached from main after reading:

expression op expression

** The derivations that appear below have the following common factor:
** (The question mark symbol (?) represents the spot where the derivations begin to differ.)

main 
expression EOF 
(?)

** In state 8, looking ahead at TIMES, reducing production
** expression -> expression op expression
** is permitted because of the following sub-derivation:

expression op expression // lookahead token appears because op can begin with TIMES
expression op expression . 

** In state 8, looking ahead at TIMES, shifting is permitted
** because of the following sub-derivation:

expression op expression 
              expression op expression 
                         . TIMES 
