Warning: you are using the standard library and/or the %inline keyword. We
recommend switching on --infer in order to avoid obscure type error messages.
%start a
%token T

%type <int> a
%%

a:
| x00 = d T T T x01 = d T T
    {let _5 =
  let x0 = x01 in
  let x =
    let x = x0 in
    ( f_c x )
  in
  ( f_b x )
in
let x =
  let x0 = x00 in
  let x =
    let x = x0 in
    ( f_c x )
  in
  ( f_b x )
in
 f_a x }

d:
| T
    {}

%%



