Warning: you are using the standard library and/or the %inline keyword. We
recommend switching on --infer in order to avoid obscure type error messages.
Grammar has 5 nonterminal symbols, among which 2 start symbols.
Grammar has 5 terminal symbols.
Grammar has 9 productions.
nullable(seplist(A)) = false
nullable(phrase) = false
nullable(other) = false
nullable(list(__anonymous_0(A,B))) = true
nullable(embedded(__anonymous_1)) = false
first(seplist(A)) = A
first(phrase) = C
first(other) = A
first(list(__anonymous_0(A,B))) = B A
first(embedded(__anonymous_1)) = D C
follow(seplist(A)) = EOF
follow(phrase) = #
follow(other) = #
follow(list(__anonymous_0(A,B))) = EOF D
follow(embedded(__anonymous_1)) = A
Built an LR(0) automaton with 20 states.
The grammar is SLR(1).
Built an LR(1) automaton with 20 states.
9 out of 20 states have a default reduction.
6 out of 20 states are represented.
0 out of 14 symbols keep track of their start position.
0 out of 14 symbols keep track of their end position.
6 out of 11 productions exploit shiftreduce optimization.
0 out of 20 states can peek at an error.
63 functions before inlining, 13 functions after inlining.
