Warning: you are using the standard library and/or the %inline keyword. We
recommend switching on --infer in order to avoid obscure type error messages.
%start a
%token <int> T
%type <int> a
%%

a:
  _10 = T _20 = T _2 = c _4 = c
    {let _3 =
             ( 0 )
in
let _1 =
  let _2 = _20 in
  let _1 = _10 in
                 ()
in
           ( _2 + _3 + _4 )}

c:
  x = T
    {       ( x + 1 )}

%%



