Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 3 terminal symbols.
Grammar has 4 productions.
nullable(s) = false
nullable(phrase) = false
nullable(a) = true
first(s) = B
first(phrase) = B
first(a) = 
follow(s) = EOF C
follow(phrase) = #
follow(a) = B
Built an LR(0) automaton with 8 states.
The grammar is not SLR(1) -- 2 states have a conflict.
Built an LR(1) automaton with 8 states.
2 shift/reduce conflicts were silently solved.
Only 7 states remain after resolving shift/reduce conflicts.
File "loop.mly", line 26, characters 2-3:
Warning: production s -> B is never reduced.
Warning: in total, 1 productions are never reduced.
2 out of 7 states are represented.
0 out of 9 symbols keep track of their start position.
0 out of 9 symbols keep track of their end position.
5 out of 7 states have a default reduction.
4 out of 5 productions exploit shiftreduce optimization.
0 out of 7 states can peek at an error.
27 functions before inlining, 2 functions after inlining.
