File "unused-attribute.mly", line 3, characters 19-31:
Warning: this attribute could not be transferred to the symbol list(B)
File "unused-attribute.mly", line 2, characters 13-25:
Warning: this attribute could not be transferred to the symbol D
%start main
%token A
%token B
%token C
%type <unit> main
%%

list_C_ [@foo "bar"]:
  
    {    ( [] )}
| x = C xs = list_C_
    {    ( x :: xs )}

main:
  _1 = A _2 = B _3 = list_C_
    {              ()}

%%



