PGFLAGS         := --infer
GENERATED       := parser.ml parser.mli lexer.ml
MODULES         := parser lexer calc
EXECUTABLE      := calc
OCAMLDEPWRAPPER := ../../demos/ocamldep.wrapper
include ../../demos/Makefile.shared
include ../../demos/Makefile.auto
