PGFLAGS         := --infer
GENERATED       := parser.ml parser.mli lexer.ml
MODULES         := parser lexer calc
EXECUTABLE      := calc
OCAMLDEPWRAPPER := ../../demos/obsolete/ocamldep.wrapper
include ../../demos/obsolete/Makefile.shared
include ../../demos/obsolete/Makefile.auto
