# Dans ce fichier, on ne doit trouver que les réglages qui dépendent
# vraiment de l'article courant.

# Les réglages qui sont les mêmes pour tous mes articles sont dans
# Makefile.cfg.

# Ce fichier est également lu comme un script, donc doit être exprimé
# dans une syntaxe commune à bash et à make.

# Le nom du fichier source principal.

DOC=main

# Le nom des fichiers à exporter vers le site Web.

NAME=menhir

# Les imports TeX pour la compilation.

export TEXINPUTS=.:

