#!/bin/sh

# Ce script installe la dernière version du Makefile magique en provenance
# de chez Christian.

mkdir tmp
cd tmp
wget http://konkuk.ac.kr/~rinderkn/Software/automatex.tar.gz
tar xvfz automatex.tar.gz
if diff ./configure.ac ../configure.ac > /dev/null && diff ./Makefile.in ../Makefile.in > /dev/null ; then
  echo "Aucune nouvelle version n'est disponible."
  cd ..
  rm -rf tmp
else
  mv configure.ac Makefile.in ..
  cd ..
  rm -rf tmp
  if pwd | grep skeletons > /dev/null ; then
    echo "Mise à jour effectuée."
  else
    echo "Mise à jour effectuée. Configuration..."
    autoconf
    ./configure
  fi
fi
