# Dans ce fichier, on ne doit trouver que les réglages qui dépendent
# vraiment de l'article courant.

# Ce fichier est également lu comme un script, donc doit être exprimé
# dans une syntaxe commune à bash et à make.

# Le nom du fichier source principal.

DOC=main

# Le nom des fichiers à exporter vers le site Web.

NAME=jourdan-leroy-pottier-validating-parsers

# Les imports TeX pour la compilation.

export TEXINPUTS=.:

