(******************************************************************************)
(*                                                                            *)
(*                                   Menhir                                   *)
(*                                                                            *)
(*                       François Pottier, Inria Paris                        *)
(*              Yann Régis-Gianas, PPS, Université Paris Diderot              *)
(*                                                                            *)
(*  Copyright Inria. All rights reserved. This file is distributed under the  *)
(*  terms of the GNU General Public License version 2, as described in the    *)
(*  file LICENSE.                                                             *)
(*                                                                            *)
(******************************************************************************)

open Grammar
open Feat.Enum

(* [sentences nt] is an enumeration of all of the sentences generated by the
   nonterminal symbol [nt]. It can be used, for instance, to enumerate all
   sentences of a certain length, or to randomly generate sentences of a
   certain length. (See Feat.Enum.) If the grammar is ambiguous, then some
   sentences can appear several times in this enumeration. *)

(* These sentences are valid according to the grammar, but are not necessarily
   accepted by the LR(1) automaton, because the construction of the automaton
   takes precedence declarations into account, which (strictly speaking) are
   not part of the grammar. *)

val sentences: Nonterminal.t -> Terminal.t list enum

val sentence: ?log:bool -> Nonterminal.t -> int -> Terminal.t array

