#!/bin/bash

mkdir -p lib
ln -sf `pwd`/menhirLib.{cmi,cmo,cmx,o} lib
cd ../demos/calc
make clean
make MENHIR=../../src/menhir PGFLAGS="--infer -v --table -lc 1 --comment" INCLUDE="-I ../../src/lib" OLNKFLAGS="menhirLib.cmx" && \
echo Compilation successful, running ./calc: && \
./calc
