(* This module defines a number of installation settings.
   Its source code is generated by the main [Makefile]. *)

(* The directory where Menhir's standard library, [standard.mly],
   is installed. *)

val libdir: string

(* Whether MenhirLib was installed via [ocamlfind] or (manually)
   in the above directory. *)

val ocamlfind: bool

